### ISSUE TITLE
react-redux-form vs redux-form

### ISSUE THREAD

**Issue by fritx** [davidkpiano/react-redux-form#10]
Hey, what is the general difference of this library and [redux-form](https://github.com/erikras/redux-form)?
What should I think about when I make a decision?
I can determinate a litte by myself, such as this separates `model` from `form`, but I need more official info.
Cheers!

**Comment by davidkpiano** [comment]
Hey @fritx, I'm working on the documentation for this! You pretty much nailed the biggest difference, but I'll post a comparison chart soon. Stay tuned!

**Comment by plandem** [comment]
it's also much less by size and has quite strict separation.

**Comment by davidkpiano** [comment]
Docs now available here! http://davidkpiano.github.io/react-redux-form/#/api/Guide:-Redux-Form-Comparison

**Comment by tnguyen14** [comment]
@davidkpiano is this guide still available somewhere? The link you posted above no longer works.

**Comment by davidkpiano** [comment]
Sure, though keep in mind that these docs do not reflect the latest versions of Redux-Form nor React-Redux-Form @tnguyen14: http://davidkpiano.github.io/react-redux-form/docs/index.html#/api/Guide:-Redux-Form-Comparison

**Comment by tnguyen14** [comment]
Thank you. I understand that the guide may not be the most updated. I am just trying to figure out what I should use.
