### ISSUE TITLE
Update selects values base on original select?

### ISSUE THREAD

**Issue by kkashou** [davidkpiano/react-redux-form#1007]
What is the best way to update another select options values base on what the user selected from the first select box in the form?

For example:

First select box with questions like ("Favorite Colors", "Favorite Animals, "Favorite Sports")

Base on the selection they chose the second selection will have answered populated from the questions they chose. If the user chose "Favorite Colors" and values for the second select box would be (Blue, Green, Black, etc ....).

Thanks

**Comment by davidkpiano** [comment]
How would you do it in plain Redux? You can just check the store values and present the other select options accordingly.

**Comment by kkashou** [comment]
@davidkpiano - But I would need to make the ajax call to grab that database value on the first selection. I noticed you have https://davidkpiano.github.io/react-redux-form/docs/api/actions.html would I use that to make the ajax call and update the values on the next select?

**Comment by davidkpiano** [comment]
You would use whichever method you're comfortable with, and once you received the data, _then_ you `dispatch(actions.change(...))` for the appropriate values.

**Comment by kkashou** [comment]
@davidkpiano - Can we reopen this ticket? I have an example of what I am trying to do but it isn't working, would like to get input on it.

https://codesandbox.io/s/k38k75ny8v

Thanks

**Comment by davidkpiano** [comment]
Your second select has no values:

```jsx
          <Control.select model=".faveColorVariation" id="faveColorVar">
          </Control.select>
```

I would redirect questions like these to stackoverflow.com unless you find a bug (or have a feature request). Thanks!
