### ISSUE TITLE
Wrong cursor position in the Control.text component using parser / formatter

### ISSUE THREAD

**Issue by em-ka** [davidkpiano/react-redux-form#1010]
### The Problem
First, thank you for the great React Redux Form, I appreciate it very much!
I've tried the new formatter option on the Control.text component, but sometimes during editing the cursor jumps to the end of the string unexpectedly.

### Steps to Reproduce
[Run the example](https://codesandbox.io/s/1qn909n6rj), place the cursor somewhere in the middle of the "10,000,000" input value and try to add / remove some numbers.

### Expected Behavior
The cursor stays at the position in the middle of the string. 

### Actual Behavior
The cursor jumps to the end of the string.

### Reproducible Code Example
[Example](https://codesandbox.io/s/1qn909n6rj)

**Comment by davidkpiano** [comment]
This is a difficult problem to solve (and why I avoided adding `formatter` for a long time). Consider solving this by making a custom component and using something like https://github.com/insin/react-maskedinput

**Comment by em-ka** [comment]
Thank you, David, for guiding me the right way. I was successful using the combination of a custom component with [NumberFormat](https://github.com/s-yadav/react-number-format) and Control.text `parser` for providing the right value back.
