### ISSUE TITLE
'Maximum call stack size exceeded' when using validators prop on a nested <Form>

### ISSUE THREAD

**Issue by durz** [davidkpiano/react-redux-form#1014]
### The Problem
When `validators` is used in a `<Form>` nested within another `<Form>` and the execution of a validator returns a value of `false`, a 'Maximum call stack size exceeded' error is produced and the browser hangs. If the validator returns `true`, it seems to work normally.

If `validators` is used instead on the parent `<Form>`, it also seems to work normally.

### Steps to Reproduce
Open the linked codepen and enter anything into the Password or Confirm password fields.

### Expected Behavior
The browser doesn't hang and the validators execute properly.

### Actual Behavior
The browser hangs and the app crashes.

### Reproducible Code Example
https://codepen.io/anon/pen/OOxxWK?editors=0010

**Comment by valorize** [comment]
Actually forms are not allowed in forms: https://wiki.selfhtml.org/wiki/Referenz:HTML/form
So I think Form should also be not.

**Comment by davidkpiano** [comment]
Right, you shouldn't have nested forms. Prefer using a `Fieldset` instead.

**Comment by valorize** [comment]
Actually the docu says you can nest: https://davidkpiano.github.io/react-redux-form/docs/api/formReducer.html -> Forms can be infinitely nested

**Comment by rikkit** [comment]
@valorize that's referring to form models only - not the `<Form>` component. It's saying that you can treat any nested object within a form model as a form model. I agree it's confusing wording.
