### ISSUE TITLE
When a tracked model doesn't exist

### ISSUE THREAD

**Issue by bstro** [davidkpiano/react-redux-form#1016]
### The Problem
I'm currently iterating over a large set of data to create a pretty substantial form. Each field in the form represents a score for an assignment. Sometimes a score object will already exist for a given assignment, and sometimes this score object will not exist.

If the score object exists, I want it to show up in the form and be able to update it. *I have this part working currently*.

When I try to change the score for a field that is not currently backed by a score object, it understandably fails; while I'm using `track`, its looking for an object that doesn't exist yet. So I need to create the score object, persist it to the server, and then let RRF handle it from there. What's the best way to do this?

Thanks!

**Comment by bstro** [comment]
It occurs to me that `localForms` (https://davidkpiano.github.io/react-redux-form/docs/guides/local.html for anyone with the same question) might be the answer to this challenge.

**Comment by bstro** [comment]
It looks like I could possibly use a combination of `Control`'s `changeAction` prop and dispatch a series of thunks that will create the model prior to attempting to perform `actions.change` on it. Thoughts?

**Comment by davidkpiano** [comment]
Yes, that, or you can pass in a function to `actions.change` to simplify things; for example, if a user doesn't exist:

```js
// change "users.nonexistant.name" to "bob"
actions.change('users', (users) => {
  const currentUser = users.nonexistant || {};
  return {
    ...users,
    nonexistant: {
      ...currentUser, // existing or new user
      name: 'bob'
    }
  };
});
```

**Comment by bstro** [comment]
Thanks! Super helpful.
