### ISSUE TITLE
Dispatch additional action onChange (typeahead)

### ISSUE THREAD

**Issue by arddor** [davidkpiano/react-redux-form#102]
Hi

First of all thank you for your great work.
I have two usecases where I would like to dispatch an additional async action when a Field changes, e.g. Typeahead. 
Just wondering what would be the suggested way to do this?

Regards

**Comment by davidkpiano** [comment]
No problem! The easiest way to do this is to pass in your own custom action creator into the  [`changeAction`](https://davidkpiano.gitbooks.io/react-redux-form/content/field_component.html#changeaction-property) prop on the `<Field>`, like this:

```js
import { Field, actions } from 'react-redux-form';

function anotherAsyncAction(model) {
  // ... your custom async action creator
}

// in render() somewhere
<Field model="user.something"
  changeAction={(model, value) => (dispatch) => {
    dispatch(actions.change(model, value)); // default behavior
    dispatch(anotherAsyncAction(model)); // your custom async action
  }}>
  <input type="text" />
</Field>
```
