### ISSUE TITLE
How to create nested form elements with one to many relationship

### ISSUE THREAD

**Issue by pdehne** [davidkpiano/react-redux-form#1023]
This is not a bug report but a request for documentation. If this is the wrong place to ask a pointer to the right place would be very much appreciated.

Given a state with a one to many relationship like this:

```
{
	currentUser: {
		id: 1,
		name: 'John Doe',
		email: 'john@doe.com',
		phones: [
			{
				id: 1,
				number: '111222333',
				type: 'private'
			},
			{
				id: 2,
				number: '444555666',
				type: 'office'
			}
		]
	}
}
```

How can one create a form where existing phone numbers can be changed or deleted and new phone numbers be added?

Here is a CodePen sample that illustrates the goal: https://codepen.io/patrick/pen/xPYeQK

In that sample the missing parts are:

- How to render the list of phone numbers if the state lives in the form state managed by react-redux-form. In the sample the initial list is rendered from the currentUser element which comes from the regular state which is probably wrong:
```
{this.props.currentUser.phones.map((phone, index) => (
  <div key={index}>
    <label>Number: </label>
    <Control.text model={track('user.phones[].number', { id: phone.id })} />
    <label>Type: </label>
    <Control.text model={track('user.phones[].type', { id: phone.id })} />
  </div>
)}
```

- How to add a new phone number to the form or remove a phone number if the state lives in the react-redux-form managed form store? I am not sure how to access the form store and add an element to the phones array of the user that is currently edited. The sample already contains an add new phone number event handler, but what to put there:
```
  handleAddNumber(event) {
  }
```

- If multiple numbers are added all would receive an initial 0 id. Would list item tracking as shown above still work given a state with two new numbers like the below. If not, what would be the right approach?
```
		phones: [
			{
				id: 1,
				number: '111222333',
				type: 'private'
			},
			{
				id: 0,
				number: '123123',
				type: 'home'
			}
			{
				id: 0,
				number: '321321',
				type: 'vacation'
			}
```

Many thanks for taking a look!

**Comment by pdehne** [comment]
Can anyone tell if it is possible at all with react-redux-form? If not I will need to switch to something different.

**Comment by davidkpiano** [comment]
It's possible. You can dispatch `actions.push('user.phones', newPhone)` to add a new phone, and of course it's smart to give each phone number a unique `id` (otherwise tracking won't work like you'd expect - since it'll just select the first match).

**Comment by pdehne** [comment]
Many thanks for answering! I think the CodePen is almost there now. But actions.push doesn't seem to have an effect, probably because the initial list is not rendered from the react-redux-form managed state:
```
{this.props.currentUser.phones.map((phone, index) => (
...
))}
```

How would I render the list of phones from the react-redux-form managed state if the form state has been populated using
```
this.props.load('user', currentUser);

...

const mapDispatchToProps = (dispatch) => {
    return {
        load: (model, value) => {
            dispatch(actions.load(model, value));
        }
    };
}

```

**Comment by davidkpiano** [comment]
> probably because the initial list is not rendered from the react-redux-form managed state:

Can I see how your store is defined?

**Comment by pdehne** [comment]
Sure! The CodePen: https://codepen.io/patrick/pen/xPYeQK contains the whole example.

**Comment by pdehne** [comment]
I added dispatch to actions.push, sadly still no effect:
`this.props.dispatch(actions.push('user.phones', { id:3, number:'777', type:'mobile'}));`

Maybe how I load the initial state is the problem:
`this.props.dispatch(actions.load('user', currentUser));`

currentUser comes from the redux state and is mapped to props using connect. I suspect 'user.phones' is not related to that entity.

Updated CodePen: https://codepen.io/patrick/pen/xPYeQK

**Comment by pdehne** [comment]
I finally found where the current form state is available in the redux store. After mapping it into the props of the form component things started working:
```
const mapStateToProps = (state) => {
    return {
        user: state.user
    };
}

...

{user.phones.map((phone, index) => (
	<div key={index}>
	  <label>Number: </label>
	  <Control.text model={track('user.phones[].number', { id: phone.id })} />
	  <label>Type: </label>
	  <Control.text model={track('user.phones[].type', { id: phone.id })} />
	</div>
))}
```

For creating new unique ids when adding phone numbers I use this:

```
handleAddNumber(event) {   
	let { dispatch, user } = this.props;

	let newID = -1;
	user.phones.forEach(function (phone) {
	  if (newID >= phone.id)
		newID = phone.id - 1;
	});

	dispatch(actions.push('user.phones', { id:newID, number:'', type:''}));
}
```

Working CodePen: https://codepen.io/patrick/pen/xPYeQK

Feel free to close this issue. Thanks for taking a look!

**Comment by davidkpiano** [comment]
Awesome, glad you got it figured out!
