### ISSUE TITLE
Form with multiple child/inner components

### ISSUE THREAD

**Issue by im1dermike** [davidkpiano/react-redux-form#1026]
I don't see anything in the documentation that describes the follow scenario:

    <Form onSubmit={...}>
      <InnerFormComponent1 />
      <InnerFormComponent2 />
      <button>Submit</button>
    </Form>

In this example, the `onSubmit` occurs at the "parent" form level, but there are two child components, each with their own fields, validation, etc. that should roll up to the parent form.

Is there an example of how this can be done with react-redux-form?

**Comment by davidkpiano** [comment]
Please show me a full working code example in CodePen or CodeSandbox.

**Comment by im1dermike** [comment]
@davidkpiano I asked how you do something in this framework because I couldn't find any documentation in re: and you ask me to implement a fully working example?

**Comment by davidkpiano** [comment]
Yep, it might help you (us) work through the problem too. Show me how you expect it to work in RRF. I don't know what's inside `<InnerFormComponent1 />`.

**Comment by im1dermike** [comment]
I can try to put together an example but the InnerComponent are just parts of a form (Controls) that have been separated based on concern.

**Comment by davidkpiano** [comment]
Try using `<Fieldset>` instead: http://davidkpiano.github.io/react-redux-form/docs/api/Fieldset.html

**Comment by im1dermike** [comment]
Thanks. I'll give it a try and get back to you. Might be a week or so fyi.

**Comment by im1dermike** [comment]
I'm still working through getting my example to work in CodeSandbox, but [here](https://codesandbox.io/s/04q2vozr4n) is the setup so you can understand it conceptually.

**Comment by im1dermike** [comment]
I finally got a chance to look at Fieldsets, and it indeed looks like that will solve my problem.  Thanks!
