### ISSUE TITLE
TypeScript Definition (gist link included)

### ISSUE THREAD

**Issue by hsrobflavorus** [davidkpiano/react-redux-form#103]
Hi, I took the time to write up the TypeScript definition file for react-redux-form. I haven't yet had a chance to test it extensively, but I believe it is mostly complete as of v0.9.0

**Gist: https://gist.github.com/hsrobflavorus/d17f5b8c87d75ce6b068**

I've got a pretty hectic schedule and workload, so if anybody would like to test this out and provide feedback or fixes, it would be much appreciated. Also, if someone is willing to write up tests and take the time to get this merged into DefinitelyTyped, that would be a huge help for everyone.

**Comment by davidkpiano** [comment]
Hey, took a quick look at this and it is fantastic! Would you mind putting it in a PR? I can go ahead and start writing tests for it when I get the time.

**Comment by asvetliakov** [comment]
Updated for version 0.10.4 for anyone interested:
[https://gist.github.com/asvetliakov/cb814992efb4d89be59867c1c0699795](https://gist.github.com/asvetliakov/cb814992efb4d89be59867c1c0699795)

Removed direct deps for redux until new TS 2.0 library references will be landed 
I can host it via typings if @hsrobflavorus agree

Alternatively @davidkpiano can host it in lib itself (just renamed to index.d.ts or add "typings" field to package.json)

**Comment by hsrobflavorus** [comment]
@asvetliakov Thank you! Much appreciated. I'd love it if you would do that, please feel free to host it wherever you have the time to place it. Thanks for leaving the author info in the header, my boss will appreciate having the link to us!

**Comment by davidkpiano** [comment]
I'll definitely add this to the main repo soon! Great work and thanks for this, both of you!

**Comment by hsrobflavorus** [comment]
@davidkpiano @asvetliakov Updated for 0.13.3 here: https://gist.github.com/hsrobflavorus/d17f5b8c87d75ce6b068

**Comment by davidkpiano** [comment]
Merged! Thanks a ton! 🎉 🎊
