### ISSUE TITLE
<Error /> giving an error when model isn't specified

### ISSUE THREAD

**Issue by Emobe** [davidkpiano/react-redux-form#1030]
### The Problem
I have been trying to get form wide errors working. I was looking at the [Comparing to redux-form](https://davidkpiano.github.io/react-redux-form/docs/guides/compare-redux-form.html) examples and saw that on the "Sync Validation" section, <Error /> didn't require a model

### Steps to Reproduce
Use the "Sync Validation" example on the "Compare to redux-form" page

### Expected Behavior
To validate the form

### Actual Behavior
Gives me an error
TypeError: Cannot read property '0' of undefined
resolveModel
node_modules/react-redux-form/lib/utils/resolve-model.js:31
    28 | 
    29 | function resolveModel(model, parentModel) {
    30 |   if (parentModel) {
    31 |     if (model[0] === '.' || model[0] === '[') {
    32 |       return '' + parentModel + model;
    33 |     }
    34 | 

### Reproducible Code Example
https://codesandbox.io/s/x2qz9396xq

**Comment by davidkpiano** [comment]
Can you make a PR that fixes the example? The `model` prop is required.

**Comment by Emobe** [comment]
Will do

**Comment by davidkpiano** [comment]
Thank you!
