### ISSUE TITLE
LocalForm is not updating it's childs with model values after the component props are updated (i.e. after dispatch)

### ISSUE THREAD

**Issue by amarendhar** [davidkpiano/react-redux-form#1037]
### The Problem

componentDidMount () {
  this.props.dispatch(fetchUserDetails());
}
render () {
  const { userDetails } = this.props;
  return (
          <LocalForm
            model="userDetailsForm"
            name="userDetailsForm"
            initialState={userDetails}
            id="userDetails"
            role="form"
            className="form h-tightSpacingBottom"
            onUpdate={this.handleFormUpdate}
            onSubmit={this.onSaveClick}
          >
            <div className="h-text-center">
              <label className="title">{PMD.userDetailsTitle}</label>
            </div>

            <div className="h-tightSpacingBottom">
              <label className="title asterisk" htmlFor="userId">{PMD.userIdTitle}</label>
              <Control
                model=".username"
                id="userId"
                type="text"
                className="form-control"
                placeholder={PMD.userIdPlaceholder}
                validators={{
                  required: (val = '') => val && val.length,
                  requiredLength: (val = '') => val.length >= 8
                }}
              />
              <Errors
                className="errors"
                model=".username"
                show="touched"
                messages={{
                  required: 'Required',
                  requiredLength: 'Must be 8 characters or more'
                }}
              />
            </div>
          </LocalForm>
        )
}

### Steps to Reproduce
Look at the above code snippet.

1. Initially "userDetails" prop is filled like this "{username:''}".
2. After I did "this.props.dispatch(fetchUserDetails());" in "componentDidMount", the "userDetails" prop is available as "{username: 'amarendhar'}".
3. But it is not updating the value of "Control with the '.username' model".

### Expected Behavior
When props are updated, then LocalForm should update associated Control-tag values in the html.
I've even checked by putting break-point, i observed, after new props recieved, LocalForm component "i.e. function LocalForm(props) {" is not getting called, so that associated Control-tag values are not getting updated.
very weird behavior.

### Actual Behavior
When props are updated, then LocalForm is not updating the associated Control-tag values.

### Reproducible Code Example
(please fork from [this CodePen template](http://codepen.io/davidkpiano/pen/yJwmEa) or [this CodeSandbox template](https://codesandbox.io/s/k3jyzwqo53))

**Comment by davidkpiano** [comment]
It's hard to read the given code example. Please place it in CodePen or CodeSandobx.

**Comment by amarendhar** [comment]
yeah, sorry, i got the solution.
Now i'm **_this.formDispatch_** to update **LocalForm** whenever it is required.
Tahnks.
