### ISSUE TITLE
action.push won't work if the model reducer is not at the root level

### ISSUE THREAD

**Issue by ataube** [davidkpiano/react-redux-form#104]
Lets assume I have model called `fooModel`with an array called `list`. 
Lets further assume I would like to put this model and all other models created with react-redux-form at the second level of my state tree called `forms`. 
```javascript
var state = {
  forms: {
    fooModel: { 
      list: []
    },    
  }
}
```
The setup of my reducers would look like this: 
```javascript
//reducers/index.js
import { combineReducers } from 'redux';
import { forms } from './forms.js' 
const rootReducer = combineReducers({
  forms,
});

//reducers/forms.js
import { combineReducers } from 'redux';
import { modelReducer } from 'react-redux-form';
export const forms = combineReducers({
  customer: modelReducer('fooModel', {})
});
```
Now at the component level if I push a item to the `fooModel.list` the following happens:
`action.push('fooModel.list', {}) //=> ok one item gets pushed`
`action.push('fooModel.list', {}) //=> no second item`

The push action is trying to get 'foo.list' starting from the root, which is wrong I guess

**Comment by davidkpiano** [comment]
Little bit confused by the code. Can you post a full code example?

**Comment by ataube** [comment]
I updated the example (see above). Hope this makes it now more clear...

**Comment by davidkpiano** [comment]
Thanks! The `model` argument of `modelReducer(model, initialState)` has to be the absolute path of the model, relative to the _entire_ store. So try this and see if it works:

```diff
export const forms = combineReducers({
-  customer: modelReducer('fooModel', {}),
+  customer: modelReducer('forms.fooModel', {})
});
```

**Comment by ataube** [comment]
Many thanks for the quick feedback, it is working if I use the `forms`-prefix for the model-reducer and all other places like:

`<Field model="forms.myModel.list[0].x" />`

`dispatch(push('forms.myModel.list', {})`

The code will get a litte verbose, especially if there are deep tree structures. But I also like the simplicity which makes react-redux-form fun to use... :-)
