### ISSUE TITLE
Issue with npm release v1.16.2

### ISSUE THREAD

**Issue by joshacheson** [davidkpiano/react-redux-form#1041]
### The Problem

The contents of `lib/` in the released tar file on npm are not what's expected given the contents of `src/`.

### Steps to Reproduce

Download v1.16.2 from npm: https://registry.npmjs.org/react-redux-form/-/react-redux-form-1.16.2.tgz

### Expected Behavior

lib/ is the compiled output of src/

### Actual Behavior

lib/ appears to contain compiled output of an older version

### Subset of code that should be consistent (aside from compilation) but is not:

lib/ (consistent with compiled output pre 1.16.2)

![image](https://user-images.githubusercontent.com/1906888/33850006-6d24913a-de80-11e7-900b-30aa443c696a.png)

src/ (consistent with source of 1.16.2)

![image](https://user-images.githubusercontent.com/1906888/33850022-78628d72-de80-11e7-91e0-6d868d8bc462.png)

**Comment by davidkpiano** [comment]
Just published a patch, let me know if that works!
