### ISSUE TITLE
Difference between Control.validators and Control.errors properties?

### ISSUE THREAD

**Issue by brahimmouhamou** [davidkpiano/react-redux-form#1047]
Hi Guys,

I'm new to RRF and I was reading the docs.

On the [Validation doc page](https://davidkpiano.github.io/react-redux-form/docs/guides/validation.html) a 'keyed validation' and a 'keyed errors' component are described but what is the main difference? When should I use the validators property and when should I choose the errors property? Or should I use both?

On the [Control doc page](https://davidkpiano.github.io/react-redux-form/docs/api/Control.html) the same example is used for both properties.

Can someone explain this to me?

**Comment by davidkpiano** [comment]
Use `validators`.

The only reason to use `errors` is if you don't like describing your validation in terms of "is this valid" and instead "is this an error".
