### ISSUE TITLE
Validating fields with array values?

### ISSUE THREAD

**Issue by joshuarh** [davidkpiano/react-redux-form#105]
When I add a validator to a form field in the array format:

```
var validateDays = function(days) {
  return days && days.length > 0;
}

<Field model='reminder.days[]' validators={ validateDays }>
  <input id="mondays" type='checkbox' value={ 1 } />
  <input id="tuesdays" type='checkbox' value={ 2 } />
</Field>
```

I would expect that the validator would receive the array as an argument, but instead it receives only the most recently changed value.

For example:

| | Validator Receives | I Would Expect |
| --- | --- | --- |
| I check "Mondays" | `"1"` | `[ "1" ]` |
| I check "Tuesdays" | `"2"` | `[ "1", "2" ]` |
| I uncheck "Tuesdays" | `"2"` | `[ "1" ]` |
| I uncheck "Mondays" | `"1"` | `[]` |

This means I can't conveniently make assertions about the whole array, like checking that at least one day is selected.

I can work around it by using the action helpers, but I wanted to check if either I am understanding this wrong or if this is desired behavior for some reason. I think it would be nice if it worked as above!

Thanks for a fantastically useful, lucid, and enjoyable-to-use library.

**Comment by davidkpiano** [comment]
> Thanks for a fantastically useful, lucid, and enjoyable-to-use library.

Greatly appreciated! :smile: 

You're right; it would be great if it worked as above. I'll add a test case and see if this is a bug.

**Comment by davidkpiano** [comment]
@joshuarh It was indeed a bug - now validators will be validated on the exact model value instead of the value passed in from the event in `0.9.1` :rocket:
