### ISSUE TITLE
integration with redux-optimistic-ui

### ISSUE THREAD

**Issue by mrsufgi** [davidkpiano/react-redux-form#1050]
I've been trying to integrate both libraries to create optimistic forms using this awesome library.  
Since redux-optimistic-ui is wrapping the reducer state with 'current' wrapping it again with combineForms creates a form with current prop.

In my <Form> I hooked into myReducer.current, it does get the current values, but when I get into revert action, my beforeState has already changed and it won't revert to the correct state. 

did anybody managed to do some optimistic updates (with revert/commit) using react-redux-form?

Thanks!

**Comment by davidkpiano** [comment]
I'm not familiar with redux-optimistic-ui. I'll reopen this if you have a working code example and can demonstrate that something with react-redux-form is preventing you from doing what you want.

**Comment by mrsufgi** [comment]
hey @davidkpiano I think the combination of those packages may be useful for many. I managed to get it to work. I'll post my a small how-to here soon! Thanks again!

**Comment by davidkpiano** [comment]
Awesome to hear @mrsufgi !!
