### ISSUE TITLE
[Question] support for object of objects keyed by id 

### ISSUE THREAD

**Issue by davidchase** [davidkpiano/react-redux-form#1052]
Hi @davidkpiano 

Thanks for a great lib, I was wondering what your thoughts were for supporting object of objects keyed by id in the deep form validation ? Currently I see the support for array of objects only.

Thanks

**Comment by davidkpiano** [comment]
Object of objects are already supported: `model="foo.bar.baz"`, try it out!

**Comment by davidchase** [comment]
@davidkpiano i mean like i have a collection like so

```js
const obj = {
  123: {number: 332},
  456: {number: 563},
  789: {number: 445},
  ...
}
```

i want to validate on form like so
```js
<Form validators={{'user.obj{}.number'}} />
```

Right now you support via `user.obj[].number` so array of objects https://github.com/davidkpiano/react-redux-form/blob/master/docs/guides/validation.md#deep-model-validation-in-form

**Comment by davidkpiano** [comment]
That seems like something that should be solved in userland. You can easily create validation on the `user.obj` model.
