### ISSUE TITLE
submitFailed property missing in _FieldState typings

### ISSUE THREAD

**Issue by SuperOleg39** [davidkpiano/react-redux-form#1053]
Hello!

**interface _FieldState** does not contain a **submitFailed** property, but i can get this property in **Control mapProps** callbacks.

This is a mistake, or property **submitFailed** should not be in **fieldValue**?

**Comment by davidkpiano** [comment]
It should, you can correct the type definition file if it's missing and I'll accept that PR.

**Comment by SuperOleg39** [comment]
Done!
