### ISSUE TITLE
Documentation? Update store only on submit

### ISSUE THREAD

**Issue by MatheoJaouen** [davidkpiano/react-redux-form#1056]
Hi,

I certainly missed something but what is the best way to make the store change only on Form submit?
LocalForm? If so, is there an example somewhere to update the store from the LocalForm values on submit, (and with store values as default values)? And is there an other way to achieve this with a classic Form? Prevent `changeAction={(v) => console.log(v)}` on every fields?
Last one, is there somewhere a documentation regarding form store structure?

For instance if you have a profile component with a user form, and the user lastName from the store in the header component, how do you do to change the lastName only on submit in order to not change it in the header on every input change?

Thanks you.

**Comment by MatheoJaouen** [comment]
well I did it with LocalForm, seems to work, but I'm not sure it's the best way?
If that can help someone (I'm using react native)
```
class ProfileScreen extends React.Component {
    constructor(props) {
        super(props);
    }

    handleSubmit(user) {
        let {dispatch} = this.props;
        dispatch(actions.change('user', user));
    }

    attachDispatch(dispatch) {
        this.formDispatch = dispatch;
    }

    render() {
        let {user} = this.props;
        let {dispatch} = this.props;
        return (

            <LocalForm
                model="user"
                component={View}
                getDispatch={(dispatch) => this.attachDispatch(dispatch)}

                onSubmit={(values) => this.handleSubmit(values)}
                initialState={user}>
                <Control.TextInput model=".firstName"/>
                <Control.TextInput model=".lastName"/>
                <Text>
                    {user.firstName}
                </Text>
                <Text>
                    {user.lastName}
                </Text>
                <Button
                    onPress={() => this.formDispatch(actions.submit('user'))}
                    title="submit"
                />
            </LocalForm>
        );
    }
}

function mapStateToProps(state) {
    return {user: state.user};
}

export default connect(mapStateToProps)(ProfileScreen);
```

**Comment by davidkpiano** [comment]
Yep, you'd want to use `LocalForm` for that. Feel free to add it to the docs, and I'll merge in that PR.
