### ISSUE TITLE
question: Form level validation and error message

### ISSUE THREAD

**Issue by madeinspace** [davidkpiano/react-redux-form#1057]
Hi there,

I have a form whose fields are split in 3 collapsible sections of an accordion, I'd like to get some sort of form level validation that would display a red asterix on each header of the accordeon to alert the user that validation has failed in that section. Not sure how to approach this as I need to validated against several model but display the error message (red asterix) if at least 1 individual validation has failed. Does that make sens?

Thanks!

**Comment by davidkpiano** [comment]
The entire form state is available to you in the Redux store. You can easily grab the validity of each section via a selector from the state, and then solve this problem as you would solve any other Redux problem. It's not RRF-specific.
