### ISSUE TITLE
Question: Recommended way to manage focus programmatically

### ISSUE THREAD

**Issue by mdgbayly** [davidkpiano/react-redux-form#106]
This is somewhat related to issue #84 and PR #93 but I guess it is also a more general question.

We have a form with a list of values. Each item in the list is a fieldset with a set of related inputs. I'm currently working on a feature to reorder the items in the list. We use up/down arrow buttons in each fieldset to move the fieldsets up/down.  We need to retain focus in the current button when it moves up/down.

Currently I'm dispatching a field focus action to change the focus to the previous/next item in the list.  This is handled by the parent of the fieldset components which is the connected component in the form.
e.g.
```
/form.js
onMoveItemUp( index ) {
    if (index === 0) {
        return;
    }
    const { dispatch } = this.props;
    dispatch(actions.focus(`myModel.items[${index - 1}].moveUp`));
    dispatch(actions.move('myModel.items', index, index - 1));
}
```

The fieldsets are nested components and the react-redux-form fields representing the buttons are passed in as props.  In their componentDidUpdate, I check to see if the focus state of either the up or down button has changed to true and if it has I call the underlying HTML element's focus() method.  The fieldset component has already saved a DOM reference to the up/down buttons using a React ref prop with callback.

e.g.
```
/fieldset.js
componentDidUpdate(prevProps) {
	const { upButtonField, downButtonField } = this.props;

	if (upButtonField.focus && !prevProps.upButtonField.focus &&
		this.upButton !== this.upButton.ownerDocument.activeElement) {
		this.upButton.focus();
	}
...
}
```

But this all seems kind of complicated. And we end up with two focus actions dispatched each time we click on an up/down button.  Maybe it would be better for the parent component to directly set the focus state of the child component rather than dispatching a focus action?  As the actions are really supposed to be used to represent the current focus state? Not change it?

Any thoughts?

One small simplification would be if the model reducer maintained the form state when moving items in PR #93 (similar to the discussion in #84).  But still puts an onus on the form app to manage the actual element focus state?

**Comment by davidkpiano** [comment]
Is it possible to post a full working code example? 

My thinking is that it might not even be necessary to programmatically maintain the focused state of the proper field, with the proper handling of `key`. For example:

```diff
{ myModel.items.map((item, index) => 
  <Field model="myModel.items[index]"
-    key={ index }>
+    key={ item.id }>
    <input type="text" />
  </Field>
}
```

Just a thought. I'd have a better idea of how best to handle this with a complete (working) code example.

**Comment by mdgbayly** [comment]
Sorry, yeah, realize a full working code example would help with these kinds of things. Our react-redux-form app is part of a larger web application so not so easy for me to post as is.  I'll try and pull some of it out into an example project to help with these kinds of questions.

In the meantime, thanks, interesting hint about keeping the key consistent.  I had not realized React would do that.  It works for the general use case of maintaining focus and so is probably the best approach generally if you don't need to use rrf for tracking focus.

There is still one interaction where we need to change the focus programmatically. If a user is using the keyboard to move items up the list e.g. by pressing enter on the up button, when an item gets to the top we disable the up button and shift focus to the down button. But maybe it would be better to do that just in React too. I'll play some more.

I'll close the question for now and re-open it if I have some more info/examples.
