### ISSUE TITLE
Unable to create Form component. Could not find form for "<model>" in the store.

### ISSUE THREAD

**Issue by Teyras** [davidkpiano/react-redux-form#1060]
### The Problem

I'm trying to integrate react-redux-form into my app to make a form that remembers the input indefinitely. My store uses Immutable.js and `redux-immutable` and it is persisted in the local storage using `redux-localstorage-immutable`.

When I try to add a simple form to my app, I get the message 'Unable to create Form component. Could not find form for "batch" in the store.'

### Steps to Reproduce

This happens with RRF version 1.16.2. My form component is inside the Provider and looks like this:

```
<Form model="batch" onSubmit={this.props.onSubmit} getDispatch={this.attachDispatch}>
  <Control.text />
   ...
</Form
```

The code that creates the store is similar to this:

```
import {createStore, compose} from 'redux';
import persistState, {mergePersistedState} from 'redux-localstorage';
import adapter from 'redux-localstorage/lib/adapters/localStorage';
import { serialize, deserialize } from 'redux-localstorage-immutable';
import { combineReducers } from "redux-immutable";
import {createForms} from "react-redux-form/immutable";


const storage = compose(
    // apply serialize from redux-localstorage-immutable
    serialize
)(adapter(window.localStorage));

let enhancers = [persistState(storage, 'redux')];
let reducers = {
    some: reducer
};
let forms = {
    batch: Map({foo: 1, bar: 2})
};

const reducer = compose(
    // apply deserialize from redux-localstorage-immutable
    mergePersistedState(deserialize)
)(combineReducers({...reducers, ...createForms(forms)}));

const enhancer = compose(...enhancers);
const store = createStore(reducer, enhancer);

export default store;
```

Is there an error in my code or is this a bug? What other info can I provide?

**Comment by Teyras** [comment]
I was able to resolve this by replacing Immutable.js with Immer. I would still like to know if there was any mistake on my side, though.

**Comment by rikkit** [comment]
@Teyras based on my reading of this PR #618 I think Immutable.js is not supported. Maybe something to do with how it represents objects? There's a lot of state tree traversal in RRF, and if the state tree is a different structure than usual JS because of Immutable, I think you'd get the kind of error that you did.

**Comment by davidkpiano** [comment]
Immutable is supported in a limited sense, but making absolutely everything immutable (which is a bad idea IMO... just use immutable helpers, not Immutable.JS) makes things much more complicated.

Immer looks fantastic, though. I'm going to be using it myself.
