### ISSUE TITLE
TYPESCRIPT : Unable to use track in action.change

### ISSUE THREAD

**Issue by Fouaib** [davidkpiano/react-redux-form#1063]
### The Problem
Hello, 

I probably found an omission in the react-redux-form.d.ts file.

Currently it is not possible to use the first action example described in your documentation with typescript

### Steps to Reproduce
Start a new react projet with typescript , add RRF and add the following code : 

import { track, actions } from 'react-redux-form';
dispatch(actions.change(
  track('user.goats[].color', {id: 123}),
  'black'));
this code appears in your documentation ( https://davidkpiano.github.io/react-redux-form/docs/api/actions.html )

### Actual Behavior
Right now there is an error because the Action.Change method only accept the type string for the model parameter.
But in your documentation you declare that for this action, the model can be a string OR a function.

### Correction
To correct this issue we need to update the definition file with : 
change: (model: string | ModelGetterFn, value: any, options?: ChangeOptions) => ModelAction;
rather than
change: (model: string, value: any, options?: ChangeOptions) => ModelAction;

This change should also be done for others actions ...

Also, you have several actions defined in the typescript definition file that doesn't seems to appear in you documentation ( batch, asyncSetErrors, addintent, clearIntent ), is it normal ?? 

I did the change locally and if you want i could create a pull request ( i cannot push the branch right now ... because i am unauthorized )

Thank you for your library :)

**Comment by davidkpiano** [comment]
I'd greatly appreciate a PR for this, and I'll get it merged in ASAP. Thank you!

**Comment by Fouaib** [comment]
i tried to add a new branch pr/typescript-def-file , but when i want to push my branch it returns a 403 for my user. Can you authorize me ?

**Comment by davidkpiano** [comment]
You have to fork the repo first, make the change in your fork, and then make a pull request to this repo.
