### ISSUE TITLE
Async validation calls batch action with the value of the input causing plain object error for actions

### ISSUE THREAD

**Issue by greghawk** [davidkpiano/react-redux-form#1065]
### The Problem
Async validation calls batch action with the value of the input causing plain object error for actions

### Steps to Reproduce
Set asyncValidators property to a text control.  Add a changeAction property set to anything you want.  Fill out the firstname field and hit enter on keyboard.

### Expected Behavior
Standard actions processing and no errors when using the enter key or clicking a submit button when a changeAction property exists

### Actual Behavior
The pure value of the input is sent as an action and fails the isObject test in redux. Yields the error:
**Actions must be plain objects. Use custom middleware for async actions**

### Reproducible Code Example
https://codepen.io/anon/pen/wpxZGW?editors=0010

**Comment by greghawk** [comment]
@davidkpiano you see this yet?

**Comment by davidkpiano** [comment]
I don't see that error in the example.

**Comment by greghawk** [comment]
You have to open the web debugger like chrome dev tools when doing the codepen and you will see it. I can see it every time

**Comment by greghawk** [comment]
![image](https://user-images.githubusercontent.com/5090707/35079492-e9129838-fbd5-11e7-9d0e-1fd67e3d8fed.png)

**Comment by rikkit** [comment]
You need to install redux-thunk to your project.

**Comment by rikkit** [comment]
Hi, I tried out your codepen and don't see the error in either the codepen or browser consoles.

**Comment by davidkpiano** [comment]
In your code you have `changeAction={()=>{}}` - that's an undefined action. Remove it and you'll see it works.

**Comment by greghawk** [comment]
@davidkpiano I only did that for brevity.  My actual code does have a function.  What is happening when i stepped into rrf is that it sends a batch action and one of the actions is a string representing the typed in value of the input box.  That is not an object and fails the redux test isObject

**Comment by davidkpiano** [comment]
Can you please post the example with the full `changeAction`? That's the culprit.

Also, if you are digging into the code and know a fix, please submit a PR.

**Comment by greghawk** [comment]
From within a control.text               

`changeAction={(model, value) => (dispatch) => {
                 dispatch(actions.change(model, value));
                 dispatch(actions.resetValidity(model, ['verification']));
               }}`

**Comment by greghawk** [comment]
I can look in to a PR.  Just wanted to confirm I wasn't doing something unexpected first.  pretty vanilla really
