### ISSUE TITLE
v1.16.4 lib/ incorrect based on src/

### ISSUE THREAD

**Issue by joshacheson** [davidkpiano/react-redux-form#1067]
### The Problem

lib/ seems to be incorrect for v1.16.4

### Steps to Reproduce

npm install react-redux-form@1.16.4 to a project, inspect lib/

### Expected Behavior

lib/ "matches" src/

### Other

note: I've been using node 8.9.3 and npm 5.6.0

It seems like build has failed for some reason on 1.16.4. I'm not _really_ sure what's happening here, because I can't reproduce easily.

If I clone this repo, `npm install`, and `npm run build`, the build works out fine.

If I install `react-redux-form@1.16.4` via npm, cd in to `./node_modules/react-redux-form`, the following:

1) lib/ doesn't reflect src/ (the marker I'm using here is that the control-component-factory does not include render props behaviour in lib/

2) If I try to build here, I get a failure (so I'm in `my-project/node_modules/react-redux-form`, i `npm install` and `npm run build`, this happens:

![image](https://user-images.githubusercontent.com/1906888/35197082-ccac986c-fea8-11e7-9913-985a332c9df1.png)

![image](https://user-images.githubusercontent.com/1906888/35197087-d2e1f948-fea8-11e7-9b99-1edb0116e09d.png)

I understand that `babel-preset-stage-2` is used (and `babel-preset-stage-2` includes `babel-preset-stage-3` which includes `transform-object-rest-spread`) so I'm not really sure what's going on here, but it seems possible that this is the issue which resulted in an incorrect publish.

**Comment by davidkpiano** [comment]
Can you try 1.16.5 and see if the same issue is there?

**Comment by joshacheson** [comment]
Looks correct. I'm totally confused as to what was wrong.
