### ISSUE TITLE
Custom events request

### ISSUE THREAD

**Issue by chrisblossom** [davidkpiano/react-redux-form#107]
Would be great if we could setup custom events directly to <input and have RRF work as expected.

For example:
```js
<Field model="user.foo" updateOn="blur">
  <input type="text" onChange={() => alert('changed')} onBlur={() => alert('blur')} />
</Field>
```

Order of actions would be ->
alert('changed') when changed and on blur:
```<input onBlur alert('blur') -->  <Field updateOn```

**Comment by davidkpiano** [comment]
Fixed in `0.9.5`!
