### ISSUE TITLE
Form input as an external component

### ISSUE THREAD

**Issue by hayola** [davidkpiano/react-redux-form#1071]
so I'm building a dynamic form (RRF). I have my set up as so - 

bookingForms: combineForms({
        bookHotel: {}
}),

However, I have created some of the form fields as a component outside the form itself; just for composition purposes. Now I'm having trouble getting my form values. How do I go about this, please?

**Comment by davidkpiano** [comment]
As in they're nested inside the form? How would you solve this in Redux? Those components can `dispatch` from anywhere in order to update the form correctly.

Alternatively, you can use `<LocalForm />` with the provided handlers in order to propagate your data.
