### ISSUE TITLE
What the reason bind twice: in the constructor and in the render() ? :)

### ISSUE THREAD

**Issue by wwwebman** [davidkpiano/react-redux-form#1075]
https://github.com/davidkpiano/react-redux-form/blob/00155f28496c69bdd2b1b7d1ac85b6cdd7b99c7f/examples/quick-start/components/user-form.js#L42

**Comment by davidkpiano** [comment]
Oh, good catch! Mind making a PR to fix that?

**Comment by wwwebman** [comment]
https://github.com/davidkpiano/react-redux-form/pull/1076

**Comment by davidkpiano** [comment]
Closed in #1076
