### ISSUE TITLE
How do you tell if form submit attempt has occurred?

### ISSUE THREAD

**Issue by im1dermike** [davidkpiano/react-redux-form#1077]
When I look at the `$form` of my form, I see the following boolean properties:

	focus
	pending
	pristine
	retouched
	submitFailed
	submitted
	touched
	valid
	validated
	validating

In need to determine if an attempt was made to submit the form, whether it be successful or not.  I would expect the `submitted` property or even `submitFailed` to be used to indicate that, but not so.  If I open a form and immediately submit it, both of those properties are false.  The only time either is true is if I attempt to submit (unsuccessfully) and then correct any errors.  In that case, `submitFailed` turns true.

Something on `$form` should indicate if a submit has ever been attempted.  I understand I can dispatch my own action to set the form submission state, etc, but I can't believe this wouldn't be baked into this library.

**Comment by valorize** [comment]
When I submit a LocalForm my fieldValue's contain a falsy submitFailed property. But only if the browser doesn't prevent the submission beforehand. In my case Firefox did prevent the submission when my form contained input's which contain the attribute `required`. Firefox did show me a popup underneath the input then. So I had to do something like this:

```
const controlProps : Partial<ControlProps<HTMLSelectElement>> = {};
  if(partialInputProps.required) {
    delete partialInputProps.required;
    controlProps.validators = {
      valueMissing: (val) => val && val.length
    }
  }

<Control.input
        model={`.${name}`}
        {...controlProps}
        {...partialInputProps}
      />
```

**Comment by valorize** [comment]
@davidkpiano What you think would be the proper way to prevent that the Browser is doing HTML5 Validations?

**Comment by rikkit** [comment]
@valorize there is a section on HTML5 validation in the documentation. http://davidkpiano.github.io/react-redux-form/docs/guides/validation.html

I can't help you on the other issue - in my usage, either `submitted` or `submitFailed` are set on the root `$form` object of my form model (i.e. if my form is at `forms.foo`, check `forms.foo.$form.submitted`)

**Comment by valorize** [comment]
@rikkit Indeed there is a documentation which indicates to add noValidate to the Form component. But if I do so the form will happily call the onSubmit function although the input is required. So actually I want to have validation. But not browser validation. Maybe we should add `noBrowserValidate` as prop to the Form component?

**Comment by im1dermike** [comment]
@valorize Yes, it doesn't appear that the issues you brought up really pertain to the topic.

@davidkpiano Can you address my original issue?  It seems like basic functionality for a forms library that is not in place.

**Comment by davidkpiano** [comment]
@im1dermike I was under the impression that this was working as expected - can you create a minimal code example to show the issue?

**Comment by im1dermike** [comment]
@davidkpiano I can try if need be, but can you explain the expected behavior you built for determining at the form-level if a submit was attempted?

**Comment by davidkpiano** [comment]
Actually, the property you want is `pending` - that tells you that a submit is in progress.

Since RRF has no way of knowing when a form is "submitted" (that is, when it successfully makes its round-trip to the API or whatever other business logic the developer might have for submitting), you have to manually dispatch `actions.setSubmitted(...)`. However, `actions.submit(promise)` abstracts this for you for most common use cases.

**Comment by im1dermike** [comment]
@davidkpiano I don't care about know when the submit the server completes.  The point in time I'm trying to identify via `$form` props is after the form is submitted (via a submit button) and after validation has fired.  `pending` is false when I submit the form.

**Comment by valorize** [comment]
@im1dermike Can't you listen for the submit action and set a redux state property to something alas `hasBeenSubmittedAtLeastOnce`
