### ISSUE TITLE
Action resetValidity(model, []) on string error generates object from string as error

### ISSUE THREAD

**Issue by marcinm2h** [davidkpiano/react-redux-form#1078]
### The Problem
Dispatching action resetValidity **with empty array as 'omitKeys' option** changes form[model].errors  to object generated from this error. (result of Object('string error')).
Also form[model].validity becames similar object.

### Steps to Reproduce
1. Set field errors to a string (action.setErrors(model, 'string error'))
2. Dispatch action resetValidity with empty arrray as 'omitKeys' parameter (actions.resetValidity(model, []))

### Reproducible Code Example
https://codepen.io/marcinm2h/pen/BYjLRY

**Comment by marcinm2h** [comment]
Probably  changing https://github.com/davidkpiano/react-redux-form/blob/13ce5b0fcaa8597accffa8b0af901f28e5b1f00a/src/reducers/form-actions-reducer.js#L233

`if (action.omitKeys) {...}`

to

`if (action.omitKeys && action.omitKeys.length > 0) {...}`

Would do the job. I'll check it later.

**Comment by davidkpiano** [comment]
Could you create a PR for this? I'll merge it in ASAP.

**Comment by marcinm2h** [comment]
https://github.com/davidkpiano/react-redux-form/pull/1079

**Comment by davidkpiano** [comment]
Closed in #1079
