### ISSUE TITLE
Update fields from custom reducer

### ISSUE THREAD

**Issue by andrewQwer** [davidkpiano/react-redux-form#108]
Hi, could you please help me with the following issue:
I have a custom reducer that I wrap with modeled enhancer. 
```javascript
var editUserReducer = function (state, action) {
case actionTypes.RECEIVED_EDITED_USER:
            return _.assign({}, state, action.payload);
....
}
module.exports = modeled(editUserReducer, 'editUser');
```

RECEIVED_EDITED_USER action occurs after AJAX request to server that returns some user data like firstName, lastName etc.
Values are correctly updated in the store:
![image](https://cloud.githubusercontent.com/assets/710513/14140524/1a083ed0-f682-11e5-9208-b43ef9d1085e.png)
but on UI firstName field remains empty.
This is how I declare my Field
```html
<Field model="editUser.firstName">
    <div className="flex-row">
           <label htmlFor="firstName" className="control-label">First name</label>
           <input type="text" id='firstName' className="form-control width240" placeholder="First name"/>
    </div>          
</Field>
```
What am I doing wrong? How to update UI fields from AJAX result?

**Comment by chrisblossom** [comment]
This might be bad practice (if so, someone please clarify), but I think you need to add ```value={store.getState().editUser.firstName}```.

```js
...
class App extends Component {
...
  render() {
  const store = this.context.store;

  return {
    <Field model="editUser.firstName">
        <div className="flex-row">
               <label htmlFor="firstName" className="control-label">First name</label>
               <input type="text" value={store.getState().editUser.firstName} id='firstName' className="form-control width240" placeholder="First name"/>
        </div>          
    </Field>
  }
}

App.contextTypes = {
  store: React.PropTypes.object,
};
```

**Comment by andrewQwer** [comment]
@chrisblossom I have direct access to `editUser` through props, so I can use it like this:
`value={this.props.editUser.firstName} ` and it works, but I thought that input value should be updated according to state anyway.

**Comment by davidkpiano** [comment]
This is related to https://github.com/davidkpiano/react-redux-form/issues/97 . I'm starting to think that if the Field `updateOn` is `"change"`, then the component should be a controlled component.

Agree? :+1:  :-1: @chrisblossom @jekamoroz @andrewQwer

**Comment by chrisblossom** [comment]
Initially I disagree. It either limits how you display your values or requires another "displayParser=" option.

Imagine you want to store a phone number in redux without any special characters/only numbers, so 2085551234 but you want to display to the user a formatted number, (208) 555-1234. Currently you would parse the value inside the store using ```value={this.props.value ...}```

If value={} is automatically added to <Field, then this would not be possible without RRF creating a displayParser option, which gets confusing...is it only for updateOn change? Blur?

Maybe I am missing something though. Very possible.

**Comment by davidkpiano** [comment]
@chrisblossom has a good point. The controls being unconnected might be a little annoying (in that you have to pass in the value to make it connected), but it also gives you the ability to format the value however you want without having to learn yet _another_ ad-hoc `<Field>` property.

```js
<Field model="user.phone"
  parser={parsePhone}
  formatter={unparsePhone}>
  <input />
</Field>
```
as opposed to just:

```js
<Field model="user.phone"
  parser={parsePhone}>
  <input value={unparsePhone(user.phone)}/>
</Field>
```

**Comment by davidkpiano** [comment]
I think the best solution right now is to just pass it into your value. Controls are uncontrolled by default (which is a feature, not a bug :wink: ) to provide lots of flexibility to you, the developer. If we make them controlled, it will become much more complicated to do custom things with the values and the model value updates.

So here's the fix:
```diff
<Field model="editUser.firstName">
    <div className="flex-row">
           <label htmlFor="firstName" className="control-label">First name</label>
           <input type="text"
                id='firstName'
                className="form-control width240"
                placeholder="First name"
+               value={editUser.firstName}
            />
    </div>          
</Field>
```

Hope that helps :smile:
