### ISSUE TITLE
Form is in a dirty state even after submitting

### ISSUE THREAD

**Issue by reneeichhorn** [davidkpiano/react-redux-form#1081]
### The Problem
When submitting a form (`rrf/setSubmitted`) the form is still considered to be dirty (`pristine` is `false`)

### Steps to Reproduce
Change something in a form (causing `pristine` to be `false`)
Then call setSubmitted on the form.

### Expected Behavior
The form should be pristine after data has been successfuly submitted.

### Actual Behavior
`pristine` of the form is still `false`

**Comment by davidkpiano** [comment]
That's expected behavior. Your form has been touched, so it's no longer pristine. You can always `dispatch(actions.setPristine('yourForm'))` to override this behavior after submit.

**Comment by reneeichhorn** [comment]
Isn't it a weird that a form is dirty even after it has been submitted? Usually you would use the `pristine` flag to determine whether or not the form has been saved yet. For example when the user navigates away without submitting data you would check if the form is `pristine` or not to warn the user that the form needs to be saved first.

**Comment by rikkit** [comment]
`pristine` means whether a user has interacted with a form or not. That's different information to whether the form has been submitted (which is indicated with `submitted` or `submitFailed`).
