### ISSUE TITLE
Is it possible to pass defaultValue property to custom component?

### ISSUE THREAD

**Issue by lenadss** [davidkpiano/react-redux-form#1082]
Hi

On a form I have to use one custom component (company standard) which requires property with the name **defaultValue** to display preselected value.
 I've tried several options like: 
 ```
<Control.custom
            model=".maxSwapTradeLimit"
            component={CustomComponent}
            controlProps={{
              defaultValue: (item) => item.modelValue,
            }}
            mapProps={{
              onChange: (item) => item.onChange,
            }}
          />
```
or
```
<Control.custom
            model=".maxSptFwdTradeLimit"
            component={CustomComponent}
            mapProps={{
              precision: 2,
              defaultValue: (item) => item.modelValue,
              onChange: (item) => item.onChange,
            }}
          />
```
But in both cases **defaultValue** property on **CustomComponent** is empty
In second case **defaultValue** property is propagated correctly to **ComponentWrapper**, after that it becomes empty.

In one of the issues here I saw your response:

>  defaultValue is for uncontrolled components, and technically, all RRF components are controlled components. In order to prevent conflicts/warnings and to preserve the intent of the developer, defaultValue in RRF is just a proxy for setting the initial value of the model. 

So my question is there any way to pass **defaultValue** to CustomComponent as it is??

**Comment by davidkpiano** [comment]
If it's preselected, wouldn't that just be the value? That is, there shouldn't be a need for a special `defaultValue`.

Anyway, you can always just wrap your `CustomComponent` in one that exhibits the correct behavior - such as one that takes the `modelValue` from RRF, and sets it as `defaultValue` to your inner `CustomComponent` if it's not set yet.

**Comment by lenadss** [comment]
Thanks for the idea! I didn't think about such solution :smile:  It works perfectly!
