### ISSUE TITLE
onSubmitFailed

### ISSUE THREAD

**Issue by kkashou** [davidkpiano/react-redux-form#1083]
I have a form that I am trying to submit and every form element is passing through validations but it is still going through onSubmitFailed function that I created.

When I console.log(e) looked under $form.errors ... I get an empty object.

What are ways for me to debug what is making the form submission go to the onSubmitFailed function as oppose to going to the onSubmit function?

I did noticed that when I update a type field of number in the redux form modal it changes the value from number to a string. I am wondering if this is the case, if so how can maintain its type? 

Thanks.

**Comment by davidkpiano** [comment]
Can you please share the code?
