### ISSUE TITLE
Simple Redux-Form Signin returns undefined / does not recognise fields?

### ISSUE THREAD

**Issue by juliathefoolya** [davidkpiano/react-redux-form#1086]
Just created this form as part of a tutorial. However, my console log is giving me `undefined` whenever I submit the form. What am I doing wrong? It should be fairly straightforward!

    import React, {Component} from 'react';
    import { reduxForm } from 'redux-form';
    
    class Signin extends Component {
      handleFormSubmit({email, password}) {
        console.log(email); // this gives me 'undefined'
      }
      render() {
        const {handleSubmit, fields: {email, password}} = this.props;
    
        return (
        <form onSubmit={handleSubmit(this.handleFormSubmit.bind(this))}>
          <fieldset className="form-group">
          <label>Email:</label>
          <input {...email} className="form-control" />
          </fieldset>
          <fieldset className="form-group">
          <label>Password:</label>
          <input {...password} className="form-control" />
          </fieldset>
          <button action="submit" className="btn btn-primary">Sign in</button>
        </form>
        );
      }
    }
    
    export default reduxForm({
      form: 'signin',
      fields: ['email', 'password']
    })(Signin);

**Comment by davidkpiano** [comment]
Wrong library. You're looking for [redux-form](https://github.com/erikras/redux-form/issues/).
