### ISSUE TITLE
Changelog / history ?

### ISSUE THREAD

**Issue by kmudrick** [davidkpiano/react-redux-form#109]
It is extremely tough to tell what has changed from release to release (recently.)

I notice that the github "releases" page had release notes for lots of versions up to v0.8.0 (which in github is tagged as "latest" release, too), but there have literally been like 20 releases since then, with no notes.

**Comment by davidkpiano** [comment]
Ah, sorry about that. I'll go ahead and write release notes for 0.9.0.

**Comment by davidkpiano** [comment]
Updated here: https://github.com/davidkpiano/react-redux-form/releases/tag/v0.9.4
