### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by KO527** [davidkpiano/react-redux-form#1096]
### The Problem
In the console, it tells me: Uncaught TypeError: Cannot read property 'length' of undefined

### Steps to Reproduce
import React, { Component } from 'react';
import { actions, Control, Form, Errors } from 'react-redux-form';

class ContactInfo extends React.Component{

        constructor(props){
                super(props);
        }

        handleSubmit(user){
                const {dispatch} = this.props;

                let userPromise = fetch('/ContactInfo', {
                        method: "POST",
                        body: JSON.stringify({email: user.email,
                                              password: user.password,
                                              passwordConfirmation: user.passwordConfirmation})
                }).then((response) => {
                        dispatch(actions.change(user.email, response.body.email));
                        dispatch(actions.change(user.password, response.body.password));
                        actions.setSubmitted('basicUserInfo', true);
                });
        }

        render(){

                const passwordsMatch = ({ password, passwordConfirmation }) => {
                     return password === passwordConfirmation;
                }

                return (

                        <Form id = 'contactInfo' model = "basicUserInfo" onSubmit = {(user) => this.handleSubmit(user)} validators = {{'': passwordsMatch}}>
                                <div className = "field">
                                        <label> Email: </label>
                                        <Control.text model = ".email"
                                              placeholder = "Email"
                                              required
             problem here --> // validators = {{maxLength: (value) => value.length <= 255 }}
                                              validateOn = "blur"/>
                                        <Errors className = "errors"
                                                model = ".email"
                                                show = {{touched: true, focus: false}}
                                                messages = {{required: 'Email is required', maxLength: 'Must be less than 255 characters'}}/>
                                        <Control.text model = ".password"
                                                      placeholder = "Password"
                                                      required
                                                      validators = {{ maxLength: (val) => val.length > 6}}
                                                      validateOn = "blur"/>
                                        <Errors className = "errors"
                                                model = '.password'
                                                show = {{touched: true, focus: false}}
                                                messages = {{required: 'Password is required', maxLength: 'Must be more than six characters'}}/>
                                        <Control.text model = ".passwordConfirmation"
                                                      placeholder = "Confirm Password"
                                                      validateOn = "blur"/>
                                        <button type = "submit">
                                                Submit
                                        </button>
                                </div>
                        </Form>
                )
        }
}

export default ContactInfo

{
  "name": "redux-simple-starter",
  "version": "1.0.0",
  "description": "Simple starter package for Redux with React and Babel support",
  "main": "index.js",
  "repository": "git@github.com:StephenGrider/ReduxSimpleStarter.git",
  "scripts": {
    "dev": "webpack",
    "start": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "test": "mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive ./test",
    "test:watch": "npm run test -- --watch"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "chai": "^3.5.0",
    "chai-jquery": "^2.0.0",
    "jquery": "^2.2.1",
    "jsdom": "^8.1.0",
    "mocha": "^2.4.5",
    "react-addons-test-utils": "^0.14.7",
    "babel-preset-stage-0": "^6.5.0"
  },
  "dependencies": {
    "babel-preset-stage-2": "^6.24.1",
    "lodash": "^3.10.1",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "react-redux": "4.3.0",
    "react-redux-form": "^1.16.5",
    "react-router": "^2.0.1",
    "react-router-dom": "^4.2.2",
    "redux": "^3.5.2",
    "validator": "^9.4.1",
    "webpack": "^1.13.1",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": "^1.14.1",
    "webpack-hot-middleware": "^2.11.0"
  }
}

~                                                                                                                                                                   
~                                 

### Expected Behavior

I expect nothing to be erroneous in the console pertaining to the line with the actual parameter 'value' in the validators prop within the Control.text

### Actual Behavior

There is a problem with that line.

### Reproducible Code Example
(please fork from [this CodePen template](http://codepen.io/davidkpiano/pen/yJwmEa) or [this CodeSandbox template](https://codesandbox.io/s/k3jyzwqo53))

**Comment by davidkpiano** [comment]
How is your store created? When you create a validator, you have to account for all possibilities. In this case, you should probably have `(value) => value && value.length < 255`.
