### ISSUE TITLE
change className of Control.Text, when validation is false

### ISSUE THREAD

**Issue by khaninD** [davidkpiano/react-redux-form#1097]
### The Problem
How i can change className of Control.Text, when validation is false ?

**Comment by davidkpiano** [comment]
See "How do I add conditional class names based on field state?" here: http://davidkpiano.github.io/react-redux-form/docs/guides/faqs.html

**Comment by khaninD** [comment]
functions in mapProps are called each time, when value changed, but i want change className onBlur event ... i try use updateOn='blur', it's not working...

**Comment by rztiwari** [comment]
I a facing the same issue. @khaninD  were you able to resolve the issue. I am using LocalForm in my case.

**Comment by rdak** [comment]
Try to use it:
```
<Component :
mapProps={{
  className: (field) => {
    if (!field.fieldValue.valid) {
      return "errorClass";
    }
    else {
      return "anotherClass");
    }
}}
```
