### ISSUE TITLE
fieldValue.validity false in mapProps when componentDidMount

### ISSUE THREAD

**Issue by khaninD** [davidkpiano/react-redux-form#1098]
### The Problem
i set validators
`                    validators={{
                      required,
                      EMAIL_VALIDATION
                    }}`
I set mapProps,
`                    mapProps={{
                      errorText: ({ fieldValue }) => {
                        if (fieldValue.validity) {
                          if (!fieldValue.validity.required) {
                            return FIELD_REQUIRED
                          } else if (!fieldValue.validity.EMAIL_VALIDATION) {
                            return EMAIL_INVALID
                          }
                        } else {
                          return ''
                        }
                      }
                    }}`
but, when component didMount, fieldValue.validity.required is false, but why? i set validateOn='blur', but it's not working...

**Comment by davidkpiano** [comment]
Please post a working code example and I will reopen this.
