### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by KO527** [davidkpiano/react-redux-form#1101]
### The Problem
In the console, I am getting 'Uncaught TypeError: Cannot read property 'length' of undefined' for the line specified below.

### Steps to Reproduce
     render(){
	
                const validateEmail = ({email}) => {
		      var VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i;
		      return VALID_EMAIL_REGEX.test(email);	
		}

		const onSubmitFailed = () => {
		 	var emailText = document.getElementsByClassName('emailText').value;
		 	var passwordText = document.getElementsByClassName('passwordText').value;
		
          
	   ------->	if (!passwordText && passwordText.length < 6){
		 		document.getElementsByClassName('passwordErrors').innerHtml = passwordText 
                                 + ' is not valid. Need at least six characters.';
		 	} else if (!emailText || emailText.length > 255 || !validateEmail(emailText)){
		 		document.getElementsByClassName('emailErrors').innerHtml = emailText + ' is 
                           not valid.';
		 	}
		}		
		
		return(
			
			<div className = 'ContactInfo'>
			<Form id = "contactInfo" model = "basicUserInfo" onSubmit = {(user) => 
                          this.handleSubmit(user)} validators = {{'': onSubmitFailed()}}>
				<div className = "field">
					<label> Email: </label>
					<Control.text model = ".email"
					      className = "emailText"
					      placeholder = "Email"
					      required
					      validators = {{maxLength: (val) => val && val.length < 255 }}
					      validateOn = "blur"/>
					   <div className='errors'>
					 	<span className='emailErrors'>
						</span>
					   </div>
			    </div>
				<div className = "field">	
					<label> Password: </label>
					<Control.text model = ".password"
						      placeholder = "Password"
						      className = 'passwordText'
						      required
						      validators = {{ maxLength: (val) => val && val.length > 6}}
						      validateOn = "blur"/>
					<div className='errors'>
					    <span className='passwordErrors'>
				        </span>
				    </div>		
			    </div>
				<button type = "submit">
				 	Submit
				</button>
			</Form>
                        <PasswordConfirmation password = 
                        {document.getElementsByClassName('passwordText').value} />
			</div>				
		)
}
		

### Expected Behavior
I expect the console to comply with what is happening in the code on npm start. 

### Actual Behavior
Only Babel says everything has compiled successfully on npm start

### Reproducible Code Example
(please fork from [this CodePen template](http://codepen.io/davidkpiano/pen/yJwmEa) or [this CodeSandbox template](https://codesandbox.io/s/k3jyzwqo53))

**Comment by davidkpiano** [comment]
This is wrong:

```
!passwordText && passwordText.length < 6
```

Check the boolean logic.
