### ISSUE TITLE
Custom reducer which just enhances state of the whole form

### ISSUE THREAD

**Issue by MatejMazur** [davidkpiano/react-redux-form#1109]
First of all I would like to thank you for this lib. It's super useful! 👍 

### The Problem
I can't to find a solution where I can add custom reducer into the form reducer process. If I'll include custom reducer to the plugins array, it's not called when form's action is dispatched. I've found that whenever some action is called it just only returns state because of this condition which is before of the plugin call at the end of the `wrapFormReducer`: https://github.com/davidkpiano/react-redux-form/blob/02b096492e6d7bef371f80ffeaea0f9502bcbf88/src/reducers/form-reducer.js#L26-L28
I think that I probably don't understand how to properly use it.

My intention is to be able to fill some fields and then it must be calculated some following (dependent) fields which are used for conditional rendering of another fields and that continues in the same spirit. 

More in depth (not important for the issue):
So I need access to the whole form state and I need to react on every change in the form because there are complex dependencies between fields (some fields are calculated but immediately used in others and some fields are both: input and output (because there are some calculated default values which user can rewrite but it needs an access to the default value in case he needs to restore some parts of the form). This type of form is a little bit similar to the Excel behavior. 
A user needs to find the best solution in his project so there are some helper (but heavy) calculations, charts etc.. I think that Redux is for this the best solution as you can separate very clearly business logic from the UI.

### Steps to Reproduce
`store.js`
```js
...
createStore(
  combineReducers({
    foo: fooReducer,
    formData: combineForms({ user: initialUserState }, 'formData', {
      plugins: [customReducer]
    })
  })
)
```
`customReducer.js`
```js
export const customReducer = (state, action) => {
  console.log(state, action);
  return state;
};
```
### Expected Behavior
It should log form's state and action.

### Actual Behavior
It's not called at all.

### Reproducible Code Example
https://codesandbox.io/s/jp0yvnwxvw

**Comment by davidkpiano** [comment]
Have you looked into using `modeled` instead?

**Comment by MatejMazur** [comment]
Thank you for your quick response! 

I was stupid because I didn't noticed that I can so easily to react on form's change. Sry about that.

Best regards,
Matt
