### ISSUE TITLE
getFormStateKey has an infinite loop when key = ""

### ISSUE THREAD

**Issue by bugzpodder** [davidkpiano/react-redux-form#1113]
I have an edge case in redux state where one of my objects has an empty key:
{
  ... {
          "first": { }
          "second": {}
          "": {}
  }
}

This trips up getFormStateKey and causes infinite recursion because it calls utils/get and returns itself.
https://github.com/davidkpiano/react-redux-form/blob/9d354f5e821212bac01bfdb2b9eff836959192ed/src/utils/get.js#L13
Called here: https://github.com/davidkpiano/react-redux-form/blob/9d354f5e821212bac01bfdb2b9eff836959192ed/src/utils/get-form.js#L60

{error: "RangeError: Maximum call stack size exceeded↵    } 

 RangeError: Maximum call stack size exceeded
    at http://----/static/js/bundle.js:117621:32
    at Array.filter (<anonymous>)
    at joinPaths (http://-----/static/js/bundle.js:117621:16)
    at http://------/static/js/bundle.js:117674:59
    at Array.some (<anonymous>)
    at getFormStateKey (http://------/static/js/bundle.js:117673:21)
    at http://------/static/js/bundle.js:117674:14
    at Array.some (<anonymous>)
    at getFormStateKey (http://------/static/js/bundle.js:117673:21)
    at http://------/static/js/bundle.js:117674:14

**Comment by davidkpiano** [comment]
Seems like a simple fix, want to make a PR? (check if the path is empty _and_ the original string isn't just an empty string, etc.)

**Comment by bugzpodder** [comment]
Yep i'll check it out.
