### ISSUE TITLE
Submitting a form issues an (empty) action regardless of actual code

### ISSUE THREAD

**Issue by Rhywden** [davidkpiano/react-redux-form#112]
This happened after doing an `npm update` just now, going from 0.9.0 to 0.9.5

I have a form defined like thus:

```
<Form model="user"
    validators={{
        username: {required},
        password: {required}
    }}
    onSubmit={(e) => onLoginClick(e)} >
        <MTextField model="user.username">
            <TextField floatingLabelText="Username"/>
        </MTextField><br />
        <MTextField model="user.password">
            <TextField floatingLabelText="Passwort" type="password"/>
        </MTextField>
        <p>{message}</p>
        <RaisedButton label="Login" type="submit"/>
        <p>Zur <a href="javascript://" onTouchTap={e => switchTabs()}>Registration</a>.</p>
</Form>
```

and upon clicking the login button, I get this:

`Actions may not have an undefined "type" property. Have you misspelled a constant?`

The `onLoginClick() `function never gets executed. It also worked as it should before the update. I'm not quite sure what "action" is actually dispatched - all of _my_ defined actions do indeed have a return value containing a type property.

(MTextField is just a wrapper for MaterialUI - and before you ask, replacing MaterialUI with standard inputs changes nothing).

**Comment by Rhywden** [comment]
Just played a bit with the version numbers - the breakage occurs when going from 0.9.0 to 0.9.1

**Comment by davidkpiano** [comment]
What does the wrapper look like?

**Comment by Rhywden** [comment]
```
import { createFieldClass, controls } from 'react-redux-form';

const MTextField = createFieldClass({
    'TextField': controls.text
});

export default MTextField
```

Taken straight from the docs.

**Comment by Rhywden** [comment]
Okay, it's an issue with the validation which makes sense, considering the commits between 0.9.0 and 0.9.1.

If I remove
```
validators={{
    username: {required},
    password: {required}
}}
```
it doesn't throw an error anymore.

**Comment by davidkpiano** [comment]
Do you have a `userForm`? http://esnextb.in/?gist=68b03db2ad0182c5915ed2dec1176c85

**Comment by Rhywden** [comment]
You mean this? https://github.com/Rhywden/nawischule/blob/master/client/reducers.jsx

**Comment by davidkpiano** [comment]
Try it now with `react-redux-form@0.9.7` (just published) - the batch validation action has been refactored and a couple more test cases added, which _should_ solve your issue.
