### ISSUE TITLE
form is still invalid when passwords and confirm password are match

### ISSUE THREAD

**Issue by pranabunni** [davidkpiano/react-redux-form#1127]
### The Problem
i am doing password validation in react-redux by adding validators to the form .But when i submit the form it still invalid even when the two fields are equal.

### Reproducible Code Example
(please fork from [this CodePen template](http://codepen.io/davidkpiano/pen/yJwmEa) or [this CodeSandbox template](https://codesandbox.io/s/k3jyzwqo53))

**Comment by davidkpiano** [comment]
I need to see an example.
