### ISSUE TITLE
<select value={}> doesn't work

### ISSUE THREAD

**Issue by freddi301** [davidkpiano/react-redux-form#113]
http://facebook.github.io/react/docs/forms.html#why-select-value

And any other dispatched actions to change model doesn't update the view

**Comment by davidkpiano** [comment]
What doesn't work about `<select value={}>`? Can you post some working code that demonstrates the issue?

**Comment by freddi301** [comment]
[h3g_ir.zip](https://github.com/davidkpiano/react-redux-form/files/204038/h3g_ir.zip)

file app/components/tableModel.js line 56

it works without enclosing <Field>...</Field>

start the project with:
npm start
npm run dev
open localhost:8080
