### ISSUE TITLE
Displaying Field Errors

### ISSUE THREAD

**Issue by harry-sm** [davidkpiano/react-redux-form#1132]
### The Problem
Hello, 
I was wondering if there is a way to display errors one at a time on a field.
![image](https://user-images.githubusercontent.com/15040197/38177802-07dcaeec-35d4-11e8-826c-c0bd1ebbc7a6.png)

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/15040197/38177812-3df4cd98-35d4-11e8-8d66-0b4b5873f480.png)

### Desired Behavior
Display the first error message from the list.
![image](https://user-images.githubusercontent.com/15040197/38177950-79a0287c-35d6-11e8-8f08-cb2d4c1bdbf4.png)

Thanks.

**Comment by davidkpiano** [comment]
In `component`, the `children` passed into the `ErrorMessage` are the array of error messages (as spans, by default). Just render only the first child.
