### ISSUE TITLE
How to style error message text in <Errors> component?

### ISSUE THREAD

**Issue by elmarini** [davidkpiano/react-redux-form#1142]
Hi, I'm using React Native and I can't seem to figure out how to style the error message. 
I have a CustomError component but the styles arent applying:
```   
<Text style={{ color: 'red' }}>
   {children}
</Text>
```
This is how the rest of the file looks like: 
```      
<Control.TextInput
        style={style}
        model={model}
        validators={validators}
      />
      <Errors
        model={model}
        messages={errorMessages}
        component={CustomError}
        show={{ touched: true, focus: false }}
      />
```
Any help would be greatly appreciated!

**Comment by davidkpiano** [comment]
What does `CustomError` look like?

**Comment by elmarini** [comment]
Sorry, closing this issue, wasn't passing in the right props.
