### ISSUE TITLE
Showing a specific form level validator error

### ISSUE THREAD

**Issue by tomspeak** [davidkpiano/react-redux-form#1145]
### The Problem
When using a form level validator e.g:

```
<Form
  validators={{
    '': {
      isLocationValid: ({ x, y }) => {
        if (x) {
          return true;
        }
        return y;
      },
    },
  }}
>
```

I have found it difficult to display the correct error message for `isLocationValid`.

```
<FieldErrors
  model="."
  messages={{ isLocationValid: 'Field required' }}
  show={_ =>
    jobFormFields.location.touched &&
    !jobFormFields.location.focus
  }
/>
```

With FieldErrors.jsx looking like:

```jsx
import React from 'react';
import { Errors } from 'react-redux-form';

const FieldErrors = props => {
  return (
    <Errors
      show={{ touched: true, focus: false }}
      wrapper={props => (
        <div className="field-errors t-small t-trim">{props.children}</div>
      )}
      {...props}
    />
  );
};

export default FieldErrors;
```

Now, this works, with a few edge cases, but the issue is that when I use `actions.submit()` that returns an error, all instances of `FieldErrors` with `model="."` (I have a few) displays the form level error that is returned from the failed submission. 

Any insight in how best to approach this would be appreciated.

### Reproducible Code Example
Let me know if you need to see the code, this is most likely me misusing the API.

**Comment by tomspeak** [comment]
@davidkpiano  -  do you require a code example? I assumed I was abusing `model="."` - I searched through every issue I could find without finding anything similar.

**Comment by davidkpiano** [comment]
A code example would be helpful.

**Comment by tomspeak** [comment]
@davidkpiano  - https://codesandbox.io/s/rm4yvjo7m4

A slightly convoluted example, but close to what I am doing. If you check the box, it'll show the necessary validation message, but when you make an API request via `submit()`, the error returned will also be shown in the title's `Error` component - this makes complete sense as I am using `model="."` - was wondering how to get this behaviour to work so I can have one error message that will validate two fields (a good example being a salary range, or fields that are only required if another field is filled out).

**Comment by tomspeak** [comment]
@davidkpiano  - I was wondering if my code example was enough to demonstrate the problem?  Cheers!

**Comment by tomspeak** [comment]
hey @davidkpiano, was wondering if you had a chance to look this over? Thanks

**Comment by davidkpiano** [comment]
Sorry, I don't. But nothing's stopping you from reading the values directly from the `store` and creating your own Error component that does what you want.

**Comment by tomspeak** [comment]
If anyone is unfortunate enough to have to show errors for form wide validations like me, this may be the dirty hack you need.

```js
import React from 'react';
import { Errors } from 'react-redux-form';

const FieldErrors = props => {
  const { field, error } = props;
  let show;

  // If we have passed a field, it is a custom Form level validation error.
  if (field) {
    // If the error key we passed exists, only show if we have interacted with the field.
    // If the key no longer exists, it means the form has submitted an error and the key was wiped, thus do not show it.
    show = error ? field.touched && !field.focus : false;
  } else {
    // Generic inline form error logic.
    show = {
      touched: true,
      focus: false,
    };
  }

  return (
    <Errors
      show={show}
      wrapper={props => (
        <div className="field-errors t-small t-trim">
          {props.children} {props.error}
        </div>
      )}
      {...props}
    />
  );
};

export default FieldErrors;
```

Used like so:

```js
<FieldErrors
  model="."
  field={jobFormFields.compensation_to}
  error={jobFormForm.errors.isValidCompensation}
  messages={{
    isValidCompensation: 'Invalid salary range',
    isRequired: MESSAGES.isRequired,
  }}
/>
```
