### ISSUE TITLE
Cannot import { createModelReducer } from 'react-redux-form/immutable' installed via npm

### ISSUE THREAD

**Issue by freddi301** [davidkpiano/react-redux-form#115]

**Comment by davidkpiano** [comment]
It should be working per this spec: https://github.com/davidkpiano/react-redux-form/blob/master/test/immutable-model-reducer-spec.js

Can I see a full code example of it not working?

**Comment by freddi301** [comment]
same project as here: https://github.com/davidkpiano/react-redux-form/issues/113

try to import in this project

I see that spec is working because imported from .../src/...

but if i try to import it simply by `import { createModelReducer } from 'react-redux-form/immutable'` the file cannot be find

**Comment by davidkpiano** [comment]
Sorry, it should be:

```diff
- import { createModelReducer } from 'react-redux-form/immutable';
+ import { modelReducer } from 'react-redux-form/lib/immutable';
```

Is there somewhere in the documentation that has `react-redux-form/immutable` instead of `react-redux-form/lib/immutable`?

**Comment by freddi301** [comment]
I couldn't find it in documentation.
You should update README.
Thank you for reply
