### ISSUE TITLE
[React Native Issue] Expected a component class, got div. 

### ISSUE THREAD

**Issue by dodomasta** [davidkpiano/react-redux-form#116]
Hi, I get this issue when trying to use with RN:
Expected a component class, got div. Each component name should start with an uppercase letter.
Any idea on how to solve ?

**Comment by davidkpiano** [comment]
Are you trying to put in more than one child component inside `<Field>` ?

For now, try adding:
```js
import { View } from 'react-native';

<Field model="..."
  component={View}>
  ...
</Field>
```

**Comment by davidkpiano** [comment]
Fixed here: https://github.com/davidkpiano/react-redux-form/commit/8f3cbb6d52e9d7e2673b3d802d92234a07e736c3 (ignore the incorrect commit title)
