### ISSUE TITLE
0.16.9 has invalid Typescript definitions

### ISSUE THREAD

**Issue by bjchambers** [davidkpiano/react-redux-form#1160]
### The Problem
Latest version fails when used with Typescript. Error is as follows:

react-redux-form.d.ts
(45,67): Cannot find name 'bool'.

### Steps to Reproduce

Use react-redux-form 0.16.9 with Typescript.

### Expected Behavior

No error -- type definitions work.

### Actual Behavior

Fails, as described above.

### Reproducible Code Example
https://codesandbox.io/s/qzvmpv0qp6

(Error does not show up in codesandbox, but reproduces after download and "yarn install", "yarn start").

**Comment by Alex0007** [comment]
@davidkpiano 
I think, there is another problem with types

```
node_modules/react-redux-form/react-redux-form.d.ts
(235,20): Cannot find name 'ChangeEvent'.
```

Typescript 2.9.2

**Comment by davidkpiano** [comment]
Please create a PR, thanks!
