### ISSUE TITLE
"Cannot find name 'bool'"

### ISSUE THREAD

**Issue by elijah-schow** [davidkpiano/react-redux-form#1181]
### The Problem

Cannot compile because the type definitions are invalid. 

### Steps to Reproduce
1. Upgrade to latest version (react-redux-form@1.16.9)
2. Try to compile react/typescript project

### Expected Behavior
Application compiles.

### Actual Behavior
Compile error:
> /Users/username/Dev/projectname/node_modules/react-redux-form/react-redux-form.d.ts
> (45,67): Cannot find name 'bool'.

**Comment by davidkpiano** [comment]
If you can fix it in a PR I'll merge it in.

**Comment by i4got10** [comment]
@davidkpiano its already fixed in master - https://github.com/davidkpiano/react-redux-form/issues/1160. Just need to release 1.16.10

**Comment by davidkpiano** [comment]
1.16.10 released!
