### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jzebgul** [davidkpiano/react-redux-form#1221]
import React from 'react';
import {connect} from 'react-redux';
import MemberListItem from './MemberListItem';
import selectMembers from '../selectors/members';

export const MemberList =(props) => (
    <div className="content-container">
    <div className="list-header">
      <div className="show-for-mobile">Members</div>
      <div className="show-for-desktop">Members</div>
     <div className="show-for-desktop">Packege</div>
    </div>
    <div className="list-body">
    {
      _**props.members.length === 0 ? (**_(getting error in this line any idea????
<div className="list-item list-item--message">       
  <span>No member</span>
</div>
) : (
    props.members.map((member) => {
      return <MemberListItem key={member.id} {...member} />;
    })
  )
}
</div>
</div>
    );

    const mapStateToProps = (state) => {
        return {
          members: selectMembers(state.members, state.filters)
        };
      };
      
      export default connect(mapStateToProps)(MemberList);

**Comment by davidkpiano** [comment]
If you have a fix, please make a PR with tests
