### ISSUE TITLE
How do I reset form errors with model state

### ISSUE THREAD

**Issue by fingermark** [davidkpiano/react-redux-form#13]
I'm calling actions.reset(model), which resets my model, but how do I also reset the form errors in my form state?  It seems that it should do that for me.

**Comment by davidkpiano** [comment]
Fixed here: https://github.com/davidkpiano/react-redux-form/commit/c6f8d8893064134f914a1979a26b935ee427a814

Now working when both updating form errors and field errors. Just npm install latest: `npm i react-redux-form@0.3.7 -s` :smile:

**Comment by fingermark** [comment]
Nice.  Fix works.
