### ISSUE TITLE
_createformReducer is not a function

### ISSUE THREAD

**Issue by bijoutrouvaille** [davidkpiano/react-redux-form#131]
I had a trip-up on this line. Looks like a typo.

https://github.com/davidkpiano/react-redux-form/blob/e82f5cb3f640862ca79a54f0394feb325fcc7b7a/src/reducers/form-reducer.js#L392

**Comment by davidkpiano** [comment]
Right, sorry about that. In 1.0, `createFormReducer` will be deprecated and it'll just be `formReducer`. For now (and the future) it's best to use `formReducer`. So this will be fixed in V1 :relieved:
