### ISSUE TITLE
Initial .validity and .errors state

### ISSUE THREAD

**Issue by chrisblossom** [davidkpiano/react-redux-form#136]
Currently the initial state for .validity and .errors is an empty plain object. I think they should both be set to null because they do not have to return an object.

[reducers/form-reducer.js#L28-L29](https://github.com/davidkpiano/react-redux-form/blob/master/src/reducers/form-reducer.js#L28-L29)

Proposed:
```js
const initialFieldState = {
  ...
  validity: null,
  errors: null,
};
```

**Comment by davidkpiano** [comment]
I'll consider this for 1.0, based on our discussions.

**Comment by davidkpiano** [comment]
I'm going to shelve this one for DX reasons, as the code developers would now have to write to prevent `Uncaught TypeError: Cannont read property '...' of null` errors would have to be more verbose:

```diff
-{form.field.errors && form.field.errors.required ? ... }
+{form.field.errors.required ? ... }
```

**Comment by chrisblossom** [comment]
FYI I had a breaking issue with this using Logstash/Elasticsearch to log redux state/actions. Because the type changed from an object to string, Elasticsearch would throw errors. Ended up having to instantly dispatch a redux action to reset the type of all errors and reset the database to clear the "learned" types.

**Comment by davidkpiano** [comment]
Oh, gotcha. In V1, this is supported:

```js
const myFormReducer = formReducer('foo', {}, {
  initialFieldState: { errors: null, validity: null }
});
```

if you want to override the initial field state. The signature is `formReducer(model, initialState, options)` where options is currently:

```js
{
  plugins: [],
  initialFieldState: {},
}
```

**Comment by chrisblossom** [comment]
That is awesome! Great news.
