### ISSUE TITLE
Question: Submit on blur with validation checking

### ISSUE THREAD

**Issue by asvetliakov** [davidkpiano/react-redux-form#138]
Thanks for library

1. My use case - i have few inputs which should be submitted separately on blur. It's convenient to treat them as form and have validation/ui state for them from the box.
I know about changeAction, but i need to perform client validation before:

```
const {field} = this.props;
<Field model="..."
           changeAction={() => { 
                dispatch(actions.change(...));
                // need to check client-side validity
                if (field.valid) {
                    dispatch(actions.submit(...));
               }
          }}
          changeOn="blur"
...
</Field>
```
2. Do you have analogue for blurAction? In this case i can set validation on field change and check validation state on blurAction and do/reject submit.
I can workaround by passing onBlur directly to input though, but i think it's not neat.

**Comment by davidkpiano** [comment]
Sorry about the GitMagic thing! Still working on configuring it.

Anyway, if you do `updateOn="blur"` instead of `changeOn="blur"` (nonexistent prop) then it should work as you have it.

**Comment by asvetliakov** [comment]
oh, yes, sorry, i mean ```updateOn="blur"``` of course.
Unfortunately this doesn't work, using your codepen example
```
        <Field model="user.username"
          validators={{
             isRequired,
            length: (v) => v.length > 1,
          }}
          changeAction={(model, value) => {
              store.dispatch(actions.change(model, value));
            store.dispatch(actions.setValidity(model, { length: false }));
            console.log(userForm.fields.username.errors.length); 
                       }}
          updateOn="blur"
          validateOn="blur">
          <label>Username</label>
....
```

after typing kkkk in field the ```userForm.fields.username.errors.length``` is still true because the userForm was binded into context (or re-render didn't happen yet, or something else)

**Comment by asvetliakov** [comment]
My fault, need ```validateOn="change"```
Sorry for bothering
