### ISSUE TITLE
Compatible with react-bootstrap?

### ISSUE THREAD

**Issue by arddor** [davidkpiano/react-redux-form#14]
Hi,

Is it possible to integrate the Field Component with the Input Component from react-bootstrap?

**Comment by davidkpiano** [comment]
I believe so; I haven't used react-bootstrap but if the custom components implement an "onChange" prop, it should work fine. I'll test it out and write some documentation on integrating RRF with react-bootstrap.

**Comment by markerikson** [comment]
Also wondering about react-widgets.

**Comment by davidkpiano** [comment]
Hey @markerikson and @arddor, I will be pushing up a small update shortly that gives full compatibility with any custom element that implements the "onChange" prop, so you can use <Field /> with those components! Docs coming soon!

**Comment by davidkpiano** [comment]
Working on dogfooding integration with react-bootstrap, and I found that its `<Input />` components do _not_ actually have `onChange` as a prop type, so RRF can't automatically detect those elements.

The good news, though, is I have an approach that allows you to explicitly tell RRF which components will be custom components:

```js
import { Field } from 'react-redux-form';
import { Input } from 'react-bootstrap';

// returns a new class that extends Field
// and maps the custom controls (keys) by name
// to the known controls (values) by name
const BSField = Field.mapControls({
  'Input': 'input'
});

// in your component's render() method
<BSField model="foo.bar">
  <Input type="text" />
</BSField>
```

What do you think of this approach? By being explicit, RRF can easily adapt itself to any 3rd-party component system, and this can be further customizable with a function that takes in the `<Field />` props and maps it to props on the custom componoent:

```
const MaterialField = Field.mapControls({
  'TextField': 'input',
  'RadioButtonGroup': (props) => ({
    name: props.model,
    valueSelected: props.modelValue
  }),
  'RadioButton': (props) => ({
    onCheck: props.onChange
  })
});

// ...
<MaterialField model="foo.bar">
  <TextField />
</MaterialField>
```

**Comment by markerikson** [comment]
Sounds good.

Sorta-vaguely-related question since I don't want to file an entire new issue: is it possible to set up RRF so that I can handle changes at the component state level first, rather than going straight as an action to a reducer?  Basically, I'd like to keep the total number of actions to a minimum (like, if I type 'a' five times real fast, I'd want to see a single action with 'aaaaa' rather than five actions with 'a', 'aa', etc).  

I've got a [quick and dirty HOC I threw together](https://gist.github.com/markerikson/554cab15d83fd994dfab) that lets me do some fancy footwork to keep keep stuff in state at first and only dispatch debounced.  Seems to work okay in the prototype I'm putting together, but I'm totally up for looking at more robust options other people have created.

**Comment by arddor** [comment]
I like the approach, well done!

**Comment by davidkpiano** [comment]
@markerikson There are two ways you can do this, both using `<Field />` and manually dispatching actions:

**With <Field />:** You can pass in a function to the `updateOn` prop that takes in the bound `change()` function internally, making debouncing as easy as this:
```js
<Field model="foo.bar"
  updateOn={(change) => debounce(change, 1000)}>
  <input type="text" />
</Field>
```

**With actions:** You can override the `change` prop:
```js
<Field model="foo.bar">
  <input type="text"
    onChange={(e) => debounce(() => actions.change('foo.bar', e), 1000)} />
</Field>
```

which is a little more verbose, but is essentially what `updateOn` does.

**Comment by davidkpiano** [comment]
@arddor @markerikson Okay, here is the semifinal syntax for creating custom `<Field />` components that can handle any 3rd-party library's components. I'll use [React Native](https://facebook.github.io/react-native/docs/textinput.html#content) as an example:

```js
import React from 'react';
import { TextInput } from 'react-native';

// createFieldClass() dynamically creates a custom <Field /> class
const NativeField = createFieldClass({
  'TextInput': (props) => ({
    ...props,
    defaultValue: props.modelValue,
    onChangeText: props.onChange
  })
});

// inside your component's render() method
<NativeField model="foo.bar">
  <TextInput />
</NativeField>
```

Now everything you expect in RRF like validation, focus, blur, change, etc. will be available to `<TextInput />`, and anything that goes through `onChangeText` will be sent to the `props.onChange` method instead.

How does this look? I would expect developers to _not_ have to handwrite this every time for common libraries, so this can easily be available as a plugin like `react-redux-form-native` or `react-redux-form-bootstrap`, or even available as part of RRF as it's a very small amount of code:

```js
import NativeField from 'react-redux-form/native';

<NativeField model="...">
  <TextInput />
</NativeField>
```

**Comment by markerikson** [comment]
I like it.  Looks pretty straightforward.

**Comment by davidkpiano** [comment]
For reference, you'd have to do this manually in Redux-Form, but it's essentially the same concept: https://github.com/erikras/redux-form/issues/334#issuecomment-182442713

**Comment by davidkpiano** [comment]
This will be landing soon! I will write docs/experiments but you can try it out now:

```bash
npm instal react-redux-form@beta
```

**Comment by davidkpiano** [comment]
Demos are now up (with material design): docs coming soon: http://davidkpiano.github.io/react-redux-form/#/recipe/custom-components

**Comment by arddor** [comment]
Awesome. However I have seen that no other recipe can be viewed. I assume that your changes have broken the other pages. Or is this just my problem?

**Comment by davidkpiano** [comment]
Sorry about that! Just pushed an update to the docs to fix that.

With that said, **react-redux-form@0.5.1** is out and yes, it can support 3rd-party and custom components!
