### ISSUE TITLE
setValidity/setErrors with top-level form model

### ISSUE THREAD

**Issue by asvetliakov** [davidkpiano/react-redux-form#142]
I thought something like this
```
dispatch(actions.setErrors("user", {
  email: {
    server: "Server validation fail" // server validation return custom error message
  },
  password: {
    server: "Server validation fail"
  }
});
```
will set corresponding errors/flag in **fields** level . Instead it does it in **form** top-level. Has it been intended? 
My use case is the client field validation + backend validation which can return an error and it will be assigned to ```field.name.errors.server``` . I don't want to mess them with form's errors because they should be field related.
I'm current forced to use something like it:
```typescript
const payload = returnedAction.payload as Error;
if (payload instanceof ValidationError) {
  let batchActions = [];
  Object.keys(payload.error).forEach(key => {
    batchActions.push(actions.setErrors(`signup.${key}`, {
      server: payload.error[key]
    }));
  })
  dispatch(actions.batch("signup", batchActions));
}
```
Is there any better way? Any thoughts?

**Comment by davidkpiano** [comment]
Yes, this is intended. This is because a field's validity can be a mapping of validation keys to validity:

```js
{
  required: true, // required is valid
  legalChars: false, // legalChars is invalid, contains illegal characters
}
```

And these are not fields, per se. In the future (pretty soon, probably tomorrow), I'll add the `setFieldsErrors` option, which will allow you to just do this:

```js
dispatch(actions.setFieldsErrors('signup', payload.error));
```

It will have the same semantics as `actions.setFieldsValidity`, except for errors instead of validity. Sound good?

**Comment by asvetliakov** [comment]
Yeah, that would be pretty good

**Comment by davidkpiano** [comment]
Okay, expect it tomorrow morning. Sorry for the delay!

**Comment by asvetliakov** [comment]
No rush, since ```actions.batch()``` is good workaround for now :smile:

**Comment by davidkpiano** [comment]
Now released in [v0.10.3](https://github.com/davidkpiano/react-redux-form/releases/tag/v0.10.3) !

**Comment by davidkpiano** [comment]
Well, naming stuff is hard. Grab from `v0.10.4` instead, the action is now called `validateFieldsErrors`.

https://github.com/davidkpiano/react-redux-form/releases/tag/v0.10.4

**Comment by asvetliakov** [comment]
Wow, that was very fast! Thank you
