### ISSUE TITLE
Submitting a form passes an empty model in production

### ISSUE THREAD

**Issue by Rhywden** [davidkpiano/react-redux-form#144]
Everything works fine in `NODE_ENV == 'development'`

It's when I hand over my app to my production server that my Login form sort of does not work anymore.

Basically, the outline of the form looks like this: 
```<Form model="user"
                      onSubmit={(user) => onLoginClick(user)}>```

But when I `console.log(user)` inside either the `onSubmit` or the `onLoginClick` all I get is the user model with empty values

![image](https://cloud.githubusercontent.com/assets/84586/14619977/9cd57188-05ba-11e6-94b8-c66fff3a7974.png)

Any ideas as to what's going on?

**Comment by davidkpiano** [comment]
Hmm interesting, is there anything else hiding behind production variables in your app? It's hard to diagnose this problem without seeing a full code example.

**Comment by Rhywden** [comment]
https://github.com/Rhywden/nawischule

Specifically: 
https://github.com/Rhywden/nawischule/blob/master/client/containers/TitleBar/LoginPopover.jsx
https://github.com/Rhywden/nawischule/blob/master/client/containers/TitleBar/LoginPopoverContainer.jsx

And, yes, I know that the validation is not exactly great at the moment :)

**Comment by davidkpiano** [comment]
Would you mind quickly adding `redux-logger` https://github.com/fcomb/redux-logger to your middleware and verifying that the state is in fact getting changed?

Material-UI is pretty buggy to work with at the moment - I'll investigate further.

**Comment by Rhywden** [comment]
Will do and get back to you tomorrow - it's a bit too late for me to be delving into this further.

**Comment by ffxsam** [comment]
I'm having a similar issue. Using the Chrome redux devtools extension, I can see that when I click in a field, there's no focus Redux dispatch action. And as I type, nothing happens in Redux either.

Paging @mbrookes of the material-ui project to see if he has any insight.

**Comment by ffxsam** [comment]
@davidkpiano Tomorrow I'll do a test case where I'll replace the fields with regular `<input>` fields and see if that makes it work.

**Comment by Rhywden** [comment]
@ffxsam Already did that. Regular `<input />` fields behave as they should both in development and production.

And, yes, MaterialUI textfields don't send the proper dispatches when in production.

Problem is that due to having upgraded to React@15 I cannot easily revert back to an earlier version of MaterialUI - would probably have to nuke the npm_modules folder and package.json and then try to rebuild everything, starting with a working version of MUI.

**Comment by ffxsam** [comment]
Well, the big question is: is this a MUI issue or an RRF issue?

**Comment by Rhywden** [comment]
The lack of error messages make such things always soooo much fun. I'm pretty sure that a language like C# would have already thrown an exception somewhere :)

**Comment by Rhywden** [comment]
Solved in #147

**Comment by davidkpiano** [comment]
Fantastic! In v1.0, I'll be introducing the `<Control>` component, which is just a lower-level component (`<Field>` uses it internally, currently).

The API would look something like this:

```js
import { controls, Control } from 'react-redux-form';
import TextField from 'material-ui/wherever';

// render...
<Control component={TextField} propsMap={controls.text} />
```

**Comment by ffxsam** [comment]
So the new `controls` and `Control` replace `createFieldClass`?

**Comment by davidkpiano** [comment]
Yes, even though `createFieldClass` will still work (I'll eventually deprecate it).

The idea is that `createFieldClass` enables the custom `Field` to "recognize" custom controls so it can know exactly how to map props/event handlers to it.

Soon, with `<Control>`, it will just recognize the `Control` and map the props according to the `Control`'s props.

Although, in many cases, you won't even need `<Field>`:

```js
// FUTURE SYNTAX!
import { Control } from 'react-redux-form';

// instead of this...
<Field model="foo.bar">
  <input type="text" />
</Field>

// it will look like this...
<Control.input type="text" model="foo.bar" />
```

This does _not_ mean that `<Field>` will be deprecated, or that there will be any breaking changes, thankfully :)

**Comment by ffxsam** [comment]
Excellent! Question about this:

```
<Control component={TextField} propsMap={controls.text} />
```

How would I pass props into `TextField` then?

**Comment by davidkpiano** [comment]
Just like normal:

```js
<Control
  component={TextField} // tells it what component to render
  propsMap={controls.text} // tells it how to map props to the compoennt
  placeholder="something" // passed straight to component
  onBlur={() => doSomething()} // will execute after dispatching actions.blur
  // ... etc.
>
```

**Comment by ffxsam** [comment]
Gotcha, so `Control` will handle passing those props into `TextField` for me. Great!

**Comment by davidkpiano** [comment]
Yep! And ideally there'd be a tiny 3rd-party library for this:

```js
import { MUIControl } from 'rrf-material-ui';

// render...
<MUIControl.TextField label="something" ...etc />
```
