### ISSUE TITLE
Make it possible to read old documentation?

### ISSUE THREAD

**Issue by ericwooley** [davidkpiano/react-redux-form#148]
We are depending on an older version of react-redux-form, what would be the best way to find docs for an older version?

**Comment by davidkpiano** [comment]
What exactly are you looking for?

The older docs can be found here: http://davidkpiano.github.io/react-redux-form/

**Comment by ericwooley** [comment]
@davidkpiano I am trying to find the docs as they were for version 0.8.4, but can't find any version controlled docs. Is there any docs that are easily accessible for version 0.8.4 or would I need to rebuild the gh-pages branch at the time of the 0.8.4 release?

**Comment by davidkpiano** [comment]
Which part of 0.8.4 specifically? Nothing was removed/changed from the documentation since then.

**Comment by ericwooley** [comment]
Well, one thing that I see is different is the doc show `createModelReducer` and the old code I am looking at imports `formReducer`.

If nothing changed then nothing changed i guess, but I usually prefer to look at docs that are somehow matched to the version I am using.

Thanks!

**Comment by davidkpiano** [comment]
Ah sorry about that, it's not deprecated yet. You can just use `modelReducer` - same thing. Will fix soon!
