### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by gitpjc** [davidkpiano/react-redux-form#15]
Hi David,
Thanks for your great module :-) I'm having trouble getting the validation working. I'm attaching 2 working examples, in both examples data is stored in Redux correctly even for the React-Bootstrap Input component, I've added some validation methods that are called on the onBlur of the Firstname field:
**Example 1 - REACT-REDUX-FORM**
I can see the validation methods are called on the onBlur because they write some log messages but I do not get the required error message 'First Name is required' displayed on the screen even though I can see in Redux that an error does exist for the firstName required validation check. 

**Example 2 - REACT-REDUX-FORM_BOOTSTRAP**
In this example the validation routines do not even get executed on the React-Bootstrap Input component but Redux is still being updated correctly when you change the value in the field so that part is working for a custom component but the validation functions are not being called.

Just unzip the attached file and then do an npm install followed by npm start on each example and access them in your browser at localhost:3000

More than likely it is something I'm doing wrong :-(

Cheers,
Paul
[Validation-problem-examples.zip](https://github.com/davidkpiano/react-redux-form/files/121213/Validation-problem-examples.zip)

**Comment by davidkpiano** [comment]
Hey Paul -

For **Example 1**, you just forgot to include the `userForm` in your `selector()` function. I'll be pushing up a quick check to better warn you that you forgot to include a valid form state for `getField()`:

```diff
const selector = (state) => ({
  user: state.user,
+  userForm: state.userForm
});
```

I'm taking a look at **Example 2** now!

**Comment by gitpjc** [comment]
Hi David,
Thanks for your quick reply, will try it out today.  Would really love to
be able to use the validation on the react-bootstrap components as well,  I
believe a lot of other people use them as well so would be great if they
are supported (I see someone else has already raised an issue about
supporting them).  I think it would be great if you could provide a
downloadable example of a simple application using your form that people
can play with so they can get the hang of it more easily and perhaps reduce
people not having to ask you questions because they have a working example
to analyze.  BTW Your documentation is very helpful but some of the code
examples on your documents page are missing some imports and braces etc..
so having a actual working example would be very helpful. Once again thanks
for the great module I really appreciate the work you have done so far.

Cheers,
Paul.

**Comment by davidkpiano** [comment]
Thanks for the feedback, Paul! I have a ton of documentation updates coming up and am still working through solutions for integrating React Redux Form with libraries such as react-bootstrap and material-ui. Let me know if it works for you and I can close out this ticket for the first issue! :)

**Comment by gitpjc** [comment]
Thanks David,  your solution for my first problem works just fine. Really
looking forward to the validation working for the react-bootstrap
components since I have to use them on our project. More than happy to test
out any solution you come up with.

Cheers,
Paul.

**Comment by davidkpiano** [comment]
Perfect! I'll defer 3rd-party integration discussion here: https://github.com/davidkpiano/react-redux-form/issues/14

**Comment by gitpjc** [comment]
Thanks David.  As I already mentioned the Redux integration seems to
already work for the react-bootstrap components just have the problem with
the validation issue.

Cheers & Thanks,
Paul.
