### ISSUE TITLE
Bug/Feature: Actions which returns actions thunks should work with custom paths

### ISSUE THREAD

**Issue by asvetliakov** [davidkpiano/react-redux-form#153]
Currently few actions, such as asyncSetValidity(), validate(), validateFields() and others only works if:
* Form model mounted in root state with same name as given to model reducer
* Root state should be plain object, so immutable.js structure and others similars are not supported

This breaks also Form/Field components so they won't work (Form will not validate fields for example and pass undefined to validators)

**Comment by asvetliakov** [comment]
Supposed fixes:

1) Provide root state prefix for such actions and forms?
2) Provide setter and getter for immutable structures for form reducer, similar as it works for modeled() in model reducer

Don't have other ideas now

**Comment by davidkpiano** [comment]
Awesome, I'll start working on custom getters/setters for immutable structures for v1. Can you elaborate on this, though?

> Form model mounted in root state with same name as given to model reducer

**Comment by asvetliakov** [comment]
Sure, but let's discuss what to do with these actions. Actually i don't like idea with the providing path prefix, since it's looks like repetition (i actually provided prefix when connect() form, why should i do it again?). Do you have any other ideas?

May be passing state prop to form/field? Or provide decorated HOC component and use context?

**Comment by davidkpiano** [comment]
> Or provide decorated HOC component and use context?

What would this look like, you think?

And I think that this problem with the prefixes can easily be solved with middleware:

```js
import { formMiddleware } from 'react-redux-form';

const store = applyMiddleware(formMiddleware)(createStore)(combineReducers({
  user: userReducer,
  foo: fooReducer,
  bar: barReducer,
});
```

where each `userReducer`, etc. are just plain existing reducers.

**Comment by davidkpiano** [comment]
@asvetliakov This first part:

> (only works if) Form model mounted in root state with same name as given to model reducer

should be fixed in `react-redux-form@0.11.3`. Can you please verify that it does, or give me code that was failing before?

**Comment by asvetliakov** [comment]
@davidkpiano Thanks for fixing, i'm very busy now with my current work (and i'm not using Form/Field in my proj), but i'll try to find some time on this week to verify / provide code / tests / or anything else that i could help.

**Comment by davidkpiano** [comment]
Closing this, I think I have all this covered pre-version 1.0. If there's anything missing, can you please open a separate ticket for it? Thanks!
