### ISSUE TITLE
is errors supported in <Form> onSubmit handler?

### ISSUE THREAD

**Issue by fairbairn** [davidkpiano/react-redux-form#156]
Just looking at source.. noticed that although errors gets checked within the validate() function on mounting, within the submit handler, it looks to only support validators prop passed on Form instead of errors prop.

```
handleSubmit(e) {
    e.preventDefault();

    const {
      model,
      modelValue,
      formValue,
      onSubmit,
      dispatch,
      validators,                 // <<-------- shouldn't errors also be in this list??
    } = this.props;

    const formValid = formValue
      ? formValue.valid
      : true;

    if (!validators && onSubmit && formValid) {  // <<---------- this only checks validators, no errors
      onSubmit(modelValue);

      return modelValue;
    }
.
.
.
.
```

We want to pass in Form errors={...} so as to capture error messages and centralize our validation logic within a central function.

**Comment by davidkpiano** [comment]
Thanks for the report! I'll add support for errors today.

**Comment by davidkpiano** [comment]
Actually, did you even try this, regardless of the source? Errors are always validated whenever there is a change, and submitting a form wouldn't change the model, which means that the errors will be properly reflected in the form validity state.

**Comment by fairbairn** [comment]
We couldn't see any accurate changes to any state under the model_form tier of data within redux, especially errors that we were attempting to set.
