### ISSUE TITLE
Form submitting although errors in validation

### ISSUE THREAD

**Issue by reduxdj** [davidkpiano/react-redux-form#158]
Hi,
Don't know if it helps but noticed this with my testing

`Object {blur: true, dirty: false, focus: false, pending: false, pristine: true…}
blur
:
true
dirty
:
false
errors
:
true
fields
:
Object
contactEmail
:
Object
firstName
:
Object
lastName
:
Object
phoneNumber
:
Object
title
:
Object
type
:
Object
__proto__
:
Object
focus
:
false
model
:
"beautyAdvisor"
pending
:
false
pristine
:
true
retouched
:
false
submitFailed
:
false
submitted
:
true
touched
:
true
untouched
:
false
valid
:
false
validating
:
false
validity
:
undefined
viewValue
:
null
__proto__
:
Object`

**Comment by davidkpiano** [comment]
Was this issue resolved?
