### ISSUE TITLE
Permit element to update sibling element

### ISSUE THREAD

**Issue by stutanne** [davidkpiano/react-redux-form#16]
I have a select (months) that needs to update a sibling select (days in that month). However, I cannot get the onchange event attached to my months selector to update its sibling. I can output the updated info via console.log and it is correct, however the days select never updates from its initial state.

This [exists as a SO question](http://stackoverflow.com/questions/35351953/reactjs-have-one-select-menu-set-the-value-of-another) which has more detailed code if helpful.

Is this something that I should be having trouble with or perhaps is not a capability of this package (or maybe I have something misconfigured)?

**Comment by davidkpiano** [comment]
This is a (small) bug with `<Field />` which will be fixed soon. In the meantime, you can forego using `<Field />` and add the action manually;

```js
<select onChange={(e) => dispatch(actions.change('foo.month', e))}>
  <option>...</option>
</select>

<select onChange={(e) => dispatch(actions.change('foo.day', e))}>
  { getDaysInMonth(foo.month).map((day) => 
    <option value={ day } key={ day }>{ day }</option>
  )}
</select>
```

**Comment by davidkpiano** [comment]
Unit test added here: https://github.com/davidkpiano/react-redux-form/commit/edfbec65297cbd1cbf5ea63ea0f662f7563e5718

Everything looks good to go! `npm install react-redux-form@0.5.2 --save`
