### ISSUE TITLE
select issue

### ISSUE THREAD

**Issue by appbank2020** [davidkpiano/react-redux-form#160]
Hi,
I am going to create react-select component in react-redux-form.
how to place select component in Field?

**Comment by davidkpiano** [comment]
Hey, you can do so like this in your `render()` function:

```js
import { Field } from 'react-redux-form';

// in render():
<Field model="test.foo">
  <select>
    <option value="one" />
    <option value="two" />
    <option value="three" />
    <optgroup>
      <option value="four" />
      <option value="five" />
      <option value="six" />
    </optgroup>
  </select>
</Field>
```

Or are you talking about [react-select](https://github.com/JedWatson/react-select)? If so, what version are you using, <1.0, or 1.0 beta?

**Comment by appbank2020** [comment]
Thanks for your answer.
I am using react-select 1.0.0.-beta12 now.

const propertyTypeOptions = [
      { value: 'apartment', label: 'Apartment/Unit' },
      { value: 'studio', label: 'Studio' },
      { value: 'house', label: 'House/Townhouse' },
      { value: 'whole', label: 'Entire flat' }
    ]

<Field model="property.propertyType">
                <div className={`form-group`}>
                  <label className="col-sm-3 control-label">Property Type</label>
                  <div className="col-sm-9">
                    <Select
                        name="propertyType"
                        value={this.props.propertyType}
                        options={propertyTypeOptions}
                        onChange={this.onPropertyTypeChange}
                    />
                  </div>
                </div>
              </Field>

The problem is that select value is not change.
dropdown is working, but select and change are not working.
Thanks for your help.

**Comment by appbank2020** [comment]
My code is following:
`<Field model="property.propertyType">
    `<div` className={`form-group`}>
      `<label className="col-sm-3 control-label">Property Type</label>`
      `<div className="col-sm-9">`
        `<Select`
          `name="propertyType"`
          `value={this.props.propertyType}`
          `options={propertyTypeOptions}`
          `onChange={this.onPropertyTypeChange}`
         `/>`
       `</div>`
     `</div>`
  `</Field>`

**Comment by davidkpiano** [comment]
Please see the docs on [Custom Components](https://davidkpiano.gitbooks.io/react-redux-form/content/react_native_&_custom_components.html).

This will become much easier in v1.0! Let me know if you run into any issues doing it the way described in the docs. 😄
