### ISSUE TITLE
React native release issues

### ISSUE THREAD

**Issue by adrienbrault** [davidkpiano/react-redux-form#161]
Hey,

My forms are working fine when my app is built in debug mode. However, with `--dev false` and the xcode release scheme, it is like react-redux-form is no longer doing anything. (The weird thing is that I don't have this issue with https://github.com/erikras/redux-form )

Any ideas ?

**Comment by davidkpiano** [comment]
This probably has something to do with the absence of `displayName` on the React Native components: https://github.com/davidkpiano/react-redux-form/issues/65

It's possible I can patch this so it works fine with React Native. There's a few short-term workarounds, though:

- Manually add `TextInput.displayName = 'TextInput'` to the components you're using (soon you won't need to do this)
- Manually wire up the actions yourself, which is pretty straightforward:

```js
import { actions } from 'react-redux-form';

// ...

<TextInput onChangeText={(val) => dispatch(actions.change('user.foo', val))} />
```

- Wait for the `<Control>` component to come out in v1.0. The API will be much nicer, and this will be feasible:

```js
import { Controls as NativeControls } from 'react-redux-form/lib/native';

// in render()
<NativeControls.TextInput model="user.foo" />
```

Please let me know if the `displayName` workaround fixes your issue!

**Comment by adrienbrault** [comment]
It works, thanks!
