### ISSUE TITLE
Minor documentation errors

### ISSUE THREAD

**Issue by jmeas** [davidkpiano/react-redux-form#165]
It seems like the docs are interchanging `modelReducer` and `createModelReducer`, and the equivalent methods for forms i.e.;

```js
import { formReducer } from 'react-redux-form';

const initialUserState = {
  firstName: '',
  lastName: ''
};

const userFormReducer = createFormReducer('user', initialUserState);
```

If I understand it correctly, the version without `create` is intended to be used? If so, I can make a PR for this fix in the next day. Lmk if that's something you're interested in @davidkpiano !

**Comment by davidkpiano** [comment]
Correct; it should be `formReducer` and not `createFormReducer`. The docs are on GitBook so I just fixed them (not sure if a PR is possible yet). Thanks a lot!

**Comment by jmeas** [comment]
:+1:
