### ISSUE TITLE
Field not working when wrapping another component

### ISSUE THREAD

**Issue by tnguyen14** [davidkpiano/react-redux-form#167]
I am just trying out react-redux-form, so I might be doing it wrong here. When I use it the way recommended, it seems to work. However, if I wrap the `Field` component around my own component (which implements input fields), it doesn't seem to be working. It looks like this:

```js
import { Field } from 'react-redux-form';
import Input from '../components/Input';

function Form (props) {
    return (
        <form>
            <Field model="user.name">
                <Input label="Name" type="text"/>
            </Field>
        </form>
    );
}
```

`Input` just wraps the native `input` or `select` field with some `label` and container elements, so my fields can be more consistent.

Am I doing this wrong?

**Comment by Faulik** [comment]
You need to add custom field with name `Input` so it will be able to recognize it. It will behave the same way.

**Comment by davidkpiano** [comment]
@Faulik is right. See the [React Native & Custom Components](https://davidkpiano.gitbooks.io/react-redux-form/content/react_native_&_custom_components.html) doc for more information.

In version 1, this will become much easier, I promise :) It will look something like this:

```js
// Warning: future syntax!
import { Control } from 'react-redux-form';

// render()
<Control model="user.name" component={Input} label="Name" type="text" />
```

**Comment by tnguyen14** [comment]
Thanks @Faulik and @davidkpiano . I am not sure what you mean by adding the custom field with key?

The doc seems to suggest that I need to implement a custom change event handler on my `Input` element, and have it dispatch an `actions.change` event. Is that right?

**Comment by davidkpiano** [comment]
Yes, that is correct. Alternatively you can use `createFieldClass` to create a custom `<Field>` class that _recognizes_ your custom `<Input>`. But you have to make sure that `Input.displayName = 'Input'`.

Let me know if the custom component solution outlined in the docs works for you!

**Comment by tnguyen14** [comment]
So I really liked the approach of using `createFieldClass` with the default `controls`, instead of declaring each `props` individually. However, my custom `Input` field is used generically for all text, textarea, checkbox etc. fields. So does that mean I'd have to create a new field of each of those input types?

**Comment by davidkpiano** [comment]
> So does that mean I'd have to create a new field of each of those input types?

Not necessarily.

Assuming your custom `Input` has a `type="..."` attribute, you can do something like this:

```js
const CustomField = createFieldClass({
  Input: (props) => {
    switch (props.type) {
      case 'text': // return ...
      case 'radio': // return ...
      default: // return ...
    }
  }
});
```

where each different type would return their _own_ prop mappings. Again, `<Control>` will make this a little bit easier. But this approach will work.

**Comment by tnguyen14** [comment]
That is nifty, and yes, `Input` has a `type` attribute. Could I even do something like

```js
const CustomField = createFieldClass({
  Input: (props) => {
    return controls[props.type]();
  }
});
```

**Comment by davidkpiano** [comment]
Yep, absolutely! The mapping function simply returns the mapping given props. So you can do anything in that function.

**Comment by tnguyen14** [comment]
Just to update this ticket after talking with David on Discord:

When trying to `createFieldClass` route, I'm getting an error because the custom component `Input` that I'm using include a non-input element (`label`). The error is `Uncaught TypeError: Cannot read property 'length' of undefined` on this line https://github.com/davidkpiano/react-redux-form/blob/b192a92/src/components/field-component.js#L133

**Comment by davidkpiano** [comment]
^ I'll have a patch for that soon. Thanks!

**Comment by tnguyen14** [comment]
@davidkpiano I just updated my app to the latest version to try this again. This time, I get this error instead. Have you seen it before?

```
invariant.js:39 Uncaught Invariant Violation: onlyChild must be passed a children with exactly one child.
invariant	@	invariant.js:39
onlyChild	@	onlyChild.js:29
render	@	field-component.js:208
```

**Comment by davidkpiano** [comment]
@tnguyen14 Can you show me your full code?

**Comment by tnguyen14** [comment]
@davidkpiano sure I just pushed a temporary branch here https://github.com/tnguyen14/ledge/tree/react-redux-form

**Comment by davidkpiano** [comment]
Hey @tnguyen14 this was just a usage issue - `createFieldClass` creates a new custom `Field` that can _recognize_ your custom components. Here's the working `NewTransaction.js` class:

```js
import React, { PropTypes } from 'react';
import { Button } from 'react-bootstrap';
import Input from '../components/Input';
import InputTypeahead from '../components/InputTypeahead';
import config from 'config';
import { connect } from 'react-redux';
import { Field, Form, createFieldClass, controls } from 'react-redux-form';
import { saveTransaction } from '../actions';

function isNotNull (str) {
	return typeof str === 'string' && str.length !== 0;
}

// make react-redux-form work with custom component
// https://github.com/davidkpiano/react-redux-form/issues/167
// this could change in react-redux-form 1.0
const CustomField = createFieldClass({
	Input: (props) => {
		let type = props.type;
		switch (props.type) {
		case 'date':
		case 'time':
		case 'number':
			type = 'text';
		}
		return controls[type](props);
	},
	InputTypeahead: controls.text
});

function NewTransaction (props) {
	const statuses = [{
		slug: 'POSTED',
		value: 'POSTED'
	}];

	const { transaction } = props;
	const submitText = props.editing ? 'Update' : 'Add';
	const submittingText = props.editing ? 'Updating...' : 'Adding...';

	return (
		<Form className="new-transaction" model="transaction" onSubmit={saveTransaction}>
			<h2>Add a new transaction</h2>
			<CustomField model="transaction.amount"
				validators={{
					required: isNotNull
				}}>
				<Input label="Amount" type="number" min="0" step="any" />
			</CustomField>
			<CustomField model="transaction.merchant"
				validators={{
					required: isNotNull
				}}>
				<InputTypeahead source={props.merchants} label="Merchant" />
			</CustomField>
			<CustomField model="transaction.date"
				validators={{
					required: isNotNull
				}}>
				<Input label="Date" type="date" />
			</CustomField>
			<CustomField model="transaction.time"
				validators={{
					required: isNotNull
				}}>
				<Input label="Time" type="time" />
			</CustomField>
			<CustomField model="transaction.category"
				validators={{
					required: isNotNull
				}}>
				<Input label="Category" type="select" options={config.categories} placeholder="Select a category" />
			</CustomField>
			<CustomField model="transaction.source"
				validators={{
					required: isNotNull
				}}>
				<Input label="Source" type="select" options={config.sources} placeholder="Select a source" />
			</CustomField>
			<CustomField model="transaction.description">
				<Input label="Description" type="textarea" />
			</CustomField>
			<CustomField model="transaction.status"
				validators={{
					required: isNotNull
				}}>
				<Input label="Status" type="select" options={statuses} />
			</CustomField>
			<CustomField model="transaction.id">
				<input type="hidden" />
			</CustomField>
			<Button bsStyle="primary" className="pull-right" type="submit" disabled={transaction.submitting}>{transaction.submitting ? submittingText : submitText}</Button>
		</Form>
	);
}

NewTransaction.propTypes = {
	editing: PropTypes.bool.isRequired
};

function mapStateToProps (state) {
	let merchants = [];
	if (state.account.merchants_count) {
		merchants = Object.keys(state.account.merchants_count).reduce(function (merchants, merchant) {
			return merchants.concat(state.account.merchants_count[merchant].values);
		}, []);
	}
	return {
		transaction: state.transaction,
		editing: !!state.transaction.id,
		merchants: merchants
	};
}

export default connect(mapStateToProps)(NewTransaction);

```

**Comment by tnguyen14** [comment]
Yup, that fixed it! Makes sense. Thanks @davidkpiano for all the incredible and timely help!

**Comment by davidkpiano** [comment]
You're welcome! Sorry if the documentation is confusing around this. `<Control>` in v1.0 will make this easier.
