### ISSUE TITLE
Validate field after changing model

### ISSUE THREAD

**Issue by Faulik** [davidkpiano/react-redux-form#168]
Hello. When i change model values externally(with change or load actions), how to trigger field validations? 
I use code like this:
```
<form>
  <Field model="name"
    validators={{
      required: isRequired
    }}
    validateOn="change"
    className={isValid(getField(form, 'name'), form)}>
    <input type="text" value={model.name}/>
    { getField(form, 'name').errors.required
      && <span className="validation_error">Is required</span>
    }
  </Field>
</form>
```
I know i can add validation on form component, but it will duplicate the ones on fields and generally will be worse. Also creating big validation object for actions.validate looks even more worse.
To find if field is invalid i use function like this: 
```
export const isValid = (field, form) => ((form.submitted || !field.pristine) && !field.valid ? "field_error" : '');
```
There definitely must be a way as this is common problem.

**Comment by davidkpiano** [comment]
There's a couple of RRF-agnostic ways of addressing this problem. One is what you mentioned - using a big validation object for `actions.validate` - this is the most robust solution because validation on `<Field>` or `<Form>` will only occur when (of course) those fields and forms are currently rendered on the page.

That would look like this:

```js
import myValidators from '../path/to/my-validators';

// wherever you are dispatching the change
dispatch(actions.batch('user.foo', [
  actions.change('user.foo', 'some value'),
  actions.setValidity('user.foo', myValidators.user.foo('some value')
]);
```

So are you requesting that validation occur whenever the `<Field>` detects a change in the `modelValue`? That's certainly doable.

**Comment by Faulik** [comment]
Yea, something like this. Or just validate action which will trigger field validations, when you don't specify them as argument.
I'm not sure about validations on render as i changing model and then render. Do i need to specify them somehow except as `value={model}`?

**Comment by Faulik** [comment]
I have done some research and not sure if this is intended but initial values aren't the ones from initial state or model object. If you specify `modelValue` on your input it will use it:
```
<input type="text" modelValue={model.name}/>
```
There is no word about it in docs so it's better to add it.

**Comment by davidkpiano** [comment]
I'm not sure I follow - though `modelValue` is meant to be internal.

However, RRF provides actions to allow you to do validation in whichever way, and so if you want validation to be arbitrarily executed, it's best to do it manually via actions. Can you make a sample use-case so I can better understand the problem?

**Comment by Faulik** [comment]
@davidkpiano Hi again. Expected behavior is like this [first example](http://codepen.io/Faul/pen/qZJqwO?editors=0010). But i need to specify full path as form name.
In general i would like to simplify it to [second example](http://codepen.io/Faul/pen/zqmoEb?editors=0010) but as you see input don't reflect actual model if model isn't full path. But it's reflect next changes just fine. 
Also in this examples validations are working fine, so i'm still investigating why mine aren't.
Thanks.

**Comment by davidkpiano** [comment]
Ah right, that's because the inputs are not controlled. Have you tried this:

```js
<input type="text" value={user.username} />
```

I'm strongly considering making inputs controlled (using internal component state) in v1.0.

**Comment by Faulik** [comment]
@davidkpiano Not that. Look at [this](http://codepen.io/Faul/pen/zqmoEb?editors=0010) I added value attribute and it has it in input, but thats not the case. Form is invalid and in console you can see `undefined` value of modelValue in validator, but model actually has it.
And now [this](http://codepen.io/Faul/pen/qZJqwO?editors=0010) code produces valid model with valid data but needs magic - model name must be full path in state. If you rename all `formStore.user` to just `user` it will give you invalid form on start and after any change event it will correctly validate.
Now i can't figure out how setting modelValue fixes this on my part.

**Comment by davidkpiano** [comment]
Please look at the documentation for this: https://davidkpiano.gitbooks.io/react-redux-form/content/model_reducers.html#model-reducers-in-stores

The `model` _must_ be the full path to the model reducer in the store, so that RRF knows exactly where to look when both getting and setting the values.

This seems like a little bit of boilerplate, and I'm thinking of ways to reduce this boilerplate. Considering an API like this:

```js
import { combineModelReducers } from 'react-redux-form';

const store = applyMiddleware(thunk)(createStore)(combineModelReducers({
  user: modelReducer('can_be_any_name', initialUserState),
  foo: modelReducer('does.not.matter', initialFooState),
});
```

**Comment by Faulik** [comment]
Oh, i missed it somehow. Thanks for your efforts.

**Comment by davidkpiano** [comment]
Thanks for pointing the confusion out to me, though. I added some documentation in various sections to further emphasize this.
