### ISSUE TITLE
getFieldFromState available?

### ISSUE THREAD

**Issue by MiMaMuh** [davidkpiano/react-redux-form#169]
Hi, 

is there a plan to make the getFieldFromState available? Or is there a reason why it's not exported? 

I want to write a component which uses the field-component with a custom input-component and passes possible error messages to the input-component directly. So I have a effect like the error-component but programmatically. 

    // props.errors will come from the mapStateToProps function 
    // using getFieldFromState(state, ownProps.model)
    return (
        <Field model={props.model} validators={props.validators} errors={props.errors}>
            <CustomInputComp
                {...props}
                errors={props.errors)}
            />
        </Field>
    );

Or is there a better way to handle such a case? Thx!

**Comment by davidkpiano** [comment]
Hey, I'll export it once I write a few unit tests for it. Probably later today!

**Comment by davidkpiano** [comment]
Added in `v0.12.0`!

```js
import { utils } from 'react-redux-form';

// available as...
utils.getFieldFromState(...)
```
