### ISSUE TITLE
Field breaks React.Children.only on child component

### ISSUE THREAD

**Issue by MiMaMuh** [davidkpiano/react-redux-form#170]
Hi, I have a component which uses React.Children.only which itself is wrapped by Field. When it is wrapped the React.Children.only helper always throws an error: 
     "onlyChild must be passed a children with exactly one child"

    // fails
    <Field ...>
        <CompUsingChildrenOnly>
            <ChildComp />
        </CompUsingChildrenOnly>
    </Field>

    // works
    <CompUsingChildrenOnly>
        <ChildComp />
    </CompUsingChildrenOnly>

As denoted [here](https://facebook.github.io/react/tips/children-props-type.html), when there is only a single child, this.props.children will be the single child component itself without the array wrapper to save the allocation of an array. 

I think the issue comes from the Field component when it clones the element in [field-component.js](https://github.com/davidkpiano/react-redux-form/blob/master/src/components/field-component.js#L99) using React.Chirldren.map which [always returns](https://facebook.github.io/react/docs/top-level-api.html#react.children.map) an array when a child is there.

React.Children.only uses simply [ReactElement.isValidElement(children)](https://github.com/facebook/react/blob/416f315c962c74e057e420b5c24e4e89744174f0/src/isomorphic/children/onlyChild.js#L30) in the background, so this will fail. :)

**Comment by davidkpiano** [comment]
Thinking about the simplest solution to this one - would it make sense for `<Field>` to _always_ generate a wrapper component (`<div>`)? Which is the current behavior for a `<Field>` containing more than one child.

**Comment by davidkpiano** [comment]
Also, can you show me a code example where this is failing?

**Comment by MiMaMuh** [comment]
Hi, yes, I created a example project here: https://github.com/MiMaMuh/react-redux-form-child-only-issue

**Comment by davidkpiano** [comment]
This will be published in the next release: 0.11.6!

**Comment by MiMaMuh** [comment]
Great, thx!
