### ISSUE TITLE
Reusable components for child fields

### ISSUE THREAD

**Issue by mruhlin** [davidkpiano/react-redux-form#173]
Hi, I'm trying to figure out how to cleanly make forms that work for common fields that are nested deep in my state tree.  Consider that I have a User object with a home address and a work address.  My state looks like this:
```
{
  user: {
    name: "Jimbob Jones",
    homeAddress: {
      street: "123 Fake St",
      city: "Austin",
      state: "TX",
      country: "USA"
    },
    workAddress: {
      street: "456 Madeup Ave",
      city: "Buda",
      state: "TX",
      country: "USA"
    }
  }
}
```
So, I want to make a reusable Address component to edit both of those.

What I have so far is something like:
```
<Form model="user">
  <Field model="user.name">
    Name: <input type="text"/>
  </Field>

  <Address prefix="user.homeAddress."/>
  <Address prefix="user.workAddress."/>
</Form>
```

and my Address component is like:
```
<Field model={this.props.prefix + "street"}>
  street: <input type="text"/>
</Field>
<Field model={this.props.prefix + "city"}>
  city: <input type="text"/>
</Field>
etc etc
```

This gets the job done, but it feels a little dirty having to pass that prefix around as a string.  Is there some better way to accomplish this?

**Comment by davidkpiano** [comment]
Hmm, good question! What about something like this?

```js
// Not real API (yet?)
import { FieldSet } from 'react-redux-form';

// render()
<FieldSet model="user.homeAddress">
  <Field model="street"> ...
  <Field model="city">...
</FieldSet>
```

Would be purely a convenience component that maps over each of its children, and if it finds a `<Field>` it will prepend its `model`. Just an idea.

The problem comes when you have something like a `<CustomFieldGroup>` or `<SomethingThatContainsAField>`... then we'd have to rely on `context`, which I strongly want to avoid to prevent complexity.

What are your thoughts? What's your ideal API for this?

**Comment by mruhlin** [comment]
Yeah nesting like that seems pretty natural (or if instead of a separate FieldSet tag you could reuse either Field or Form tags, might be better).  Maybe if everything just nested inherently.  
```
<Form model="user">
    <Field model="address">  <!-- this is implied user.address -->
        <Field model="city"> <!-- this is implied user.address.city -->
```
Would kind of be a breaking change though.

I'm new to React and Redux so a little reluctant to throw out suggestions that might be terrible.  Ideally I'd like to just pass in the exact object I'm modifying but I guess there's no way to finagle that since we have to know where to put it in state when we're done with our changes.  Maybe if I could pass a selector that returns the object rather than a string path? i.e.
UserForm:
```
var userSelector = (state) => (state.user)
<Form model={userSelector}>
   <Field model={compose((user) => (user.name), userSelector}/>
   <Address model={compose((user) => (user.homeAddress), userSelector}/>
   <Address model={compose((user) => (user.workAddress), userSelector}/>
```

Address:
`<Field model={compose((address) => (address.street), this.props.model}/>`

That seems a little verbose now that I type it out, but maybe there's a way to clean up the syntax?

**Comment by davidkpiano** [comment]
Have you looked into [tracking collections](https://davidkpiano.gitbooks.io/react-redux-form/content/tracking_collections.html) for inspiration?

Having "stringly-typed" models is the most succinct syntax so far, because a string path tells RRF where to retrieve _and_ set the value, all from one versatile string.

However, I can see something like this being useful:

```js
<Field with={user} model="address">
// ...
</Field>
```

which will work by finding the appropriate path that `user` lies (which is findable, since `user` is an object and its path can be found by `===` reference). The benefit here is the shortcut that, if your `user` lies in a deep path, such as `forms.foo.bar.baz.user`, and you're using a custom `mapPropsToState` function to get `const { user } = this.props` in `render()`, you don't need to pass in the full path.

Thoughts on this?

**Comment by davidkpiano** [comment]
@mruhlin If I am going to use context, this API might make more sense:

```js
<Form model="user" context={true}>
  <Field model="address"> // 'user.address'
    // ...
  </Field>
</Form>
```

**Comment by lennerd** [comment]
Just my two cents:

``` js
<Form model="user">
    <Field model=".address">  <!-- this is implied user.address -->
        <Field model=".city"> <!-- this is implied user.address.city -->
```

Similar to relativ directory paths.

**Comment by davidkpiano** [comment]
@lennerd I'm going to plan on handling it with only single nesting. This is because DOM structure does not necessarily reflect data structure.

```js
<Form model="user"
  <Field model=".address"></Field>
  <Field model=".address.city"></Field> // can be outside, shouldn't nest fields
</Form>
```

**Comment by lennerd** [comment]
Sorry, I don't quite get, what you mean. You mean a Field component is user outside of Form?

**Comment by davidkpiano** [comment]
The way it's going to work is that `<Form>` is going to create a context (optional) so that any field inside `<Form>`, no matter its nesting, can elect to have a shortened model prepended with a dot, which would look in the context and find the correct model.

**Comment by lennerd** [comment]
But isn't that possible with the dot syntax? Omitting the dot would select the model directly. Similar to `react-router` where route URLs can be appended to there parent route if you don`t add a starting slash. 

Sorry to maybe sound stupid. Maybe it would help if you can give a code example.

**Comment by lennerd** [comment]
It would also be possible to have to dots selecting the previous parent. `..name` in `user.images` would select `user.name` for example.

**Comment by mruhlin** [comment]
Cool, this looks good.  So for my example about home and work addresses, I'd just have to use multiple form tags, i.e.?

```
<Form model="user">
    <Field model=".name"/>
    <Field model=".email"/>
    // etc
</Form>
<Form model="user.homeAddress">
    <AddressFields />
</Form>
<Form model="user.workAddress">
    <AddressFields />
</Form>
<SubmitButton />
```
AddressFields.jsx...
```
<Field model=".street"/>
<Field model=".city"/>
//etc
```

If I did it that way, I'd still only need one set of reducers in my redux store right, or would I need to create separate form reducers for each address?

**Comment by davidkpiano** [comment]
> If I did it that way, I'd still only need one set of reducers in my redux store right, or would I need to create separate form reducers for each address?

You can do it under a single `userForm` and that will work fine. If you wanted to treat `user.homeAddress` as its own isolated form, you'll have to wait until version 1 for that. But yes, that's how the syntax should work, as you have it.

**Comment by davidkpiano** [comment]
This has been added to the latest `@beta`! Currently it works if the root model is in `<Form>` and the partial models are in `<Control>`. Before 1.0, I plan on supporting `<Field>`, `<Errors>`, as well as perhaps adding a `<Fieldset>` component that will let you add a context without creating a `<Form>`?

```js
// Object access
<Form model="user">
  <Control.text model=".firstName" />
</Form>

// Array access
<Form model="users">
  <Control.text model="[3].firstName" />
</Form>

// Parent tracker
<Form model={track('users[]', {id: 123})}>
  <Control.text model=".firstName" />
</Form>

// Child tracker
<Form model="user">
  <Control.text model={track('.friends[].firstName', {id: 123})} />
</Form>

// Parent and child tracker
<Form model={track('users[]', {id: 123})}>
  <Control.text model={track('.friends[].firstName', {id: 456})} />
</Form>
```
