### ISSUE TITLE
Removing items from an array will incorrectly persist fields

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/react-redux-form#174]
(Placeholder issue for @cbioley)

Previously failing test case here: https://github.com/cbioley/react-redux-form/blob/63eac0575e3ec6590d7133fc42464c8212ec1170/test/form-reducer-spec.js

**Comment by cbioley** [comment]
@davidkpiano Hey mate! You've indeed fixed my initial issue, thank you!

I'm afraid to have found another weird behaviour while stress testing (read: clicking like a freak on add/remove/add/add/remove/...) my app, so I now need to narrow down what I've done and write a test to show the issue.

I hope you don't mind if I post here when I have something to show.

I wish you a nice day ☀️

**Comment by cbioley** [comment]
@davidkpiano Here's a failing test:

```js
  it('should clean after itself when a valid field (scenario with 3 items)', (done) => {
    const reducer = formReducer('test', {
      items: [
        { name: 'item1' },
        { name: 'item2' },
        { name: 'item3' },
      ],
    });

    const state1 = reducer(
      undefined,
      actions.setValidity('test.items[0].name', true));
    const state2 = reducer(
      state1,
      actions.setValidity('test.items[1].name', false));
    const state3 = reducer(
      state2,
      actions.setValidity('test.items[2].name', true));

    assert.isFalse(state3.valid, 'form should be invalid');

    let removedState;

    const dispatch = action => {
      removedState = reducer(state3, action);
      assert.isFalse(removedState.valid, 'form should still be invalid');
      done();
    };

    const getState = () => state3;

    actions.remove('test.items', 2)(dispatch, getState);
  });
```

**Comment by cbioley** [comment]
@davidkpiano Thanks!

**Comment by davidkpiano** [comment]
Will be in next patch release @cbioley!

**Comment by cbioley** [comment]
@davidkpiano No prob, I could test from master branch 👍 

I ... (I don't know how to say that) ... _may_ have found another tiny annoyance regarding the errors this time. 

But fear not, this is way less annoying (for my case at least) so you can pretend I don't exist for now ^^

**Comment by cbioley** [comment]
@davidkpiano Please, don't hate me :)

```js
  it('should clean all props after itself when a field is removed', (done) => {
    const reducer = formReducer('test', {
      items: [
        { name: 'item1', dummy: true },
        { name: 'item2', dummy: true },
      ],
    });

    const invalidItem = reducer(
      undefined,
      actions.setValidity('test.items[1].name', false)
    );

    let removedState;

    const dispatch = action => {
      removedState = reducer(invalidItem, action);
      assert.isUndefined(removedState.fields['items.1.name']);
      assert.isUndefined(removedState.fields['items.1.dummy']); // <-- this field is leftover
      done();
    };

    const getState = () => invalidItem;

    actions.remove('test.items', 0)(dispatch, getState);
  });
```

**Comment by davidkpiano** [comment]
Of course I won't hate you, thanks for the report! It's the edge cases like this that makes the library more robust and resilient. I'll look into this.
