### ISSUE TITLE
Testing <Form>s Q

### ISSUE THREAD

**Issue by jmeas** [davidkpiano/react-redux-form#175]
I'm writing tests for a component that uses a `<Form>`. My first approach exploded because there was no `<Provider>` in the test, nor was I explicitly passing a store prop to the form in my component. I'm not particularly interested in doing either of these things, so my plan was to use rewire to replace the react-redux-form with a stubbed version that didn't blow up when a `store` attr isn't present.

This is def. going to work, but I'm curious to know if anyone has had luck using a system that doesn't involve rewiring?

**Comment by davidkpiano** [comment]
Hm, this is an interesting question because `<Form>`, `<Field>`, `<Errors>`, etc. are all assuming that a store exists. I'll play around with this and see if I have a good answer for you.

**Comment by davidkpiano** [comment]
@jmeas If you can, I would mock up RRF like this:

```js
import React from 'react';

// React-Redux-Form mock:
const rrf = {
  Field: (props) => <div {...props} />,
  Form: (props) => <form {...props} />,
  Errors: (props) => null,
}

export default rrf;
```

Hopefully that works for your testing use cases!

**Comment by jmeas** [comment]
Cool. I'll do that. Thanks!
