### ISSUE TITLE
createFieldClass is not a function

### ISSUE THREAD

**Issue by plandem** [davidkpiano/react-redux-form#18]

**Comment by davidkpiano** [comment]
Do you have the latest version of `react-redux-form`? This test seems to pass with the existence of `createFieldClass()`: https://travis-ci.org/davidkpiano/react-redux-form/jobs/109377535#L610

Latest version is `react-redux-form@0.5.2`

**Comment by plandem** [comment]
i did npm update for 'react-redux-form' - nothing came

**Comment by davidkpiano** [comment]
Sorry @plandem, I can't reproduce this: http://esnextb.in/?gist=c461ad2839e613de42aa

**Comment by arddor** [comment]
I think it would be good if he wrote what he actually did that lead to the error...
I'm assuming and this is a wild guess, that he does something like this (for react-bootstrap):
```javascript
const BSField = createFieldClass(
  {Input: 'input'}
);
```
But actually he should do:
```javascript 
const BSField = createFieldClass(
  {},
  {Input: 'input'}
);
```
This would result in somewhat a similar error.

**Comment by davidkpiano** [comment]
Ah, right. I recently simplified the API (though not published to NPM yet) that simplifies that so that it's only one argument. I'll write some docs and a few extra tests to show meaningful error messages.
