### ISSUE TITLE
onChange from Field component can only accept an event

### ISSUE THREAD

**Issue by morsdyce** [davidkpiano/react-redux-form#180]
I have a component that wraps around 3 fields and consolidates them into 1 value.

I want to be able to call the onChange callback with my value so RRF model can change (currently the onChange fires but has no value).

I tried simulating an event by providing the following object to the onChange function:
```js
{ target: { value: 'my value' } }
```
But the value was still not passed through.

How can I pass the new value without it being part of a specific event?

**Comment by davidkpiano** [comment]
Can you show me your full code? Are you trying to create a custom event?

There is an internal function called `getValue()` in RRF:

```js
function getValue(value) {
  return isEvent(value) ? getEventValue(value) : value;
}
```

So, `{ target: {...}}` would _not_ be interpreted as an event because it is not an `instanceof Event`.

Try providing the actual value (e.g., the string `'my value') instead of a fake event, or you can make it an actual event:

```js
let customEvent = new Event('custom');
customEvent.target = { value: 'my value' }
```

Please let me know if that works.

**Comment by morsdyce** [comment]
I am trying to call onChange with the value I want it to update but I get a change event with an empty value.

Here is an example of what I am trying to do, note that I removed the methods that generate the actual option with values (in this example there is only the default option).

The specific line i'm refering to is: ```this.props.onChange(`${day}/${month}/${year}`)```

```js
class BirthdayDropdown extends React.Component {

  constructor(props) {
    super(props);
    
    this.state = {
      year: '',
      month: '',
      day: ''
    };
  }
  
  onChange(key, event) {
    this.setState({ [key]: event.target.value }, () => {
      this.props.onChange(`${day}/${month}/${year}`)
    });
  }
  
  render() {
    return (
      <Input type="select" onChange={ this.onChange.bind(this, 'year') }>
        <option value="">Select a year</option>
      </Input>
      <Input type="select" onChange={ this.onChange.bind(this, 'month') }>
        <option value="">Select a month</option>
      </Input>
      <Input type="select" onChange={ this.onChange.bind(this, 'day') }>
        <option value="">Select a day</option>
      </Input>
    );
  }
  
}
```

**Comment by davidkpiano** [comment]
Is the above code valid? This JSX is invalid:

```js
    return (
      <Input type="select" onChange={ this.onChange.bind(this, 'year') }>
        <option value="">Select a year</option>
      </Input>
      <Input type="select" onChange={ this.onChange.bind(this, 'month') }>
        <option value="">Select a month</option>
      </Input>
      <Input type="select" onChange={ this.onChange.bind(this, 'day') }>
        <option value="">Select a day</option>
      </Input>
    );
```

and will throw this error: `Adjacent JSX elements must be wrapped in an enclosing tag`

**Comment by morsdyce** [comment]
Sorry about that, I didn't run the code just tried to make the minimum viable example.

it should be wrapped in a div in order to be valid JSX

**Comment by davidkpiano** [comment]
Hey @morsdyce, please see this esnextb.in for a working example:

http://esnextb.in/?gist=15beae7c68217d593a28cfe256e4c3ce

**Comment by morsdyce** [comment]
Ok, I just tested it with how you specified it and then modified it to use a custom component field using createFieldClass and it seems to work fine.
My example: http://esnextb.in/?gist=d83cb4f1c426576e93bd278f481f7f9e

It's probably an issue somewhere in my project.

Sorry to bother you :)
