### ISSUE TITLE
Question: Change value and revalidate a field when another field is changed.

### ISSUE THREAD

**Issue by dreid** [davidkpiano/react-redux-form#183]
http://esnextb.in/?gist=f0b9b22bbe837861533683dbfdd03ec4

This form attempts to model a dependency between two fields:

Field a is invalid if it is empty.
Field b is invalid if it is emtpy.
Field b is disabled if field a is invalid.

When field a is changed field b should be cleared and invalidated.

The above esnextbin accomplishes this by adding a changeAction to field a which dispatches `actions.change` and `actions.setValidity` against field b before returning `actions.change` against field a.

This feels… complicated, is there a better way? Is this even sufficient?

**Comment by davidkpiano** [comment]
Great question, and thanks for the detailed example.

For these usage scenarios, it's best to ask yourself **how would you accomplish this in plain Redux**.

This might be more code, but in plain Redux, you'd probably have a reducer that handles the relationships:

```js
function customReducer(state = {a: "", b: ""}, action) {
  switch (action.type) {
    case 'CHANGE_A':
      if (!action.value) {
        return {
          a: "",
          b: "",
        }
      }
      
      return {
        ...state,
        a: action.value,
      };
    default:
      return state;
  }
}
```

so something like this: http://esnextb.in/?gist=796d924d52a6a7383bee5066d9471f53

**Comment by dreid** [comment]
And I'd also have to wrap the formReducer to handle the revalidation?

Ideally as a user of react-redux-form I'd be able to:

1. Specify validation information for a field in exactly one place. (preferably near the field specification)
2. Have all changes validated.

**Comment by davidkpiano** [comment]
> Specify validation information for a field in exactly one place. (preferably near the field specification)

Validation is done via actions, in order to be completely agnostic and flexible to how you want to do your actions. It's definitely possible to keep all validators in one place; the structure is up to you. A simple example is keeping all validators in `<Form validators={{...}}>`.

> Have all changes validated.

Do you mean that when you dispatch `actions.change('foo.bar', '...')`, that validation should occur then too?

**Comment by dreid** [comment]
> Do you mean that when you dispatch actions.change('foo.bar', '...'), that validation should occur then too?

That is what I would expect. I was quite surprised to discover the differences between the `onChange` function passed to my controls and the result of calling `actions.change`.

If not exactly when `actions.change` is dispatched it seems like there should be some documented public mechanism for making changes exactly as onChange would.

**Comment by davidkpiano** [comment]
Okay, I'll plan this as a general enhancement, since you're right -- if a `<Field>` detects that the value has changed externally, it should validate against its `validators` and update the validity of that field.

**Comment by davidkpiano** [comment]
@dreid Here's the unit test if you're interested: https://github.com/davidkpiano/react-redux-form/commit/8d95837b259d83c79cd398da6e4e95f4ab41a907#diff-b43d85b01204324e63c810644e344418R617 I'm confident this will solve your use-case; please let me know if it doesn't!

Will be released in the next patch.
