### ISSUE TITLE
missing memoize resolver

### ISSUE THREAD

**Issue by dehbmarques** [davidkpiano/react-redux-form#188]
In the modelValueUpdaterMap (here: https://github.com/davidkpiano/react-redux-form/blob/master/src/utils/sequence.js#L32) the model props is being passed as the map key.
This leads to the change action always passing the same cached value to the form and model reducers.

Here is a sample of the problem. As I typed 'abc' the change action was called three times. In the first call the modelValueUpdaterMap returned the input value and cached this same value, and in the next calls it returned the cached value from the memoize map object.
![screen shot 2016-05-05 at 3 09 21 pm](https://cloud.githubusercontent.com/assets/3743180/15052320/73acbf70-12d3-11e6-9e01-8c311182e313.png)

Creating a resolver like this `(props, eventValue) => props.model + eventValue` solved the problem. But is this the right solution?

Great lib BTW.

**Comment by davidkpiano** [comment]
I ended up just removing memoization for now. Thanks for catching that!
