### ISSUE TITLE
Clearing the model in the reducer and then resubmitting the form does not trigger validation

### ISSUE THREAD

**Issue by fromanother** [davidkpiano/react-redux-form#195]
I have a form that I'd like to use repeatedly, ie. fill the values, hit submit, form gets cleared, fill in other values, submit the form again, and so on.

I have only one field, `name`, and a validator for it which checks that the field is not empty. In the reducer when I get a successful response from the server I set the `model.name` to it's initial value, which is `''`.

When the page first loads, the form works as expected, it does not submit the data if the `name` field is empty and focusing and then blurring the name text input will show that it has a validation error (because it is empty).

After I fill in the name field and submit the form, the name field is emptied (in the reducer) like this:

    const initialState = {
      name: ''
    }
    
    ...
    
      case POST_CREATE_SUCCESS:
        return {
          ...initialState
        }

But now, submitting the empty form again actually sends the data, does not go through validation. Since the name field is empty, it should not send the data.

Focusing and then blurring the empty name field does not cause a validation error to show, only if I type something in it and then delete it and then blur the field do I finally get an error.

I tried using `actions.setDirty` after submitting the form, but it didn't help.

**Comment by davidkpiano** [comment]
Just pushed out a patch that solves this very issue, as long as your `validators` are defined on `<Field>` or `<Form>`: `react-redux-form@0.12.2`

This patch solved #183 which posits that validation should occur when `<Field>` detects that the model value has changed, regardless of _how_ it changed (externally, etc.)

Please upgrade to the latest and let me know if it solves your issue!
