### ISSUE TITLE
fields submitFailed does not change after a submit failed

### ISSUE THREAD

**Issue by konzz** [davidkpiano/react-redux-form#198]
The state of the form has a property submitFailed that turns true after a submission fails, for example when the form isn't valid, but the same property in the fields remains false.

is this intended? if so, when does the property in the fields turns true?

Thanks in advance.

**Comment by davidkpiano** [comment]
Yes, this is intended. In v1, any subsection of the fields (i.e., any node) can be submitted as a "form" - that is to say, if you want to submit the entire `user` or just `user.address`, you can do so. So the `submitFailed` only reflects that submission has failed when trying to submit that specific model.

Hope that helps!

**Comment by konzz** [comment]
Thanks! Yes it helped.
