### ISSUE TITLE
ref no longer working

### ISSUE THREAD

**Issue by arcticfalcon** [davidkpiano/react-redux-form#199]
Hi, I updated to v0.12.* and with the change of cloneElement to createElement in class Control, refs in components inside Field are lost. 
I assume this is a bug?
Thanks!

**Comment by davidkpiano** [comment]
Can you show me your code that was previously working and is now broken, so I can add it as a test case?

**Comment by arcticfalcon** [comment]
I'm using custom components and it happens with any component mapped in the `createFieldClass` definition

```javascript
<Field model={`${model}.${field}`} errors={errors} validateOn="blur">
    <DatePicker ref="picker" />
</Field>
```
(`Field` component there is from `createFieldClass`)

Thanks!

**Comment by davidkpiano** [comment]
@arcticfalcon Fixed! Relevant test case here: https://github.com/davidkpiano/react-redux-form/commit/aa376ba198fe9a14675813b3266d21cc76ab3b62#diff-b43d85b01204324e63c810644e344418R1436

This will go out in 0.12.5

**Comment by arcticfalcon** [comment]
Awesome! Thanks!
