### ISSUE TITLE
Consider changing name

### ISSUE THREAD

**Issue by fhelwanger** [davidkpiano/react-redux-form#2]
First of all, very nice project, thanks :smiley: 

This project's name is very similar to [redux-simple-router](https://github.com/rackt/react-router-redux). But recently, they changed its name to react-router-redux.

@ryanflorence made some really good points in [this comment](https://github.com/rackt/react-router-redux/issues/80#issuecomment-166946652).

I think that if you agree with that, the time to change is now :)

**Comment by davidkpiano** [comment]
Good point, would it make more sense as **react-redux-form** or **react-form-redux** do you think?

**Comment by fhelwanger** [comment]
I think **react-redux-form** is better.

**Comment by davidkpiano** [comment]
And it's done! Thank you for the suggestion!

```
npm install react-redux-form --save
```

**Comment by fhelwanger** [comment]
Nice, thanks!
