### ISSUE TITLE
Remove action - Bug?

### ISSUE THREAD

**Issue by cdreve** [davidkpiano/react-redux-form#200]
Hi,
  I have a component that is displayed multiple times and the data is stored in an array, one item for each display of the component.
  At a later point, I want to be able to remove an item from the array.
  To do this, I have tried to dispatch action.remove, but it doesn't work.
  From what I can tell, if I use `form.foo`, no data is found at this model, but if I use `model.foo`, if finds the data, it fires the `rrf/change` action with the proper model and value, but the `model` is not updated.

  The only difference between my case and the test case below is that I render a new view on user interaction. 

  ```javascript
  it('should remove the item at the specified index of the array represented by the model', () => {
    const store = applyMiddleware(thunk)(createStore)(combineReducers({
      form: formReducer('test'),
      model: modelReducer('test', { foo: [] })
    }));
    const index = 1;
    TestUtils.renderIntoDocument(
      <Provider store={store}>
        <Field model="test.foo.0.val">
          <div>
            <label />
            <input defaultValue="value" />
          </div>
        </Field>
      </Provider>
    );
    TestUtils.renderIntoDocument(
      <Provider store={store}>
        <Field model="test.foo.1.val">
          <div>
            <label />
            <input defaultValue="value" />
          </div>
        </Field>
      </Provider>
    );
    TestUtils.renderIntoDocument(
      <Provider store={store}>
        <Field model="test.foo.2.val">
          <div>
            <label />
            <input defaultValue="value" />
          </div>
        </Field>
      </Provider>
    );
    assert.equal(store.getState().model.foo.length, 3);
    store.dispatch(actions.remove('test.foo', index));
    assert.equal(store.getState().model.foo.length, 2);
  });
  ```

Is this a bug? Or am I not using this properly?

 Thanks

**Comment by davidkpiano** [comment]
I got this working. You just have to make sure that the `model` argument in `modelReducer(model, ...)` is the exact path to this reducer:

```diff
    const store = applyMiddleware(thunk)(createStore)(combineReducers({
      form: formReducer('test'),
-     model: modelReducer('test', { foo: [] })
+     model: modelReducer('model', { foo: [] })
    }));
```

and modify the rest of the test accordingly.
