### ISSUE TITLE
submitFailed not propagated to fields.

### ISSUE THREAD

**Issue by dreid** [davidkpiano/react-redux-form#222]
I'd like to not show fields as invalid unless they are not pristine, or submitting the form has failed.

However, although the `fieldValue` prop passed to the control has `submitFailed` it is not set to true when the `setSubmitFailed` is dispatched by the `Form` component, and the control does not appear to have access to the `Form`'s `submitFailed`.

**Comment by davidkpiano** [comment]
This will be officially addressed in V1, but I can patch it. It should propagate down.
