### ISSUE TITLE
createFieldClass documentation should recommend using [CustomComponent.displayName] as the key in the controlsPropMap.

### ISSUE THREAD

**Issue by dreid** [davidkpiano/react-redux-form#224]
This makes the Field class definition more resilient to changes such as wrapping the CustomComponent in a connect or other decorator.

**Comment by davidkpiano** [comment]
Done! Thanks for pointing that out. https://davidkpiano.gitbooks.io/react-redux-form/content/react_native_&_custom_components.html#createfieldclasspropsmap-defaultprops

**Comment by davidkpiano** [comment]
Updated docs here: https://davidkpiano.gitbooks.io/react-redux-form/content/custom_components.html
