### ISSUE TITLE
Redux updates seem to always cause re-render of every Control

### ISSUE THREAD

**Issue by etrepum** [davidkpiano/react-redux-form#225]
While trying out react-redux-form I've run into some performance issues (at least in dev mode), such that the rendering can't even keep up with typing if there are enough controls on the page. It seems that any change to the store ends up re-rendering all of the Controls.

I've found a few contributing factors by observing the differences in props with a trivial `shouldComponentUpdate` on a custom control component.

* `sequenceActions` returns an object full of closures (`onChange`, `onBlur`, etc.). These closures will change identity on every call, so the result of Control's `mapStateToProps` will always differ, and cause a re-render.
* Control's render is passing `controlProps` and `component` as properties in React.cloneElement / React.createElement as these are included in `...props`. These also seem to be changing identity on every render, possibly as a result of the first thing.

I haven't done a full audit yet, there could be problems with Field too… but there definitely seems to be an issue with how Control is currently implemented.

**Comment by davidkpiano** [comment]
Thanks for starting this audit, @etrepum. I plan on addressing the implementation of `<Control>` and this is extremely helpful. The closures can be mitigated, and there can probably be some optimizations on how we handle `props` and `controlProps`. Let me know if you find anything else and we can keep a running list of these things.

**Comment by etrepum** [comment]
I went ahead and created a PR with a test that demonstrates the problem at a relatively high level, if that test can be made to pass then the hard problems should be solved.

**Comment by davidkpiano** [comment]
Fixed with #227 🎉
