### ISSUE TITLE
Update wiki typo

### ISSUE THREAD

**Issue by bradleyprice** [davidkpiano/react-redux-form#23]
I can't send a PR for a wiki change, but I believe that this line is typo'd in the Redux-Form-Comparison page:

`loginForm: createModelReducer('loginForm')`

and should be

`loginForm: createFormReducer('loginForm')`

**Comment by davidkpiano** [comment]
Thanks, @bradleyprice! Fixed the wiki. It should actually be `loginForm: createFormReducer('login')` because it keeps track of the form state of the `login` slice of the state.
