### ISSUE TITLE
Form component always have unnecessary rerender

### ISSUE THREAD

**Issue by Darmody** [davidkpiano/react-redux-form#235]
![image](https://cloud.githubusercontent.com/assets/6788752/15626900/38c73898-2504-11e6-8099-0dd0e55f8e4f.png)

Maybe Form component should add `pure render` feature too?

**Comment by davidkpiano** [comment]
This might be fixed by c600e5dcaf8afa6efdff0cadbc148abe3a98f743 for #237, can you please verify?

**Comment by Darmody** [comment]
@davidkpiano Cool!

**Comment by davidkpiano** [comment]
Awesome, closing for now. I'm taking a deeper look into performance for V1, so stay tuned!
