### ISSUE TITLE
Performance: Form and Errors components update props on any redux store change

### ISSUE THREAD

**Issue by etrepum** [davidkpiano/react-redux-form#237]
Incorporating the entire redux store into the props for a component is a bit of an anti-pattern for a react-redux mapStateToProps as it will cause the component's props to update in lock step with the redux store, even if completely unrelated to the model in question.

I've seen this anti-pattern in both form-component and error-component:

```javascript
function selector(state, { model }) {
  …
  return {
    ...state, // this is the bad part
    … // these specific props are fine 
  };
}
```

**Comment by davidkpiano** [comment]
Fixed, thanks for pointing that out! Oversight on my part. Should be out in the next patch.
