### ISSUE TITLE
Getting "Uncaught TypeError: Cannot read property 'valid' of undefined" on 0.13.1

### ISSUE THREAD

**Issue by omerzach** [davidkpiano/react-redux-form#238]
I'm seeing the issue discussed in https://github.com/davidkpiano/react-redux-form/issues/139 on version 0.13.1 (which I got by running `npm install react-redux-form --save`). Using version 0.9.14 fixes the problem so it seems the issue was reintroduced between those versions.

**Comment by davidkpiano** [comment]
Do you have a `formReducer` on the state?

**Comment by omerzach** [comment]
Nope, I'm doing exactly what https://davidkpiano.gitbooks.io/react-redux-form/content/step_by_step.html describes except without a `formReducer` (since it says "Form reducers are always optional")

**Comment by davidkpiano** [comment]
Ah sorry, I should have mentioned in the docs that form reducers are required if you're using a Form component (which sorta makes sense). I'll rectify this in the docs and by adding a development warning in the code.
