### ISSUE TITLE
Any performance issues or cons if combined?

### ISSUE THREAD

**Issue by VladShcherbin** [davidkpiano/react-redux-form#239]
If we have for example 7 forms - it is 14 store keys. I want to combine it into `forms` key:

```js
forms: combineReducers({
  user: ...
  userForm: ...
  ...
})
```

Are there any cons of doing this (performance or smth else) ?

**Comment by davidkpiano** [comment]
I don't believe so! They're all just functions and I think the performance impact would be minimal.

**Comment by VladShcherbin** [comment]
Awesome, then I'll be using RRF this way. Thanks!
