### ISSUE TITLE
No values onSubmit if form has no initialState

### ISSUE THREAD

**Issue by VladShcherbin** [davidkpiano/react-redux-form#240]
Currently, there is an _optional_ initialState for a form. If you create a form without state, onSubmit you won't have any fields, even if you specify the value like this and it is rendered:

```js
const Input = ({ field, label }) => (
  <Field model={field}>
    <div className="form-group">
      <label>{label}</label>
      <input type="text" value="123" />
    </div>
  </Field>
)

const PriceTablesForm = () => (
  <Form model="forms.priceTable" onSubmit={values => console.log(values)}>
    <Input field="forms.priceTable.priority" label="Priority" />
    <button>Save</button>
  </Form>
)
```

I guess there is no way to have a component with a defaultValue that works with no initialState ?

**Comment by davidkpiano** [comment]
Can you set this up in an www.esnextb.in to better demonstrate your issue?

Also, important to note that `<input type="text" value="123" />` will _always_ have `value == "123"` since it's a controlled component. That might be where the issue lies.

**Comment by VladShcherbin** [comment]
@davidkpiano I tried, but it doesn't save the gist

js
```js
import React from 'react'
import ReactDOM from 'react-dom'
import { createStore, combineReducers, applyMiddleware } from 'redux'
import { Provider, connect } from 'react-redux'
import thunk from 'redux-thunk'
import { modelReducer, formReducer, Field, Form, actions } from 'react-redux-form'

// First name is defined
const initialArticleState = {
  isVisible: 'true'
}

const store = applyMiddleware(thunk)(createStore)(combineReducers({
  article: modelReducer('article', initialArticleState),
  articleForm: formReducer('article', initialArticleState)
}))


const ArticleForm = () => (
  <Form model="article" onSubmit={values => console.log(values)}>
    <Field model="article.isVisible">
      <label>Visibility:</label>
      <input type="checkbox" />
    </Field>
    <Field model="article.priority">
      <label>Priority:</label>
      <input type="number" value="1" />
    </Field>
    <button>Save</button>
  </Form>
)

function mapStateToProps({ article }) {
  return { article }
}

ConnectedArticleForm = connect(mapStateToProps)(ArticleForm);

const App = () => (
  <Provider store={ store }>
    <ConnectedArticleForm />
  </Provider>
)

ReactDOM.render(<App />, document.getElementById('app'))
```

html

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>ESNextbin Sketch</title>
  <!-- put additional styles and scripts here -->
</head>
<body>
  <div id="app"></div>
</body>
</html>
```

package

```json
{
  "name": "esnextbin-sketch",
  "version": "0.0.0",
  "dependencies": {
    "react": "15.1.0",
    "react-dom": "15.1.0",
    "redux": "3.5.2",
    "react-redux": "4.4.5",
    "redux-thunk": "2.1.0",
    "react-redux-form": "0.13.1"
  }
}
```

The *priority* value is 1, but when you submit form, you see no value in console. This is what I'm talking about.

**Comment by davidkpiano** [comment]
Do you want the value to always be 1? The reason this is not part of the model state is because it is set directly to the component, and not set in the Redux store.

Here's an alternative:

```js
// ...
componentDidMount() {
  this.props.dispatch(actions.load('article.priority', 1)); // silently set the value
}
render() {
  // ...
  <Field model="article.priority">
    <input readOnly />
  </Field>
}
// ...
```

Will this work for your use case?

**Comment by VladShcherbin** [comment]
@davidkpiano the `value` is just an example. I usually have a `defaultValue` for a checkbox for example, but it won't be in onSubmit values too if not defined in initialState.

If we have 10 checkboxes, triggering dispatch 10 times on componentDidMount is not a good idea I guess.

So, basically, we should always set initialState in the reducers or we won't have the default values.

**Comment by davidkpiano** [comment]
If you want to use `defaultValue` you still can - your input just won't be controlled. Have you tried that?

```js
<Field model="article.priority">
  <input defaultValue="1" />
</Field>
```

**Comment by VladShcherbin** [comment]
@davidkpiano yes, it works for in with type text, number, etc. But I can't make it work for a checkbox.

**Comment by davidkpiano** [comment]
Checkbox values are considered read-only; that is, their value doesn't ever change. It can only be toggled, such as `true/false`. What's your use case for checkboxes?

**Comment by VladShcherbin** [comment]
@davidkpiano here is a [demo](http://esnextb.in/?gist=cb5dbbcad18f0218c41fde355236054a) on `esnextb.in`

I'm trying to understand, if I need to always set all fields in initialState.

In the demo you can see a checkbox. If you open a console and submit the form - you won't have the checkbox value.

Plus, I found that if you don't specify the initialState for another input in the demo (title), you'll get the uncontrolled/controlled error for it.

**Comment by VladShcherbin** [comment]
Okay, I'm closing this as I won't be using `Field` element. Will try to figure it out with custom components.

**Comment by davidkpiano** [comment]
In the demo you provided, I submitted the form and got a value for both the input and checkbox once I've added the initial values.

**Comment by VladShcherbin** [comment]
@davidkpiano yes, this was the whole issue - you need to always to set the initialState values.
