### ISSUE TITLE
validation and custom components

### ISSUE THREAD

**Issue by keown** [davidkpiano/react-redux-form#241]
i've a custom component (material-ui) mapped in this way

```
const MaterialField = createFieldClass({
  'TextField': (props) => ({
    name: props.name,
    defaultValue: props.defaultValue,
    modelValue: props.modelValue,
    onChange: props.onChange,
    onBlur: props.onBlur,
    onFocus: props.onFocus,
    onKeyPress: props.onKeyPress,
    validators: props.validators,
    validateOn: props.validateOn,
    updateOn: props.updateOn,
    fieldValue: props.fieldValue
  })
});
```

that's my component code

```
<MaterialField model="logInUser.email"
  validators={{
    required: (val) => val && val.length,
    isEmail: validator.isEmail
  }}
  validateOn="blur">
  <TextField autofocus='autofocus'
    hintText={I18n.t('activerecord.attributes.user.email')}
    floatingLabelText={I18n.t('activerecord.attributes.user.email')}
    type='email'
    name='user[email]'
    id='user_email'
    {...textFieldStyle}
    autoComplete='off'
    errorText={emailErrorTxt}/>
</MaterialField>
```

everything seems to work fine but when the page load the form is in a valid state even if it's not.
if i use a regular input element wrapper in a `Field` component everything seems to work fine.
am i missing something?

**Comment by davidkpiano** [comment]
Have you tried this?

```js
import { controls, createFieldClass } from 'react-redux-form';

const MaterialField = createFieldClass({
  'TextField': controls.text,
});
```

That should work as expected. Inside `createFieldClass`, the mapping is only meant to be for when props don't share the same common event handler prop names as normal components.

For example, if my custom component has `onChangeValue` instead of `onChange`, I'd map it like this:

```js
const CustomField = createFieldClass({
  'CustomText': (props) => ({
    onChangeValue: props.onChange,
  })
})
```

This tells the `CustomField` that whenever something goes through `onChangeValue` in `CustomText`, it should go through the normal `props.onChange` instead.

**Comment by keown** [comment]
@davidkpiano 

```js
const MaterialField = createFieldClass({
  'TextField': controls.text,
});
```
this solution works but unfortunately the name attribute of the input field is overridden with something like `logInUser.email` (in my case) and i need stay with my value `user[email]`

is there any solution?

**Comment by davidkpiano** [comment]
@keown Yep, just fixed it! Will go out in the next patch today.

**Comment by keown** [comment]
thanks a lot @davidkpiano !
