### ISSUE TITLE
Is keeping all forms in the store a good idea

### ISSUE THREAD

**Issue by VladShcherbin** [davidkpiano/react-redux-form#243]
Currently, all forms are created in the store on app load. If we have 10 forms - we have all of them in the store with all fields, props.

Is it a good idea to store all forms instead of creating one by one when the form is rendered (maybe some memory usage, etc) ?

**Comment by davidkpiano** [comment]
This would make a good enhancement - I'll keep it in mind for V1.0. I'm also planning on only having a single atomic `formReducer` be the requirement for 1.0, since that way, any part of the "form tree" can itself be a form, which would allow for multiple forms (dynamically created/removed, as you mentioned).

**Comment by VladShcherbin** [comment]
@davidkpiano oh, this future enhancements will be great. Thank you for the package and for answering all my questions!

Feel free to close the issue or to leave it as a note / roadmap.

**Comment by davidkpiano** [comment]
I'll leave it open until v1.0 hits 😄

**Comment by davidkpiano** [comment]
@VladShcherbin So after thinking about this, I figured that this would be the ideal API which requires the least amount of typing (in fact, even less typing than if you were to normally combine Redux reducers):

```js
// BEFORE
import { createStore, combineReducers } from 'redux';
import { modelReducer, formReducer, modeled } from 'react-redux-form';
import bazReducer, { initialBaz } from '../path/to/baz-reducer';

const initialFoo = ...;
const initialBar = ...;

const store = createStore(combineReducers({
  foo: modelReducer('foo', initialFoo),
  fooForm: formReducer('foo', initialFoo),
  bar: modelReducer('bar', initialBar),
  barForm: formReducer('bar', initialBar),
  baz: modeled(bazReducer, 'baz'),
  bazForm: formReducer(bazReducer, initialBaz),
});
```

```js
// AFTER - v1.0.x
import { createStore } from 'redux';
import { combineModelReducers } from 'react-redux-form';
import bazReducer from '../path/to/baz-reducer';

const initialFoo = ...;
const initialBar = ...;

const store = createStore(combineModelReducers({
  foo: initialFoo, // not a function!
  bar: initialBar, // not a function!
  baz: bazReducer, // function - will be modeled()
}, 'forms'); // <-- key where the formReducer will live
```

The `formReducer` will be what significantly changes in v1.0 for simplicity, and because of its atomic/fractal nature, only one is needed - forms can be infinitely nested, and any subtree can itself be a form. So forms will be accessed from the store like this:

```js
// in connected component:
render() {
  const { forms } = this.props;

  const fooForm = forms.foo;
  const barForm = forms.bar;
  const bazForm = forms.baz;

  const fooAddressForm = fooForm.address;
  const fooAddressFormValid = fooAddressForm.$form.valid;
  const fooCityValid = fooAddressForm.city.valid; // `foo.address.city` is a primitive value, not a form

  // ... etc.
}
```

Thoughts on this?

**Comment by VladShcherbin** [comment]
@davidkpiano yes, this is a perfect API for me as well.

A single `formReducer` with nested forms. It will be easy to create / modify / remove forms in it, take field values, etc. Just like in your examples.

I like this simplicity a lot 👍

**Comment by greaber** [comment]
I might prefer an API that requires a little more typing but is more obvious.  I think that might be the true simplicity.  For instance,

```javascript
import { createStore, combineReducers } from 'redux';
import { modelReducer, formReducerFromModelReducer, modeled } from 'react-redux-form';
import bazReducer, { initialBaz } from '../path/to/baz-reducer';

const initialFoo = ...;
const initialBar = ...;

const foo = modelReducer('foo', initialFoo);
const bar = modelReducer('bar', initialBar);
const baz = modeled(bazReducer, 'baz');

const store = createStore(combineReducers({
    foo,
    bar,
    baz,
    forms: {
        foo: formReducerFromModelReducer(foo),
        bar: formReducerFromModelReducer(bar),
        baz: formReducerFromModelReducer(baz)
    }
});
```

This only uses the ordinary `combineReducers`, so the structure of your store is transparent from your code, even to people who don't know React Redux Form; and it doesn't use a function that has two different behaviors depending on whether it is passed a function or a non-function.  Also, for better or worse, it is less opinionated about how many form reducers you should have.

**Comment by zargold** [comment]
I really need/want to somewhat dynamically build form components based on an API call so its difficult/impossible to build them in from the beginning. Like I have a form for Component A which takes fields `[ 'name', 'description', 'image', 'a few more fields coming from server',]` as opposed to Component B which takes fields `[ 'name', 'description', 'image', 'a few more fields coming from server',]` so hopefully the solution will allow for this.

**Comment by davidkpiano** [comment]
@zargold You're in luck because V1 (now in `beta`) allows for dynamic and infinitely recursive forms. If you have something like this:

```js
const store = createStore(combineForms({
  dynamic: {},
}));
```

and you receive data that you dispatch, such as:

```js
dispatch(actions.change('dynamic.foo', {
  bar: 'this is a dynamic field',
  baz: 'so is this one',
}));
```

Then `forms.dynamic.foo` _becomes_ a new form state that you can treat like any other form state.

**Comment by davidkpiano** [comment]
Available in latest `@beta` - feel free to let me know if you are having trouble implementing the above for your use case. I am writing documentation now, which will be available at `https://davidkpiano.github.io/react-redux-form`.
