### ISSUE TITLE
<Form> validators throws Error when using immutable

### ISSUE THREAD

**Issue by mewben** [davidkpiano/react-redux-form#244]
My `user` reducer is an immutable Map.
I have this form:
```jsx
<Form
	model="user"
	validators={{
		email: { isEmail },
		password: { required }
	}}>
```

Then the console throws this error:
```
Uncaught TypeError: This library (validator.js) validates strings only
```

I tried not using immutable. It was fine.
Thanks for this cool lib btw. 👍

**Comment by davidkpiano** [comment]
> Thanks for this cool lib btw. 👍

I appreciate it, thanks!

This is a (non-)issue with validator.js - a recent update to their latest version.

Just make sure that what you're passing into the function is a string:

```js
validators={{
  email: (value) => isEmail(value + ''),
}}
```

for instance. Hope that helps!

**Comment by mewben** [comment]
> ```jsx
validators={{
  email: (value) => isEmail(value + ''),
}}
```

Thanks but this doesn't help... value is `undefined` when using immutable.

Yes I agree it's non-issue with validator.js

I guess it's in the way immutable access the values.
