### ISSUE TITLE
Littlest documentation error

### ISSUE THREAD

**Issue by jmeas** [davidkpiano/react-redux-form#247]
On [this page](https://davidkpiano.gitbooks.io/react-redux-form/content/react_native_&_custom_components.html) of the docs, you can find the following code snippet in the example on creating a custom component:

```js
return (
      <CustomInput
        onCustomChange={e => dispatch(actions.change(model, e))}
      >
    );
```

it's missing the `/` before the closing bracket.

**Comment by davidkpiano** [comment]
Fixed, thank you!

**Comment by jmeas** [comment]
✌️
