### ISSUE TITLE
Form reducers documentation doesn't render properly on github pages

### ISSUE THREAD

**Issue by lunaryorn** [davidkpiano/react-redux-form#25]
See http://davidkpiano.github.io/react-redux-form/#/api/Guide:-Form-Reducers?_k=129scc:
<img width="837" alt="bildschirmfoto 2016-02-23 um 17 02 57" src="https://cloud.githubusercontent.com/assets/224922/13257498/4f9defee-da4f-11e5-874f-0ae64b41d26f.png">

Note how markdown rendering breaks after the first code block.  The page renders correctly in the wiki.

**Comment by davidkpiano** [comment]
Weird, I had an extra backtick that was throwing the rendering off. Thanks for noticing this! It should be fixed once the cache is refreshed for Github Pages.

**Comment by lunaryorn** [comment]
@davidkpiano Thank you very much for the quick fix.
