### ISSUE TITLE
Support for <input type="file" /> in Field component

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#250]
How hard would it be to add support for `<input type="file" />` for use in Field component?

**Comment by davidkpiano** [comment]
It should already work, in that it changes the model's value to the file path.

Example here: http://davidkpiano.github.io/react-redux-form/docs/index.html#/recipe/various-controls (warning: old version but nothing should be different in the current version)

Look for the file uploader component there. Does it perform the expected result?

**Comment by zabojad** [comment]
> It should already work, in that it changes the model's value to the file path.

It should not change the model's value to the file path but rather to the File object... When we have an `<input type="file" />`, we usually need the file object to send it over XmlHttpRequest...

**Comment by zabojad** [comment]
I've workarounded it with:
```
	function handleFileChange(evt : js.html.InputEvent) {

		var f = evt.target.files[0];

		props.dispatch(actions.change("my_model.picture", f));

		props.dispatch(actions.validate("my_model.picture", [ myValidators.isImage ]));
	}

// ...

				<!-- <Field model="my_model.picture"> -->

					<input type="file" 
						   onChange={handleFileChange}
						   accept="image/*" 
						   capture="camera"
						   id="picture-select" />

				<!-- </Field> -->
				
				<Errors model="my_model.picture"
					    messages={{
						    "0": "File must be an image"
				    	}}
				    	show={{ touched: true, focus: false }} />
```
But it is a workaround. I think it should work like this out of the box, don't you think?

PS: don't mind the syntax, this is Haxe javascript syntax...
