### ISSUE TITLE
<select> with only one option in Field cannot trigger action rrf/change

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#254]
When I have only one option in a `<select>`, the `rrf/change` cannot be triggered.

It results on this field being always empty and not settable, except if we gave it a `defaultValue`...

PS: version `"react-redux-form": "^0.13.1"`

**Comment by davidkpiano** [comment]
Sorry, this is not React-Redux-Form specific. If you try to do this without RRF (or even Redux), you will run into the same issue:

```js
class App extends React.Component {
  constructor() {
    super();
    
    this.state = { value: '' };
  }
  handleChange(e) {
    console.log(e.target.value); // never gets logged
    this.setState({ value: e.target.value });
  }
  render() {
    return (
        <select value={this.state.value} onChange={this.handleChange.bind(this)}>
          <option value="one" >One</option>
        </select>
    )
  }
}
```
