### ISSUE TITLE
Some issues with lingering fields

### ISSUE THREAD

**Issue by dave-clover** [davidkpiano/react-redux-form#256]
Thank you for the great library.  It has been extremely useful and saves us a ton of time.  I am developing a complicated form and have hit an issue.  I'm not sure what the best solution is, so I'm listing some thoughts here.  Basically, the issue centers around not being able to remove field metadata from the `formReducer` after the field is no longer on the page.

A few issues/comments:

1) It doesn't seem like the `omit` action removes the metadata from the `formReducer`.  If you `omit` a field that is currently invalid, the field metadata stays around.

2) When you call `reset` on an object, it would be nice to have an option that resets the properties of that object as well.  For example, I do `actions.reset('blah')`, it would be nice if all properties of `blah` were also removed from the `formReducer`, i.e. `blah.foo` and `blah.bar`.

3) When you dynamically remove a field from the form, the field metadata in the `formReducer` stays around.  If the field was invalid when it was removed, the form will be left in an invalid state and cannot be made valid (at least I think?).  The desired behavior would be to leave the model values in the `modelReducer`, but completely remove the field from `formReducer`.  We previously used formsy-react, and they did something similar and worked nicely.  For context, we have some fields that are shown and hidden based on the user's input in another field.  For what it's worth, I believe this behavior can be fairly easily replicated by calling an action on `componentWillUnmount` of the `Field` class.  The issue here is the `reset` action doesn't seem totally appropriate because the field metadata still persists in the `formReducer`.  It would be nice to have an action that totally removes the field metadata from the `formReducer`.  I looked through some of the issues in this repo, which is how I found `omit`, but it doesn't seem to remove the field metadata from the `formReducer`.  Perhaps that's the easiest thing to do right now?

Thoughts?  I am happy to make any changes, but I want to hear your opinion before submitting a PR.

**Comment by davidkpiano** [comment]
Hmm, the `formReducer` _should_ be acting upon any removed items from an `actionTypes.CHANGE` action by removing the field completely. This will be more elegantly solved in V1.0 but for now, can you give me steps to reproduce?

I will definitely welcome any PRs around this.

**Comment by dave-clover** [comment]
Okay, I believe I was mistaken.  I wasn't using `omit` correctly.  I was doing something like:

`actions.omit('blah', 'foo.bar')` instead of `actions.omit('blah.foo', 'bar')`.

I've been thinking a lot about what to suggest, but I think it's probably fine as it is now.  The only thing that might be nice is to allow the user to do `actions.omit('blah.foo.bar')`, but it seems easy to reproduce this behavior by splitting on the last dot character.

**Comment by davidkpiano** [comment]
> The only thing that might be nice is to allow the user to do `actions.omit('blah.foo.bar')`

That actually would be a good shorthand enhancement, potentially. There's a couple reasons that it's two arguments right now:

- `omit(model, props)` can take in more than one prop, so you can bulk omit properties like:

```js
// Remove `blah.foo.bar` and `blah.foo.baz`
dispatch(actions.omit('blah.foo', ['bar', 'baz']));
```

- There might be an enhancement in the future where you can pass in a predicate:

```js
// pretend this lives on store.blah
const normalizedState = {
  foo: { id: 1 },
  bar: { id: 2 },
  baz: { id: 3 },
};

// will remove blah.bar and blah.baz
dispatch(actions.omit('blah', (val) => val.id > 1));
```

**Comment by dave-clover** [comment]
Thanks for the quick reply.  The predicate thing would be very cool.

Just brainstorming here, but it might also be nice to specify the name of the property:

`dispatch(actions.omit('blah', (val, name) => name != 'baz'));`

**Comment by davidkpiano** [comment]
Right, all predicates used throughout the RRF library are of the standard `(value, key, collection) => {...}` syntax.

**Comment by dave-clover** [comment]
Very cool.  Thanks again for such a great library!  The amount of boilerplate code we no longer have to write is enormous.
