### ISSUE TITLE
Validation break if load action called

### ISSUE THREAD

**Issue by i4got10** [davidkpiano/react-redux-form#257]
Why ``load`` action in ``componentDidMount`` breaks validation?

http://codepen.io/anon/pen/jrPmaM at 30 line

**Comment by davidkpiano** [comment]
Not sure I follow; can you please list the following?

- What are the **steps** to reproduce the issue?
- What is the **expected** outcome?
- What is the **actual** outcome?

**Comment by i4got10** [comment]
expected: if one of fields is empty form will be invalid
to reproduce: load the example http://codepen.io/anon/pen/jrPmaM and try to type anything in inputs. At start I expect that form is invalid.

**Comment by i4got10** [comment]
Also try to comment line 32. With line commented, form start to work as expected

**Comment by davidkpiano** [comment]
Sorry, I can't reproduce this in the latest RRF (version 0.13.x). Here's a working version: http://esnextb.in/?gist=a697395c0e02a5b68555c6f1691f103b

**Comment by i4got10** [comment]
try to add 

``
 componentDidMount() {
    this.props.dispatch(action.change('user', {username:'', email: ''}));  
  }
``

**Comment by davidkpiano** [comment]
Yep, still worked as expected: http://esnextb.in/?gist=a697395c0e02a5b68555c6f1691f103b

**Comment by i4got10** [comment]
@davidkpiano, I`ve got it. Sorry, it was really hard to understand. Problem raise if your have **two** form reducers with similar names(like _user_ and _userEx_). I made a [fork](http://esnextb.in/?gist=1225a9edcb310e0dd7a64e88a9f80562) from your example to demonstrate the problem. Interesting thing here if you comment user and userForm reducers(line 10, 11) validation start to work as expected.

Expect: that validation will work.
Reproduce: type some text in input

**Comment by davidkpiano** [comment]
Oh, I know what's going on. Making a patch now.

**Comment by i4got10** [comment]
Thanks!
