### ISSUE TITLE
Custom field mappings do not work with react production mode

### ISSUE THREAD

**Issue by morsdyce** [davidkpiano/react-redux-form#261]
When deploying my application in production mode react mangles the component names.
This causes the custom field mapping to not work because the component doesn't have the same name.

usage example:

```
const BootstrapTextField = createFieldClass({
  FormControl: controls.text
});

const MyComponent = () => (
    <div>
      <BootstrapTextField model="forms.test">
          <FormControl type="text" />
      </BootstrapTextField>
    </div>
);
```

What comes out in production mode when looking at the react dev tools is something similar to:
```
<div>
    <o model="forms.test">
      <t type="text" />
    </o>
  </div>  
```

How does the library currently checks the child components? is it using displayName or something else?

I don't have time right now to prepare a full reproduction test case but will try to do it later today.

**Comment by davidkpiano** [comment]
Yep, it's using `displayName`, which is minified in production mode, unfortunately.

V1 will solve this issue, but until then, an easy workaround is this:

```js
import CustomTextInput from '../path/to/custom-text-input';

CustomTextInput.displayName = 'CustomTextInput';

// ... do everything else like normal
```

For more info, see:
- https://davidkpiano.gitbooks.io/react-redux-form/content/react_native_&_custom_components.html#custom-components
- https://github.com/davidkpiano/react-redux-form/issues/224
- https://github.com/davidkpiano/react-redux-form/issues/176
- https://github.com/davidkpiano/react-redux-form/issues/161
- https://github.com/davidkpiano/react-redux-form/issues/65

**Comment by davidkpiano** [comment]
I've actually just introduced a more idiomatic way to do this:

```js
const BootstrapTextField = createFieldClass({
  FormControl: controls.text
}, {
  componentMap: {
    FormControl: FormControl
  }
});
```

This allows RRF to recognize the component by its constructor, instead of by its `.displayName`. Will be available in `0.13.6+`

**Comment by morsdyce** [comment]
The syntax seems a bit verbose, maybe instead of providing a separate map you could supply the actual component as the key?

**Comment by davidkpiano** [comment]
Oh, smart idea. I'll update that now.
