### ISSUE TITLE
Field component updateOn

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#267]
Why can't a Field component `updateOn` `submit` ?

In my case, it would allow big performance improvments...

Also, about the function we can pass to the [updateOn](https://davidkpiano.gitbooks.io/react-redux-form/content/field_component.html#updateon-property) prop: does it take as argument anything that would help us implement a custom behavior (state of the form, etc...) ?

**Comment by zabojad** [comment]
Also is it normal that a form can be submitted even if the validation rules set at the Field components level do not pass?

**Comment by davidkpiano** [comment]
> Why can't a Field component updateOn submit ?

Because when a `<form>` is submitted, it is the sole receiver of that event, and there is (currently) no way of letting the `<Field>` component know that a form is _about_ to be submitted before the `<form>` handles the event. If you have any ideas on how to accomplish this, feel free to let me know.

> In my case, it would allow big performance improvments...

Try using `updateOn="blur"`.

> Also, about the function we can pass to the updateOn prop: does it take as argument anything that would help us implement a custom behavior (state of the form, etc...) ?

This behavior is deprecated. Use the `changeAction={...}` prop instead.

> Also is it normal that a form can be submitted even if the validation rules set at the Field components level do not pass?

No, if you are using `<Form>`, then the `onSubmit={...}` handler will never be called for an invalid form.

**Comment by zabojad** [comment]
>> Also is it normal that a form can be submitted even if the validation rules set at the Field components level do not pass?

> No, if you are using `<Form>`, then the onSubmit={...} handler will never be called for an invalid form.

Then I have the following bug: if I submit a form without touching any field, it does trigger the onSubmit callback...

**Comment by davidkpiano** [comment]
Are you using a `<form>` or RRF's `<Form>` component?

If you are using `<form>` you need to check validity before submitting.

**Comment by zabojad** [comment]
Let me describe more precisely the issues I have. Let's consider the following form:
```
<Form model="form_survey"
 	   onSubmit={saveCb}>

	<div>
		<Field model="form_survey.answers.1"
			   validators={{ "required": myValidators.isRequired }}>
			<label>
				<input key={1} type="radio" value={1} />
				<span>Option 1</span>
			</label>
			<label>
				<input key={2} type="radio" value={2} />
				<span>Option 2</span>
			</label>
			<label>
				<input key={3} type="radio" value={3} />
				<span>Option 3</span>
			</label>
		</Field>
		<Errors model="form_survey.answers.1"
					  messages={{
						    "required": "This answer is required"
				    	}}
					  show={{ touched: true, focus: false }} />
	</div>
	<div>
		<Field model="form_survey.answers.2"
			   validators={{ "required": myValidators.isRequired }}
			   updateOn="blur">
			<input type="text"
				   placeholder="Please type something" />
		</Field>
		<Errors model="form_survey.answers.2"
					  messages={{
						    "required": "This answer is required"
				    	}}
					  show={{ touched: true, focus: false }} />
	</div>
	<div>
		<Field model="form_survey.answers.3"
			   validators={{ "notEmpty": myValidators.isNotEmpty }}>
			<label>
				<input key={1} type="checkbox" value={1} />
				<span>Option 1</span>
			</label>
			<label>
				<input key={2} type="checkbox" value={2} />
				<span>Option 2</span>
			</label>
			<label>
				<input key={3} type="checkbox" value={3} />
				<span>Option 3</span>
			</label>
		</Field>
		<Errors model="form_survey.answers.3"
					  messages={{
						    "notEmpty": "This answer is required"
				    	}}
					  show={{ touched: true, focus: false }} />
	</div>

</Form>
```
Details / Problems:
- If I do not touch any field and submit, `onSubmit` is triggered.
- If I touch one required field but do not fill it, then validation triggers (and do not pass) and submission fails (`onSubmit` not triggered). The first submit will trigger validation on the touched field only (not other fields). A second touch on submit will trigger validation on all fields but will not display the validation message on untouched fields.
- another issue I have on this form is: if I touch a field that has validators, fill it correctly or incorrectly (both gives the same behaviour) and touch another field, then the focus is not set on this other field and I have to touch it again to set focus on it. Here are the actions it generates:
```
{"type":"rrf/batch","model":"form_survey.answers.2","actions":[{"type":"rrf/blur","model":"form_survey.answers.2"},{"type":"rrf/change","model":"form_survey.answers.2","value":"jkl","silent":false,"multi":false}]}

{"type":"rrf/setErrors","model":"form_survey.answers.2","errors":{"required":false}}

{"type":"rrf/focus","model":"form_survey.answers.3"}
```
While this behavior would be acceptable if validation on `form_survey.answers.2` did **not** pass, it is not OK when it has passed...

**Comment by zabojad** [comment]
I am using RRF `Form` component, not HTML `form`.

**Comment by davidkpiano** [comment]
I've copy/pasted your example (replaced `form_survey` with `user` but otherwise it's the same thing) here: http://esnextb.in/?gist=df6cfa4a49e2a3ecadb6a03dcc07f2a0

> If I do not touch any field and submit, onSubmit is triggered.
I can't reproduce this.

> If I touch one required field but do not fill it, then validation triggers (and do not pass) and submission fails (onSubmit not triggered).
This is expected, right?

> The first submit will trigger validation on the touched field only (not other fields).
This is also expected. When you touch a field, only that field is touched.

> A second touch on submit will trigger validation on all fields but will not display the validation message on untouched fields.
Can't replicate. All validation messages show.

> if I touch a field that has validators, fill it correctly or incorrectly (both gives the same behaviour) and touch another field, then the focus is not set on this other field and I have to touch it again to set focus on it. 

I couldn't replicate this either. When I focus on the second field, type anything (or nothing), and press `TAB`, it properly focuses the following field.

Please look at the link at the top and see if you are still getting the same issues. Also, it's best if you isolate each issue into a minimal test case with the least amount of code possible to replicate the error. Otherwise, it's difficult for me to debug the issue in a timely manner.

**Comment by zabojad** [comment]
@davidkpiano Thank you for your help in debugging this.

I'm trying to isolate what could cause the behaviour I've described and trying to reproduce it on esnextbin.

I did not yet manage to reproduce all what I've described yet but here is a first reproduced issue: http://esnextb.in/?gist=df6cfa4a49e2a3ecadb6a03dcc07f2a0 => If you submit this right after rendering, it will display a validation on the first field while it should not.

Also something odd with the radio and checkbox inputs: if you change their value, it will trigger as many `rrf/setErrors` actions as there are `<input>` tags the the `Field`. Couldn't it be optimize?

I continue on trying to reproduce those issues...

**Comment by davidkpiano** [comment]
I just updated the gist: http://esnextb.in/?gist=df6cfa4a49e2a3ecadb6a03dcc07f2a0

The first issue is not an issue; I accidentally did `isRequired()` for a number, and since a number doesn't have `.length` it was always invalid. Changed it to `numRequired()` and it works.

> Also something odd with the radio and checkbox inputs: if you change their value, it will trigger as many rrf/setErrors actions as there are <input> tags the the Field. Couldn't it be optimize?

Yes, that would make a good enhancement.

**Comment by zabojad** [comment]
OK, first thing cleared out: I know now why it as submitting without validating. I'm using validator.js and the isNull() method of this lib return false on `undefined` (why ?!). And my form had validators only on input type text...

I think the issue can be closed.

I'll open a new one if needed and will provide a working reproducer on esnextbin.

Thank you @davidkpiano !

**Comment by davidkpiano** [comment]
Yeah, I'm moving away from using validator.js myself, there are other good libraries out there. Thanks for the detailed issue!
