### ISSUE TITLE
Select Component Doesn't Work

### ISSUE THREAD

**Issue by Ahmtdnz** [davidkpiano/react-redux-form#269]
I need help for custom component. Select component doesnt work with Field.

```js
<Field model="user.city">
<label>{labelText}</label>
<Select ref="stateSelect" autofocus options={autosuggest} simpleValue clearable={true} name="selected-state" placeholder="Select City."  value={this.state.selectValue} onChange={this.updateValue} />
</Field>`
```

[http://prntscr.com/beocfz](url)

**Comment by davidkpiano** [comment]
Which custom Select component is this? Did you read the docs on [Custom Components](https://davidkpiano.gitbooks.io/react-redux-form/content/custom_components.html)?

**Comment by Ahmtdnz** [comment]
Sorry, i didn't see. Do you have custom component example ? 

Thanks for help.

**Comment by davidkpiano** [comment]
The Material-UI `TextField` example works well:

```js
import { createFieldClass, controls } from 'react-redux-form';
import TextField from 'material-ui/lib/text-field';

const MaterialField = createFieldClass({
  'TextField': controls.text
}, {
  componentMap: {
    TextField: TextField
  }
});

// render():
<MaterialField model="...">
  <TextField />
</MaterialField>
```

**Comment by ishwinder** [comment]
Were you able to make the select component of material-ui work with react-redux-form ? Material-ui select seems too buggy :(

**Comment by philippzentner** [comment]
@davidkpiano TextField etc are working great. But it seems to have hard times with custom select & menuitem (option) controls.

**Comment by davidkpiano** [comment]
@philippzentner can you share your current problematic code?
