### ISSUE TITLE
How to use Cascading Dropdown in this form ??

### ISSUE THREAD

**Issue by rahulraibit** [davidkpiano/react-redux-form#275]
Hey I want to know how to implement the cascading dropdown in my form. I am new to react redux and  I am facing issues to implement the custom events. for eg. Onchange event of the one field how to update the model of another field. If possible kindly give  some example. Thanks in advance

**Comment by davidkpiano** [comment]
This seems like a specific use-case. Can you show me the code you have for this so far?

You can dispatch `actions.change('some.other.model', ...)` at any time:

```js
<Field model="first.model">
  <input onChange={() => dispatch(actions.change('second.model', ...))} />
</Field>
```

**Comment by rahulraibit** [comment]
Thanks for the Reply. But In my case I have a base form which will dynamically generate the controls and  a parent page that will pass the model for generating the form. Now I want the handler in my base form should be generic that will simply pass the required data to parent where I can Call my custom reducer and play some logic. 

Here is an example.

**Base Form** 

```
if (element.fieldType === 'selector') {
<select  key={element.id}  onchange={this.props.handleChange.bind(element, this)}>{ element.values.map(function (value) { return <DropDownOptions options = {value} /> }) }</select>
}
```
Here is the **handleChange** method that will simply pass the current element and the model to parent form where I will call the reducer and do what ever I want, so that my base form will be generic .

```
handleChange(element, e){
 this.props.handleChange(element, this.props.formFieldValues.apiKeyFields);
}
```
  
**Parent Form**

```
const initialState = {
apiKeyFields: {                    
  Device :{
    Category : ''"
   }
},
uiKeyFields : {
    Fields: [{
      label: 'Category',
      fieldType: 'selector',
      id: 'Category',
      apiKey: 'Device.Category',
      values: CountryList
    }}}

const store = createStore(combineReducers({
  formFieldValues: modelReducer('formFieldValues', initialState),
  formFieldValuesForm: formReducer('formFieldValues', initialState),
  AddDeviceReduer : modelReducer('formFieldValues', initialState)    //Custom Reducer
}));

<Provider store={ store }>
 <BaseForm onSubmit={this.sendFormData}  handleChange={this.handleChange}/>
    </Provider>

handleChange(element, values){
    console.log(element + e);
    var selected ='';
    if(element.id == "Category"){
      selected = values.Category;
    }
  }
```


Forgive me If I am doing something Crazy, only my motive is to make the base form generic, So that it can be reusable and all the custom logic I can handle in the parent form with my Custom reducer.

**Comment by davidkpiano** [comment]
This seems pretty contrived, and I don't see where you are `connect()`ing your components to make `dispatch` available in the props. Please break the problem down to the most minimal example possible (that is, without the custom logic) and put it on www.esnextb.in so that I may be able to help you.
