### ISSUE TITLE
best way to validate multiple fields

### ISSUE THREAD

**Issue by sattaman** [davidkpiano/react-redux-form#28]
What is the best way to validate multiple fields at once, for instance checking two password fields match, or at least one checkbox is ticked?

**Comment by davidkpiano** [comment]
To validate multiple fields, remember that you can always:

- Validate _any part_ of the state
- Validate at _any time_ (via actions)

Assume you have a model that looks like this:

```js
{ user: {
  password: "",
  confirmPassword: "",
  choices: []
} }
```

with a corresponding `userForm` from `userForm: createFormReducer('user')` in your store.

For the first part, validation will likely belong to `user` unless you want to copy the same error for both `user.password` and `user.confirmPassword`. Then, it's just a matter of dispatching the `setValidity` action:

```
import { actions } from 'react-redux-form';

// in your connected component
const { user, dispatch } = this.props;

dispatch(actions.setValidity('user', {
  passwordsMatch: user.password == user.confirmPassword
});
```

Then you can grab that validation key:

```js
// in your connected component
const { userForm } = this.props;

return (
  // ...
  { userForm.errors.passwordMatch
    ? <span>Passwords don't match</span>
    : <span>Nice! Passwords look great. Not that I can see them but, you know.</span>
  }
  // ...
);
```

Hopefully that makes sense! You have full control of when you `dispatch(actions.setValidity(...))`, but if you want to do it inside a `<Field>` component, take a look at [this example](http://davidkpiano.github.io/react-redux-form/#/recipe/validation-on-blur) with the `validators={...}` property.

With a group of checkboxes, if they're part of the same model, validation works as normal:

```js
<Field model="user.choices[]"
  validators={{
    required: (vals) => vals.length
  }}>
  <input type="checkbox" value={1} />
  <input type="checkbox" value={2} />
  <input type="checkbox" value={3} />
</Field>
{ getField(userForm, 'choices').errors.required
  ? <span>Please select one value.</span>
  : null
}
```

Let me know if this all makes sense :)

**Comment by sattaman** [comment]
Brilliant, thank you !
