### ISSUE TITLE
server side validation on submit

### ISSUE THREAD

**Issue by venelin-mihaylov** [davidkpiano/react-redux-form#289]
I have the following scenario:
I want to have separate server validation before create/update, and to be able to return the errors from the server and visualize them in the UI.
On create/update record the user submits data to the server, and the server validates the data before performing the actual update to the database. In case of an error, the server returns fields along with errors. The server provides the error message.
On the client, if the update call to the server has failed, I manually set the errors flag for the fields in the form, so that the error can be visualized. I use  actions.setErrors('tournamentModel.name' ,'too many errors') . The error is correctly passed to rrf, and it is correctly visualized in the UI.
On subsequent form.onSubmit() /user clicks button/ 
rrf triggers: "rrf/setSubmitFailed", "rrf/setFieldsValidity" /errors:true/ and does not call my onSubmit prop.
How can I manually set errors for a form field? Am I missing something?
The form itself is pretty basic, just one field "name".

Thank you for your work!

**Comment by tomspeak** [comment]
Which version of RRF are you using? I believe I faced something similar, which, if I understand your problem correctly, was fixed [here](https://github.com/davidkpiano/react-redux-form/commit/d2d2fd1bc24032e73e7e9072fe5e665c6240cc29) in v0.13.5.

**Comment by venelin-mihaylov** [comment]
0.13.8, the latest

**Comment by venelin-mihaylov** [comment]
I was able to better pinpoint the issue, will open a new issue with better description.
