### ISSUE TITLE
Linting rules

### ISSUE THREAD

**Issue by chrisblossom** [davidkpiano/react-redux-form#29]
Would you be opposed to a PR implementing AirBnB's eslint rules? https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

**Comment by davidkpiano** [comment]
I'd love to add AirBNB's eslint config into RRF and start linting, sure! I'll add it soon.

**Comment by chrisblossom** [comment]
I can give it a go if you'd like. If/when you have time, send me a message on discord's reactiflux.

**Comment by chrisblossom** [comment]
Closed via https://github.com/davidkpiano/react-redux-form/pull/30
