### ISSUE TITLE
Form state path for a collection is item.0 instead of item[0]

### ISSUE THREAD

**Issue by compact** [davidkpiano/react-redux-form#292]
Here's a diff to demonstrate what I mean: https://github.com/compact/react-redux-form/commit/49b12ea53c2c6ef1ad5bad5f9f0cedf6d410e484

Is it intended for the form state path to be `'fields.deep.collection.0.five'` rather than `'fields.deep.collection[0].five'`? I was expecting the latter and then realized it's the former. This isn't a huge deal, I think it would help to distinguish an array from an object with numeric keys.

I'm accessing this form state directly to tell whether each field is valid, touched, etc.

Thanks!

**Comment by davidkpiano** [comment]
Yes, that is intended. This will be addressed in V1, where you could access it as if it were an array, like so:

```js
const { userForm } = this.props;

userForm.deep.collection[0].five; // => field state

**Comment by compact** [comment]
In V1, if I want to access the state directly from say a selector, will it be `.0` or `[0]`?

**Comment by davidkpiano** [comment]
It will be the exact same shape as the state, so `[0]`. Also keep in mind that internally, lodash's `.get` method interprets `foo[0]` and `foo.0` the same.
