### ISSUE TITLE
Allow function for Field validateOn

### ISSUE THREAD

**Issue by TLadd** [davidkpiano/react-redux-form#294]
Would it be possible to allow the Field's validateOn to take a function, which is passed the fieldValue? May make sense to pass the modelValue as well for some other use case.

My reason for wanting this ability: I basically want error messages to appear on blur, but to disappear on change. Thus, my field currently looks like
```
<Field validateOn={ !valid && (touched || submitFailed) ? 'change' : 'blur' }>
...
</Field>
```

Since I'm depending on these values from the formReducer, I'm forced to pass in the form state through my own container. It would be nice to avoid having to have this extra container.

**Comment by davidkpiano** [comment]
Yeah sure, I'll mark it as an enhancement.

> I basically want error messages to appear on blur, but to disappear on change.

You can do this with the `<Errors />` component like so:

```js
<Errors model="..." show={{ focus: true, touched: true, submitFailed: true }} ... />
```

**Comment by TLadd** [comment]
Cool, thanks for the tip.

**Comment by davidkpiano** [comment]
Actually, yeah, because of the event sequencing logic, it's preferred to just have it validate on a certain event, such as `"change"` or `"blur"`, and show the errors conditionally like I've demonstrated.
