### ISSUE TITLE
How to manually submit the form?

### ISSUE THREAD

**Issue by mewben** [davidkpiano/react-redux-form#296]
I have a form which does **not** use `<button type="submit">` to avoid submitting the form when the user presses the `Enter` key.

I tried putting ref on the Form component
```jsx
<Form ref="myForm">
```

then calling `this.refs.myForm.submit()` upon clicking the button throws this error:
```js
_this.refs.myForm.submit is not a function
```

Is there any way to manually submit the form through this? Thanks

**Comment by tomspeak** [comment]
There's an existing discussion at #285.

**Comment by davidkpiano** [comment]
Yeah, I'll be creating a temporary workaround for this. It's really not good practice to be attaching ad-hoc methods on the form instance, so we'll have to think of a better way to accomplish this.

**Comment by davidkpiano** [comment]
Now there is!

```js
class App extends React.Component {
  attachNode(node) {
    this._form = findDOMNode(node);
  }
  handleClick() {
    this._form.submit();
  }
  handleSubmit() {
    // ...
  }
  render() {
    return (
      <div>
        <Form
          model="test"
          onSubmit={this.handleSubmit.bind(this)}
          ref={this.attachNode.bind(this)}
        >
          <Field
            model="test.foo"
          >
            <input type="text" />
          </Field>
        </Form>
        <button onClick={this.handleClick.bind(this)} />
      </div>
    );
  }
}
```

**Comment by mewben** [comment]
Super awesome! Thanks for the quick address on the request... 👍

**Comment by jenyckee** [comment]
@davidkpiano This causes a refresh when I try this

**Comment by snowghost24** [comment]
How do you trigger the handleSubmit  function and pass the event?
