### ISSUE TITLE
Field does not work with embedded inputs

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#301]
In my app, I need to attach some logic on inputs elements related to scrolling on focus. As it's always the same things, I've generalized it in a FocusInput component that just renders this:
```
import api.react.ReactComponent;
import api.react.ReactMacro.jsx;

typedef FocusInputRefs = {
    inputNode : js.html.InputElement
}

class FocusInput extends ReactComponentOf<Dynamic, Dynamic, FocusInputRefs> {

    private function onFocus() {

        haxe.Timer.delay(

                function() {

                    js.Browser.document.querySelector(".layout").scrollTop = refs.inputNode.offsetTop;
                },

                500
            );
    }

    override function render() {

        return jsx('
            <input {...props}
                   ref="inputNode"
                   onFocus={onFocus} />
        ');
    }

}
```

and I try to use this in forms like a normal input:
```
<Field model="form_login.login"
	   updateOn="blur">

<FocusInput type="text"/>

</Field>
```

However, when doing so, the RRF `Field` component completely ignore the FocusInput comp while what it's doing is simply rendering an input and passing it all its props...

What could be done so that the Field comp take it under consideration ?

**Comment by davidkpiano** [comment]
Have you read the section on custom components? https://davidkpiano.gitbooks.io/react-redux-form/content/custom_components.html

**Comment by davidkpiano** [comment]
Please create an example on www.esnextb.in as well, otherwise I am unable to reproduce this.
