### ISSUE TITLE
How can I use the TimePicker from Material-ui?

### ISSUE THREAD

**Issue by armandomendivil** [davidkpiano/react-redux-form#305]
This is my code 
`const MaterialField = createFieldClass({
  'TextField': controls.text
});`

`<MaterialField model="week.monday.in">
  <TimePicker
  format="24hr"
  hintText="00:00"
  />
</MaterialField>`

Also i have performance problems with the TextField :(

**Comment by davidkpiano** [comment]
> Also i have performance problems with the TextField :(

What's the issue?

Also, try to map dispatching actions directly to the component first: https://davidkpiano.gitbooks.io/react-redux-form/content/custom_components.html

**Comment by davidkpiano** [comment]
Closing this as it is a usage question. Let me know if dispatching actions directly works!
