### ISSUE TITLE
Errors component should not render its wrapper component when there is no error 

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#309]
This is exactly the same issue as #266 however it now happens only on form root errors (for example on password match validation), ie on errors set at key "".

**Comment by davidkpiano** [comment]
Thanks for reporting, can you spin up a quick www.esnextb.in if you get the chance to demonstrate the error with your use case so I can create accurate unit tests?

**Comment by davidkpiano** [comment]
@zabojad This should fix the issue. Can you please confirm in `0.14.0`?

**Comment by zabojad** [comment]
@davidkpiano I confirm it works fine now with `0.14.0` :)!
