### ISSUE TITLE
Problem with zero as a number

### ISSUE THREAD

**Issue by i4got10** [davidkpiano/react-redux-form#311]
Starts from 0.13.7 there is a problem with a zero value(number must be number)

Example
https://esnextb.in/?gist=942f1e034d5960539f10baeedc56536b

**Comment by i4got10** [comment]
it also affect object values now. ``{}`` translates to ``[object Object]`` before. Dont know matter it or not

**Comment by davidkpiano** [comment]
Curious, why would a value that's meant for a text field be an object? In order to display the view value, JS has to convert it to a string, which happens to be `"[object Object]"`.

**Comment by youtnbe** [comment]
my component in custom control get value as empty string, but in redux store value is 0
