### ISSUE TITLE
Issues on 0.14.0 and 0.14.1

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#312]
On `0.14.0` and I'm having the following issues (please check on [esnextb reproducer](https://esnextb.in/?gist=45c657f908a1d78ccc42935ede829e7f) and change the RRF version to `0.14.0` in the package tab):

-> the `validateOn="submit"` on the Form component is completely ignored and fields get validated on blur

I've just updated to `0.14.1` and I'm having the following issues (please check on [esnextb reproducer](https://esnextb.in/?gist=45c657f908a1d78ccc42935ede829e7f) and ensure you have RRF `0.14.1` in the package tab ):

-> fields do not update on blur even when there are explicitely set to do so,

-> form thus cannot be submitted anymore as values don't get updated...

**Comment by zabojad** [comment]
@davidkpiano 3537554 does not address the issues I've described for `0.14.1`? Do you confirm it's a bug?

**Comment by davidkpiano** [comment]
@zabojad This test case should reproduce your exact bug: https://github.com/davidkpiano/react-redux-form/commit/3537554b9b78a6dc0cc7311c9f7d1a6fcf2d8c6e#diff-55bc9da456e5c128d620d4d263cb75b3R333

Yes, I did confirm it as a bug and it will be released the next patch later today. Can you look over that test case and make sure that it is exactly your use case? I tried to replicate it as much as possible.

**Comment by zabojad** [comment]
> Can you look over that test case and make sure that it is exactly your use case?

@davidkpiano yes this test case covers the `0.14.0` bug. I'm however not very familiar with writing test cases and I'm thus not sure it covers the `0.14.1` bug I've mentioned initially which is:

> -> fields do not update on blur even when there are explicitly set to do so,

I'm pretty sure [this fix](https://github.com/davidkpiano/react-redux-form/commit/3537554b9b78a6dc0cc7311c9f7d1a6fcf2d8c6e#diff-cfaf268029a93726219cd338fd34ab7cR32) just covers the `0.14.0` issue, not the `0.14.1` one.

**Comment by zabojad** [comment]
@davidkpiano `updateOn="blur"` still doesn't work on latest version :(...

**Comment by davidkpiano** [comment]
@zabojad You mean when you update the model externally, it doesn't show in the control? #278 

V1.0 is nearing completion and that is fixed in there 🎉

**Comment by zabojad** [comment]
@davidkpiano ok then I won't bother reporting anything else on v0 and I'll wait quietly for v1 :D...
