### ISSUE TITLE
Warn when using track outside of Field component

### ISSUE THREAD

**Issue by edmcmanwich** [davidkpiano/react-redux-form#314]
I tried using the track function outside of the Field model props assuming that it would return the path to the model. This didn't work. I'm guessing that the function doesn't have access to the state outside of the Field component and therefore can't find the index. However, I would expect this to throw some kind of warning. Instead it ignores the brackets and returns a path without and index and silently overwrites that part of the state. Maybe it would be better to warn the user about this?

**Comment by davidkpiano** [comment]
You can use the track function outside `<Field model={...} >`. It is a function that returns a function that, given a state, returns the expected model path. And it's a pure function, so it isn't (nor should it be) context-aware.

```js
const tracker = track('group.users[].name', { id: 3 });
const path = tracker(state); // something like 'group.users[5].name'
```
