### ISSUE TITLE
How to use with ImmutableJS?

### ISSUE THREAD

**Issue by ottoo** [davidkpiano/react-redux-form#319]
Hey. I tried to look around and find how to use the project with ImmutableJS, but couldn't really figure it out? Could you at some point provide a section in the documentation?

I tried to create a modelReducer and formReducer with

```js
import { modelReducer } from 'react-redux-form/lib/immutable';
import { formReducer } from 'react-redux-form';
import Immutable from 'immutable';

export default combineReducers({
  user: modelReducer('rootReducer.userData.user', Immutable.Map())
  userForm: formReducer('rootReducer.userData.user', Immutable.Map())
});
```

and something like this. Does the model need to be converted toJS() here or can it be straight the Immutable.Map() from the model?

```js
const { user } = this.props;

<Form model="user"  onSubmit={...}>
  <Field model="user.username">
    <input type="text">
  </Field>

  <Field model="user.password">
    <input type="password">
  </Field>
</Form>
```

and then somewhere in code attach this to the store. Is this the correct way? My form would render, but the inputs didn't render/take in any values, though actions were dispatched.

**Comment by Sephi-Chan** [comment]
Same problem here.

**Comment by davidkpiano** [comment]
I'm working on this! What's going to happen temporarily in `0.x` is you'll have to `import { Field } from 'react-redux-form/lib/immutable'` as well, and then use that.

In V1 it'll work the exact same way, importing from `'react-redux-form/immutable'` instead however.`

**Comment by davidkpiano** [comment]
@sephi-chan @ottoo Can you do me a huge favor and post a minimally reproducible code sample on www.esnextb.in that shows that `<Field>` doesn't work with an immutable model reducer using Immutable.JS? That way I can write accurate unit tests.

**Comment by davidkpiano** [comment]
Here's the fix, just like I mentioned. Now you have to import `Field` as well from `react-redux-form/lib/immutable` (which isn't a huge deal, since you're importing stuff from there anyway).

If you're curious to how this was done, it's just this:

```js
const ImmutableField = createFieldClass(undefined, {
  getter: immutableGetFromState,
});
```

where `immutableGetFromState(state, model)` is a function that gets the model from the state, and checks along the way to see if it's an Immutable data structure. If it is, it calls `.get()` to get the value instead of accessing it directly.

**Comment by Sephi-Chan** [comment]
I get errors when i import Field from react-redux-form/lib/immutable.

Here us the minimal code :

```es6
import React from 'react';
import ReactDOM from 'react-dom';
import { Map } from 'immutable';
import { Provider, connect } from 'react-redux';
import { createStore, combineReducers } from 'redux';
import { actions, formReducer } from 'react-redux-form';
import { Field, modelReducer } from 'react-redux-form/lib/immutable';

const initialUserState = {
  firstName: '',
  lastName: ''
};

const store = createStore(combineReducers({
  user: modelReducer('user', Map(initialUserState)),
  userForm: formReducer('user')
}));


class UserForm extends React.Component {
  handleSubmit(event) {
    event.preventDefault()
    let { user, dispatch } = this.props;

    // Do whatever you like in here.
    // You can use redux simple form actions such as:
    // actions.setPending('user', true);
    // actions.setValidity('user.firstName', user.firstName.length > 0);
    // actions.setSubmitted('user', true);
    // etc.
  }
  render() {
    let { user } = this.props;

    return (
      <form onSubmit={this.handleSubmit.bind(this)}>
        <Field model="user.firstName">
          <label>First name:</label>
          <input type="text" />
        </Field>

        <Field model="user.lastName">
          <label>Last name:</label>
          <input type="text" />
        </Field>

        <button type="submit">
          Finish registration, { user.firstName } { user.lastName }!
        </button>
      </form>
    );
  }
}

function mapStateToProps(state) {
  return { user: state.user };
}

const ConnectedUserForm = connect(mapStateToProps)(UserForm);


class App extends React.Component {
  render() {
    return (
      <Provider store={ store }>
        <ConnectedUserForm />
      </Provider>
    );
  }
}


ReactDOM.render(<App />, document.getElementById('container'));
```

**Comment by mackenzie-gray** [comment]
This hasn't seemed to fix the issue for myself either, I am getting `Unknown prop 'getter'` in my console now after building from src and importing the lib into my project.

**Comment by ozum** [comment]
I also couldn't manage to get a working example with react-redux-form either `v0.x` or `v1 beta`. Could you please provide single file minimal working example.

**Comment by erin-doyle** [comment]
Is it possible this is still not working completely with immutable.js?

I am using the latest version (1.0.3) of react-redux-form.  I am importing combineForms from react-redux-form/lib/immutable and using it like so:

```
import { combineForms } from 'react-redux-form/lib/immutable';

const store = createStore(combineReducers({
    routing: routerReducer,
    intl: intlReducer,
    form: combineForms({
        recipientName: fromJS({ name: '' }),
        senderNameEmail: fromJS({ name: '', email: '' })
    }, 'form')
}));
```

then in my form I'm importing Field and Form from the same place like so:

```
import { Field, Form } from 'react-redux-form/lib/immutable';

const handleSubmit = (formData) => {
    console.log('Submitted Data: ');
    console.dir(formData);
};

const RecipientNameForm = (props) => {

    return (
        <Form model="form.recipientName" onSubmit={ (data) => handleSubmit(data) }>
            <section className="panel">
                <Field model=".name">
                    <div className="input-group">
                        <label>{ recipientMessages.label }</label>
                        <div>
                            <input type="text" />
                        </div>
                    </div>
                </Field>
            </section>
            <ButtonComp btnType="submit">
                <FormattedMessage
                    tagName='span' { ...recipientMessages.button } />
            </ButtonComp>
        </Form>
    );
};

export default RecipientNameForm;
```

It seems as if when things like updateField() or changeActionReducer() are called they are passed the state as a plain object but when mapStateToProps() in the form-component is called it's passed the state as an Immutable Map and therefore the modelValue is unable to be retrieved as the code attempting to access the value is expecting a plain object.  So the store seems to be getting updated but my onSubmit handler receives undefined.

I can't tell if maybe there's something not correct about my implementation or if react-redux-router is still not really proven to be compatible with immutable?

**Comment by davidkpiano** [comment]
@erin-doyle I'm still working on making React-Redux-Form compatible with ImmutableJS. It's a non-trivial task, but I'm halfway done.

**Comment by erin-doyle** [comment]
Ah ok, well that certainly helps to know!  This is a really great library and I thank you for all your efforts so far so I will definitely be looking forward to that!  If you wish to dole out any of the work I'd be very interesting in chipping in and contributing!

**Comment by davidkpiano** [comment]
Thanks @erin-doyle - always willing to accept PRs! Essentially, here's a concept of what I'm doing to make RRF compatible with ImmutableJS.

First, we start with an original function:
```js
import get from 'lodash/get';
import i from 'icepick';

function double(state, prop, value) {
  const firstValue = get(state, prop); // eg. get(user, 'age') for user.age
  const doubledValue = firstValue * 2;
  return i.set(state, prop, doubledValue);
}
```

Then we separate the internal operational functions into "strategies":
```js
import get from 'lodash/get';
import i from 'icepick';

const strategy = {
  get: (state, path) => get(state, path),
  set: (state, path, value) => i.set(state, path, value),
};

function double(state, prop, value) {
  const firstValue = strategy.get(state, prop);
  const doubledValue = firstValue * 2;
  return strategy.set(state, prop, doubledValue);
}
```

And then we create a function that takes in a `strategy` and returns the original function with the specified strategy:

```js
// ...

const defaultStrategy = { ... }; // same as above

function createDoubler(strategy = defaultStrategy) {
  return function double(state, prop, value) {
    const firstValue = strategy.get(state, prop);
    const doubledValue = firstValue * 2;
    return strategy.set(state, prop, doubledValue);
  }
}

export default createDoubler();
export { createDoubler };
```

From there, we can `import { createDoubler } from ...` and use it with an ImmutableJS strategy like:

```js
import { createDoubler } from 'path/to/doubler';

function immutableGet(state, path) { /* ... */ }
function immutableSet(state, path, value) { /* ... */ }

const immutableStrategy = {
  get: immutableGet,
  set: immutableSet,
};

const doubler = createDoubler(immutableStrategy);

export default doubler;
```

**Comment by erin-doyle** [comment]
So is my assumption correct that a punch list of what's left to do can be determined from the export list in https://github.com/davidkpiano/react-redux-form/blob/master/src/immutable.js where there is not yet an immutable counterpart?

**Comment by davidkpiano** [comment]
Yep! And also a slight refactoring of the unit tests (I got started on this in `field-component-spec.js`):

```js
// ...

const testContexts = {
  standard: {
    Field: _Field,
    actions: _actions,
    modelReducer: _modelReducer,
    formReducer: _formReducer,
    get: _get,
    length: (value) => value.length,
  },
  immutable: {
    Field: ImmutableField,
    actions: immutableActions,
    modelReducer: (model, initialState) =>
      immutableModelReducer(model, Immutable.fromJS(initialState)),
    formReducer: immutableFormReducer,
    get: (value, path) => {
      const result = value.getIn(toPath(path));
      try {
        return result.toJS();
      } catch (e) {
        return result;
      }
    },
    length: (value) => value.size,
  },
};

Object.keys(testContexts).forEach((testKey) => {
// ... all the tests
```

**Comment by erin-doyle** [comment]
I think this is pretty close to being done now.  In my testing everything seems to be working.  The only exception I'm finding at this point is if creating the store using the [redux-immutable library](https://github.com/gajus/redux-immutable).  If the entire store is immutable there seems to still be problems, most notably in get-form.js, otherwise if only the models within the store are immutable but the store itself is not, things seem to be working well.

I am already working on a branch for making things compatible with redux-immutable but just wanted to post that update!

**Comment by davidkpiano** [comment]
> if only the models within the store are immutable but the store itself is not, things seem to be working well.

Yep, this is the intention @erin-doyle - if we can keep the `formReducer` as working with plain JS objects (even if working with immutable models), I think that should still satisfy most use cases.

**Comment by erin-doyle** [comment]
So here is what the structure looks like when using redux-immutable's combineReducers like so:

```
const initialUserState = Immutable.fromJS({
  firstName: '',
  lastName: '',
});

const store = applyMiddleware(thunk)(createStore)(combineReducers({
  ...createForms({
    user: initialUserState,
  })
}));
```

```
state: Map
  user: Map
  forms: { // Object
    form: { // Object
      errors: Object
      focus: false
      initialValue: { // Object
        user: Map
      }
      model: ""
      pending: false
      pristine: true
      retouched: false
      submitFailed: false
      submitted: false
      touched: false
      valid: true
      validated: false
      validating: false
      validity: Object
      value: { // Object
        user: Map
      }
    },
    user: { // Object
      errors: Object
      focus: false
      initialValue: Map
      model: "user"
      pending: false
      pristine: true
      retouched: false
      submitFailed: false
      submitted: false
      touched: false
      valid: true
      validated: false
      validating: false
      validity: Object
      value: Map
    }
  }
```

Does that still look acceptable to you?  I think the only problem is that now the root state is a Map so just getting a form or model must be done differently in addition to getting values from models.  But it looks like once you get the form it's shape remains a plain object.

**Comment by erin-doyle** [comment]
Actually nevermind, I can see now that isn't right.  It looks like the forms.user object does not contain the structure that it should.  I can look into that.

**Comment by erin-doyle** [comment]
#457 should now make the structure of the forms.user object match whether using an immutable implementation or not.

**Comment by erin-doyle** [comment]
I believe this is now done.  I've done a good amount of testing and have not found any further issues with using just redux or redux-immutable.  I think all that remains is documenting it! :)

**Comment by davidkpiano** [comment]
Docs here! http://davidkpiano.github.io/react-redux-form/docs/guides/immutable.html
