### ISSUE TITLE
Issues with checkboxes

### ISSUE THREAD

**Issue by sattaman** [davidkpiano/react-redux-form#32]
I've been having issues getting checkboxes to work. 

When using the exact code in
http://davidkpiano.github.io/react-redux-form/#/recipe/complex-values

The events are fired, the model updates but the checkbox does not get checked.

**Comment by sattaman** [comment]
I ideally want to get it working with ReactBootstrap, I have tried both using controls.checkbox and controls .text.

```
export const CheckboxFormField = createFieldClass({
    'Input': controls.checkbox
});

<CheckboxFormField model="options.type[]"  validators={{required: (vals) => vals.length}}>
                        <Input type="checkbox" label="SMS" value="sms" />
                        <Input type="checkbox" label="Email" value="email" />
                    </CheckboxFormField>
```

**Comment by davidkpiano** [comment]
Sorry about that! This change is now fixed and published in `react-redux-form@0.6.3`. 

The issue had to do with how `<Field>` knew which "updating" action to choose for each control. It didn't think that `Input` was a checkbox, but now it does, as long as it has `type="checkbox"`.

**Comment by muuki88** [comment]
So this is working with `CheckboxFormField` now? We have react-bootstrap as well and the complex-values examples doesn't work properly: instead of appending hobbies to the list, it just overrides it. Even we use plain `input` elements.

I'll report if the `CheckboxFormField` works for use.

**Comment by muuki88** [comment]
@sattaman were does the `controls.checkbox` property come from?

**Comment by muuki88** [comment]
Sorry. `import {controls} from 'react-redux-form';`

**Comment by davidkpiano** [comment]
Yes, it should be working with checkboxes now. Let me know if you have further issues.

**Comment by sattaman** [comment]
@muuki88 yes that's exactly what I found, I got it working with a singe checkbox in the end like this: 

```
export const CheckboxFormField = createFieldClass({
    'Input': (props) =>
        ({onChange: (e, val) => { props.onChange(!props.checked)} })
});

   <CheckboxFormField model="myModel.field">
                <Input type="checkbox" label="Check" checked={myModel.field} />
            </CheckboxFormField>
```

@davidkpiano Another issue I had was, since all the bootstrap elements use the same control 'Input', something like 

```
export const CheckboxFormField = createFieldClass({
    'Input':controls.checkbox
});

export const TextFormField = createFieldClass({
    'Input': controls.text
});
```

Didnt work

**Comment by muuki88** [comment]
We figured it out. Our error was that we didn't use the correct model paths. Because nesting _reducers_ with _combineReducers_ is the same as [model in nested state](http://davidkpiano.github.io/react-redux-form/#/recipe/model-in-nested-state?_k=t4nbbq).

[This jsfiddle](https://jsfiddle.net/muuki88/0r0dpu1q/) demonstrates how things are working now. Why it took us so long: all other form inputs seem to work (text fields, radio buttons). The checkbox however has an internal `checked` state. 

Anyway, thanks for your great library and the extensive documentation :)

**Comment by davidkpiano** [comment]
Awesome, glad you got it working @muuki88 ! Let me know if there's anything you'd like to see in the docs and I'll be sure to add it.
