### ISSUE TITLE
Advice on where to put form data?

### ISSUE THREAD

**Issue by tmartensen** [davidkpiano/react-redux-form#321]
This is more of a question than an issue, but what is the best practice for keeping form data with the form? For example: currently, I'm loading several arrays of options from the server and using them to populate options in some selects. Where would these options be stored in state? Any suggestions would be helpful. Thanks!

**Comment by davidkpiano** [comment]
What kind of options would these be? Is it related to the model or the form state?

If it's the model, make a custom reducer and wrap it in `modeled(...)`: https://davidkpiano.gitbooks.io/react-redux-form/content/model_reducers.html#using-existing-reducers

**Comment by tmartensen** [comment]
I would think that the options would be form state, because those choices might not necessarily be saved as part of the model. For instance, when selecting a car, you would only select one make (e.g., Ford) to be come part of the model. All the other options should be somewhere in state, but not in the model. Does that make sense?

**Comment by davidkpiano** [comment]
So you're talking about an array of options such as `{ makes: ['Ford', 'BMW', 'Audi', 'Tesla'] }` etc.? Seems to me like this is a constant that should be referenced in a separate reducer, since the model reducer only cares about what the _current value_ is, and the form reducer only cares about the _state of the form_, such as `focus`, `pristine`, etc.

I'd set up something like this:

```js
import { actionTypes } from 'react-redux-form';

const makeReducer = (state = [], action) => {
  switch (action.type) {
    case actionTypes.CHANGE:
      if (action.model === 'vehicle.make') {
        switch (action.value) {
          case 'car':
            return ['Ford', 'BMW', 'Audi', 'Tesla'];
          default:
            // etc.
        }
      }
    // ... etc. return state
  }
}
```

**Comment by tmartensen** [comment]
That answered my question! Thanks!
