### ISSUE TITLE
[React.Native] How to run submit logic?

### ISSUE THREAD

**Issue by alexesDev** [davidkpiano/react-redux-form#322]
I see a source code, ```<form>``` has submit event and it run validation.
But how can I run the validation for the native form? (for empty form)

```js
import { Form } from 'react-redux-form/lib/native';

<Form model="user">
  <button??? />
</Form>
```

**Comment by alexesDev** [comment]
Solution

```js
const FormComponent = ({ onSubmit, submitProps, children, ...props }) => (
  <View {...props}>
    {children}
     <TouchableOpacity onPress={onSubmit} {...submitProps}>
       <Text>Submit</Text>
     </TouchableOpacity>
  </View>
);
```

```js
<Form component={FormComponent} validators={validators} ...>
   ...
</Form>
```

**Comment by davidkpiano** [comment]
@alexesDev That's a good solution! Since RRF is a library, and not a framework, more than one solution exists and you can use the one that best fits your needs. You can validate directly on the `<Field>`s, or you can dispatch actions that validate before submitting.

**Comment by alexesDev** [comment]
@davidkpiano Is an awesome library! Very gracefully :+1:
