### ISSUE TITLE
Multiple levels of tracking

### ISSUE THREAD

**Issue by debradley** [davidkpiano/react-redux-form#323]
This is either a question or an enhancement request...

The data I'm working with represents a multiple choice quiz. A quiz has many questions and each question has many choices. That means the model I need to navigate looks like: `quiz.questions[x].choices[y].prompt`. track() will get me to `quiz.questions[id=x].choices` but no further - how do I get the rest of the way?

**Comment by davidkpiano** [comment]
See the answer over here: https://github.com/davidkpiano/react-redux-form/issues/313

However, would something like this make sense? 

```js
// future? syntax
import { trackDeep } from 'react-redux-form';

// ...
<Field
  model={trackDeep('quiz.questions[].choices[].prompt', { id: 12 }, { key: 'a' })}
>
```

`trackDeep` would be a function with the signature `(modelPath, predicates...)` where each predicate would refer to each collection. So in the above example:

- the model for the questions with `id === 12` would be found...
- and then the model for the choices with `key === 'a'` inside that questions model would be found.

Would this be a good addition to the API? cc. @hgylfason

**Comment by debradley** [comment]
Thanks for the link to 313 - that definitely helps me move forward for now.

As far as the API for nested fields, what you're proposing makes sense to me. Though I don't think there needs to be a `trackDeep` added, you could add the new behavior to `track` without breaking anything, right?

**Comment by davidkpiano** [comment]
> you could add the new behavior to track without breaking anything, right?

Good catch, yes I can!

**Comment by davidkpiano** [comment]
Added to `@beta` here: https://github.com/davidkpiano/react-redux-form/commit/44e0712144e5775aa1f6d0f2d7a39b0a80805ec4
