### ISSUE TITLE
Nested reducers.

### ISSUE THREAD

**Issue by odub** [davidkpiano/react-redux-form#325]
Hi,

I want to use `react-redux-form` outside of the root-level reducer.

My root reducer would look this:
```js
// reducers/index.js
import { combineReducers } from 'redux';
import formReducer from './form';

const someOtherReducer = state => state;

export default combineReducers({
  other: someOtherReducer,
  form: formReducer,
});
```

With the formReducer as:
```js
// reducers/form.js
import { modelReducer, formReducer } from 'react-redux-form';

export const createUser = modelReducer('changePassword', {});
export const createUserForm = formReducer('changePassword', {});

export default combineReducers({
  createUser,
  createUserForm,
});
```

This doesn't seem to work. I've tried:
* setting the string input to `modelReducer` and `formReducer` to `'form.changePassword'`
* doing the same in the views
* doing the same in only one of the views or the reducer definition (both ways around)

Is this a supported pattern?

**Comment by odub** [comment]
Btw everything works just fine when I put the `modelReducer` and `formReducer` calls in the root. For a large app, this doesn't seem too elegant, though.

**Comment by davidkpiano** [comment]
In order for RRF to know where to read/update the model, it needs to be provided the _exact path_ (relative to the store state) to the model, so try this:

```js
// reducers/form.js
import { modelReducer, formReducer } from 'react-redux-form';

// this will be accessed in the state as .form.createUser
export const createUser = modelReducer('form.createUser', {});

// same model as the model reducer
export const createUserForm = formReducer('form.createUser', {});

export default combineReducers({
  createUser,
  createUserForm,
});
```

Let me know if the above solution works with your use case.

**Comment by odub** [comment]
Nice! Thanks for the solution.
