### ISSUE TITLE
Validate by several events

### ISSUE THREAD

**Issue by Slavenin** [davidkpiano/react-redux-form#327]
Hi!
How i can validate data by several events, example, focus and blur?

**Comment by davidkpiano** [comment]
This would be a good enhancement for V1.0. I imagine the syntax would be:

```js
<Field model="..."
  validateOn={['focus', 'blur']}
>
```

**Comment by Slavenin** [comment]
I think the same

**Comment by davidkpiano** [comment]
Fixed and will go out in next `@beta`! The syntax is exactly as above, and can be used in any similar props, such as `updateOn`, `validateOn`, `asyncValidateOn`, etc.
