### ISSUE TITLE
Do not run async validations before sync validations are passing

### ISSUE THREAD

**Issue by morsdyce** [davidkpiano/react-redux-form#329]
Currently the Field component will run async validations even though the sync validations didn't pass.

It is possible to overcome this issue by checking the value and calling the done callback as true but it doesn't seem very intuitive and requires additional code for every async check.

It would be nice if the async validations would only run if the sync validations have passed.

**Comment by davidkpiano** [comment]
Still planning this as an enhancement, but as an option - there are use-cases where async validity _should_ run even though sync validity is invalid. As a contrived example, say there's a `username` field with:

- **sync** validity that it cannot be the same as the `email` field
- **async** validity that it cannot be already taken

It would be useful to see simultaneous errors that the username is the same as the email field _and_ that it's already taken, so the user can know that simply changing the email won't make it valid.

**Comment by morsdyce** [comment]
I personally think the example didn't fit to what you were trying to say, the point of this is to minimize requests to the server so if the sync validity is invalid there is no reason to hit the server.

But I agree you should let the consumer of this library to decide what he wants.
I personally would put the async only when sync passes as the default setting as it is for example in angular 1 and probably many more libraries/frameworks.

**Comment by davidkpiano** [comment]
Okay, good point.
