### ISSUE TITLE
Question: Use of "for of" es6 syntax forces bundle bloat in IE11

### ISSUE THREAD

**Issue by mdgbayly** [davidkpiano/react-redux-form#333]
This line in form-reducer.js uses the new "for of" syntax. 

https://github.com/davidkpiano/react-redux-form/blob/master/src/reducers/form-reducer.js#L173

This causes babel to output Symbol related code which means that you then have to polyfill Symbol for browsers that still don't support it (e.g. IE11)

Polyfilling symbol is adding another 77 K to our bundle (using core-js).  Maybe there is a less verbose way but not found it yet...

We seem to have to add this to our webpack config to get the Symbol code to work:
```
var entry = [
        ...
	'core-js/es6/symbol',
	'core-js/es6/object',
	'core-js/es6/typed'
];
```
Which ends up being 10% of our bundle...

core-js: 77.2 KB (9.68%)

Any chance you could switch to using a less modern for loop? :-)

**Comment by davidkpiano** [comment]
Done! Look for this one in an upcoming patch!
