### ISSUE TITLE
Feature request: UMD build

### ISSUE THREAD

**Issue by mdgbayly** [davidkpiano/react-redux-form#334]
Consider building a umd version of react-redux-form as part of your npm install.

As part of our bundle optimization task, we're moving a number of common libs to our own CDN.  A number of other React based packages include a umd build of the package in their npm install which makes it easy to copy up to a private CDN.

I see there is already some umd based build code in this repo, but I'm not sure if it's being used, and I had to tweak it a bit to get it to work.

Is this something you'd be open to including?

Once you include it, it makes it easy for clients to pick it off the [npmcdn](https://npmcdn.com/#/) too.

**Comment by davidkpiano** [comment]
Yes, I'd be open to including that. What did you need to add to get it to work? If you'd like to make a PR, I'd be happy to merge it. Otherwise I can look into it sometime this weekend.

**Comment by mdgbayly** [comment]
Created a PR #341 
Not sure if best approach but was working for me.
Cheers
