### ISSUE TITLE
Updating the model on change based on fields calculations

### ISSUE THREAD

**Issue by MilanThomas** [davidkpiano/react-redux-form#342]
My model reducer is linked to a state like this :
```
state= {
  a: 2,
  b: 3,
  result: 5
}
```
In my Form, I have 2 **`<Fields />`** pointing to state.a and state.b

I want to calculate, **as the user is typing** and while validating his input the **result of state.a + state.b**

As soon as the user has typed correct values, I want to **display this result**, **update state.result with the calculated value** while still **updating the model** as he keeps on typing.

How would you do it ?

Thank you.

_I made it work for the onSubmit event, but I can't seem to find a proper way to do it onChange. Feel free to ask me if you need more context or code to understand my question :)_

**Comment by davidkpiano** [comment]
As Redux suggests, `result` is **derived data** so it's best handled in a selector: http://redux.js.org/docs/recipes/ComputingDerivedData.html

So you ideally would have a state that only contains non-derived data:

```js
state = {
  a: 2,
  b: 3,
}
```

and a selector:

```js

const MyComponent = // ...

export default connect((state) => ({
  ...state,
  result: state.a + state.b,
})(MyComponent);
```

**Comment by MilanThomas** [comment]
Oh, I see ! Indeed, that makes a lot of sense. 
Thank you for pointing me in the right direction and for creating react-redux-form :)
