### ISSUE TITLE
Validating arrays with dynamic lengths?

### ISSUE THREAD

**Issue by mewben** [davidkpiano/react-redux-form#343]
I have this following Model and Form
```js

const parent = {
	firstName: '',
	lastName: '',
	children: [{
		firstName: '',
		lastName: '',
		age: 1
	}]
}

const parentModel = modelReducer('parentModel', parent)
const parentForm = formReducer('parentModel', parent)
```

Then, I dispatch this object to the parentModel: (Notice that the children has 2 objects in the array)
```js
const parentFromDB = {
	firstName: 'John',
	lastName: 'Doe',
	children: [{
		firstName: 'Alice',
		lastName: 'Doe',
		age: 1
	}, {
		firstName: 'Bob',
		lastName: 'Doe',
		age: 150
	}]
}

dispatch(actions.load('parentModel', parentFromDB))
```

Now, I have an edit form to edit the children's names and age. How do I validate every `age` of the array to, let's say less than 100? 

My initial code passes the `parentForm` and accesses the `fields` to see if it is `valid`. However, I can only see the first object in the array. Is there a way to do this? Thanks and more power.

**Comment by davidkpiano** [comment]
On the `<Form>`, just add a validator:

```js
import { Form } from 'react-redux-form';

// ...

<Form model="parentModel"
  validators={{
    'children': (children) => children.every({ age } => age < 100)
  }}
>
```

Does that answer your question?

**Comment by mewben** [comment]
Thank you for the quick response. The code works. Thanks. However, what I really wanted was to attach a className to the `age` input whenever it is invalid.

```js
{parentModel.children.map((child, k) => {
	return (
		<div key={k}>
			<Field model={`parentModel.children[${k}].firstName`}>
				<label>Child {k + 1} - First Name</label>
				<input type="text" />
			</Field>
			<Field model={`parentModel.children[${k}].age`}>
				<label>Child {k + 1} - Age</label>
				<input type="text" className={'----> ERROR CLASS HERE IF NOT VALID <---'} />
			</Field>
		</div>
	)
})}
```

I tried accessing the `parentForm.fields.children.0.age.valid` which is fine, but `parentForm.fields.children.1.age.valid` is undefined.

**Comment by davidkpiano** [comment]
Can you put it up on www.esnextb.in so I can reproduce?

And are you accessing it via `parentForm.fields['children.0.age'].valid`? That's the current (ugly) way to access a field.

In V1.0, you can access it more intuitively: `parentForm.children[0].age`.

**Comment by mewben** [comment]
> And are you accessing it via parentForm.fields['children.0.age'].valid? That's the current (ugly) way to access a field.

Yes. That's what I'm using right now. However, it doesn't have `['children.1.age']`

![Screenshot Log](http://res.cloudinary.com/dmapjljrk/image/upload/v1470274971/Screen_Shot_2016-08-04_at_9.40.00_AM_u2crbu.png)

Here's the [code](https://esnextb.in/?gist=e4614eb59e3f9b2833a6243fad6022bc).

I tried using `"react-redux-form": "^1.0.0-beta.1",` but it doesn't compile in esnextb.in
Here is the sreenshot using beta in my local machine:
![Screenshot log v1beta](http://res.cloudinary.com/dmapjljrk/image/upload/v1470275807/Screen_Shot_2016-08-04_at_9.56.13_AM_w5ttqr.png)

Notice that there's only 1 object in the array instead of 2 from the parentModel.

P.S. Sorry for the big images. Don't know how to make them smaller. :)

**Comment by davidkpiano** [comment]
Try adding a validator directly to the field:

```js
<Field model={`parentModel.children[${k}].age`}
    validators={{
      max: (age) => age < 100
    }}
  >
    <input type="text" />
  </Field>
```

I get the expected result in the console when I try this.

**Comment by mewben** [comment]
Ahhh.. yes.. this works.. Thank you very much. :)
