### ISSUE TITLE
Handling validation with parameters for later viewing

### ISSUE THREAD

**Issue by Psykar** [davidkpiano/react-redux-form#344]
Say you have a 'between' validator, with a min max value, there is currently no way to easily get this up to  a messages prop on `<Error>` without returning a string from an `errors` prop, as otherwise you lose the min / max values and only would have the 'between' key.

ie, this won't work as a validator because even if we put something else instead of true, it gets evaluated as truthy.
```javascript
        between: value => {
          if (validator.isInt(`${value}`, {
            max,
            min,
          })) {
            return true
          }
          return false
        },
```

This will work as an errorValidator, but now we've got messages in the middle of our logic, which you suggest should be avoided.
```javascript
        between: value => {
          if (validator.isInt(`${value}`, {
            max,
            min,
          })) {
            return false
          }
          return `${field} should be between ${min} and ${max}`
        },
```

Ideally I should be able to do something like
```javascript
        between: value => {
          if (validator.isInt(`${value}`, {
            max,
            min,
          })) {
            return false
          }
          return {min, max}
        },
```
then
```javascript
messages = {
  between: ({min, max, value}) => ``${value} is not between ${min} and ${max}`
}
<Error model={...} messages={messages}/>
```

**Comment by davidkpiano** [comment]
This would make a good enhancement, but I think we can avoid "nesting" the value in the first argument by just providing the `error` in the second argument:

```js
// message (as function) API:
// [key]: (value, error) => message

<Error model="..."
  messages={{
    between: (value, {min, max}) => `${value} is not between ${min} and ${max}`,
  }}
>
```

What do you think about that?

**Comment by Psykar** [comment]
Ah, of course, then it's literally the same object returned from validate, sounds good to me.

The part that's a little more up in the air for me (before I'd look at starting a PR) is if the object should be returnable from both 'validator' and 'errorValidator'. The semantics for validate become a little funny if it can be {true/false/object} from validate, where 'object' is actually effectively a 'false' for most purposes except the messaging.
errorValidator, where 'object' is equivalent to 'true' seems more palatible, but the 'validator' pattern seems to be more recommended.

**Comment by davidkpiano** [comment]
As far as what's recommended and not recommended, I wouldn't be biased on one approach over another, especially with a complex validity use-case such as this one (which would even be non-trivial with any other validation library).

I'd say the way to go, if we're using this API, is to have it as an `errors={{...}}` validator on the `<Field>` (or `<Form>`, your preference), where a truthy object, such as `{min, max}` would signify an error.

Alternatively, the easiest way to really accomplish this without any API changes is to have something like this...

```js
const MIN_LENGTH = 3;
const MAX_LENGTH = 12;

// ...

<Errors model="..."
  messages={{
    between: (val) => `${val} is not between ${MIN_LENGTH} and ${MAX_LENGTH}`
  }}
>
```

**Comment by Psykar** [comment]
Ha, unfortunately in my use case min/max can change based on the value of another field, so const's are out. If only everything was simple... 

Can't commit the time to a PR just yet, but I'm hoping sometime this week.
