### ISSUE TITLE
updateOn='blur' combined with actions.change() does not work

### ISSUE THREAD

**Issue by venelin-mihaylov** [davidkpiano/react-redux-form#345]
I async load data from the server.
Then I use actions.change() / actions.load() to show the data in the form
when the fields have updateOn='change', this works
when the fields have updateOn='blur', the data from the model does not show in the form

am I doing something wrong? Seems to the correct APIs to use ...

https://esnextb.in/?gist=6385b34bd63ac05bf69227fc6c165e6c

**Comment by davidkpiano** [comment]
This is addressed in V1 and is due to the fact that `updateOn="blur"` in v0.x is an _uncontrolled_ component: https://github.com/davidkpiano/react-redux-form/issues/278

**Comment by venelin-mihaylov** [comment]
Thank you for your response.
