### ISSUE TITLE
Field validity reset on component unmount

### ISSUE THREAD

**Issue by Psykar** [davidkpiano/react-redux-form#346]
While it looks like it was intentional, this is playing havoc with my usecase, which is a multipage form, with any page being navigate-able at any one point, causing all fields on a page to unmount and have their validity reset.

https://github.com/davidkpiano/react-redux-form/blame/master/src/components/control-component.js#L89

This definitely makes sense if the validity is set on the `<Field>` component, but if validity is set at the `<Form>` level, a field which is invalid and gets unmounted, gets it's validity set to true and will never be checked again even on form submission as it only checks if the field's value changes.

Four options I'd say (plus some workarounds if this isn't feasible) - 
1. A force revalidate action on the entire form (as an argument to actions.validate ? )
2. A prop on the `<Form>` component to disable this reset
3. A prop on `<Field>` to disable this reset
4. I manually iterate my validators and setInvalid on the fields myself
5. ... or make all my fields not use the `<Field>` component, or make my pages show/hide instead of add/remove from the DOM, or stop users navigating if the current page is invalid etc. etc.....
...

I'd prefer 2, but that's likely also the hardest of the lot to implement, and means adding more props... any thoughts?

**Comment by davidkpiano** [comment]
I can make it so that only validity present in the Field's `validators` are reset on unmount, would that make sense?

**Comment by Psykar** [comment]
If you're comfortable with that sure, that seems rather special case-y to me - although I suppose most people will be using *either* field level or form level validation, not both.

**Comment by Psykar** [comment]
Another thing to note here - if the <Form> component's `validators` or `errors` prop changes, the form validation isn't touched. I feel that if either of these properties changes, the entire form should be revalidated.

**Comment by davidkpiano** [comment]
@Psykar after the latest `@beta`, if this issue persists:

> Another thing to note here - if the <Form> component's validators or errors prop changes, the form validation isn't touched. I feel that if either of these properties changes, the entire form should be revalidated.

can you open up another ticket for it?
