### ISSUE TITLE
<Field> copies style to its children components.

### ISSUE THREAD

**Issue by djkz** [davidkpiano/react-redux-form#349]
Before when we had 
`<Field style="width:50%"><label /><input /></Field>` we would get top div with the applied style and input with no style (you could set it manually).

Now the top field style propagates to the child component so you have `<div style="width:50%"> <input style="width:50%" /></div>` as the resulting HTML.

Style should probably be blacklisted from being passed and applied manually to the child components.

**Comment by davidkpiano** [comment]
Made a fix for this here: https://github.com/davidkpiano/react-redux-form/commit/b50773fface01b2f4b3c88a43ae96ee9e759ad04

I'll write a unit test to assert that it works as expected soon!
