### ISSUE TITLE
Immutable support doesn't seem to work

### ISSUE THREAD

**Issue by Kuzmin** [davidkpiano/react-redux-form#35]
If I do

```
import { createModelReducer } from 'react-redux-form/immutable';
```
 
It doesn't work, even though that's the way it's supposed to work according to the docs. Any idea of what's wrong? Trying to import from `react-redux-form/src/immutable` also doesn't work.

**Comment by davidkpiano** [comment]
Try this:

```js
import { createModelReducer } from 'react-redux-form/lib/immutable';
```

Sorry, must be a typo. I'll update the docs. See this to verify that it works: http://esnextb.in/?gist=2ab8505dfda15d995a7e
