### ISSUE TITLE
v1 - alpha release?

### ISSUE THREAD

**Issue by enkay** [davidkpiano/react-redux-form#350]
Is there an alpha available for v1?

I would like to give this package a try however it seems like the latest release has a lot of issues that are fixed in v1.

If it's just the upgrade guide and docs missing from v1, I wouldn't mind playing around with it instead of dealing with issues in 0.* that have already been fixed.

**Comment by Psykar** [comment]
There's actually a beta release already on npm:
`npm install react-redux-form@1.0.0-beta.2` should work

**Comment by enkay** [comment]
Great, thank you!

**Comment by davidkpiano** [comment]
@enkay @Psykar Keep in mind that there are a couple breaking changes (although 90% of the API has remained the same), and I will be documenting these today!

**Comment by davidkpiano** [comment]
The latest (in progress) documentation is available here: https://davidkpiano.github.io/react-redux-form - I will be working on finishing this this week.

To keep up to date with the latest beta versions, just `npm install react-redux-form@beta` 🎉
