### ISSUE TITLE
File input  - Invariant Violation

### ISSUE THREAD

**Issue by wojciech-bilicki** [davidkpiano/react-redux-form#351]
When I am trying to use library to add file to Form I get: 

> Invariant Violation: A state mutation was detected between dispatches, in the path `invoice.invoice_file.0.lastModifiedDate`. This may cause incorrect behavior.

The Field for the file looks like this: 
```
<Field className="btn" model="invoice.invoice_file">
            <span>Plik z fakturą</span>
            <input type="file" name="invoice_file" />
  </Field>
```

Also couldn't find anything about fileInput in the documentation. It would be nice if we could get an example.

Also I was trying to get this going with custom handler: 

```
<div className="btn">
            <span>Plik z fakturą</span>
            <input type="file" name="invoice_file" onChange={this.handleFileUpload}/>
          </div>

... 
  handleFileUpload(e){
    e.preventDefault();
    let file = e.target.files[0];
    this.props.mergeModel('invoice.invoice_file', file);
  }

... 

function mapDispatchToProps(dispatch) {
  return {
    saveInvoice: bindActionCreators(saveInvoice, dispatch),
    changeModel: bindActionCreators(actions.change, dispatch),
    mergeModel: bindActionCreators(actions.merge, dispatch)
  };
}
``` 

But this also causes Invariant Violation error. Did anyone got this right with file input?

**Comment by davidkpiano** [comment]
Can you put it up on www.esnextb.in with the minimally reproducible code?

Also, for reference, here is the unit test for `<input type="file" />`: https://github.com/davidkpiano/react-redux-form/blob/master/test/field-component-spec.js#L489-L521

I'm working on the V1 docs right now, and will definitely include this.

**Comment by wojciech-bilicki** [comment]
Ok, so I put this on esnextbin.in and it was alright. So I checked what are the differences between my project and esnextbin setup and I found out I was using redux-immutable-state-invariant

https://github.com/leoasis/redux-immutable-state-invariant

At that was causing the error to show in console.
