### ISSUE TITLE
async validation example

### ISSUE THREAD

**Issue by enkay** [davidkpiano/react-redux-form#356]
I have a form with a few inputs I want to do async validation when it's submitted to the API. I've been reading the docs and browsing the issues here but I feel like there's always a piece of the puzzle missing. It might be because I'm new to React and Redux but it would be great to have comprehensive examples that don't assume you already know how everything works.

That being said here's what I currently have:

My form fields have a `field.touched && !field.valid` check that adds a `has-error` class to the field container. This works on sync validation.

Form fields also have an `Error` component with show set to `{ touched: true }`. This also works on sync validation.

Here's my current handleSubmit function:

```
handleSubmit(input) {
	const { dispatch } = this.props
	const submitPromise = dispatch(submitWelcomeForm(input))
	dispatch(actions.submit('forms.welcome', submitPromise))
}
```

`submitWelcomeForm` makes a fetch requests and returns Promise.reject(errors) if the submit if validation is not successful on the API. My forms are located under `forms` in the redux store.

The current API returns an error object like this: `{ fieldName: 'Error description', otherFieldName: 'Error description' }`.

This doesn't seem to to do anything. The form field don't get the `has-error` class and the `Error` components don't get set either.

Also is it normal that if I don't change anything in the form and try to submit a second time, it doesn't make the request to the API server and immediately dispatches a `setSubmitFailed` and `setFieldsValidity` action?

***

I also want to have access to a "submitting" variable in the render function while the form is submitting, validating, etc. to disable the submit button. I'm currently doing `const submitting = form.pending || form.validating`, is this the best way to achieve this?

**Comment by davidkpiano** [comment]
The property `.pending` indicates that a form is submitting, and that property alone should be satisfactory.

For returning an error with the field names in the object, try `actions.submitFields(promise)` (sorry if this is not documented - I'm working on V1 and that will have a ton of documentation and examples!)

With both of these in mind, can you make a quick www.esnextb.in that demonstrates the failing code?

**Comment by enkay** [comment]
Thank you for taking the time to answer.

I got it to work using `actions.submitFields('model)`

**Comment by davidkpiano** [comment]
Well it's just a convenience action. RRF is a library, so you can implement your own submit behavior like this:

```js
import { actions } from 'react-redux-form';

// custom action
const submitMyForm = (values) => {
  return (dispatch, getState) => {
    dispatch(actions.setPending('myForm'));

    postToAPI(values)
      .then((result) => {
        dispatch(actions.setPending('myForm', false));
        
        // do what you want with the result
      })
      .catch((errors) => {
        dispatch(actions.setFieldsErrors('myForm', errors));
      });
  }
}
```

And that way you can more granularly control the behavior of submitting your form. You're not required to use the provided `actions.submit()` or `actions.submitFields()`, and (hopefully) it's fairly straightforward to write your own implementations 😄

**Comment by enkay** [comment]
Thanks for your help.

Is it possible that the `submitFields` method is not setting the `pending` variable to `false` automatically once the request has been made?

It seems stuck in `pending` state even though the form submitted successfully. I've added it manually but is this how it should work? It seems like it should set it to false automatically since it was set to true. Could it be I'm doing something wrong in my `submitPromise`?

```
handleSubmit(input) {
	const { dispatch } = this.props
	const submitPromise = dispatch(submitForm(input))
	dispatch(actions.submitFields('form', submitPromise))
	.then(() => { dispatch(actions.setPending('forms', false))})
}
```

**Comment by davidkpiano** [comment]
Hmm... nope, the code should be setting `pending` to `false`:

```js
// in form-reducer.js
case actionTypes.SET_SUBMITTED: {
        const submittedState = {
          pending: false,
          submitted: !!action.submitted,
          submitFailed: false,
          touched: true,
          untouched: false, // will be deprecated
        };
```

Once the promise is resolved (or rejected) either `setSubmitted` or `setSubmitFailed` will be called, which both set `pending: false`. Also, your `submitPromise` should just be a normal promise, so something like this:

```js
handleSubmit(values) {
  // ...

  // normal promise
  const promise = postToAPI(values).then(...);

  dispatch(actions.submitFields('form', promise));
}
```

**Comment by enkay** [comment]
I was not referencing the form properly, `pending` is now getting set to `false` properly and errors are showing when the API returns a validation error, thank you.

Now I'm running into this issue where if the server responds with an error, and I try to submit the form again without changing anything, it doesn't get submitted to the server.

Instead, it dispatches `setSubmitFailed` and `setFieldsValidity` removing all the errors on the form. At this point if I try to submit it again, it submits to the server.

Is this the intended behavior or do I have something funky going on elsewhere?
