### ISSUE TITLE
Validation not working for fields?

### ISSUE THREAD

**Issue by th3fallen** [davidkpiano/react-redux-form#359]
No idea what im doing wrong but i have a field like so
```
<Form ref="inviteManager" model="shared.unclaimed.inviteManager.model" className="invite-manager-form">
        <fieldset className={fieldsetClasses}>
          <Field model="shared.unclaimed.inviteManager.model.to"
                 className={fieldsetClasses}
                 validators={{
                   required: (val) => val && val.length,
                   isEmail: validator.isEmail,
                 }}
          >
```

reducers:
```
const initalState = {
  to: '',
  message: '',
};

export const inviteManager =  combineReducers({
  model: modelReducer('shared.unclaimed.inviteManager.model', initalState),
  form: formReducer('shared.unclaimed.inviteManager.model'),
});
```

it stops submission of the form but the store never updates the error status of the field under the form

**Comment by davidkpiano** [comment]
Can you put this up on www.esnextb.in ?

From what I can see, you should be able to find it under `.inviteManager.form.fields.to.errors`. Is that where you're looking?

**Comment by th3fallen** [comment]
im not entirely sure i can put a running example up there, but i can provide the code of the files. https://gist.github.com/th3fallen/a754755559d2c72f59ac64a377fb226a

**Comment by th3fallen** [comment]
For some reason after stashing the changes and moving on and coming back it now works as expected...  thanks for the help anyway
