### ISSUE TITLE
V1 validation detection

### ISSUE THREAD

**Issue by th3fallen** [davidkpiano/react-redux-form#361]
So im currently running v1 with a field with two validators `required` and `isEmail` i get the following

![](http://th3fallen.d.pr/1h8y3.jpg)

is there a single key somewhere that is like `isvalid` or `valid` or `error` vs checking against all those keys in errors?

**Comment by davidkpiano** [comment]
So currently in v1, since `valid` can be derived from the state, you have to do:

```js
import { utils } from 'react-redux-form';

isValid(fieldValue); // true or false, depending on validity
```

But I might consider adding it back, even if it might cause performance issues in very large forms. What do you think? Vote 👍 or 👎

**Comment by th3fallen** [comment]
👍  i think it would be useful for the time being i can use `isValid()` but it would be nice to have it in state imo

**Comment by davidkpiano** [comment]
Added it back in `1.0.0-beta.6`!
