### ISSUE TITLE
V1 cannot find $form issue

### ISSUE THREAD

**Issue by th3fallen** [davidkpiano/react-redux-form#364]
Sorry for all the issues but dont see a slack or irc channel to ask these in. 

But given the following.

form 
```
<Form ref="inviteManager" model="shared.unclaimed.inviteManager" className="invite-manager-form">

          <Field model="shared.unclaimed.inviteManager.to"
                 className={fieldsetClasses}
                 validateOn="blur"
                 validators={{
                   required: (val) => val && val.length,
                   isEmail: validator.isEmail,
                 }}
          >
            <label className="form-control-label" htmlFor="to">Email Or Mobile Number</label>
            <input type="text" className={inputClasses} />
          </Field>
</Form>
```

reducer 
```
import { formReducer, modelReducer, combineForms } from 'react-redux-form';


const initalState = {
  to: '',
  message: '',
};

export const inviteManager =  combineForms(initalState);
```

error 
```
get-field-from-state.js?8197:29 Uncaught TypeError: Cannot read property '$form' of null
```

am i missing something simple?

state is as follows
http://www.jsoneditoronline.org/?id=4aac2367e3bca1350d1ada0fd21099e8
![](http://th3fallen.d.pr/1e5DL.jpg)

**Comment by th3fallen** [comment]
Also not sure if this would be possible but for us that will use this in nested states (most i assume) would it be possible to be able to set the full state for the form container then have all `Control` or `Field` elements models be based on the forms model?

I.e `form model="shared.unclaimed.inviteManager"`

`field model="to"` would become `shared.unclaimed.inviteManager.to`

May be a stretch but could be neat.

**Comment by davidkpiano** [comment]
@th3fallen Yep, that's definitely possible... I just need to work out the logic for it. I think that V1 will initially only allow this for string models, and disallow that behavior if the model is a `getter` function, such as `track(...)`. It would look like this:

```js
<Form model="user">
  <Field model=".name" /> // user.name
</Form>
```

See #173 for more details.

**Comment by davidkpiano** [comment]
As for the initial issue, I know exactly what the bug is and will fix it soon.

**Comment by th3fallen** [comment]
@davidkpiano awesome thanks man, glad it wasnt something i was doing wrong for once.

**Comment by davidkpiano** [comment]
Fixed here: 3026bb4

**Comment by th3fallen** [comment]
thanks so much i'll check it out now

**Comment by davidkpiano** [comment]
I didn't push the version yet though... that'll be later today.

**Comment by th3fallen** [comment]
@davidkpiano any chance you could tag that fix? when installing from the v1 branch i get a ton of errors from webpack crying about it not being installed :(

**Comment by th3fallen** [comment]
> @davidkpiano any chance you could tag that fix? when installing from the v1 branch i get a ton of errors from webpack crying about it not being installed :(

ah didnt see your previous comment. sounds good i'll keep an eye out
