### ISSUE TITLE
V1 Duplicating state

### ISSUE THREAD

**Issue by th3fallen** [davidkpiano/react-redux-form#365]
After your fix for the $form not found issue (thanks) i notice inside of the forms state key its duplicating the entire tree to the form.

![](http://th3fallen.d.pr/15jTm.jpg)

**Comment by davidkpiano** [comment]
Can you share how you're creating the store?

**Comment by th3fallen** [comment]
```
import { combineForms } from 'react-redux-form';


const initalState = {
  to: '',
  message: '',
};

export const inviteManager =  combineForms(initalState);
```

**Comment by davidkpiano** [comment]
See the gist in #366
