### ISSUE TITLE
Documentation for Form component

### ISSUE THREAD

**Issue by muuki88** [davidkpiano/react-redux-form#37]
Hi,

I found the [field-components](https://github.com/davidkpiano/react-redux-form/blob/master/src/components/form-component.js). However there are no docs and the component seems to define some none-self-explanatory properties.

Using it like this

```jsx
import {Form} from 'react-redux-form';

...

render() {
  return <Form model="myReducer.myModel">
        { /* a lot of nested components here */}
  </Form>
}
```

yields this error:

```
Uncaught TypeError: Cannot read property 'props' of undefined`(form-component.js:49)
```

It seems that the `this` scope is not set correctly.

**Comment by davidkpiano** [comment]
Ah, I'm actually still in the process of developing the `<Form>` component, once we've figured out what exactly we want its API to look like. Sorry, that's supposed to be a private (beta) API for now, but I will be adding it the next release. Stay tuned!

**Comment by muuki88** [comment]
Awesome :) Looking forward to it. We really like your library, but form  validation is always a bit... tricky ;)

**Comment by davidkpiano** [comment]
Documentation is here! https://davidkpiano.gitbooks.io/react-redux-form/content/form_component.html
