### ISSUE TITLE
<Field updateOn='blur' /> does not set the value attribute of the wrapped field

### ISSUE THREAD

**Issue by msteward** [davidkpiano/react-redux-form#370]
ESNextbin: https://esnextb.in/?gist=62d69ee530d873f3c139c054fb4640ca

When using `updateOn='blur'` on a `<Field/>` the `value` attribute of the wrapped input field is not set after the blur. This causes some issues with libraries like MaterialUI which expect the value attribute of the input to be set in order to hide placeholder text etc.

From the ESNextbin above I've created two fields, one with the updateOn set to `change` (the default) and the other set to `blur` to demonstrate the issue. Enter text in both fields and then inspect the `<input />` element. For the `change` field you'll see the `value` attribute is set on the input field, for the other it is not.

**Comment by davidkpiano** [comment]
@msteward I noticed this was on `v0.14.4`. Would you mind trying it with `react-redux-form@beta` (which does make all inputs controlled, even blur inputs) and see if it fixes the issue?

**Comment by davidkpiano** [comment]
Since V1 will be directly controlling all components (regardless of update on blur, change, etc.) I'll close this ticket. The issue should not happen in the latest `@beta`, but if it does, feel free to open a new issue.
