### ISSUE TITLE
Which one is latest version?

### ISSUE THREAD

**Issue by ozum** [davidkpiano/react-redux-form#371]
Hi,

I'm using rrf `v1.0.0-beta.6`, which seems latest development version, as of this post, according to github branches. However `npm outdated` reports there is also `v1.0.0` and `npm update` updates to `v1.0.0` every time.

Which version should I use as latest development version?

Regards,

**Comment by davidkpiano** [comment]
If you install `react-redux-form@latest`, it _should_ be `0.14.4`, please use that version until `v1.0` is out of beta.

**Comment by ozum** [comment]
Thank you @davidkpiano. I know that current latest production version is `0.x.x`.

I asked which is the latest **development** version, `v1.0.0` or `v1.0.0-beta.6`?

**Comment by davidkpiano** [comment]
Ah, my apologies! So it's always at `npm install react-redux-form@beta`, so it would currently be `v1.0.0-beta.6`.
