### ISSUE TITLE
V1 getting warning using UglifyJs

### ISSUE THREAD

**Issue by elisherer** [davidkpiano/react-redux-form#374]
I get the warning on build:

> WARNING in script/vendor.441b96625be42c65f895.min.js from UglifyJs
> Dropping side-effect-free statement [../~/react-redux-form/lib/utils/index.js:1,0]

I'm guessing that it's because of the empty index.js file in the src/utils folder which gets transpiled into
`'use strict';`
can you remove this file from that folder (until you export something by it)?

**Comment by davidkpiano** [comment]
Done!
