### ISSUE TITLE
V1 combineForms must be the root reducer

### ISSUE THREAD

**Issue by elisherer** [davidkpiano/react-redux-form#375]
Hi,

I came across a problem where combineForms must be the root reducer because it is created with combineReducers. making it either the root reducer or a mounted reducer.
If I want to use the combineForms but with additional reducers of my own, this is not possible.

I suggest dividing combineForms into 2 exported functions:

(1) createCombinedForms - same logic as the current one, just returning the object parameter with the reducers and their keys.
```js
export function createCombinedForms(forms, model = '', options = {}) {
  ...

  return {
    ...modelReducers,
    [key]: formReducer(model, initialFormState, { plugins }),
  };
}
```
(2) combineForms:
```js
export const combineForms(forms, model = '', options = {}) =>
    combineReducers(createCombinedForms(forms, model, options));
```

now if I want to add to the root reducer more reducers I will do:
```js
combineReducers({
    ...createCombinedForms(forms, model, options),
    awesome: myAwesomeReducer
});
```

**Comment by davidkpiano** [comment]
The `combineForms()` reducer creator does not need to be at the root, you just have to specify _where_ it is in relation to the store's state as its model:

```js
// ...
  const reducer = combineReducers({
    something: anotherReducer,
    deep: combineForms({
      foo: { bar: 'baz' },
    }, 'deep'), // <= specify model path here
  });
```

Can you try the above pattern and see if it works for your original use case?
Can you try a pattern

**Comment by ozum** [comment]
@davidkpiano, isn't form model `deep.foo` in that case?

**Comment by davidkpiano** [comment]
```js
const store = applyMiddleware(thunk)(createStore)(combineForms({
  something: anotherReducer,
  notDeep: initial,
});
```

And the form would be accessible in `store.getState().forms.notDeep.$form`. I'm updating the V1 documentation as we speak so all this (and more) will be in there.

**Comment by elisherer** [comment]
your suggestion solves the problem having the combineForms needing to be the root reducer, but forces a namespace for all the models, making the model names longer.
I prefer to use the modelReducer and formReducer.
I ended up creating a function of my own that given an array of models, creates a reducers dictionary (object) with {model} and {model}Form keys for each model which I then spread into my combineReducers function. it would have been nice to make all the forms under a mount point called 'forms' and let their names be the model names (without the form) but that, again, requires adding a parent model.

**Comment by davidkpiano** [comment]
Yeah it's tricky because the _point_ of models is to tell React Redux Form "hey, this is my address, this is where I am in the store's state." So the deeper you go, the longer your model names will be. Having React Redux Form search deep through all the objects for the models is prohibitive (performance-wise) and nondeterministic since models, by their nature, have no "signature" that tells React Redux Form that it came from a `modelReducer`.

**Comment by davidkpiano** [comment]
V1 is out! Please let me know if the documentation is unclear on this topic.

**Comment by dsomel21** [comment]
This solution isn't working for me. I looked at the [Model Documentnation](https://davidkpiano.github.io/react-redux-form/docs/api/modelReducer.html) but it doesn't help with applying my own reducers.  

I tried doing the following to merge my own reducers, my middleware and the *forms*, but 

`.

    export default function configureStore(initialState) {
       return createStore(
          reducers,
          initialState,
              combineForms({
                  signupForm: initialSignupForm,
                  loginForm: initialLoginForm,
             }),
             applyMiddleware(thunk)
        );
    }
    const createStoreWithMiddleware = configureStore();
`

and my store is equivalent to `Provider store={createStoreWithMiddleware}`.

If I remove the combineForms({ }) function, my reducers for my components work but form won't and vice versa.

**Comment by davidkpiano** [comment]
@dsomel21 To colocate the form reducers with existing reducers, use `createForms()`: https://davidkpiano.github.io/react-redux-form/docs/api/createForms.html

**Comment by dsomel21** [comment]
Sorry to bug you, but I am getting a really wierd issue now. 

`

    const reducers = combineReducers({

        theReducers,

	    createForms({

	        signupForm: initialSignupForm,

	       loginForm: initialLoginForm,

	  })
    })
`


` 
    
    export default function configureStore(initialState) {

        return combineReducers(
            
            reducers		
	    
            initialState,

            applyMiddleware(thunk)
	
        );
    }
`

I am not sure if this is the approach you would recommend, I looked at the (createForm)[https://davidkpiano.github.io/react-redux-form/docs/api/createForms.html]  and that was what I came up with. The issue I am getting is that it keeps saying that createForm is not a function
