### ISSUE TITLE
Loading data into multiple instances of a form.

### ISSUE THREAD

**Issue by yourfavorite** [davidkpiano/react-redux-form#378]
I have a bunch of forms all stacked on top of each other in rows.  I couldn't seem to find an example of how to handle multiples of the same form on the page. I will be handling the submit for each instance of the form onBlur as per the example in the docs.

I have it working if I populate an initial state when I first create my state. I previously had my own reducer that via action creator would fetch the data to populate the state but now I'm using the modelReducer(). Since my initial load of the app will not have a state (I will need to load it in after the fact from a database), how do I go about loading in the initial data?

For reference, my model looks like this (simplified here):
```
sites: [
  {id: '1', name: 'site one'},
  {id: '2', name: 'site two'},
],
tasks: [
  {id: '1', site_id: '1', name: 'task one'}
  {id: '1', site_id: '1', name: 'task two'}
  {id: '1', site_id: '2', name: 'task three'}
]
```

So the output would be a form with site name, followed by two forms with task name. followed by another form with site name, followed by one form with task name.

**Comment by davidkpiano** [comment]
Which version are you using? Dynamic forms are a new feature in v1.0 (currently in beta).

**Comment by yourfavorite** [comment]
I'm using the latest stable release. Is the beta available anywhere with documentation? I'm working on a personal project so production ready code isn't necessarily a must.

**Comment by yourfavorite** [comment]
Looked through the docs and doesn't seem like there's much there yet. Is there an example of a dynamic form anywhere that I could poke through?

**Comment by davidkpiano** [comment]
Yeah, I'm still working on the docs. Most things are unchanged from v.0.14 however. There's more info in this issue about dynamic forms: https://github.com/davidkpiano/react-redux-form/issues/243#issuecomment-241548472

**Comment by yourfavorite** [comment]
Being that I'm still learning react/redux I couldn't figure out how to get v1 beta working in my electron boilerplate. I did however work out this solution. Is this really a bad way to handle what I'm trying to do?

In my parent component that maps through each site to make forms, I pass down a `sites` prop that is used to build everything out. And then on componentWillMount I dispatch actions.change.
```
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import { actions } from 'react-redux-form';
import SiteRow from './SiteRow';

class SiteList extends Component {
  static propTypes = {
    sites: PropTypes.array,
    dispatch: PropTypes.func
  };

  componentWillMount() {
    this.props.dispatch(actions.change('sites',
    [
      {id: '1', name: 'site one'},
      {id: '2', name: 'site two'},
    ]));
  }

  renderSites(sites) {
    return sites.map((site) => {
      return (
        <SiteRow key={site._id} site={site} form={site._id} />
      );
    });
  }

  render() {
    return (
      <div>
        {(this.props.sites.length > 0) ? this.renderSites(this.props.sites) : 'Loading...' }
      </div>
    );
  }
}


function mapStateToProps(state) {
  return {
    sites: state.sites
  };
}

export default connect(mapStateToProps)(SiteList);
```

**Comment by davidkpiano** [comment]
Thanks for the excellent example; that looks idiomatic and correct! In V1, `forms.sites[0]` would be a form, as would `forms.sites[1]`.
