### ISSUE TITLE
FieldActions Validate is not processed

### ISSUE THREAD

**Issue by muuki88** [davidkpiano/react-redux-form#38]
Hi,

We have a form distributed over different components:

```jsx
<MyForm>
  <Step1 model={userModel} formModel={userFormModel} />
  <Step2 model={userModel} formModel={userFormModel} />
  <Step3 model={userModel} formModel={userFormModel} />
</MyForm>

...

const mapStateToProps = (state) => ({
  steps: state.register.steps,
  userModel: state.register.user,
  userFormModel: state.register.userFormModel
});

```

The steps are arranged in an accordion, so the user would be able to skip steps. However in the end, when the user clicks the _submit_ button all fields should be validated. I tried to send

```jsx
onSubmit() {
    this.props.validate('register.user.name');
    this.props.validate('register.user.age');
}
```

But no validators were triggered. The other options I could think of were

- duplicating the validators and check them in the top component as well
- check if `userFormModel` contains the entry key and then check the validity

What would be a good way to do this?

**Comment by davidkpiano** [comment]
I'm not sure where you found `props.validate` but that is not part of the React-Redux-Form API. Validation is done through actions, such as `setValidity()`, `setErrors()`, or `asyncSetValidity()`, etc.

Here's an example with the `submit()` action that uses promises:

```js
function submitPromise(user) {
  return new Promise((resolve, reject) => {
    if (user.password === 'hunter2') {
      return resolve(true);
    }

    return reject(value.errors);
  });
}

// ... in your component
handleSubmit() {
  const { user, dispatch } = this.props;

  dispatch(actions.submit('user', submitPromise));
}
```

I'm working on writing up a full example for this.

**Comment by muuki88** [comment]
Sorry, missed this important part :) 
The `props.validate` was mapped from the `actions` in the `mapDispatchToProps` method.

```jsx
import {actions as formActions} from 'react-redux-form';

const mapDispatchToProps = (dispatch) => ({
  validate: (model) => dispatch(formActions.validate(model))
});
```

The action is defined [here](https://github.com/davidkpiano/react-redux-form/blob/master/src/actions/field-actions.js#L14-L17)

**Comment by davidkpiano** [comment]
Yep, that action wasn't supposed to be exposed yet, sorry! 

For now, try sticking to the validation actions in the documentation: http://davidkpiano.github.io/react-redux-form/#/api/Guide:-Validation

**Comment by muuki88** [comment]
Okay, thanks for the clarification. We hoped to trigger the validation state for all nested components at once, so we don't have to duplicate the `validators` and put the model keys everywhere.

Will this be part of a future release?

**Comment by davidkpiano** [comment]
Yes, coming very soon! See this issue comment for what that will look like: https://github.com/davidkpiano/react-redux-form/issues/31#issuecomment-189468586

And feel free to chime in to see if that looks like an easy-to-understand, intuitive API.

Remember: validation cannot be baked into the reducer because 1) reducers should be simple and have as little logic as possible, and 2) validation should be able to be asynchronous, and not run all the time (e.g. some validation runs on field changes, some validation runs on blur, some validation runs only on form submit, etc.)

**Comment by davidkpiano** [comment]
@muuki88 The `<Form>` field with validation on submit has just been released in `react-redux-form@0.7.0`!

Check the release notes for details, and please let me know if this fits your use case: https://github.com/davidkpiano/react-redux-form/releases/tag/v0.7.0

**Comment by muuki88** [comment]
Thanks a lot @davidkpiano . This is indeed what we were looking for. I can now see why validator "duplication" is necessary as reducers can/should not be aware of any logic, but instead being provided with by actions. 

May be I can create a small [esnextb example](http://esnextb.in/) showing how we do the validator implementation.

**Comment by muuki88** [comment]
I build a [small example](http://esnextb.in/?gist=06a8032e63e5e66fac06) showing how we could use this feature. Feel free to use this for you documentation. Putting the validators in all the correct places feels a bit error prone. Maybe the spread operator helps here ( esnextb seems to not support it ). WDYT?

**Comment by davidkpiano** [comment]
Great example! As far as putting all the validators in the correct places, you no longer need to specify validators in the `<Field>` if you don't need to. Just add:

```diff
<Form model="..."
  validators={{ ... }}
+  validateOn="change"
>
```

to your form, and it will run the validation (for only the changed fields) whenever a field changes.

Setting validators in `<Field>` is good when you want to:

- Validate on something other than change, such as `"blur"`
- Have async validators (which don't make sense for a form submit, at least not right now)

**Comment by davidkpiano** [comment]
You no longer need to add `validateOn="change"` to the form. That is the default action. Here are the full docs for the `<Form>` component: https://davidkpiano.gitbooks.io/react-redux-form/content/form_component.html

**Comment by muuki88** [comment]
Sweet! Thanks :)
