### ISSUE TITLE
Strange behaviour for updateOn="blur"

### ISSUE THREAD

**Issue by ozum** [davidkpiano/react-redux-form#381]
Hi,

In `v1.0.0-beta.7` for the following code I get strange behaviour for key press. Characters are printed 2 key press after and some get lost. (Please see attached gif.)

This happens only `updateOn="blur"`

```js
<Field updateOn="blur" model={track(`${modelBase}.items[].name`, { id: item.id })}>
  <input type="text" />
</Field>
```

![2016-09-02_15-25-43](https://cloud.githubusercontent.com/assets/1497060/18203796/e5ca7f14-7121-11e6-8bda-a2db7616481f.gif)

Regards,

**Comment by davidkpiano** [comment]
Fixed! This will go out in the next beta release.

**Comment by ozum** [comment]
Thanks.
