### ISSUE TITLE
v1 Form level initial validation 

### ISSUE THREAD

**Issue by Psykar** [davidkpiano/react-redux-form#384]
http://codepen.io/anon/pen/GjgNLx?editors=0011#0

It seems that the initial validation of lastName here is lost when the field is toggled on, and the `<Form>` validator is no longer checked from there on in.

On the state, the value of 
`this.props.reduxState.forms.user.lastName.validity` changes from
```
{
  required: false
}
```

to
```
{
  badInput: true,
  customError: true,
  patternMismatch: true,
  rangeOverflow: true,
  rangeUnderflow: true,
  stepMismatch: true,
  tooLong: true,
  tooShort: true,
  typeMismatch: true,
  valueMissing: true
}
```

**Comment by Psykar** [comment]
A closer look implies that the validator I've used is incorrect, as it doesn't get passed the value from `user.lastName` when validating, however I'm not actually certain what would be correct.

If the `<Form>` validator is set to
```
{
  lastName: {
    required: (value) => {
      console.log("checking last name", value)
      return false
    }
  }
}
```
Then it does get value on the validator, but the form state looks incorrect then as it comes out as 
`forms: {$form: {...}, lastName: {...}, user: {...}}`

**Comment by davidkpiano** [comment]
This is fixed now and will be out in the latest `@beta`. You're correct that `'user.lastName'` should be `'lastName'` as the validator key. Here is the fix:

```diff
  if (action.type === actionTypes.SET_FIELDS_VALIDITY) {
    return map(action.fieldsValidity, (fieldValidity, field) =>
        fieldActions.setValidity(field, fieldValidity, action.options)
      ).reduce((accState, subAction) => setValidityActionReducer(
        accState,
        subAction,
-       toPath(subAction.model)), state);
+       localPath.concat(toPath(subAction.model))), state);
  }
```

I'll close this once I have unit tests for it!
