### ISSUE TITLE
Cannot Type in Collection Textbox After Change of Array

### ISSUE THREAD

**Issue by ozum** [davidkpiano/react-redux-form#391]
# Version
`v1.0.0`: OK
`v1.0.0-beta.1` to `v1.0.0-beta.8`: Affected
`v1.0.0-beta.9`: OK

# Problem
After altering array of collection (for example deleting an item from array) text boxes of collection items behaves unexpected such as order of tab is corrupted, cannot type text boxes, cannot focus text boxes.

# Details
I will try to explain the problem over an example. Example code repo can be found `git@bitbucket.org:fortibase/item-list.git`, commit `3b6651a`.

## Steps to reproduce
1. Fetch example from repo. (`git@bitbucket.org:fortibase/item-list.git`, commit `3b6651a`)
2. Run with `npm run dev-server`
3. Go to [http://localhost:8080](http://localhost:8080)
4. Type `12345` in quantity text box of 1st and 2nd lines.
5. Push `Remove` button of 3rd line to delete that line.
    1. **Problem:** Enter `Tab` 10-20 times to see tab does not behave as expected. (See first video)
    2. **Problem:** Type `12345` in quantity text box of 3., 4., 5., 6. lines to see blinking caret disappears and you cannot type anymore. (See second video)
    3. **Problem:** Cannot focus product text boxes of later lines.

First Problem: Tab behaves strangely.

![2016-09-08_16-27-11](https://cloud.githubusercontent.com/assets/1497060/18351093/7072dfb2-75e1-11e6-961b-5c02b09a897b.gif)

Second Problem: I try to enter 4-5 numbers in text boxes, but cannot type.

![2016-09-08_15-59-50](https://cloud.githubusercontent.com/assets/1497060/18350828/634001fe-75e0-11e6-933a-f4763c4bc811.gif)

Regards,

**Comment by davidkpiano** [comment]
Thanks again for the detailed report @ozum! I couldn't reproduce the focus/tabbing problems locally (when I pulled the latest from your branch), but I _did_ discover another weird cursor bug.

Also, I published the latest `1.0.0-beta.9`, can you do me a huge favor and try with that?

**Comment by ozum** [comment]
`1.0.0-beta.9` is OK. It's not affected from all three problems I reported.

**Comment by davidkpiano** [comment]
Awesome! :tada:
