### ISSUE TITLE
No re-render when first time merge data

### ISSUE THREAD

**Issue by yoyeung** [davidkpiano/react-redux-form#394]
I have some issue when i using this library.
The situation is when i finished initial form.
I need to make an ajax call to get update data to prefill the form.
I am using this:
```
store.dispatch(actions.fetchdata()).done(function () {
    console.log(store.getState());
    store.dispatch(formActions.merge('customer',customerToFillin(store.getState())));

});
```
actually it will not update 
if i add this after the first merge.
```
store.dispatch(formActions.merge('customer',{refresh:true}));
```
if will refresh.
I don't know why the first merge is working but did not call the render method again.
in my view i have some "this.props.customer.name". it's need recall render method to update it.

**Comment by davidkpiano** [comment]
I can't reproduce this in 0.14.x: https://esnextb.in/?gist=3e82d2400f65c5eaedeb7932f42d7b05

Please look at the above code and see if it matches your use case. I notice you're chaining `.done` to `dispatch` - are you using any other middleware than `redux-thunk`?

Also, if you want to post a minimal use-case example in www.esnextb.in, that would be really helpful 😄

**Comment by yoyeung** [comment]
Sorry i cannot reproduce it in www.esnextb.in.
