### ISSUE TITLE
Form submission does not happen right after validation

### ISSUE THREAD

**Issue by i4got10** [davidkpiano/react-redux-form#395]
Live example: https://esnextb.in/?gist=1225a9edcb310e0dd7a64e88a9f80562

_Steps to reproduce:_ 
1) Click button - form is invalid now
2) Type some text - form is still in invalid state(in reason of ``validateOn="submit"``)
3) Click button - ok, form is valid now. But method ``_save()`` did not invoked.
4) Click button again - submission successfully passed, method ``_save()`` invoked.

Problem here is that method ``_save()`` must be called in 3rd step.

**Comment by davidkpiano** [comment]
I confirmed this is a tiny bug in v1.0, and will have a fix for that. By the way, you can use 1.0@beta in the above code without changing any code.

**Comment by i4got10** [comment]
I can't use ``1.0@beta`` in my real project, because it does not work without applying many changes right now. So, fix for 0.14.x branch would be appreciated.
