### ISSUE TITLE
Plural Models with Single Form

### ISSUE THREAD

**Issue by sdlovecraft** [davidkpiano/react-redux-form#398]
I am confused by model reducer/ form reducer pattern when dealing with plural models. If i have a `ChildForm`, and I wish the form to be used to dynamically add to a `children` model, how would you suggest I approach this? 

At the moment,  I have `childForm`, `child`, and `children` models in my store. I am dispatching actions on submit to clear the `child` and the `childForm` model, while pushing the data from the `child` model into the `children` model. Is there a nice way for me to eliminate this child model? It doesn't seem to be doing a lot for me. 

Thanks,

Sam

**Comment by davidkpiano** [comment]
Yes, there is. Consider a store that looks like this:

```js
// combineForms comes form RRF v1
const store = createStore(combineForms({
  children: [],
});
```

And a very simple function that returns a new child:
```js
const createChild = (name) => ({ name, age: null });
```

Then you can add a child by using `actions.push()`:

```js
<button
  onClick={() => dispatch(actions.push('children', createChild('bob')))}
>
  Add bob
</button>
```

And you can reference that exact child by name (or other unique ID) by using `track()`:

```js
// edit only bob's age
<Field model={track('children[].age', {name: 'bob'})}>
  <input type="number" />
</Field>
```

Hope that helps!
