### ISSUE TITLE
Dynamic form validators do not stick

### ISSUE THREAD

**Issue by marcpeterson** [davidkpiano/react-redux-form#403]
I'm using Form validators.  These validators change based on the state tree.  For instance, if a certain checkbox is checked a new text field is exposed, and I change the list of validators to include one for that new text field.

But this list of new validators don't seem to stick until I actually type something into that input.  Until then, the form's state tree only shows the original validators that exists when the form was first rendered.  Is this supported?

**Comment by davidkpiano** [comment]
What version are you on? And can you show some example code that reproduces the issue?

**Comment by marcpeterson** [comment]
Version 0.14.5.  I'll write a short example.  If it's not enough I can try to make a complete set of files that exhibit it.

Say I create my validators in the container, and pass them into the component.
MyContainer.js
let validators = {
  text1: {
    notEmpty
  }
}

Then I use those validators in the Form.
MyComponent.js
<Form model="user"
  validators={validators}>

Then a user action triggers a new field to appear.  The container adds a validator for that new field.

MyContainer.js
let validators = {
  text1: {
    notEmpty
  },
  text2: {
    notEmpty
  }
}

That new set of validators gets to the component.  But it doesn't show up in the state tree until I type something into the text2 field.  It's almost like the new set of validators wasn't enough to trigger an update of the Form's validators in the state tree.

**Comment by davidkpiano** [comment]
I believe this was fixed in `0.14.6`: #377 

Please install `0.14.6` and let me know if the problem persists.

**Comment by marcpeterson** [comment]
Indeed it was fixed!  Sorry, I should have searched first.  Much thanks, this is a great library!
