### ISSUE TITLE
Uncaught TypeError: mapProps is not a function

### ISSUE THREAD

**Issue by slashwhatever** [davidkpiano/react-redux-form#407]
Attempting to use custom controls in beta as per the docs [here](https://davidkpiano.github.io/react-redux-form/docs/guides/custom-controls.html). 

The below form works fine when using standard fields as per the example in the Quick Start guige. As soon as I update to use custom controls, I get an error.

```

import React from 'react';
import {Form, Control} from 'react-redux-form';

const MyTextInput = (props) => <input className="my-input" {...props} />;

class ReactReduxForm extends React.Component {
	handleSubmit(campaignObject) {
		// Do anything you want with the form value
		console.log(campaignObject);
	}

	render() {

		return (
			<Form model="campaignObject" onSubmit={(campaignObject) => this.handleSubmit(campaignObject)}>
				<Control
					model="campaignObject.name"
					component={MyTextInput}
				/>

				<Button primary type='submit'>Update</Button>
			</Form>
		);
	}
}

export default ReactReduxForm;

```

**Comment by davidkpiano** [comment]
😅 I actually just fixed this last night! Grab the latest `@beta` at `react-redux-form@1.0.0-beta.11` - the `mapProps={...}` prop will default to the standard control prop mapping for `<input type="text">`-like controls.

**Comment by davidkpiano** [comment]
Are you on the latest `@beta`? Should be `1.0.0-beta.11`

**Comment by davidkpiano** [comment]
Also, to fix this without updating RRF, you can use `<Control.text model="...">`.
