### ISSUE TITLE
Typo in import isTouched

### ISSUE THREAD

**Issue by glensomerville** [davidkpiano/react-redux-form#408]
There is a type in the 1.0.0 version in `form/index.js`. The path has a capital `'./is-Touched'`, whereas the file is lowercase `is-touched.js`.

**Comment by davidkpiano** [comment]
```js
import isValid from './is-valid';
import isPending from './is-pending';
import isTouched from './is-touched';
import isRetouched from './is-retouched';
```

The paths are correct (otherwise ESLint or Webpack would have yelled at me), but as a general question, should file names match their exports? E.g.; 

```diff
- import isTouched from './is-touched';
+ import isTouched from './isTouched';
```

**Comment by glensomerville** [comment]
Thanks! I was getting a compile error in webpack from this, but perhaps my version was a bit stale already.

Regarding the file naming, perhaps matching names with exports makes things easier to spot, but the convention may vary.

**Comment by vegansk** [comment]
@davidkpiano, this bug still exists when using ``npm install --save react-redux-form@beta``

**Comment by davidkpiano** [comment]
@vegansk What version does it say that you have?

**Comment by vegansk** [comment]
@davidkpiano, it's very strange. It worked after some time. CI builds of my project was broken, but now it's ok. Version in package.json is ``^1.0.0-beta.12``.
