### ISSUE TITLE
Nested combined reducers breaks forms

### ISSUE THREAD

**Issue by newtriks** [davidkpiano/react-redux-form#410]
Based on the example provided in this repos. 

1. If I update `store.js` as below to replicate my having another store where I am combining reducers then combining this into the top level reducer:

```
const initialUserState = {
  firstName: 'me',
  lastName: '',
};

const foo = (state = {}, action) => {
  switch (action.type) {
    default:
      return state;
  }
};

const bar = combineReducers({
  user: modelReducer('user', initialUserState),
  userForm: formReducer('user', initialUserState),
})

const store = applyMiddleware(thunk)(createStore)(combineReducers({
  foo,
  bar,
}));
```

Then update the `user-form.js` to account for this change in state path:

```
function mapStateToProps(state) {
  return { user: state.bar.user };
}
```

I notice the model in the component reflects this model change. However, the form Fields are not populated with the initial state nor can I type anything into the text input fields, it always gets overwritten by resetting the text?

![sep-21-2016 18-14-09](https://cloud.githubusercontent.com/assets/31971/18721185/3fe08e94-8027-11e6-8d0e-6946a76d5304.gif)

I can confirm this happens in the latest beta release also.

**Comment by newtriks** [comment]
Okay, on further digging through previous issues it's led me to using `createFormReducer`...

**Comment by davidkpiano** [comment]
Currently, your store has this shape:

```js
{
  foo,
  bar: {
    user,
    userForm,
  },
}
```

That means that both the `modelReducer` and `formReducer` for the user is actually at the path `"bar.user"`, not `"user"`. So you would fix it like so:

```js
const bar = combineReducers({
  user: modelReducer('bar.user', initialUserState),
  userForm: formReducer('bar.user', initialUserState),
})
```

And it should work as expected. If you are using `combineForms`:

```js
const bar = combineForms({
  user: initialUserState
}, 'bar');
```

and you can access your user form from `bar.forms.user`.

Let me know if this helps! 😄

**Comment by newtriks** [comment]
Thanks for the quick response @davidkpiano, using the beta version those approaches work. Previous versions of your lib e.g. pre 1.0 the first example didn't seem to work oddly? Regardless, it's all good with the beta thanks!

**Comment by newtriks** [comment]
@davidkpiano one final question sorry, which is the preferred approach and why?

**Comment by davidkpiano** [comment]
> which is the preferred approach and why?

The preferred approach is `combineForms()` for a couple of reasons:
- It's much less code and boilerplate that you have to write! 🎉 
- It's a _very_ thin wrapper on top of `combineReducers()`.
- It consolidates all your forms into a single `.forms` state, instead of having to define all of your forms reducers.
- There is the _possibility_ in the future that the API for `combineForms()` might be enhanced in the future to let you pass in options/plugins to the created `formReducer`.
