### ISSUE TITLE
Error in ./~/react-redux-form/lib/reducers/form/change-action-reducer.js

### ISSUE THREAD

**Issue by slashwhatever** [davidkpiano/react-redux-form#411]
Module not found: Error: Cannot resolve module 'fbjs/lib/shallowEqual' 

https://puu.sh/rl79R/984570f882.png

Seems to be since updating to 1.0.0

**Comment by davidkpiano** [comment]
Are you running `npm install react-redux-form@beta --save`?

There is nowhere in the beta that is importing that module.

**Comment by slashwhatever** [comment]
Seems I'm getting this from 1.0.0

I'll update to the beta channel and see what I get....

**Comment by davidkpiano** [comment]
That's weird that that happened. Glad that you can no longer reproduce it!
