### ISSUE TITLE
Documentation is not working on Safari

### ISSUE THREAD

**Issue by mbiernacik** [davidkpiano/react-redux-form#412]
Hey. I noticed that documentation of v1 is not working properly on Safari (iOS/OS X). There is a scroll issue and documentation is unreadable.

I checked in browser console that one file cannot be downloaded https://davidkpiano.github.io:35729/livereload.js and browser does not display rest of the page.

I made a small investigation and discovered that probably this [commit](https://github.com/davidkpiano/react-redux-form/commit/9bfc6a3b1707526930500448785d0c517221748d) caused a problem.

Can you look at that? I think that the simplest solution would be delete `live reload` plugin, but decision is up to you ;)

**Comment by davidkpiano** [comment]
Thanks for pointing that out! I went ahead and removed that plugin.

**Comment by mbiernacik** [comment]
I just checked and scroll issue still exists. So problem must be with something else than plugin I mention above.

**Comment by davidkpiano** [comment]
Scroll issue should be fixed now!
