### ISSUE TITLE
can anyone point me to an example using a dynamic form?

### ISSUE THREAD

**Issue by gehsekky** [davidkpiano/react-redux-form#413]
I'm trying to use RRF with a form where we are dynamically generating form fields depending on values from the state. So if you specify "number of nights" as 4, another screen will display four rows in an accordion, each row with 3 form fields associated with that given "night". Is this possible with RRF?

**Comment by davidkpiano** [comment]
It's absolutely possible. I'll create a recipe soon. Here's an idea of how you can accomplish that:

```js
// ...
const createNight = () => ({ foo: '', bar: '', baz: '' });

const store = createStore(combineForms({
  builder: { numNights: 1 },
  nights: [createNight()],
});
````

```js
// ...
class Row extends React.Component {
  render() {
    const { model } = this.props;
    
    return (
      <Form model={model}>
        <Control.text model=".foo" />
        <Control.text model=".bar" />
        <Control.text model=".baz" />
      </Form>
    );
}

// this needs to be connect()-ed
class Builder extends React.Component {
  render() {
    const { builder } = this.props;

    return (
      <div>
        <label>Number of nights?</label>
        <Control.text type="number" model="builder.numNights" />

        {Array(builder.numNights).fill(null).map((_, i) =>
          <Row key={i} model={`nights[${i}]`} />
        }
      </div>
    );
}
```

(some imports, etc. left out for brevity)

**Comment by gehsekky** [comment]
@davidkpiano This is fantastic, thank you. Are dynamic forms are at all supported in the old 0.14.x branch or just in the beta?

**Comment by davidkpiano** [comment]
They're supported in both `0.14.x` and `1.0` (now out of beta)!
