### ISSUE TITLE
Prevent form submit when button is not type submit

### ISSUE THREAD

**Issue by anaibol** [davidkpiano/react-redux-form#414]
Hi, I am building a multistep form with buttons to go to the next step. It seems that by default all buttons do form submit.
With a onClick event on the button, both actions are fired. Is there a way to prevent that?

Thanks!

**Comment by davidkpiano** [comment]
Keep in mind that the default behavior of an HTML5 `<button>` element is to submit a form: http://w3c.github.io/html-reference/button.html

In order to prevent this default behavior, you must explicitly state its type:

```html
<button type="button">
  Next Step
</button>
```

**Comment by anaibol** [comment]
Thank you very much @davidkpiano!
