### ISSUE TITLE
Problem with React Native and react-dom

### ISSUE THREAD

**Issue by janhenkgerritsen** [davidkpiano/react-redux-form#415]
When I try to use react-redux-form in my React Native application I get the following error:

`EventPluginRegistry: Cannot inject event plugin ordering more than once. You are likely trying to load more than one copy of React.`

This is the same issue as [this one](https://github.com/facebook/react-native/issues/8007).

This problem makes react-redux-form unusable with React Native.

I have to admit that I am relatively new to developing with React and React Native, so maybe I am missing something simple?

If you need some more information just let me know what you need.

**Comment by davidkpiano** [comment]
@janhenkgerritsen I found the issue, was able to replicate it in a React Native test project, and went ahead and fixed it. Thanks for the report!
