### ISSUE TITLE
React Native undefined is not a function (evaluating 'babelHelpers.typeof(obj)')

### ISSUE THREAD

**Issue by janhenkgerritsen** [davidkpiano/react-redux-form#417]
If I change some text in a `<Control.TextInput>` element in a React Native application I get the error

`undefined is not a function (evaluating 'babelHelpers.typeof(obj)')`

I found [this StackOverflow question](http://stackoverflow.com/questions/39016025/reactnative-babelhelpers-typeof-is-not-a-function/39016277) where the accepted answer says that the `es2015` preset in the `.babelrc` file does not work with React Native and will lead to this error if enabled.

If I remove this preset from the `.babelrc` file that comes with react-redux-form the error is gone.

**Comment by davidkpiano** [comment]
Sorry about that! The fix will be published in an upcoming patch.
