### ISSUE TITLE
form reset with blank fields bug

### ISSUE THREAD

**Issue by VincentCordobes** [davidkpiano/react-redux-form#418]
Hi,

I have noticed something weird with `<Errors show="touched" />` after the form has been reset with empty fields; error messages are no longer displayed when fields are touched again. Is it the expected behaviour ?

You can reproduce this on your codepen example http://codepen.io/davidkpiano/pen/b63b4a409763716b4101faa68d1f25e0

Here is a scenario:
1. Touch a field (for example `username`)
2. 'Unfocuse' the field (leave it blank) -> the error msg is displayed 
3. Click the reset button
4. Touch the field again
5. 'Unfocus' the field (leave it blank) -> the error msg is **not** displayed

Another scenario: 
1. Load the page
2. click the reset button 
-> Error messages are not displayed when we touch fields

**Comment by Maxim-Chugaev** [comment]
I have same issue. And more, after reset model my form is valid with empty fields.

**Comment by VincentCordobes** [comment]
Yep, plus the `errors` field is the empty object.
 I guess it comes from `reducers/form/reset-action-reducer` updating the field with `initialFieldState` which contains the `errors: {}`. Maybe we should "revalidate" the form after it has been reset ?

**Comment by davidkpiano** [comment]
Thankfully, this was a simple fix. See a347a18 - this will go out in the next patch.
