### ISSUE TITLE
actions.load & validations

### ISSUE THREAD

**Issue by venelin-mihaylov** [davidkpiano/react-redux-form#419]
Scenario:

```
initialModel: {}
```

I have a "Form" with sync validators on "Control"s. On mount the validators are triggered, my fields become invalid. I call `actions.load()` The fields are still invalid.

_/If I call actions.change(), then the fields are no longer  "pristine"/_

**I need to load data into the model/form and the fields to be pristine and valid** 

_/The data that I load has been validated before, I do not want to validate it on load/_
I can manually use actions.setValidity(), but for a large form the performance cost is too great. (dev mode, but still)

How can I load data and the values to be pristine and valid with minimal cost? I can do actions.setInitial() / actions.setValidity() / actions.setPristine() , but IMHO that would be too costly for a large form? Maybe you can provide an additional option to actions.load(), like {valid: true} ?
Thanks :)

**Comment by davidkpiano** [comment]
How about a combination of `actions.reset('your.initialModel')` and `actions.load('your.initialModel', newValue)`?

**Comment by venelin-mihaylov** [comment]
Seems to work :) . Thanks a lot :)
