### ISSUE TITLE
Action to reset form validation

### ISSUE THREAD

**Issue by Kukkimonsuta** [davidkpiano/react-redux-form#42]
I'm working with scenario where all validation is processed on server while attempting to post the form and get back list of errors. Now all works pretty nicely, except that on second submit I don't know what fields were fixed since the last update, so I can't clear their validation state, so my question is:

1) is there a way to clear validation for all fields within given form state?
2) is there a way to enumerate fields?

My action looks like this:
```js
function create_control_submit(data) {
    return function (dispatch) {

        let request = new HttpRequest("/admin/users/api/create", "POST");

        return request.getResponse({ data: data })
            .then((response) => response.bodyAsJson())
            .then((response) => {

                if (response.validation) {

                    for (let state of response.validation) {
                        console.log("state", state);

                        dispatch(form.setErrors('createControl.createForm.data.' + state.name, state.error));
                    }

                }

            });
    }
}
```

**Comment by davidkpiano** [comment]
> **1) is there a way to clear validation for all fields within given form state?**

Yes, using the `actions.reset(model)` action. However, this will also set the `model` in the model reducer to its initial state; is this desired?

If not, I can see the use for an `actions.resetField(model)` action that only resets the field's form state, and not the model state.

> **2) is there a way to enumerate fields?**

You mean like `foo.bar[4].baz`? Yes, if I'm understanding your question correctly. What use-case are you looking for?

**Comment by Kukkimonsuta** [comment]
No, clearing the model is not desired behavior and reseting the field is not an option since I don't know what fields I need to reset. What I need is something like

```js
dispatch(actions.resetValidation('createControl.createForm.form'));
```

that would be the same as calling for each field
```js
dispatch(actions.setErrors('createControl.createForm.data.' + fieldName, null));
```

The scenario is:

* user fills form
* user submits form
* server returns validation error on field `GivenName` and `Birthdate`
* `actions.setErrors` is dispatched for `GivenName` and `Birthdate`
* user fixes `Birthdate` field
* user submits form
* server returns validation error on field `GivenName`
* `actions.setErrors` is dispatched for `GivenName`

But at this point are both fields `GivenName` and `Birthdate` marked as invalid from previous submit attempt, so I'd like to clear the validation errors before calling `actions.setErrors` for respective fields. This would be possible by dispatching `actions.setErrors` with `null` error for each field, but I'd have to name all the fields - instead I'd like to either get list of fields that are invalid or an action to reset the validation on them.

**Comment by davidkpiano** [comment]
Okay, this seems very doable. Would something like `actions.resetValidity('createControl.createForm.form'))` make sense for that?

This `actions.resetValidity(model)` action would do two things:
- Reset the `.validity` and `.errors` of the `model` itself
- Reset the `.validity` and `.errors` of any submodels (such as `createControl.createForm.data.GivenName`, etc.)

How does this look? I can add it in `0.7.1`

**Comment by Kukkimonsuta** [comment]
Sounds good, thank you :+1:

**Comment by davidkpiano** [comment]
@Kukkimonsuta There is now an `actions.resetValidity(model)` action that you can dispatch that will reset the `.validity` and `.errors` of just the model in `0.7.2`.

I'm working on completely revamping documentation so I'll add that in there when I can as well! But you can use this right now in `0.7.2`

**Comment by davidkpiano** [comment]
Now present (officially) in `0.8.0`! https://github.com/davidkpiano/react-redux-form/releases/tag/v0.8.0

**Comment by Kukkimonsuta** [comment]
Thank you.

**Comment by davidkpiano** [comment]
Documentation here: https://davidkpiano.gitbooks.io/react-redux-form/content/field_actions.html
