### ISSUE TITLE
Utils like getField but for model value and form fields?

### ISSUE THREAD

**Issue by MiMaMuh** [davidkpiano/react-redux-form#424]
Hi, are there simple utils like getField to get the models' value or field-object of a input based on its model-path? 
To do things like this easily:
```jsx
function mapStateToProps(state, ownProps) {
    const model = ownProps.model; // get something like: 'user.firstName'
    const value = getValue(state, model); // returns the firstName value of the input-field
    const valueField = getValueField(state, model); // returns the field object { focus, pending, ... }
    ...
}
``` 
Currently, when I want to get the value I have to use getField and truncate ```.firstName``` from the model ```user.firstName``` and then get the value by ```value.firstName```. It is okay, but it would be convenient to have such utils as part of the lib already.

**Comment by davidkpiano** [comment]
If you are using [lodash](lodash.com), you can just use lodash's `get` function:

```js
import get from 'lodash/get';

function mapStateToProps(state, ownProps) {
  const model = ownProps.model;
  const value = get(state, model);
  // ...
}
```

But I will make available the internal util functions for getting the model value and the field value. I agree; it would make things more convenient.
