### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by venelin-mihaylov** [davidkpiano/react-redux-form#427]
I am using RRF with semantic ui react components.
By default, when a field is changed, the whole form is re-rendered.
All fields are also re-rendered on focus and blur for every field. 
I experimented with updateOn='blur' and ignore=['focus','blur'] .
1. If I use updateOn='blur', only the currently edited field is re-rendered on change, which is ok. 
1.1 Then I add ignore=['focus']. Thus, the form is re-rendered only on field blur. 
1.2 Unfortunately for a medium-large form (master-detail with approx. 30 fields total) even this is too much, and whole form feels too slow. 
2. I tried ignore=['change','focus','blur']
2.1 The form works beautifully, but the model is not updated at all :)

What can I do to avoid re-rendering of all form fields?

**Comment by davidkpiano** [comment]
Can I see a reproducible example of the code? Also, are you `connect()`-ing your form?

**Comment by venelin-mihaylov** [comment]
In general my forms are connect() -ed. 
In the example below the form is not. The behavour is the same. 
I use "trace react updates" in the react chrome plugin to look at what is being re-rendered. 
https://codepen.io/vmihaylov/pen/PGKbLW

**Comment by max-mykhailenko** [comment]
I also have performance problems. My form has 1300 checkboxes and connect() time awful. Form render time is more than 20 seconds. Main delay is in `ConnectedControl` component. What you can recommend for me?

**Comment by venelin-mihaylov** [comment]
Additional thoughts:
Is there a need to re-render all fields on focus, blur, and on every model change (even if it's not the current field)?
From where that 'feature' comes? Can it be avoided? 
maybe shouldComponentUpdate() can be used?

**Comment by davidkpiano** [comment]
> Is there a need to re-render all fields on focus, blur, and on every model change (even if it's not the current field)?

No, and it shouldn't. I'll investigate this. I am using `shouldComponentUpdate` in the controls.

@max-mykhailenko Can you provide me a reproducible example, so that I can accurately address the performance issue? Is it just 1300 checkboxes?

**Comment by max-mykhailenko** [comment]
You can just create loop with 1300 iteration and render Control.checkbox in every iteration. Warning: browser tab will hang for 15-20 seconds.

**Comment by Maxim-Chugaev** [comment]
I have same issue, and i can give access to my repository.

**Comment by davidkpiano** [comment]
@Maxim-Chugaev That would be great - I'm putting priority on this issue.

**Comment by Maxim-Chugaev** [comment]
I will try to do it in the near future. Now profiler showed this result. May will be helpful.
![Image ]
(https://dl.dropboxusercontent.com/u/29852799/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-09-30%2022.00.43.png)

**Comment by davidkpiano** [comment]
Also, using something like [react-virtualized](https://github.com/bvaughn/react-virtualized) in your project might be helpful.

**Comment by VladShcherbin** [comment]
Using custom components like this one also triggers component rerendering:

```js
<Control.text model="forms.user.name" component={Input} />
```

**Comment by davidkpiano** [comment]
@VladShcherbin Are you using the latest version? Also, keep in mind that **Trace React Updates** in the devtools does not _only_ trace renders; it traces whether a component _may_ render (that is, if `shouldComponentUpdate` is called) even if it won't render. https://github.com/facebook/react-devtools#does-trace-react-updates-trace-renders

If your form is large, ideally you should be using `updateOn="blur"` as well.

**Comment by VladShcherbin** [comment]
@davidkpiano yes, this was an issue with 1.0.3, with 1.0.5 everything is great 👍

**Comment by VladShcherbin** [comment]
@davidkpiano I found another interesting stuff - the form has one element, but it renders twice on initiation, also clicking on label triggers rerendering as well. Here is the photo of the form & element + video of the issue:

![screen shot 2016-10-01 at 4 20 09 pm](https://cloud.githubusercontent.com/assets/6711845/19014329/4b2a58c4-87f3-11e6-8d98-9f47a5326f99.png)



[rrf.zip](https://github.com/davidkpiano/react-redux-form/files/504368/rrf.zip)

**Comment by Maxim-Chugaev** [comment]
I think I made a stupid mistake, maybe it's not a problem of the library.
```javascript
new webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify('production')
        })
```
i added this code to my webpack config, and after this my app nice was working.

**Comment by MioQuispe** [comment]
Also got this issue. Only have 11 fields in my form but it's unusable unless I set updateOn="blur".
Thanks for your great work on this awesome library @davidkpiano !

**Comment by davidkpiano** [comment]
@MioQuispe By any chance, can I see the code for your form?

**Comment by MioQuispe** [comment]
@davidkpiano Not sure if I'm allowed to share the code but I could strip out the relevant parts and send it in a private message. I'm on a deadline atm so I'll do it some time in the near future...

**Comment by MioQuispe** [comment]
@davidkpiano I sent you an email with some code.

**Comment by davidkpiano** [comment]
Performance seems to be significantly improved with #755! 🎊 🎉
