### ISSUE TITLE
Question: how to find out that collection data is changed or not.

### ISSUE THREAD

**Issue by koyoyo** [davidkpiano/react-redux-form#429]
I want to do autosave if data has been changed on every minute. So, I find the way to determine that each field is change or not. For general field, I can check on `pristine` in form data. But for collection field, it's hard to loop to check that it is changed or not because it's has `$form` among with data.

Do you have any suggestion how to check it ??

This is my example store.

```
deep: {
  forms: {
    $forms: {...},
    trip: {
      $form: {...},
      name: '',
      photos: {
        $form: {...},
        1: {
          url: '',
          description: ''
        },
        2: {
          url: '',
          description: ''
        }
      }
    }
  },
  trip: {...}
}
```

Thanks.

**Comment by davidkpiano** [comment]
I'll actually add this as an enhancement - the way you'd do it currently is by something like:

```js
Object.keys(deep.forms.trip).every((key) => {
  if (key === '$form') return true;

  return // check if pristine here
}
```

I'll fix that up real quick so that all you have to do is:

```js
deep.forms.trip.$form.pristine;
// => returns true if every field inside deep.forms.trip is pristine
```

**Comment by koyoyo** [comment]
Thanks very much.
