### ISSUE TITLE
Accessing dispatch from a stateless function

### ISSUE THREAD

**Issue by udalrich** [davidkpiano/react-redux-form#430]
The validation examples get the `dispatch` function from `this.props.dispatch` and are implemented by extending `React.Component`.  I do not see how to do it with a stateless function.  I have a form

```jsx
    const TheForm= (props) => {
         console.log('theForm props', props);
         return (
           <Form model="stuff" onSubmit={mySubmitFunc}> 
              ...
            </Form>
         )
    }
```

This is rendered by

```jsx
    <Provider store={store}
         <TheForm />
    </Provider>
```

This looks like what is in the examples, but `props` is an empty object.

**Comment by davidkpiano** [comment]
That is correct. The `dispatch`, etc. props are passed into `<Form>`, not the outer `<TheForm>` container.
