### ISSUE TITLE
Accumulate all errors inside one Errors element?

### ISSUE THREAD

**Issue by udalrich** [davidkpiano/react-redux-form#431]
It appears that a single `<Errors>` will only show the errors for one field.  What is a good way to accumulate all of the errors in a single place?  I am looking for something like

    <Form model="data">
       <Control.text model=".foo" validators={{v1, v2}} validateOn="blur">Foo</Control.text>
       <Control.text model=".bar" validators={{v1, v3}} validateOn="bar">Bar</Control.text>
       
       <Errors model=".foo,.bar" ...>...</Errors>
     <Form>
      
Is there a way to do this?  It does not look like `<Errors>` supports this, but is there another way?

**Comment by davidkpiano** [comment]
This is not currently supported, though you can always do:

```js
{['.foo', '.bar'].map((model) =>
  <Errors model={model} key="model"/>
)}
```

Is this sufficient? I can _look into_ having `model` accept an array, e.g., `model={['.foo', '.bar']}` but that's a little bit more magical than the above approach with the only advantage being a little less code.

**Comment by davidkpiano** [comment]
I'm going to close this in favor of the above approach - don't want to add _too_ much magic to the API! 😅
