### ISSUE TITLE
change model after reset 

### ISSUE THREAD

**Issue by Maxim-Chugaev** [davidkpiano/react-redux-form#439]
I edit my form and submit data. 
After submit i call 
```javascript
dispatch(actions.reset('model'))
```
 and after some time i call
```javascript
dispatch(actions.change('model'))
```
after change, my form has errors, but model is valid.

need help, pls.

![cat](http://think-differ.by/images/8659687.l3ht5ycfnl.W665.jpg)

**Comment by davidkpiano** [comment]
What does your store/form look like? Can I see some example code so I can get a better idea of what the issue is?

**Comment by Maxim-Chugaev** [comment]
i reproduced the problem in this repository 
https://github.com/Maxim-Chugaev/react-redux-form_problem
![screen](https://dl.dropboxusercontent.com/u/29852799/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-10-04%2016.20.41.png)
1) model changed in
``` javascript
componentDidMount () {
		setTimeout(()=> {
  			this.props.dispatch(actions.change('user', MyState));
  		}, 1000);
	}
```
2) click button reset
3) click button load
```javascript
<button onClick={()=> this.props.dispatch(actions.change('user', MyState))}>
   Load
</button>
```

**Comment by davidkpiano** [comment]
This is fixed, and will go out in the next patch today!

**Comment by venelin-mihaylov** [comment]
I have the same issue, thanks for fixing it! 👍

**Comment by linguafranka** [comment]
@davidkpiano Sorry for adding noise to an old thread.

I've a similar issue:

```
"react-redux-form": "^1.14.0",
```

```js
componentDidMount() {
  const entry = this.props.user;

  // initialize form
  if (entry) {
    this.props.dispatch(actions.change('userForm', {
      firstName: entry.firstName,
    }));
  }
}
```
```js
validators={{
  required: value && value.length > 0,
}}
```
Dispatching a change action in cDM doesn't seem to take into account validation. `firstName` will get a value after the change action, but the model remains invalid and has errors.

The workaround is to wrap actions.change() in a setTimeout which resolves the issue. Is this a known issue?

Thanks!

**Comment by davidkpiano** [comment]
Not a known issue, it's by design. When you do a change in your `<Control>` component, _two_ things happen:

- `actions.change`
- `actions.setValidity` (assuming `validateOn="change"`)

Since you are _manually_ dispatch `actions.change`, you also need to manually dispatch `actions.setValidity` (or `actions.validate` with the validators).

**Comment by linguafranka** [comment]
I see what you mean. Thanks for the explanation. I wish there was a way to rerun validations after a change model. Especially useful when populating edit forms with initial data. For a large model, it'd get super verbose to do `actions.validate` with all the validators. Also is very error prone to define validators for models in two separate locations.

On a different note, moving actions.change to `componentWillUpdate` seems to work without `setTimeout`.

Thanks again!

**Comment by davidkpiano** [comment]
Might be a version 2 feature! (still spec-ing it out)
