### ISSUE TITLE
Add class to div surrounding input on error

### ISSUE THREAD

**Issue by KevinBrolly** [davidkpiano/react-redux-form#441]
Hello,

I am using Bootstrap with react-redux-form and I am trying to use bootstrap's validation.

I want my input to look like this:

```html
<div class="form-group has-error">
<label class="control-label" for="inputError1">Input with error</label>
<input type="text" class="form-control" id="inputError1">
</div>
```

However I cannot figure out how to create a custom component and pass the validated prop so that I can conditionally add the "has-error" class to the div.

I tried making a custom input component and passing it through <Control.text component={myInput} /> but it is not passed any props that I can use to check if the field is valid.

What is the correct way to do something like this?

**Comment by davidkpiano** [comment]
Hey! I think #433 is the same issue (solution inside). You are provided `fieldValue` in your props which you can map in `mapProps` and use to check the validity of the form:

```jsx
<Control.text
  component={MyInput}
  mapProps={{
    valid: ({fieldValue}) => fieldValue.valid
  }}
/>

// in MyInput
const MyInput = (props) => (
  <div className={`formGroup ${props.valid ? '' : 'has-error'}`}>
  // ...
);
```
