### ISSUE TITLE
Error component does not show error when show changes to true

### ISSUE THREAD

**Issue by MiMaMuh** [davidkpiano/react-redux-form#444]
Hi, thx for the last fixes!

I want to show all errors of the input fields after a next-button was pressed. I'm using the ```Error``` component with its ```show```prop. At first, I pass a function, later, when the button was pressed, I pass ```true```. The issue is, the ```Errors```comps do not re-evaluate when ```show``` is changed? So the errors won't be shown till the validation of the form is rerun or the ```Error``` component will mount.

```jsx
function showAfterEdit(field) {
    return field.touched && !field.focus;
}

// when the user presses the button, this.state.showFormErrors will be true
const showErrors = (this.state.showFormErrors) ? true : showAfterEdit; 
<Errors
    model={model}
    messages={messages}
    show={showErrors} // changing show does not show the errors ...
/>
```

**Comment by davidspiess** [comment]
Anyway i expected the error messages to show up after submitting a form.
E.g in https://davidkpiano.github.io/react-redux-form/docs/recipes/sync-validation.html when submitting the form without filling out anything.

**Comment by davidkpiano** [comment]
Sorry, this was caused by very strict `shouldComponentUpdate` logic in `<Errors>`, which was only checking if the `fieldValue` or `formValue` (derived props) changed. I've set it to just do a simple `shallowEqual` on the props, which should catch that the `show="..."` has changed.

In the future (a minor release), if you want to tweak performance, you will be able to do so like this:

```jsx
// Only update for derived (Redux) props
<Errors dynamic={false} />

// Use shallowEqual to compare ALL props
// This is the default.
<Errors dynamic={true} />

// Only update for derived props and these props which
// you specify are expected to change.
// e.g., this tells Errors "expect the 'show' prop to change"
<Errors dynamic={['show']} />
```
