### ISSUE TITLE
Parser appending characters after rrf/change is dispatched

### ISSUE THREAD

**Issue by lasergoat** [davidkpiano/react-redux-form#446]
I have a form with two inputs each with a parser. Each parser only returns a certain number of digits, aka truncates the data.

For instance: '4111111111111111111111111111' myParser-> '4111 1111 1111 1111'

However, the field shows all the extra ones. 

**Seen here: my parser returns the truncated string:**

![parser](https://cloud.githubusercontent.com/assets/15964/19127357/38cf78a8-8b04-11e6-8de4-979a1beeb6cd.png)

**Seen here: the rrf/change is dispatching the correct data also.**

![chang](https://cloud.githubusercontent.com/assets/15964/19127356/38cf0f3a-8b04-11e6-8167-fdce53a193be.png)
 

Weirdly, the model contains the correct result of the parser, but not the view value.

**Comment by lasergoat** [comment]
just confirmed it by `npm run build` and moving the control-component to my project's npm folder. this fix works.

**Comment by davidkpiano** [comment]
Merged #447 which fixes this! Thanks!
