### ISSUE TITLE
Form won't submit when validators are included on custom component

### ISSUE THREAD

**Issue by zach-waggoner** [davidkpiano/react-redux-form#448]
https://esnextb.in/?gist=f0752a3ce1d089a66c80b9304b2e2b24

Remove the "component={Custom}" and it works.

**Comment by davidkpiano** [comment]
Ah, that's because you're rendering a simple `<input>` element with no handlers! Make sure to explicitly pass the mapped props onto your custom element:

```diff
-const Custom = () => <input type="text" />;
+const Custom = (props) => <input type="text" {...props} />;
```

And then it will work. 👍
