### ISSUE TITLE
Typescript Definitions (react-redux-form.d.ts) is outdated

### ISSUE THREAD

**Issue by briantobo** [davidkpiano/react-redux-form#453]
It seems the d.ts file in the npm package is outdated. The comment at the top of the file mentions it is for v0.13.4
Has someone written a new one for v1.0 yet, or have any plan to do so ?

For now I'm stuck at:
```
// module has no exported member 'combineForms'
import { combineForms } from 'react-redux-form';
```

**Comment by davidkpiano** [comment]
I'd love for someone to take the reins on that; I am not familiar with TypeScript (yet) and don't have the time to work on it - I'm more focused on the core functionality of React Redux Form.

Maybe submit a PR with the updated definitions for https://hacktoberfest.digitalocean.com/ ? 😄

**Comment by BrianDGLS** [comment]
I'll pick this up.

**Comment by BrianDGLS** [comment]
@davidkpiano I have added an updated .d.ts file as part of #456 . 

I used the Microsoft [gen-dts](https://github.com/Microsoft/dts-gen) tool to generate it.

Before closing this ticket could you add the hacktoberfest label please?

**Comment by tiagoefmoraes** [comment]
@BrianDGLS Are you still working on the typings? 
The new one doesn't export anything and declares a namespace that the old one didn't.

**Comment by noah79** [comment]
Agree - the .d.ts with this project isn't usable.
