### ISSUE TITLE
Control.select doesn't put default selection into state until changed.

### ISSUE THREAD

**Issue by yourfavorite** [davidkpiano/react-redux-form#458]
I have the following 

```jsx
<Control.select model=".type">
  <option value="listing">Listing</option>
  <option value="product">Product</option>
</Control.select>
```

If I change this field, the value gets added to the state appropriately. However if I leave the field alone because the default value of Listing is correct, then the state will be missing the .type value. Is there a step I should take to make sure the value of select inputs gets added to the state by default? I have tried adding defaultValue but that doesn't have any effect.

**Comment by davidkpiano** [comment]
It might be a bug that `defaultValue` does not initially load the value, though ideally you would have this default value as part of the initial state in your model reducer (or in `combineForms`). RRF does not assume that the first `<option>` is the default value, and I don't believe the W3 spec does either - it assumes that `<option selected>` is the default. Ideally, you'd have a select that looks like this:

```html
<select>
  <option value="" selected disabled>Choose here</option>
  <option value="1">One</option>
  <option value="2">Two</option>
  <option value="3">Three</option>
  <option value="4">Four</option>
  <option value="5">Five</option>
</select>
```

So I'll check on two things:

- [ ] `defaultValue` works as expected (though this should be avoided)
- [ ] `<option selected>` explicitly specified works as expected _as the default value_
  - having an initial value for the select's model in the store would override this

**Comment by ramiel** [comment]
In react you can simply assign a value to the `select` element and this will set the according option, as explained [here](https://facebook.github.io/react/docs/forms.html#why-select-value). Will this way work also on RRF?

**Comment by davidkpiano** [comment]
@ramiel Yes, setting `<select value="something">` will work. Remember that setting it to a static value doesn't allow it to be changed, however.

**Comment by ramiel** [comment]
Yes but looks like `<Control.select model=".name" value="defaultName">...</Control.select>` doesn't work the same way. Am I doing something wrong? I'll try to put an example somewhere to see if it is reproducible.

**Comment by davidkpiano** [comment]
@ramiel 

```jsx
<Control.select model=".name" value="defaultName">...</Control.select>
```

The above code, as-is, will never allow the value of `.name` to be changed. See here: https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by ramiel** [comment]
So, should this work?
```JS
<Control.select model=".name" defaultValue="defaultName">...</Control.select>
```

**Comment by davidkpiano** [comment]
Yes, `defaultValue` works.

**Comment by ramiel** [comment]
Ok, thank you, I'll try

**Comment by ramiel** [comment]
If I set the defaultValue, the option is choosed but not set in the modelValue. Is an expected behavior?

**Comment by davidkpiano** [comment]
@ramiel Can you open a separate ticket for that?

**Comment by ramiel** [comment]
Of course

**Comment by dilipagheda** [comment]
@davidkpiano I am getting same issue as @ramiel
