### ISSUE TITLE
Example guide for file attachments / Photo attachments

### ISSUE THREAD

**Issue by geekyme** [davidkpiano/react-redux-form#459]
Any tips on how I can integrate photo data obtained from https://github.com/lwansbrough/react-native-camera into the form and render it?

**Comment by davidkpiano** [comment]
In the example code for the repo:

```js
import { actions } from 'react-redux-form';

// Assuming your form/app/etc. is connected:

// ...
  takePicture() {
    const { dispatch } = this.props;

    this.camera.capture()
      .then((data) => dispatch(actions.change('user.photo', data)))
      .catch(err => console.error(err));
  }
```

**Comment by geekyme** [comment]
I did that but the model in `user.photo` is still `{}`.

**Comment by davidkpiano** [comment]
Can you copy-paste the code that fully reproduces the issue?

**Comment by geekyme** [comment]
I did this in my component: 

```
this.camera.capture()
      .then(data => {
        const fileName = `${Date.now()}.jpg`;
        const fileData = { uri: data.path, name: fileName, type: 'multipart/form-data' };
        actions.push('forms.createListing.photos', fileData);
      })
      .catch(err => console.error(err));
```

And this is my reducer: 

```
export default combineReducers({
  routes,
  me,
  forms: combineForms({
    createListing: {
      name: '',
      desc: '',
      price_day: null,
      photos: [],
    },
  }, 'forms'),
});
```

**Comment by davidkpiano** [comment]
You have to `dispatch` the `actions.push()` action:

```diff
this.camera.capture()
      .then(data => {
        const fileName = `${Date.now()}.jpg`;
        const fileData = { uri: data.path, name: fileName, type: 'multipart/form-data' };
-       actions.push('forms.createListing.photos', fileData);
+       dispatch(actions.push('forms.createListing.photos', fileData));
      })
      .catch(err => console.error(err));
```

**Comment by geekyme** [comment]
Thank you it works!

On 13 Oct 2016, at 1:11 AM, David Khourshid <notifications@github.com<mailto:notifications@github.com>> wrote:


You have to dispatch the actions.push() action:

this.camera.capture()
      .then(data => {
        const fileName = `${Date.now()}.jpg`;
        const fileData = { uri: data.path, name: fileName, type: 'multipart/form-data' };
-       actions.push('forms.createListing.photos', fileData);
+       dispatch(actions.push('forms.createListing.photos', fileData));
      })
      .catch(err => console.error(err));

-
