### ISSUE TITLE
field state does not have correct values for form level actions

### ISSUE THREAD

**Issue by KevinBrolly** [davidkpiano/react-redux-form#462]
As per #452, Field state does not appear to be updated when form-level actions happen.

For example, given a Control which has:

    mapProps={{
        touched: ({fieldValue}) => fieldValue.touched,
        focus: ({fieldValue}) => fieldValue.focus,
        valid: ({fieldValue}) => fieldValue.valid,
        submitFailed: ({fieldValue}) => fieldValue.submitFailed
    }}

The submitFailed prop passed to the input will always be false. Even when the form has been submitted and validation has failed, and the form state is set to submitFailed: true.

**Comment by cesarp** [comment]
I am having a similar issue, if I add mapProps then my custom component never dispatches a change.

Without mapPros I see in dev tools:

1. focus
2. change
3. setFieldsValidity

With mapProps nothing is dispatched.

**Comment by jomasti** [comment]
For me, children of an array field don't get the updated field state on submission failed. They validate correctly, and I can see that there is an error in the state for the subfield. I want to show the error if touched (or submitFailed), but since it never gets the updated state, the error isn't shown.

I have a simplified structure like this:
```
{
  name: '',
  description: '',
  questions: [{
    title: '',
    text: '',
    type: '',
    options: [{...}],
  }, {
    ...
  }]
}
```

And for the questions, I'm mapping over them in a function called in the main form:

```
const renderQuestions = ({ questions }, dispatch) => (
  <ul>
    {questions.map((question, index) => {
      <li>
        <Field model={`.questions[${index}].type`}>
          <select>
            {options}
          </select>
        </Field>
        <Control.text
          model={`.questions[${index}].title`}
          placeholder="Title"
          type="text"
          validators= {{ required }}
        />
        <Errors
          model={`.questions[${index}].title`}
          messages={{
            required: 'A title is required'
          }}
        />
        ... (question object used in here)
      </li>
    })}
  </ul>
);
```

Anything in the fields under `questions` doesn't get the updated state.

**Comment by davidkpiano** [comment]
@jomasti @cesarp What version of RRF are you on?

**Comment by jomasti** [comment]
Oh, sorry. I'm on 1.0.12.

**Comment by cesarp** [comment]
1.0.12 too

**Comment by davidkpiano** [comment]
Try in 1.0.13 once I make the patch!

**Comment by jomasti** [comment]
I can confirm that it works for my use case! Thanks!

**Comment by cesarp** [comment]
I am still having the same issue

**Comment by davidkpiano** [comment]
@cesarp 

> I am having a similar issue, if I add `mapProps` then my custom component never dispatches a change.

Can you share your custom component's code? This sounds like a separate issue.

**Comment by cesarp** [comment]
It was a little bit more complex than this but even after reducing it to this it fails, not sure if I am doing something wrong but without the mapProps it works although I want to get the errors, touch, and a few other props to style the component a bit different.

```javascript
(props)  => {

  const {
    label,
    type,
    required,
    touched,
    ...otherProps
  } = props;

  return (
    <FormGroup label={label}
               required={required}>
      <div>
        <input type={type}
               className="Input"
               required={required}
               {...otherProps}/>
        <div>{touched}</div>
      </div>
    </FormGroup>
  )
}
```
