### ISSUE TITLE
Unknown props warning on Control.checkbox

### ISSUE THREAD

**Issue by AaronLaBrie** [davidkpiano/react-redux-form#465]
Hello! I'm using a `<Control.checkbox .../>` component which is producing an unknown props error on render:

```Warning: Unknown prop `changeAction` on <input> tag. Remove this prop from the element. ```

I'm on the latest release at time of writing (1.0.10). Thanks!

**Comment by tomzilla** [comment]
Same. React 15.3.2

**Comment by AaronLaBrie** [comment]
Whoo! Thanks for the swift turnaround!
