### ISSUE TITLE
Outdated Wiki Page: "Redux Form Comparison"

### ISSUE THREAD

**Issue by antmdvs** [davidkpiano/react-redux-form#467]
https://github.com/davidkpiano/react-redux-form/wiki/Guide:-Redux-Form-Comparison

The wiki page doesn't reflect the latest version of redux-form which now has a `<Field />` component.

**Comment by davidkpiano** [comment]
Fixed by deleting that page. Here's the most up-to-date comparison: http://davidkpiano.github.io/react-redux-form/docs/guides/compare-redux-form.html

**Comment by antmdvs** [comment]
I had a feeling you were going to do that :) I still think the general philosophy you had in the summary of that wiki page as well as the Main Differences bullet points would be helpful to carry over.
