### ISSUE TITLE
Recipe "custom-components" looks strange

### ISSUE THREAD

**Issue by i4got10** [davidkpiano/react-redux-form#47]
http://davidkpiano.github.io/react-redux-form/#/recipe/custom-components

Slider reset to initial value on every checkbox change.

![screencast 2016-03-04 17-25-16](https://cloud.githubusercontent.com/assets/1151154/13527077/5f221eea-e22e-11e5-86f8-481c39836b72.gif)

**Comment by davidkpiano** [comment]
Huh, that's weird. I'm wondering if it's a problem with material-ui itself. I'll take a look.

**Comment by clarkie** [comment]
material-ui does add a lot of 'fluff' to the form elements. I had similar problems with redux-form too.

**Comment by davidkpiano** [comment]
Redoing the docs and recipes for upcoming v1.0 - I'll reopen if this problem appears again!
