### ISSUE TITLE
How to access form state from component

### ISSUE THREAD

**Issue by cyberwombat** [davidkpiano/react-redux-form#470]
Im a bit new to the React redux field so this may be obvious. I have a form and wish to show a div based on the form state. I understand how to set the form states but am not sure how to access it again within my form:

````
<Form model={deep.user}...
    { deep.user.$form.pending : '<h4>Sending</h4>' : '' } // This doesn't work - how to I get `deep.user` instance?
````

I see on some sample that the user is passed as props:
````
UserForm.propTypes = {
  dispatch: React.PropTypes.func.isRequired,
  user: React.PropTypes.shape({
    firstName: React.PropTypes.string.isRequired,
    lastName: React.PropTypes.string.isRequired,
  }).isRequired,
};
````
Do I need to do this with a nested deep object?

Thanks

**Comment by davidkpiano** [comment]
Do you have [redux-logger](https://github.com/evgenyrodionov/redux-logger)? It might come in handy.

How are you defining your state? If it's something like this:

```js
const store = createStore(combineForms({
  foo: initialFoo,
});
```
then you can access the forms from your state like so:

```js
class FooForm extends Component { ... }

const mapStateToProps = (state) =({
  fooForm: state.forms.foo
});

export default connect(mapStateToProps)(FooForm);
```

And then in your component:

```js
render() {
  const { fooForm } = this.props;

  if (fooForm.$form.pending) {
    return <div>Loading...</div>
  }

  // etc.
}
```

**Comment by cyberwombat** [comment]
Perfect thank you.
