### ISSUE TITLE
v 1.0.10 broke my code

### ISSUE THREAD

**Issue by Maxim-Chugaev** [davidkpiano/react-redux-form#473]
I have error after update on latest version.
```javascript
bundle.js:17859 Warning: performUpdateIfNecessary: Unexpected batch number (current 1702, pending 1684)
```
The error occurs after call actions.reset('mymodel');

**Comment by davidkpiano** [comment]
Can you post the full code example that reproduces the issue?

**Comment by Maxim-Chugaev** [comment]
https://github.com/Maxim-Chugaev/react-redux-form_problem
yep, last commit visualize problem.
You need open page, and click reset, then all UI be freezed.
