### ISSUE TITLE
No value on changeAction (checkbox)

### ISSUE THREAD

**Issue by ramiel** [davidkpiano/react-redux-form#474]
In the function taken from `changeAction` I'm expecting two arguments to be fullfilled: `model` and `value` or at least is what I understood from the documentation. In a checkbox only the `model` seem to have a value, while `value` is undefined. Is it normal?

**Comment by davidkpiano** [comment]
What does your store look like? It could be that the initial value of your model is `undefined`.

**Comment by ramiel** [comment]
You're right. This is the store:
```js
const reducers = combineReducers({
    ...createForms({
        options: [],
    }),
    auth,
    routing: routerReducer
})
const store = createStore(reducers, {}, middlewares); // with thunk in middlewares
```

Then, the component looks like this (only the relevant parts)

```jsx
{ 
this.props.payment_options.map((option, index) =>
  <Control.checkbox
  key={index} 
   model={track(`options[].enabled`, {id:   option.id}), 'enabled')}
   changeAction={(model, value) => dispatch => {
   // async code....
   dispatch(actions.toggle(model))
}}
/>
)
}
```

and the array of options, once fetched contais object like
```js
{
id: 1,
name: '...'
}
```

**Comment by davidkpiano** [comment]
This looks invalid:

```js
   model={track(`options[].enabled`, {id:   option.id}), 'enabled')}
```

But besides that, is the component working? Since your model value is `undefined`, it's going to be passed `undefined` as the second argument to the change action, but for a checkbox, that shouldn't matter - it's falsey so `actions.toggle` will just set the model to `true`.

**Comment by ramiel** [comment]
Sorry, I cutted the code to simplify it. Is
```js
model={track(`options[].enabled`, {id:   option.id})}
```
and
```js
{
id: 1,
name: '...',
enabled: true/false
}
```
Yes, it is working. Enabled is not undefined but actually it works even if it is undedfined
