### ISSUE TITLE
Adding and removing fields from field array

### ISSUE THREAD

**Issue by rusandreev** [davidkpiano/react-redux-form#480]
I didn't get from docs how realize adding and removing rows in field array. Here is the [gist](https://esnextb.in/?gist=965e0e6235182e3d000ecb10226b30a7) for example. In this example I got an error "Uncaught ReferenceError: initialMember is not defined" after clicking the button "Add Member". What's wrong?

**Comment by davidkpiano** [comment]
You're missing `initialMember`:

```js
const initialMember = {
  firstName: '',
  lastName: ''
};

const initialState = { 
  members: [initialMember]
};
```

Should work after that 👍
