### ISSUE TITLE
Field.render always adds a wrapper div.

### ISSUE THREAD

**Issue by dreid** [davidkpiano/react-redux-form#482]
It appears this started happening in https://github.com/davidkpiano/react-redux-form/commit/d856da1c6302b4daedff5e613a1ac956adf420bb

It'd be nice if there were an easy way to disable this in the short term. Passing null doesn't work because Field.render now unconditionally calls `React.createElement` with component.

Passing a component like:

```
const OnlyChild = ({children}) => React.Children.only(children);
```

To enforce that there is only one child per Field doesn't work because children is always an array. https://github.com/davidkpiano/react-redux-form/issues/481

**Comment by davidkpiano** [comment]
Anyway, this is fixed, and now behaves just as you described:

```js
<Field model="foo.bar" component={null}>
  <input type="text" />
</Field>
```

This will **throw** if there is more than one child.
