### ISSUE TITLE
Nested forms are not supported by React, nor by HTML5

### ISSUE THREAD

**Issue by robinspark** [davidkpiano/react-redux-form#490]
This may cause issues in some browsers for some people.

https://github.com/facebook/react/issues/6567

gaearon commented on Apr 22
"It is not valid HTML: http://stackoverflow.com/questions/555928/is-it-valid-to-have-a-html-form-inside-another-html-form"

To solve it, remove either the parent form, or the child form. You can pass a prop to the child component telling it not to render the form. You also don't have to use the form element if you just need some inputs. You may render them directly.

If you ignore the warning there is a risk that it will render incorrectly in some browsers and potentially break React interaction on the page."

**Comment by davidkpiano** [comment]
Right. Ideally you shouldn't be nesting forms, whether it's `<form>` or `<Form>`. There's a few workarounds:

- If you want a "form" inside a form that doesn't submit, you can set `<Form component="div" ...>`
- Also, you can set `<Fieldset model="...">` (not documented yet)
- If you _do_ want a "form" inside a form that does submit, you'll have to submit manually by using `actions.validSubmit(model, promise)`.

**Comment by robinspark** [comment]
I ended up moving the inner form inside a <Dialog> component after the form, so I can easily validate and submit.

**Comment by ngbrown** [comment]
What if the outer `Form` has `<Form component="div" ...>` and the inner `Form` is intended as a normal `form` so that `enter` on an `input` control submits the inner form?  It seems that the behavior I'm getting is that the outer `Form` `onSubmit` is firing.
