### ISSUE TITLE
how to use react-redux-form with redux-immutable library

### ISSUE THREAD

**Issue by sinbazhou** [davidkpiano/react-redux-form#492]

**Comment by sinbazhou** [comment]
I try to use react-redux-form with redux-immutable library,but failed

**Comment by davidkpiano** [comment]
Are you importing from `react-redux-form/immutable` ?

**Comment by davidkpiano** [comment]
Docs here! http://davidkpiano.github.io/react-redux-form/docs/guides/immutable.html
