### ISSUE TITLE
When a 'type=number' Control's value has its last decimal removed, cursor is placed at the beginning of input.

### ISSUE THREAD

**Issue by MixKCet** [davidkpiano/react-redux-form#493]
Hey!

Found this weird issue when creating an input with a float value. Created a gist here:
https://esnextb.in/?gist=87dc7cd3f897aeeed43b2c0f0d1435dd

Try backspacing from each of the fields to see the behaviour.

Cheers

**Comment by davidkpiano** [comment]
@MixKCet Seems similar to these issues:

https://github.com/facebook/react/issues/7781
https://github.com/facebook/react/issues/7253
https://github.com/facebook/react/pull/7359

So this is unrelated to RRF, but a current issue with React itself.

Here's a simple workaround:

```jsx
        <Control.text
          model='.floaty'
          type='number'
          step='.1'
          value={undefined}
        />
```

The above makes the control _uncontrolled_, so it can't be remotely updated, but it also avoids the React issues.

**Comment by MixKCet** [comment]
Huh, look at that. Thanks @davidkpiano!
