### ISSUE TITLE
getFieldFromState returns incorrect object when using createForms and formReducer

### ISSUE THREAD

**Issue by TLadd** [davidkpiano/react-redux-form#498]
I have a root reducer that looks something like

```
combineReducers({
   deep: combineReducers({
      form: formReducer('deep.formModel', initialDeepFormState),
      formModel: modelReducer('deep.formModel', initialDeepFormState)
   }),
   ...createForms({
      someForm: initialSomeFormState,
      someOtherForm: initialSomeOtherFormState,
   }),
})
```

So I have a couple of forms that I'm setting up using createForms, but I also have a model and form reducer that I'm creating directly in another branch of the tree.

When I call getField(state, 'deep.formModel'), instead of getting back the object that resides at state.deep.form, I instead get back state.forms. 

Stepped through the code some and it seems like the || subStateModel === '' causes this here: https://github.com/davidkpiano/react-redux-form/blob/master/src/utils/get-form.js#L25. Since the forms object created by createForms has a model field of '', the path returned is always 'forms' in this case.

**Comment by TLadd** [comment]
Ended up just moving the outlying reducers into createForms. There probably isn't really a good reason to have a shape like the above, so it's fine with me if you would like to close.

**Comment by davidkpiano** [comment]
Sounds good; I'll continue to investigate this.

Basically, when you do `createForms` or `combineForms`, it creates a "universal" form reducer that can accommodate all forms.
