### ISSUE TITLE
getFormStateKey causing performance issues (Electron - getter specific)

### ISSUE THREAD

**Issue by MrBlenny** [davidkpiano/react-redux-form#499]
the `getFormStateKey` function in `get-form.js` is causing major performance issues for me (v1.0.8)

![example](https://i.imgur.com/SqIfdCH.png)

That is 7 seconds or processing. When I refresh my app it is called a grand total of 18,401 times (I've got about 20 checkboxes and 3 inputs on the page).

I'm not quite sure why it is being called so many times - I assume it is the result of having a deeply nested state (at most [8 layers](https://i.imgur.com/4y7bN66.png)) and doing some weird recursion.

Any idea why this is happening? Or, debugging tips?

**Comment by davidkpiano** [comment]
@MrBlenny Can you do two things:

- Upgrade to the latest patch version of RRF (`1.0.14`)
- Share your code, if possible?

At the very least, I'd like to see how your store code is structured.

**Comment by MrBlenny** [comment]
I've updated to `1.0.14` but the issue is still there.

Do you have any idea what part of the store would be causing the issue (middleware/store-structure/reducers etc)? This is part of a multi-window electron application so it is hard to share the code unless I know what section could be causing the issue.

Here is a more detailed CPU profile:

![example](https://i.imgur.com/q7s43ov.png)

The store state tree looks something like:

![state tree](https://i.imgur.com/4y7bN66.png)

Store config:
```
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import promise from 'redux-promise-middleware';
import createLogger from 'redux-logger';
import { hashHistory } from 'react-router';
import { routerMiddleware } from 'react-router-redux';
import getRootReducerRenderer from '../reducers/rootReducer.renderer.js';
import forwardToMain from './middleware/forwardToMain';
import forwardToRendererWindow from './middleware/forwardToRendererWindow';
import routerFix from './middleware/routerFix';

export default function configureStore(initialState) {
  const middleware =[
    thunk,
    promise(),
    routerFix,
    forwardToMain,
    forwardToRendererWindow,
    routerMiddleware(hashHistory),
  ];
  if(process.env.NODE_ENV == 'development') {
     middleware.push(createLogger({
      level: 'info',
      collapsed: true,
    }));
  }
  const enhanced = [applyMiddleware(...middleware)];
  enhanced.push(window.devToolsExtension ? window.devToolsExtension() : noop => noop);
  const rootReducer = getRootReducerRenderer();
  const enhancer    = compose(...enhanced);
  const store       = createStore(rootReducer, initialState, enhancer);

  if (!process.env.NODE_ENV && module.hot) {
    module.hot.accept('../reducers', () => {
      store.replaceReducer(require('../reducers'));
    });
  }

  return store;
}
```

**Comment by MrBlenny** [comment]
The issue seems to be related to the store object itself.

When using electron the store often seems to end up with a getter functions instead of normal keys/values. I'm not sure what/why this is.

![Example](https://i.imgur.com/CUzBe3x.png)

This store structure does not play nice with the recursive `get-form` calls.

**Comment by davidkpiano** [comment]
> There is probably no easy fix.

You're probably right, but I can still try to make it easier for developers. How does this look?

```js
<Form
  model="user"
  form={theFormState}
>
  // ...
</Form>
```

where `theFormState` is the path to the form state. This will allow you, the developer, to tell RRF "don't bother looking for the form, I already know where it is" as an enhancement.

**Comment by MrBlenny** [comment]
Yep, that looks good.
I very much like the idea of disabling getting form and field values from the model. 

Passing model AND value to the form and field/control components feels much more react-like to me.

**Comment by zargold** [comment]
when you say path to form would that allow someone to say this nested object is the form who's path is 'itemsByUrl.myUrl.idWithinUrl[3].item' in other words change that aspect of the state? Right now I am using actions.load to load that path into the Form but I will get to avoid that or am I misreading 

>  is the path to the form state. This will allow you, the developer, to tell RRF "don't bother looking for the form, I already know where it is"

**Comment by davidkpiano** [comment]
I'm not sure of the API for this yet. I'm evaluating if it's redundant with `<LocalForm>`.

**Comment by davidkpiano** [comment]
Closing this, as `get-form` has since been completely reimplemented and improved. If this is still a problem, feel free to open a separate issue.
