### ISSUE TITLE
please give more examples

### ISSUE THREAD

**Issue by plandem** [davidkpiano/react-redux-form#5]
i'm quite new at field of react and redux, but i already like your implementation. But can you write more examples? Not like 'snapshots' of code, but full version? For example at your site there is only 'demo' for validating on submit - without any code. And i would like to connect the dots - see at least one full version of example - like small app. It would help a lot.

p.s.: i like that your library do only one thing, like https://github.com/callum/redux-routing - just routing, that also can work without react.

**Comment by davidkpiano** [comment]
Thanks, @plandem! I'm still working on fleshing out the documentation, but yes, I will add full examples.

What's a good example full, end-to-end example of a form app that you would like to see coded up? I plan on adding many examples. I'm open to suggestions.

**Comment by plandem** [comment]
well as for me - i'm highly interesting with anything that can be used with backend - login/register and etc. Right now i just can't understand how to make it to submit :(

**Comment by plandem** [comment]
for example, 'getField' is not working too
```
import { Field, Form, getField } from 'react-redux-form';
...
<FieldError field={getField(userForm, 'login')}/>
```

**Comment by davidkpiano** [comment]
How are you using `getField()`? It's meant to return the field from the form for form states such as focus, blur, valid, errors, etc.

Can you share your full code?

**Comment by plandem** [comment]
http://davidkpiano.github.io/react-redux-form/#/recipe/sync-validation?_k=kma7hv

like here, but just imported 'getField' too:
```
import { Field, Form, getField } from 'react-redux-form';
```

anyway, it works fine via:
```
userForm.field('username')
```

**Comment by davidkpiano** [comment]
Do you have the latest `react-redux-form`? The `getField()` function was a recent addition.

**Comment by plandem** [comment]
lol :) not sure now :) i installed your project today :)

**Comment by davidkpiano** [comment]
I just updated it today, `npm install` the latest minor version. Sorry for the confusion! I didn't want a magic `myForm.field('blah')` method in the state.

**Comment by plandem** [comment]
hmmm....u just did: 
```
npm update --save
```
and no updates :(

**Comment by davidkpiano** [comment]
Okay, I just confirmed the issue. If you install to the latest version (updated in the docs too), `getField` will be available.

```
npm install react-redux-form@0.3.1 --save
```

Hope that works!
