### ISSUE TITLE
Can't set initial value in Controls

### ISSUE THREAD

**Issue by diffused** [davidkpiano/react-redux-form#501]
I can't seem to set any initial values in a Control. The data is showing in state however it doesn't display when rendering out the form Control,

I am using react-router-redux btw

I'm using the following:

```
const initialAccountState = {
  firstName: 'blah',
  middleName: 'kjkj'
};

const forms = combineForms({
  account: initialAccountState,
});

export default combineReducers({
  routing: routerReducer,
  forms,
});
```

My store setup is:
```
import { applyMiddleware, createStore, compose } from 'redux';
import { browserHistory } from 'react-router';
import { routerMiddleware } from 'react-router-redux';
import thunk from 'redux-thunk';
import promise from 'redux-promise-middleware';

import reducer from './reducers';

const middlewares = [thunk];

if (process.env.NODE_ENV === `development`) {
  const createLogger = require(`redux-logger`);
  const logger = createLogger();
  middlewares.push(logger);
}

middlewares.push(thunk);
middlewares.push(promise());
middlewares.push(routerMiddleware(browserHistory));

const store = compose(applyMiddleware(...middlewares))(createStore)(reducer);
export default store;
```

The component looks like:

```
@connect((store) => {
  return {
    account: store.forms.account.account,
  };
})
class AccountProfile extends Component {  
  handleSubmit(values) {
  }

  render() {
    return (
      <section className="panel">
        <Form model="account"
          onSubmit={(values) => this.handleSubmit(values)}
          className="form-horizontal">
          
          <Control.text model="account.firstName" />
        </Form>
      </section>
    )
  }
}
```

When the page loads, I can see redux state forms.account.firstName is set to 'blah'

**Comment by davidkpiano** [comment]
Here's the issue:

```jsx
<Control.text model="account.firstName" />
```

The model here is `account.firstName`, however, in the store you defined:

```js

const forms = combineForms({
  account: initialAccountState,
});

export default combineReducers({
  routing: routerReducer,
  forms,
});
```

that model would actually live under `forms.account.firstName`.

So here's the fix:

```diff
-<Control.text model="account.firstName" />
+<Control.text model="forms.account.firstName" />
```

Hope this helps!

**Comment by diffused** [comment]
Awesome, thanks. 
Makes sense now. I initially thought the <Form model="account"> was referring to account prop and the the controls inside somehow hinged off that.

Cheers for that. Will update my thinking on how this works now :D

**Comment by diffused** [comment]
Just have another question around this model hookup.

I'm using `Form model="forms.account"` 
with a control of `Control.text model="forms.account.firstName"`

The initial value shows up however any changed value doesn't appear in the handleSubmit function

**Comment by davidkpiano** [comment]
Hmm, would you mind opening that up in a separate issue for tracking purposes?

**Comment by diffused** [comment]
sure thing
