### ISSUE TITLE
The novalidate attribute is not added to the <form> element

### ISSUE THREAD

**Issue by robinspark** [davidkpiano/react-redux-form#505]
"If you want to disable HTML5 validation for a form, add a novalidate attribute to the form element"
https://davidkpiano.github.io/react-redux-form/docs/guides/validation.html

version: 1.0.13

**Comment by davidkpiano** [comment]
Right, you have to add it yourself. It is optional, and many developers might not want to use `novalidate`, in order to show errors using the DOM API.

**Comment by robinspark** [comment]
I got it to work.

The rrf documentation needs to updated, as it specifies "novalidate", whereas React requires it to be in camel case. ie. "noValidate" with a capital 'V'.

**Comment by davidkpiano** [comment]
Fixed in the docs!

**Comment by robinspark** [comment]
cheers : )
