### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by Agalla81** [davidkpiano/react-redux-form#506]
Hi @davidkpiano,

Fantastic library.

While reading the documentation I found an inconsistency:

Api > Action Creators: describes _asyncSetValidity_
Based on the API it seems as the correct function is _asyncSetValidty_

Guides > Validation: describes _setAsyncValidty_
```
import { actions } from 'react-redux-form';

// wherever validation occurs...
const { user, dispatch } = this.props;

dispatch(actions.setAsyncValidity('user.username', (value, done) => {
  asyncCheckUsername(value)
    .then((response) => done({ available: response.available });
}));
```

Nothing major of course but possibly worth correcting to avoid confusions.

Thanks again for a great library!

**Comment by davidkpiano** [comment]
Thanks for the report!
