### ISSUE TITLE
Reset Form on Navigate

### ISSUE THREAD

**Issue by Agalla81** [davidkpiano/react-redux-form#507]
Hi,

I would like to reset the form every time the user navigates out from the registration page.
What's the recommended approach? Considering that, ideally, the page is kept as a presentational component (stateless functional component).

Thanks

**Comment by davidkpiano** [comment]
Are you using React Router? Wherever you would define a hook for navigating out, you can just `dispatch(actions.reset('your.model'))`.

Also, #420 should solve this naturally when implemented.

**Comment by Agalla81** [comment]
Thanks for the reply. Router is an option; ended up resetting on componentWillMount for a regular stateful component. Will certanily investigate the new option when available!

**Comment by davidkpiano** [comment]
#420 has shipped: https://github.com/davidkpiano/react-redux-form/releases/tag/v1.2.0 let me know if it works for your use case!
