### ISSUE TITLE
Classname conditionals for inputs

### ISSUE THREAD

**Issue by tomspeak** [davidkpiano/react-redux-form#509]
Currently the way to apply classnames for errors is like so:

```jsx
<Field model="user.name">
  {(fieldValue) => <input className={fieldValue.valid ? '' : 'invalid'} />}
</Field>
```

A proposed API to alleviate having to use functions for children is:

```jsx
<Control.text model="user.name"
  classNames={(fieldValue) => {
    'has-error': !fieldValue.valid,
    'focused': fieldValue.focus,
  }}
/>
```

This is very similar to the `classnames` API, and I think is quite intuitive.

**Comment by davidkpiano** [comment]
I've thought about this a little and figured it's best not to add any extra API for something that's already handled naturally in `mapProps`:

```jsx
<Control.text
  model="user.firstName"
  mapProps={{
    className: ({fieldValue}) => fieldValue.focus
      ? 'focused'
      : ''
  }}
/>
```

The above is more flexible and will work as expected 😄
