### ISSUE TITLE
Cannot find module 'react-redux-form/immutable'

### ISSUE THREAD

**Issue by dmitrif** [davidkpiano/react-redux-form#511]
Hi, great work!

I am currently attempting to use `^1.0.15`, but getting the following error while importing:

```fes_1 | Error: Cannot find module 'react-redux-form/immutable'
fes_1 |     at Function.Module._resolveFilename (module.js:326:15)
fes_1 |     at Function.Module._load (module.js:277:25)
fes_1 |     at Module.require (module.js:354:17)
fes_1 |     at require (internal/module.js:12:17)
fes_1 |     at eval (webpack:///external_%22react-redux-form/immutable%22?:1:18)
fes_1 |     at Object.<anonymous> (/var/frontend/build/main.js:2092:2)
fes_1 |     at __webpack_require__ (/var/frontend/build/main.js:517:30)
fes_1 |     at fn (/var/frontend/build/main.js:48:20)
fes_1 |     at eval (webpack:///./app/redux-helpers/modules/reducer.js?:9:18)
fes_1 |     at Object.<anonymous> (/var/frontend/build/main.js:907:2)
```

Please advise :)

Thanks!

**Comment by davidkpiano** [comment]
Oops, try `react-redux-form/lib/immutable` instead.

**Comment by davidkpiano** [comment]
Updated in the docs: http://davidkpiano.github.io/react-redux-form/docs/guides/immutable.html

<img width="352" alt="screen shot 2016-11-02 at 8 54 41 am" src="https://cloud.githubusercontent.com/assets/1093738/19929499/08a46044-a0da-11e6-80a2-823d66511dab.png">

**Comment by Neophy7e** [comment]
@davidkpiano there is still places where it's `react-redux-form/immutable` instead of `react-redux-form/lib/immutable`

eg : https://github.com/davidkpiano/react-redux-form/blob/master/examples/immutable/store.js

**Comment by davidkpiano** [comment]
@Neophy7e Now, `import { ... } from 'react-redux-form/immutable'` will work in the next release.

**Comment by gocamille** [comment]
Hi @davidkpiano ! Has the next release been released? Just `npm installed` but don't get these changes. 😞

**Comment by davidkpiano** [comment]
@gocamille Yes, these should be under `react-redux-form@1.2.3`. Try clearing your npm cache or `rm -rf node_modules` if you are not able to see the changes.
