### ISSUE TITLE
Error with immutable

### ISSUE THREAD

**Issue by dmitrif** [davidkpiano/react-redux-form#514]
Hi! It's me again. I changed include to use `import { combineForms } from 'react-redux-form/lib/immutable';` however, an error appears:

```
fes_1 |     TypeError: Cannot use 'in' operator to search for 'get' in true
fes_1 |         at /var/frontend/node_modules/react-redux-form/lib/utils/get-from-immutable-state.js:21:18
fes_1 |         at Array.reduce (native)
fes_1 |         at Object.immutableGetFromState [as get] (/var/frontend/node_modules/react-redux-form/lib/utils/get-from-immutable-state.js:17:15)
fes_1 |         at /var/frontend/node_modules/react-redux-form/lib/utils/get-form.js:56:23
fes_1 |         at /var/frontend/node_modules/immutable/dist/immutable.js:4899:25
fes_1 |         at /var/frontend/node_modules/immutable/dist/immutable.js:4364:24
fes_1 |         at /var/frontend/node_modules/immutable/dist/immutable.js:2869:56
fes_1 |         at /var/frontend/node_modules/immutable/dist/immutable.js:3018:36
fes_1 |         at /var/frontend/node_modules/immutable/dist/immutable.js:2834:35
fes_1 |         at /var/frontend/node_modules/immutable/dist/immutable.js:1379:16
```

The reducer is set up as such:
```
let forms = combineForms({
  billingInfo: billingInfoInitialState,
});

export default combineReducers({
  config,
  forms
});
```

And the form is set up as such:
```
import React from 'react';
import { Control, Form, actions } from 'react-redux-form/lib/immutable';

export default class BillingForm extends React.Component {
  handleSubmit(billingInfo) {
    const { dispatch } = this.props;
  }

  render() {
    return (
      <Form model="billingInfo" 
        onSubmit={(billingInfo) => this.handleSubmit(billingInfo)}>

        <label>Address 1</label>
        <Control.text model="billingInfo.address" />
             
        <button type="submit">Submit</button>
      </Form>
    );
  }
};
```

Please advise. Thank you!

**Comment by dmitrif** [comment]
Also tried using createForms instead, still failing.

**Comment by dmitrif** [comment]
Seems like createForms update didn't stick, after rebuilding it works. Thanks.

**Comment by davidkpiano** [comment]
I'm pretty sure the check I added in 7efde9f will fix the issue, can you check when the next release goes out?

**Comment by dmitrif** [comment]
Thanks, David!

I see the tag for 1.1.0 but when trying to install from NPM it's saying that version doesn't exist.

**Comment by davidkpiano** [comment]
Hmm, try again?

<img width="343" alt="screen shot 2016-11-03 at 11 03 56 am" src="https://cloud.githubusercontent.com/assets/1093738/19971390/3d318540-a1b5-11e6-8fba-9b01c874645e.png">

**Comment by dmitrif** [comment]
I think this particular issue is fixed. but I think I realized why this doesn't work for us, is this library compat with redux-immutablejs?

Cheers.

**Comment by davidkpiano** [comment]
Paging @erin-doyle - she would know the answer to that 😄 I believe it _is_ supposed to work with `redux-immutablejs`.

**Comment by dmitrif** [comment]
Thank you!

It ends up tripping up on lines such as:

Line 19 in get-field-from-state.js
```const formPath = toPath(form.$form.model);```

Since I believe form itself is an immutable object in this case. Along with some other spots.

**Comment by davidkpiano** [comment]
If you'd like to help out with PRs, I'd gladly get them merged in ASAP. The solution to fixing this is two-fold, so for example:

In `get-field-from-state.js`:

```diff
-const formPath = toPath(form.$form.model);
+const formPath = toPath(s.get(form, ['$form', 'model']));
```

And then in `src/immutable.js`:

```diff
function immutableGetFieldFromState(state, modelString) {
-  return getField(state, modelString, { getForm: immutableGetForm });
+  return getField(state, modelString, { getForm: immutableGetForm, get: immutableGetFromState });
}
```

Should be simple fixes, and since you can recreate the errors, you (or someone who uses Immutable.JS) would be best to diagnose them. 🙏 

Personally, I do _not_ use Immutable.JS (I use icepick.js so that I can work with standard JS types).

**Comment by dmitrif** [comment]
@davidkpiano Thanks :) Working on it!
