### ISSUE TITLE
Are checkboxes broken?

### ISSUE THREAD

**Issue by mikkelwf** [davidkpiano/react-redux-form#517]
Hi

I'm trying to incorporate rrf into my app.
I simply cannot get checkboxes to work

I'm doing this simple example 
```
<Form model='playground'>
  <Control.checkbox
    model='.boolean.checkbox1'
    value={true} />

  <Field model='.boolean.checkbox2'>
    <label>
      <input type='checkbox' value={true} /> Check me!
    </label>
  </Field>
</Form>
```

The redux action `rff/change` is triggered when i check the box, but the `checked` state is not updated. I've tried both with 1.0.15 and 1.1.0, but nothing is working.

**Comment by davidkpiano** [comment]
![nov-03-2016 13-15-28](https://cloud.githubusercontent.com/assets/1093738/19976825/a9cb2028-a1c7-11e6-9ee3-2eaa4e137976.gif)

The code as-is works just fine for me (see above).

But you can also try removing the `value` prop in your checkboxes.

**Comment by mikkelwf** [comment]
I've resolved it.

I put the `combineForms` like this in my `createStore`:
```
createStore({
  form: combineForms(...)
})
```

And the consequent naming of my forms in my views did not resolve to the right form in rrf (nothing was actually stored in redux).. 

So beginners error. I read the documentation again, and its not 100% clear that the naming changes when you nest combineForms in the state. But maybe i just didn't read it well enough.. :)

Anyway, thanks for the quick reply. Keep up the good work.. :)

**Comment by davidkpiano** [comment]
> So beginners error. I read the documentation again, and its not 100% clear that the naming changes when you nest combineForms in the state. But maybe i just didn't read it well enough.. :)

I'll try to make this clearer! Think of `combineForms` as expanding to an object. So in theory, you'd end up with something like:

```
{
  form: {
    foo: ...
    bar: ...
  }
}
```

And then your models would be `form.foo` and `form.bar`, respectively.

**Comment by mikkelwf** [comment]
It makes total sense when you get it. :)

I guess i just thought i had to omit the part of the path above the `combineForms`..

**Comment by davidkpiano** [comment]
> I guess i just thought i had to omit the part of the path above the combineForms..

Yes, that's right but your syntax is a bit off. `combineForms` (like `combineReducers`) returns a `reducer` function, so you want this:

```js
const store = createStore(combineForms({
  ...
}));
```
