### ISSUE TITLE
Dependency on redux-thunk. Can it be removed?

### ISSUE THREAD

**Issue by BerkeleyTrue** [davidkpiano/react-redux-form#518]
I'm in need of a replacement for redux-form and this project was looking hopeful until I saw in your codebase that you export a lot of thunks and expect the user to be using redux-thunk. That leaves out users of redux-observable/promise/saga. 

Could this project be made to be async agnostic? @davidkpiano mentioned that something was in the works.

**Comment by davidkpiano** [comment]
Yep, working on it! The latest `1.2.2` has it removed _for the most part_. I just have to make a note in the docs for all the (optional) actions that do depend on it, such as `actions.filter`, `actions.submit`, etc.

**Comment by BerkeleyTrue** [comment]
So filter and submit are still thunks?

**Comment by davidkpiano** [comment]
Yes, but they're entirely optional to use. Just helper actions.

**Comment by BerkeleyTrue** [comment]
Awesome! That should be enough to resolve this issue.

Happy Coding
