### ISSUE TITLE
Access the global form state in a custom form component

### ISSUE THREAD

**Issue by dmzkrsk** [davidkpiano/react-redux-form#523]
Currently `<Form component={...} />` doesn't accept `mapProps` like '<Control component={...} />'.

Is there a way to access global `formValue` for custom form components?

I found, that `Form`'s `children` can be a function and recieve `formValue`. Is it a recommended way to do this? If so, see also #522

**Comment by davidkpiano** [comment]
You can use the `onUpdate={(formValue) => ...}` prop on the `<Form>` element, does that help?

**Comment by davidkpiano** [comment]
Also, yes, you can pass in a function-as-children to `<Form>` to achieve the same result. See the documentation here for more information on the `onUpdate={...}` prop: http://davidkpiano.github.io/react-redux-form/docs/api/Form.html
