### ISSUE TITLE
InitialState does not appear when LocalForm is rendered for the first time or when it is rendered

### ISSUE THREAD

**Issue by bnlambert** [davidkpiano/react-redux-form#524]
Hi!
react-redux-form is a great job. I am currently having a hard time assigning my props to initialState in LocalForm.
My code looks like this

`<LocalForm
	    initialState ={this.state.patient}
	    onSubmit={this.handleSubmit}
	    model="patient"
        onUpdate={(form) => this.handleUpdate(form)}
        onChange={(values) => this.handleChange(values)}
		
      >
        <Control.text model=".firstname" />
        <Control.text model=".middlename" />
		
		<button type="submit" > Submit! </button>
      </LocalForm>
`

LocalForm is defined in a child component, which is returned when a given parameter is passed in the url. So I passed the props for the parent scope to assign it to initialState. My constructor looks like this.
`constructor(props){
		super(props);
		
		
		this.state = {
			patient: this.props.patient
		};
		......
}`

When the form displays for the first time,no initial value appears and even when i refresh the form but when I move to another child component and come back to the form component, i see the initial data showining such that I event update them with success
. please help.
Thanks

**Comment by davidkpiano** [comment]
Does the state arrive asynchronously? That is, when the component is first rendered, could `this.state.patient` be undefined (because it is waiting for an AJAX call, etc.)?

**Comment by bnlambert** [comment]
The component having the form is a child component that receives initial data through props directly from the parent component. 

`<ChildComponent patient={this.state.patient} />`
Not ajax. When I refresh the form, initial data disappears.

**Comment by bnlambert** [comment]
Could be a problem with the version I am using? I simply ran the command
`npm insta`

**Comment by davidkpiano** [comment]
Sorry, I can't replicate the issue. Make sure you have the latest version of RRF. The below minimally reproducible use case works as expected:

```js
class App extends React.Component {
  constructor() {
    super();

    this.state = { patient: { name: 'bob' } };
  }
  render() {
    return (
      <LocalForm initialState={this.state} model="patient">
        <Control.text model=".name" />
      </LocalForm>
    );
  }
}
```

Please compare your code to the above and verify that the input does in fact have `"bob"` as the initial state.
