### ISSUE TITLE
Dynamic Forms

### ISSUE THREAD

**Issue by nahushfcc** [davidkpiano/react-redux-form#525]
As far as I know If I want to model a Form I need to create a reducer for the corresponding form data right. What if I want to create forms dynamically. How do I model the forms without creating the corresponding reducer at runtime?

**Comment by davidkpiano** [comment]
1. Have a root form reducer:

```js
const store = createStore(combineReducers({
  forms: formReducer('forms', {}),
});

// alternatively...
const store = createStore(combineForms({}));
```

2. Now, all forms, dynamic or otherwise, can live under this single `forms` form reducer. So if you dynamically create:

```jsx
<Form model="forms.completelyNew">
...
</Form>
```

then the form state will be created for you under:

```js
store.getState().forms.completelyNew;
```

Or if you `connect()`, just `this.props.forms.completelyNew`, of course.

Hope that helps!

**Comment by stunaz** [comment]
@davidkpiano Nope it doesn't work.
I take your [codepen ](http://codepen.io/davidkpiano/pen/1c8e41d9f739d5d2827e4e2b38fe1a76) and created the store as `const store = createStore(combineForms({}), applyMiddleware(thunk));`

yes the values are in the states, but the following did not work:

The `radios` and the `checkboxes` doesnt work . (cant set a radio nor a checkbox)
and submitting the form return `undefined`.

![dynamic](https://cloud.githubusercontent.com/assets/1305483/20184755/c914cb94-a737-11e6-8f8e-c94721fff292.png)

**Comment by davidkpiano** [comment]
Can you post the link to your modified codepen?

**Comment by stunaz** [comment]
Can't fork a private pen

just changed the line :

```javascript
const store = createStore(combineForms({
  user: initialUserState,
}), applyMiddleware(thunk));
```
to
```javascript
const store = createStore(combineForms({}), applyMiddleware(thunk));
```

**Comment by nahushfcc** [comment]
Yeah it doesn't work. I tried both the `formReducer` as well as `combineForms`, [here's](http://codepen.io/anon/pen/qqbMLz) the code pen

**Comment by davidkpiano** [comment]
I updated my answer above: https://github.com/davidkpiano/react-redux-form/issues/525#issuecomment-259126628

Long story short, it doesn't work if you are missing a model reducer. So you can still do dynamic forms, it just needs to be based on an existing model reducer:

```js
const store = createStore(combineReducers({
  forms: formReducer('forms', {
    dynamic: {},
  }),
});

// alternatively...
const store = createStore(combineForms({ dynamic: {} }));
```

Hopefully that makes sense. **Always have at least one model reducer**.

**Comment by nahushfcc** [comment]
I used 
```
const store = createStore(combineForms({ dynamic: {} }));
```
and it worked like a charm. Thanks

**Comment by lnhrdt** [comment]
@davidkpiano is the solution you posted here still the correct way to setup react-redux-form with dynamic forms? I'm having a hard time getting it to work with 1.6.0.

I'm share @stunaz's sentiment here:
> Coming from redux-form i have a hard time to migrate to rrf especially if i have to declare each form in advance.
and I feel like I'd rather have the declaration of my form, its initial state, etc. all contained within the form component itself.

**Comment by davidkpiano** [comment]
@lnhrdt Can I see your code please? You do _not_ have to declare each form in advance - it can work dynamically.

**Comment by davidspiess** [comment]
@davidkpiano tiny nitpick in your example above. The form model path has to be `forms.dynamic.completelyNew` instead of `dynamic.completelyNew`

```jsx
<Form model="forms.dynamic.completelyNew">
...
</Form>
```

**Comment by davidspiess** [comment]
What if i need dynamic model reducers too?

**Comment by husainshabbir** [comment]
@davidkpiano I tried as per your instructions to create my store for dynamic forms like this:

```javascript
const store = createStore(combineReducers({
  forms: formReducer('forms', {
    dynamic: {},
  }),
});
```

Then, when I create my form `<Form model="dynamic.completeNew">`, I get this error:

    Error: Unable to create Form component. Could not find form for "dynamic.completelyNew" in the store.

[This pen](https://codepen.io/hwithk/pen/zzGypw) reproduces the error. Am I doing something incorrectly?

**Comment by davidkpiano** [comment]
Try this:

```js
const store = createStore(combineForms({
  dynamic: {}
});
```

Ideally, you should never need to use `formReducer` directly.

**Comment by husainshabbir** [comment]
I might be missing something obvious here. How do I do that when I have my
own reducers that I must combine using combineReducers?

**Comment by davidkpiano** [comment]
See here: http://davidkpiano.github.io/react-redux-form/docs/api/createForms.html

**Comment by husainshabbir** [comment]
Ah, thanks. I realized what my mistake was. I was using the word **forms** as the property name to hold all my dynamic forms, which was probably causing a problem. Changing the name to **myForms** did the trick.
