### ISSUE TITLE
Question about states after submitting

### ISSUE THREAD

**Issue by cyberwombat** [davidkpiano/react-redux-form#526]
I've noticed that the submit handler will only be called once if successful. If the user then submits again the handler is not called and the `submitFailed` state is set to true.  Is this intended behavior?  I am not clear on how to use states to mark my form as done. I can understand not doing a double submit but why would my form revert to `submitted: false` when the user clicks again?

After 1st submit
    
    submitted: true
    submitFailed: false

Click again (with same valid content)

    submitted: false
    submitFailed: true

**Comment by davidkpiano** [comment]
> why would my form revert to submitted: false when the user clicks again?

Is there validation on the form?

**Comment by cyberwombat** [comment]
There is but just one field.  This may be an issue with my promise. I use axios redux middleware and dispatch that. It returns a promise which I pass to the submit action to dispatch. It submits the form but perhaps only once. If I do a straight axios call it seems to work so gonna look into that further. Closing for now - sorry about that.

**Comment by cyberwombat** [comment]
I see. It's because my promise, on success, returns a data object (axios request data) as opposed to `true`. 

So I have:
````
const postUser = api.post({/* user data */})
dispatch(actions.submit('user', postUser));
````
Instead of: 
````
const postUser = api.post({/* user data */})
  // API success
  .then(() => true) // validity = true
  // API failure
  .catch((err) => err) // errors = err

dispatch(actions.submit('user', postUser));
````

So it makes a successful submit and marks form submitted as true, but only once. What is the reasoning behind requiring a boolean true as opposed to a successful resolve?

**Comment by davidkpiano** [comment]
>  What is the reasoning behind requiring a boolean true as opposed to a successful resolve?

It's initially to set validity but I feel we can get rid of that. I see no use cases for automatically setting validity after a successful promise.

**Comment by cyberwombat** [comment]
I was pondering this yesterday and I can see that it makes it easier (as things are now) to handle things like failed authentication where a successful resolve should be handled differently based on whether it was correct. So it's not a form error but an invalid one. If the boolean check gets removed how would this scenario take place?

     formCheck()
       .then(res => res.isValidLogin)
      .catch((err) => err)
