### ISSUE TITLE
Validators in nested structures are not executed after actions.load()

### ISSUE THREAD

**Issue by ckoehn** [davidkpiano/react-redux-form#528]
If I load data in `onComponentDidMount()`, the validators of the nested (`items` and `subitems`) fields are not fired afterwards. If you remove the name of an `item` or `subitem`, the form should display an error message. This only happens on nested structures and not on the toplevel `username` field. 

https://esnextb.in/?gist=4985e147f3c4d3db5c9dce8eb6a886af

**Update**
The error messages of additionally added `subitems`are shown. The _old_ ones are still invisible.

**Comment by tiagoefmoraes** [comment]
I have the same problem and found that it validates the same quantity of items in the `store`'s initial state 

In the provided sample doing the following "works", but if we load `DATA2` it breaks and doesn't validate  the second item.

```javascript
const DATA = {
  username: 'loaded',
  items: [{name: 'item 1', subitems: [{name: 'subitem 1'}, {name: 'subitem 2'}]}],
};

const store = createStore(combineForms({
  user: DATA,
}), applyMiddleware(thunk, createLogger()));

const DATA2 = {
  username: 'loaded',
  items: [{name: 'item 1', subitems: [{name: 'subitem 1.1'}, {name: 'subitem 1.2'}]},
              {name: 'item 2', subitems: [{name: 'subitem 2.1'}, {name: 'subitem 2.2'}]}],
};

```

**Comment by tiagoefmoraes** [comment]
Managed to fix this, @davidkpiano can you look and say if this is the right way to solve this?

**Comment by davidkpiano** [comment]
@tiagoefmoraes Fix looks good to me! I can refactor later. Mind making a PR?

**Comment by tiagoefmoraes** [comment]
@davidkpiano Will rebase and create PR tomorrow
