### ISSUE TITLE
model reducer documentation

### ISSUE THREAD

**Issue by greaber** [davidkpiano/react-redux-form#53]
Hi!  I am still learning about react-redux-form, but I thought I would let you know about a couple areas in the documentation that caused me a bit of confusion or that could possibly be improved.

One is that you discuss custom model reducers in the "Model Reducers" section and then again in "Using Existing Reducers".  I think it would be clearer to consolidate discussion into one place.

The other is that using a reducer to store full name seems like an anti-pattern; it is just the sort of derived data that the React docs tell us we should recompute instead of storing in component state, and the same applies to Redux.  It could be acceptable to store derived data in Redux if the computation were really expensive, but even then, unless I am misunderstanding something, I don't think you would have anything like the `GET_FULL_NAME` action; you would just have actions to set the underived data and a derived data reducer that would respond to those actions, no?

**Comment by davidkpiano** [comment]
Hey @greaber, you're absolutely correct. I'm actually in the process of rewriting (and adding a lot to) the documentation right now, and I will be separating the documentation by chapters, with "model reducers" being one of them.

Do you have any suggestions for a better example where you would want to use an existing reducer with React-Redux-Form?

**Comment by greaber** [comment]
Thanks for the lightning response.  I'm not sure about an example for the docs, but in my case I have an existing model, and I would like to provide an interface for the user to edit parts of it using forms.

**Comment by davidkpiano** [comment]
Consolidated here: https://davidkpiano.gitbooks.io/react-redux-form/content/model_reducers.html
