### ISSUE TITLE
How to toggle fields based on other fields

### ISSUE THREAD

**Issue by cyberwombat** [davidkpiano/react-redux-form#531]
Right now I use redux to toggle some fields based on the status of some radios. I dispatch my custom action from `changeAction={this.changeMethod}` in the radios. It works fine. I am wondering if there is a build in way to do this. I've noticed that the form will no rerender when `form.value.myradio` changes. Is there a way to force the render?  I tried using ` dispatch(actions.change('...', value))` but that does not cause a refresh either.

So:
````
render() {
   return (
     {  this.props.form.value.myfield === 'something' ? .... : .... }
````

**Comment by davidkpiano** [comment]
> Right now I use redux to toggle some fields based on the status of some radios. 

What do you mean by toggle? Do you mean that the radio button is toggling some other radio buttons?

If so, that's a good use-case for a custom reducer. Here's an example:

```js
import { actionTypes } from 'react-redux-form';

function toggleReducer(state, action) {
  if (action.type === actionTypes.CHANGE) {
    if (action.model === 'toggle.foo') {
      // toggle.bar and toggle.baz will have the
      // same value as toggle.foo
      return {
        ...state,
        bar: action.value,
        baz: action.value,
      };
    }
  }

  return state;
}
```

And then you can just have that be a modeled reducer:

```js
const store = createStore(combineForms({
  toggle: toggleReducer,
}), applyMiddleware(...));
```

**Comment by cyberwombat** [comment]
I'm toggling children component (a bunch of inputs) based on the value of a radio. I have a reducer working now - I will make it the actionTypes though.  I was hoping to dispatch an action that causes a from rerender in the same way that say changing pristine state does. I can access the radio value from `props.form.value.radio` so it seemed a bit silly to create another prop but I don;t know how to force the rerender. Thanks
