### ISSUE TITLE
'dispatch' is not a function 

### ISSUE THREAD

**Issue by gocamille** [davidkpiano/react-redux-form#536]
Hi @davidkpiano! I am not using `redux-thunk` but `redux-saga` on an `ImmutableJS` project and am getting this error on this line: 

`field-actions.js:270 Uncaught TypeError: dispatch is not a function(…)submit 
@ field-actions.js:270handleSubmit 
@ form-component.js:351ReactErrorUtils.invokeGuardedCallback 
@ ReactErrorUtils.js:70executeDispatch 
@ EventPluginUtils.js:89executeDispatchesInOrder
@ EventPluginUtils.js:112executeDispatchesAndRelease 
@ EventPluginHub.js:44executeDispatchesAndReleaseTopLevel 
@ EventPluginHub.js:55forEachAccumulated 
@ forEachAccumulated.js:25processEventQueue 
@ EventPluginHub.js:231runEventQueueInBatch 
@ ReactEventEmitterMixin.js:18handleTopLevel 
@ ReactEventEmitterMixin.js:29handleTopLevelImpl 
@ ReactEventListener.js:73perform 
@ Transaction.js:138batchedUpdates 
@ ReactDefaultBatchingStrategy.js:63batchedUpdates 
@ ReactUpdates.js:98dispatchEvent 
@ ReactEventListener.js:150`

We have the form wired `onSubmit` like so:

**Index.js Parent Container**

```
render() {
    const { step } = this.props;
    const somePromise = new Promise((resolve) => {
      setTimeout(() => { resolve(true); }, 5000);
    });

    switch (step) {
      case 0:
        return (<Step0 {...this.props} />);
      case 1:
        return (<Step1 {...this.props} handleSubmit={actions.submit('register', somePromise)} />);
```

**step1.js Child Container**

```
          <Form
            model="register"
            validators={{
              '': { passwordsMatch },
              name: { alphanumeric },
              email: { email },
              password: { password },
              confirmPassword: { password },
            }}
            onSubmit={props.handleSubmit}
          >
            <div className={`${styles.formFieldWrapper}`}>
              <Control
                type="text"
                model=".name"
                placeholder="Add your full name"
              />
              <Errors
                model=".name"
                messages={{
                  required: 'Required',
                  alphanumeric: 'Must only contain letters and numbers',
                }}
              />
            </div>
...
```

**Comment by davidkpiano** [comment]
Over here is the problem:

```js
actions.submit('register', somePromise)
```

The `actions.submit` is an action _thunk_ creator, and it requires `redux-thunk`. With that said, it's easy to recreate this action so that it is suitable for `redux-saga`. This is the core of the action:

```js
const submit = (model, promise) => (dispatch) => {
  dispatch(actions.setPending(model, true));

  promise.then(response => {
    dispatch(actions.setSubmitted(model, true));
  }).catch(error => {
    dispatch(actions.setSubmitFailed(model));
  });
};
```

The extra code and code related to validity is removed for clarity. Feel free to use the above as a template for handling submit logic yourself inside a saga.
