### ISSUE TITLE
Multiple submit buttons

### ISSUE THREAD

**Issue by dave-clover** [davidkpiano/react-redux-form#539]
I have a very specific case I'm having trouble with.  I have a form with two submit buttons and I need to be able to figure out which button was clicked.  Since `onSubmit` on the form doesn't pass the event through, I can't do this.  Also thought about some workarounds, but since the form doesn't have an `onSubmitFailed` prop, the workarounds don't really work.  I can go into more detail if you have questions.  Any thoughts?

**Comment by dave-clover** [comment]
Also...happy to submit a PR.  Of the two options I mentioned, do either (or both) appeal to you?  Or do you have another idea?

**Comment by davidkpiano** [comment]
The easiest way to do this right now is to add an `onClick` event handler to each of your buttons that changes the model before it is submitted:

```
<Form ... >
  <button onClick={() => dispatch(actions.change('user.clicked', 'foo'))}>
    Submit Foo
  </button>
  <button onClick={() => dispatch(actions.change('user.clicked', 'bar'))}>
    Submit Bar
  </button>
</Form>
```

Now, when your form is submitted, you can just reference the `'user.clicked'` (feel free to rename) model to see what was clicked to submit the form.

This is very similar to what you would do with vanilla JS/HTML: http://stackoverflow.com/questions/547821/two-submit-buttons-in-one-form

What did you have in mind?

**Comment by davidkpiano** [comment]
Also, I'm going to keep this up as an enhancement, because I'd like to add two new `<Control>` components:

- `<Control.button>` for `<button type="button">`
- `<Control.submit>` for `<button type="submit">`

And then you can just do the above like:
```jsx
<Form ... >
  <Control.submit model="user.clicked" value="foo">Submit Foo</Control>
  <Control.submit model="user.clicked" value="bar">Submit Bar</Control>
</Form>
```

**Comment by dave-clover** [comment]
Thanks for the response and example.  My main concern is that if the form is invalid, "foo" or "bar" will stick around in the store longer than I would like.  My comment about having an "onSubmitFailed" function was so I could clear out that field if that happens.

This flow is the thing that is bothering me:

1. User tries to submit and either:
  a. It's valid and onSubmit is called
  b. It's invalid and nothing is called.

I don't think listening for the "rrf/setSubmitFailed" action in my reducer will work because the model my form is connected to is passed in through a prop (it's a generalized form component).

`onSubmitFailed` would allow me to do this: `dispatch(actions.reset('user.clicked'))`.

Thanks again for the quick response and great library.

**Comment by davidkpiano** [comment]
Hey @dave-clover, hope you don't mind but I went ahead and added the `onSubmitFailed` prop. Here's the docs on it: http://davidkpiano.github.io/react-redux-form/docs/api/Form.html#onsubmitfailed

**Comment by dave-clover** [comment]
@davidkpiano thank you very much for adding this.  I got caught up with some other tasks before I could get back to this issue.
