### ISSUE TITLE
Issues with Field / createFieldClass and uglify2 mangling

### ISSUE THREAD

**Issue by kmudrick** [davidkpiano/react-redux-form#54]
Not sure how to give much more information than this: when using uglify2 with name mangling on (which is the default behavior) - the wrapper components that get created using Field or createFieldClass are not getting props passed through to the underlying component (so onChange never fires for instance - whether I am re-mapping onChange or not.)

It might also be caused by babel (I'm using 5.8) - honestly at this point in time, I have _no_ idea how to efficiently debug stuff like this with multiple levels of transpiling and parsing and react magic.

**Comment by davidkpiano** [comment]
By any chance do you have a link to the repo using uglify2 with createFieldClass?

**Comment by kmudrick** [comment]
Is this helpful?  I created gists with what the output looks like for field-component with mangling off and with it on.  Copy pasted from my browserify bundle output.

https://gist.github.com/kmudrick/8bff15a1089e4470429e

https://gist.github.com/kmudrick/9f6052f983e95aba1d1b

**Comment by kmudrick** [comment]
FWIW, other specifics:

browserify 9.0.4
babelify 6.4.0
gulp-uglify 1.5.3 (uses uglify-js 2.6.2)

**Comment by davidkpiano** [comment]
@kmudrick This looks related to https://github.com/davidkpiano/react-redux-form/issues/65 . The solution/workaround there is to provide a `.displayName` for the custom component.

**Comment by kmudrick** [comment]
Awesome, thanks!  I am still pretty new to react so I didn't realize that could be the issue.  I'll give the displayName thing a try.

**Comment by kmudrick** [comment]
Confirmed that dropping in a displayName on the 3 custom components I was wrapping in Field fixed this issue for me

**Comment by davidkpiano** [comment]
Excellent! :confetti_ball:
