### ISSUE TITLE
Some questions about the correct workflow

### ISSUE THREAD

**Issue by VladShcherbin** [davidkpiano/react-redux-form#540]
Hey, I saw most of the issues are now solved :)

I have a few questions about the workflow of RRF:

On initial start, we have smth like this:

```js
rrf: {
  user: {
    firstName: "",
    lastName: ""
  },
  forms: {
    user: {
      firstName: {...}
      lastName: {...},
      $form: {...}
    },
    $form: {...}
}
```

**1)** So, `rrf.user` is a model, which values are updated when the form inputs are updated. `rrf.forms.user` is the created form with this model and `rrf.forms.user.$form` object has the form state (errors, etc).

If this is correct, why aren't the values in `rrf.forms.user.$form.value` changed on field change?

<details>
  <summary>State</summary>
 
```js
rrf: {
  user: {
    firstName: "hey",
    lastName: "ho"
  },
  forms: {
    user: {
      $form: {
        value: {
          firstName: "", <-- why
          lastName: "" <-- why
        }
      }
    }
  }
}
```
</details>

---

**2)** What is the purpose of `rrf.forms.$form`, what are the values `focus`, `pending`, etc inside of it for? There is also `rrf.forms.$form.value.user.firstName` value, that is also not updated when the input is changed.

**Comment by davidkpiano** [comment]
I'll be adding this to the documentation soon (well, after the holidays)!

**Comment by VladShcherbin** [comment]
hey @davidkpiano , maybe you could drop 1-2 small sentences about, I just wanted to understand the purpose.

I am planning to fully move to RRF for quite some time, but still need a few answers.

**Comment by davidkpiano** [comment]
Sure, no problem. I'll do that today. For now, I'll answer your questions directly:

> So, `rrf.user` is a model, which values are updated when the form inputs are updated. `rrf.forms.user` is the created form with this model and `rrf.forms.user.$form` object has the form state (errors, etc).

This is correct.

> If this is correct, why aren't the values in `rrf.forms.user.$form.value` changed on field change?

They should be - I'll fix this.

> What is the purpose of `rrf.forms.$form`, what are the values `focus, pending`, etc inside of it for? 

The `forms.$form` indicates the _entire form state_, so `focus` would represent if any field in the form is focused, same with `pending`, `touched`, etc.

**Comment by VladShcherbin** [comment]
Since no one asked for this, we can probably close it.

The only question remaining for me is the 2 - What is `deep.forms.$form` for and it fields (focus, pending, etc), is it the state of all forms or just unused props?

<img width="226" alt="screen shot 2017-01-23 at 3 55 31 pm" src="https://cloud.githubusercontent.com/assets/6711845/22204805/e5b7befa-e184-11e6-87a1-20e652a1c810.png">

**Comment by davidkpiano** [comment]
> is it the state of all forms or just unused props?

They reflect the state of all fields from this form, and the form itself.

**Comment by VladShcherbin** [comment]
@davidkpiano , nah, there is no form for it.

I have only 1 form - named `login`, so I have `deep.login` as model and `deep.forms.login` as form. There I have `deep.forms.login.$form` with the form state.

What I'm asking is - `deep.forms.$form`, it's like a global `$form` for all forms, what's the state there for 🤔

**Comment by VladShcherbin** [comment]
It's even written there - `model: "deep"`, but I don't have such model 🤔
