### ISSUE TITLE
setInitial action alters model value starting in v1.2.3

### ISSUE THREAD

**Issue by TLadd** [davidkpiano/react-redux-form#546]
Both v1.2.3 and v1.2.4 have an issue where setInitial resets the model state in addition to the field state. This is not present in v1.2.2

Here is an example:
https://esnextb.in/?gist=ebf458ab31ce4849be7816057b33c60c

**Comment by davidkpiano** [comment]
What is the expected result? That the field state is not touched?

**Comment by TLadd** [comment]
The docs indicate that setInitial ought to change the field state but not the model.
