### ISSUE TITLE
Imperatively reset only validation errors on a <LocalForm> (and is this a valid requirement?)

### ISSUE THREAD

**Issue by jonathanconway** [davidkpiano/react-redux-form#547]
For the purposes of a form I'm working on, I would like to imperatively reset all validation errors on a `<LocalForm>`.

(Background: it's a single `<LocalForm>`, but it's presented as a wizard, so that one field at a time is shown and the user steps backwards and forwards between fields until they get to the end.

If they hit Submit on the first field, I want to show a validation error and make them fix it. But after they fix it and hit Submit, I want the next field to show up without any validation errors. So I aim to solve this by imperatively resetting all validation errors on Submit.)

I located a [`RESET_VALIDITY` action and reducer](https://github.com/davidkpiano/react-redux-form/blob/master/src/reducers/form-actions-reducer.js#L176) that seems to do this, but I can't seem to find a way to actually apply this to the store, as react-redux-form seems to keep its store private.

Any rough ideas how I could make this work, or if am I barking up the wrong tree?

I'm still pretty new to react-redux-form, so I just want to check if I'm missing something before I begin work on a pull-request.

**Comment by davidkpiano** [comment]
For anything beyond basic form functionality, you'll probably want to just use a normal `<Form>`. However, if you want to do custom dispatching to a `<LocalForm>`, that is still possible if you **create your own store**:

```jsx
import { createStore } from 'redux';
import { LocalForm, combineForms } from 'react-redux-form';

const localStore = createStore(combineForms({ ... }));

// then, in your LocalForm:
<LocalForm store={localStore}>
  // ...
</LocalForm>

// you can then dispatch to the localStore:
localStore.dispatch(someAction);
```

I haven't tried this yet, but it should work in theory. Can you try it out and see if it works for your use case?

**Comment by davidkpiano** [comment]
Actually, the `getDispatch` prop solves this much more nicely as of the latest version (1.4.1):

```jsx
<LocalForm
  model="user"
  getDispatch={(dispatch) => this.formDispatch = dispatch}
>
// etc.
</LocalForm>
```

**Comment by jonathanconway** [comment]
Sorry about the late reply. Thanks @davidkpiano, yes, that does solve it. Cheers!
