### ISSUE TITLE
Touching a field doesn't update form's touched prop

### ISSUE THREAD

**Issue by bgriffith** [davidkpiano/react-redux-form#549]
Hi @davidkpiano - Great to see RRF come on so far! Doing a great job :+1: 

Currently when I touch a field with a form, while the field's `touched` property is updated to `true`, the `touched` property of the form remains `false` - Could you please give me some clarification if this is a bug or intended? 

If it's intended - what's the recommended approach to updating the overall form prop? I did look at the docs but didn't find my answer!

Using `v1.2.4`

This is from the standard [gist in the readme](https://esnextb.in/?gist=b31277251f5c24df9b13b2cc95abc00c)
![screen shot 2016-12-01 at 13 02 27](https://cloud.githubusercontent.com/assets/2854338/20794897/7a588bfe-b7c6-11e6-9e4a-23b29348fd8a.png)

**Comment by davidkpiano** [comment]
Thanks, @bgriffith! This has been fixed and will appear in the next patch today.

**Comment by bgriffith** [comment]
Brill! Appreciate the quick response!
