### ISSUE TITLE
Can the Form component use Field validation?

### ISSUE THREAD

**Issue by SomethingSexy** [davidkpiano/react-redux-form#55]
I couldn't find this in the documentation but if I am using the `<Form>` component can I also use `<Field>` validators or do I have to put all of the validations on the `<Form> `?  Looking at the code it looks like it just pulls it off the `<Form>.`

**Comment by davidkpiano** [comment]
Yes, the `<Form>` component can use `<Field>` validation.

Why would you want both? Simple: you might want validation to occur at different times.

- For `<Form>`, validation by default occurs whenever a field changes and on submit.
- For `<Field>`, validation by default occurs on change, but can be tweaked so that it only validates on blur, e.g. `<Field model="foo.bar" validateOn="blur">`.
- The `<Field>` component can also call asynchronous validation at any time (on `blur` by default).

Hope that answers your question!

**Comment by SomethingSexy** [comment]
Thanks! I noticed when I submit against the <Form> it doesn't seem to run any validation that is set on the <Field> is that correct?

**Comment by davidkpiano** [comment]
That's correct. I'm going to clarify this in the updated docs, but the cleanest pattern is to put any validation you want on submit in the `<Form validators={{...}}>` prop.

```js
import { Form } from 'react-redux-form';

function required(val) {
  return val && val.length;
}

// in render() return block:
<Form model="user"
  validators={{
    email: required,
    firstName: required,
    lastName: required
  }}
  onSubmit={ ... }>
  // etc.
```

**Comment by SomethingSexy** [comment]
That makes sense with what I am seeing, thanks! I have one other question then with regards to using the `<Form>` like you described.  If I have an array of data attached to that form, how would I go about adding that validation on the `<Form>` ?

**Comment by davidkpiano** [comment]
Okay, let's say you have a `foo` model that looks like this (with a model reducer, of course):

```js
const foo = {
  numbers: [1, 2, "blah", 4, 5]
};
```

If you want to validate that all the items in `foo.numbers` are a number, you can add a validator such as this one:

```js
import every from 'lodash/every';

function isNumber(num) {
  return Number.isInteger(num);
}

// in render():
<Form model="foo"
  validators={{
    numbers: (val) => every(val, isNumber)
  }}>
```

Each validator in `<Form validators=...>` will get the _exact value_ of whatever model you're pointing to. From there, it's up to you to validate it however you'd like.

**Comment by SomethingSexy** [comment]
Thanks, that should work.  Can you go deeper than that as well within numbers if necessary? If numbers was an array of objects?

**Comment by davidkpiano** [comment]
Yep! RRF makes no assumptions about your model data structure, so you can go as deep as you want with the path you specify.

```js
// You can do this!
<Field model="user.phones[3].type.foo.bar.baz">
  ...
</Field>
```

**Comment by davidkpiano** [comment]
Also, here's helpful documentation on the `<Form>` component that answers your question as well: https://davidkpiano.gitbooks.io/react-redux-form/content/form_component.html

**Comment by SomethingSexy** [comment]
Ya what I was asking (sorry if I didn't make that clear) was doing something like this 

`<Field model="user.phones[3].type.foo.bar.baz">
  ...
</Field>`

but on the `<Form>` instead of the `<Field>`.  I don't see that in the Form documentation.  My only thought is that I would have to do a Form level validation and then process? Unless the validation on the form can handle 

`<Form model="foo"
  validators={{
    numbers.type: (val) => isRequired
  }}>`
or something to that effect?

**Comment by davidkpiano** [comment]
Oh, sorry. Yes, it can. You can do this:

```js
<Form model="foo"
  validators={{
    'numbers.type': isRequired
  }}>
```

Notice how the path to the model inside `foo` is in quotes. All RRF is doing behind the scenes is concatenating the form's `model` and each validator key with a period; e.g. `foo.numbers.type`. That's how it knows where to look.

**Comment by SomethingSexy** [comment]
Awesome, thanks for your time! I will try this out tonight.
