### ISSUE TITLE
Can peer-dep on redux-thunk be removed?

### ISSUE THREAD

**Issue by BerkeleyTrue** [davidkpiano/react-redux-form#550]
> npm WARN react-redux-form@1.2.5 requires a peer of redux-thunk@^2.0.1 but none was installed.

Moving from redux-form to redux-react-form on a project that uses epics instead of thunks.

Doing a quick search doesn't show any imports of redux-thunks outside of the examples directory.

Is it possible to remove this dependency?

**Comment by davidkpiano** [comment]
Almost! I'm doing quick tests today and tomorrow and removing it internally, and then I'll remove the peer dependency when it's 100% ready to be removed. Stay tuned!

**Comment by BerkeleyTrue** [comment]
@davidkpiano Thanks! I'm looking forward to refactoring out redux-form.
