### ISSUE TITLE
Control.text not setting input type

### ISSUE THREAD

**Issue by sl33kr** [davidkpiano/react-redux-form#551]
Hi,
Just started using this as an alternative to redux-form as we like the seperation between form state and model state.

We have come across an issue though, it would see that Control.text isn't setting the correct input type.

Don't know if this is deliberate or a bug?

https://github.com/davidkpiano/react-redux-form/blob/master/src/components/control-component.js#L633

**Comment by sl33kr** [comment]
Thanks David!

This was messing with some styling coming from an external library we use.

**Comment by davidkpiano** [comment]
You're welcome! This will go out tomorrow. If you need it today, you can add it manually:

```
<Control.text
  controlProps={{type: 'text'}}
  model="..."
  // etc.
/>
```
