### ISSUE TITLE
actions.remove issue in v1.1.0+

### ISSUE THREAD

**Issue by msteward** [davidkpiano/react-redux-form#553]
React Redux Form version: 1.3.0
Lodash Version: 4.17.2

## Steps to reproduce:
1. Create repeating form element and add a few instances (see screenshot below for sample form state structure following this) using `actions.push('modelName', initialModelState)`
<img width="561" alt="screen shot 2016-12-02 at 08 56 41" src="https://cloud.githubusercontent.com/assets/685691/20842869/e8d5f204-b86d-11e6-9a50-5263e6f213c2.png">

2. Remove one of the items using `actions.remove('modelName', index)` (http://davidkpiano.github.io/react-redux-form/docs/api/actions.html#actions-remove)
3. Try to remove a second item in the array using the same `actions.remove` method.

## Expected Result:
The items are removed as expected.

## Actual Result:
The first item is removed without issue. Subsequent attempts to remove items result in the following error:
<img width="714" alt="screen shot 2016-12-02 at 09 00 43" src="https://cloud.githubusercontent.com/assets/685691/20842859/dcff3134-b86d-11e6-9800-acaf3f485305.png">

## Further Info
This breakage for me was introduced in v1.1.0. v1.0.15 does not exhibit this error.
The problems appears to be introduced in line 37-66 of `src/reducers/form/change-action-reducer.js`

On the first remove that works the value of `field` on line 38 is an object with the `$form` attribute:
<img width="414" alt="screen shot 2016-12-02 at 09 07 18" src="https://cloud.githubusercontent.com/assets/685691/20843141/0b068e14-b86f-11e6-957e-d9b1da75fb57.png">

On the second the remove the value is a basic array:
<img width="175" alt="screen shot 2016-12-02 at 09 08 21" src="https://cloud.githubusercontent.com/assets/685691/20843164/1c8dfa78-b86f-11e6-8cab-ca9248ce442a.png">

Nothing else had been done to the form state in between the 2 removes and there are no custom reducers involved.

**Comment by davidkpiano** [comment]
Really excellent issue description, thanks so much! Looking into this now.
