### ISSUE TITLE
Uncaught error on form submit when submitted by return key on a custom changed field

### ISSUE THREAD

**Issue by hermanfenderson** [davidkpiano/react-redux-form#556]
[EDIT... the problem is when submitting by return key on a custom changed field]

I am surely missing something but when I submit a form when validation is failed I get this error: 
"Uncaught Error: Actions must be plain objects. Use custom middleware for async actions."

The form is not submitted (which is the required behaviour....) but I don't know how to handle that error...

**Comment by hermanfenderson** [comment]
Maybe I should just RTFM a bit more...

**Comment by davidkpiano** [comment]
Can I see the failing code? At the very least, I'd like to make error messages clear :)

**Comment by hermanfenderson** [comment]
Here is the relevant part of the code...
If I submit without validation errors... I can see the submit working
If I submit with validation errors... the submit is not triggered but I get that error...

// formRigaBolla.js (a container)
class FormRigaBolla extends React.Component {
  
updatePrice = (model,value) => {
   this.props.actionsRigaBolla.updatePriceFromDiscount(model,value,this.props.formRigaBolla);
}

render() {
    const { formRigaBolla} = this.props;
     return(
           <Form model="form2.rigaBolla"  className="form-horizontal" onSubmit={v => console.log(v)}>

<div className="form-group">
           <Col sm={2} >
             <FormGroup controlId="prezzoListino" validationState={formRigaBolla.prezzoListino.valid ? null : "error"}>
                   <ControlLabel>Listino: </ControlLabel>
                    <Control.text model=".prezzoListino" component={FormControl} changeAction={this.updatePrice}/>
                    <HelpBlock>
                    <Errors
                         model=".prezzoListino"
                         messages={{
                            isRequired: 'Please provide an email address.',
                            isEmail: 'Please provide an email address.',
                        }}
                    />
                    </HelpBlock>
             </FormGroup>     
           </Col>  
          </div>
          

//And an action calling a modeled reducer here: 
//actions/rigaBolla.js

export function updatePriceFromDiscount(model, value, formRigaBolla) 
{ 
  if (isPercentage(value))
  {
  var sconto1 = formRigaBolla.sconto1.value;
  var sconto2 = formRigaBolla.sconto2.value;
  var sconto3 = formRigaBolla.sconto3.value;
  var prezzoListino = formRigaBolla.prezzoListino.value;
   //Qui devo gestirmi quale e' il campo in ingresso...
  var changedField = model.split('.')[2];
  switch (changedField)
      {
      case 'sconto1' : sconto1 = value; break;
      case 'sconto2' : sconto2 = value; break;
      case 'sconto3' : sconto3 = value; break;
      case 'prezzoListino' : prezzoListino = value; break;  
      }      
  
  return (dispatch) => {
    //Devo cambiare leggermente qui per non aggiornare il prezzo di listino quando sarà chiamato da un libro vero
    dispatch(actions.setValidity(model, {isPercentage: true}));

    dispatch(actions.change(model, value));
    dispatch(actions.change(formRigaBolla.prezzoUnitario.model, discountPrice(prezzoListino, sconto1, sconto2, sconto3)));
   
  };
  }
  else 
  { 
  return (dispatch) => { 
    dispatch(actions.setValidity(model, {isPercentage: false}));
    dispatch(actions.change(model, value));  
    } 
  }
}

**Comment by hermanfenderson** [comment]
This is the full console output of the error BTW

Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.
    at Object.performAction (<anonymous>:1:24263)
    at a (<anonymous>:1:18806)
    at dispatch (<anonymous>:1:22133)
    at Object.eval [as dispatch] (webpack:///./~/redux-thunk/lib/index.js?:14:16)
    at Control.handleKeyPress (webpack:///./~/react-redux-form/lib/components/control-component.js?:484:22)
    at Object.ReactErrorUtils.invokeGuardedCallback (webpack:///./~/react-dom/lib/ReactErrorUtils.js?:70:16)
    at executeDispatch (webpack:///./~/react-dom/lib/EventPluginUtils.js?:85:21)
    at Object.executeDispatchesInOrder (webpack:///./~/react-dom/lib/EventPluginUtils.js?:108:5)
    at executeDispatchesAndRelease (webpack:///./~/react-dom/lib/EventPluginHub.js?:43:22)
    at executeDispatchesAndReleaseTopLevel (webpack:///./~/react-dom/lib/EventPluginHub.js?:54:10)

**Comment by hermanfenderson** [comment]
I pushed in github the latest version of my code: 

https://github.com/hermanfenderson/BrucaBook

The relevant files are: actions/brucaBook.js and containers/FormRigaBolla2.js

**Comment by davidkpiano** [comment]
Can I see the code for the custom changed field/control?

**Comment by hermanfenderson** [comment]
//This action: but if I keep only a one liner with a change action I will get that error as well...

export function updatePriceFromDiscount(model, value, formRigaBolla) 
{ 
  if (isPercentage(value))
  {
  var sconto1 = formRigaBolla.sconto1.value;
  var sconto2 = formRigaBolla.sconto2.value;
  var sconto3 = formRigaBolla.sconto3.value;
  var prezzoListino = formRigaBolla.prezzoListino.value;
   //Qui devo gestirmi quale e' il campo in ingresso...
  var changedField = model.split('.')[2];
  switch (changedField)
      {
      case 'sconto1' : sconto1 = value; break;
      case 'sconto2' : sconto2 = value; break;
      case 'sconto3' : sconto3 = value; break;
      case 'prezzoListino' : prezzoListino = value; break;  
      }      
  
  return (dispatch) => {
    //Devo cambiare leggermente qui per non aggiornare il prezzo di listino quando sarà chiamato da un libro vero
    dispatch(actions.setValidity(model, {isPercentage: true}));

    dispatch(actions.change(model, value));
    dispatch(actions.change(formRigaBolla.prezzoUnitario.model, discountPrice(prezzoListino, sconto1, sconto2, sconto3)));
   
  };
  }
  else 
  { 
  return (dispatch) => { 
    dispatch(actions.setValidity(model, {isPercentage: false}));
    dispatch(actions.change(model, value));  
    } 
  }
}

**Comment by hermanfenderson** [comment]
I've found the problem. It was in my brain!!! 
Didn't wrap the function in a dispatch block... 

Now it works perfectly. I am closing the issue.
