### ISSUE TITLE
[PROPOSAL] Form state shape

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/react-redux-form#56]
It seems that grabbing a field from the form state is a bit tedious, especially if you have to do something like `userForm.fields['foo.bar.baz'].pristine`, etc.

So, every field, regardless of how deep it is, needs to make these fields available:

```js
const initialFieldState = {
  blur: true,
  dirty: false,
  focus: false,
  pending: false,
  pristine: true,
  submitted: false,
  touched: false,
  untouched: true,
  valid: true,
  validating: false,
  viewValue: null,
  validity: {},
  errors: {},
};
```

And the current shape of the form state is this:

```js
const formShape = {
  ...initialFieldState,
  fields: {
    'foo': { ...initialFieldState },
    'foo.bar.baz': { ...initialFieldState },
  }
}
// ...etc.
```

**Proposal(s)**

Let's find an easier way to both maintain the shape of the original model shape, _and_ easily grab the relevant form/field states for each field (and form). Here's an initial suggestion, taking cues from how Angular does its forms:

```js
formShape = {
  foo: {
    bar: { ... }
    $field: { ...initialFieldState }
  },
  $field: { ...initialFieldState }
}
```

So that fields can be accessed as if it were the original model, with the special `$field` key containing the entire state of the field, like `userForm.foo.bar.$field.errors`.

Any other suggestions? What is easiest for everyone?

**Comment by chrisblossom** [comment]
+1. A flatter state shape would be a lot cleaner to work with. It would make accessing the whole form's state just as easy as it would be accessing each field. I would vote for a leading _ as it seems more JS-like, but $ works just as well.

This change will also make it consistent with the form itself.

``` javascript
const { form, formShape } = this.props;

console.log(form.foo); // value

console.log(formShape.fields.foo); // field state
// vs
console.log(formShape.foo); // field state
```

**Comment by greaber** [comment]
+1. I have a slight preference for $.

**Comment by chrisblossom** [comment]
I am good with $. I still think this is a good idea to move forward on. @davidkpiano what are your current thoughts?

**Comment by mdgbayly** [comment]
Still very new to react-redux-form so not sure I fully appreciate the issues being discussed here.
Is this discussion concerned with how to represent nested fields properties in the form state object?

How do you envisage handling arrays in this proposed approach?

I think this is how they are currently represented?
```
formShape: {
  ...initialState
  fields: {
    foo: {...initialState},
    foo.bar: {...initialState},
    phones: {...initialState},
    phones.0: {...initialState},
    phones.1: {...initialState}
  }
}
```
This proposal is talking about changing to something more structured?
```
formShape = {
  $field: { ...initialFieldState  },
  foo: {
    bar: { $field: {...initialFieldState  } },
    $field: { ...initialFieldState }
  },
  phones: [
    { $field: {...} },
    { $field: {...} },
  ]
  // where does phones $field go? A property of the phones array object?
  // OR
  phones: {
    0: { $field: {...} },
    1: { $field: {...} },
    $field: {...}
  }
}
```

Am I talking about something different?

**Comment by chrisblossom** [comment]
Looking at your deep-field example, it should currently look something like this (I think):
```js
const base = {
  /* base state */
  fields: {
    foo: {
      /* base.foo state */
      fields: {
        bar: { /* base.foo.bar state */ },
      },
    },
    phones: {
      /* base.phones state */
      fields: {
        0: { /* base.phones.0 state */ },
        1: { /* base.phones.1 state */ },
      },
    },
  },
};

const fooState = base.fields.foo;
const barState = base.fields.foo.fields.bar;
```

The proposal would make it:
```js
const base = {
  $field: { /* base state */ },
  foo: {
    $field: { /* base.foo state */ },
    bar: { /* base.foo.bar state */ },
  },
  phones: {
    $field: { /* base.phones state */ },
    0: { /* base.phones.0 state */ },
    1: { /* base.phones.1 state */ },
  },
};

const fooState = base.foo.$fields;
const barState = base.foo.bar;
```

**Comment by mdgbayly** [comment]
OK - not sure if I'm talking about the same thing but I thought currently fields were represented in a completely flat structure?

![image](https://cloud.githubusercontent.com/assets/493938/13996592/bc90ea7c-f0eb-11e5-93f0-2cbe24ea811e.png)

But I like your proposal, although it does make the syntax for accessing state and form state different?

Current:
```
console.log(info.phones[1]); // value

console.log(infoForm.fields['phones']); // array field state
console.log(infoForm.fields['phones.1']); // item field state
```

Proposed?:
```
console.log(info.phones[1]); // value

console.log(infoForm.phones.$fields); // array field state
console.log(infoForm.phones.1.$fields); // item field state
```
OR
```
console.log(info.phones[1]); // value

console.log(infoForm.phones.$fields); // array field state
console.log(infoForm.phones[1].$fields); // item field state
```

I was a little confused by the current difference in syntax for representing arrays in models (bracket notation) and arrays in fields (dot notation)? But maybe there is a good reason for that?

**Comment by davidkpiano** [comment]
> I was a little confused by the current difference in syntax for representing arrays in models (bracket notation) and arrays in fields (dot notation)? But maybe there is a good reason for that?

Yeah, that's a point of confusion -- it's because you might have an object with a key with spaces and/or dots, so there needs to be bracket as well as dot notation. This proposal somehow tries to resolve that.

Also, I was thinking of an alternative syntax that minimally abstracts the `.$field` accessor:

```js
import { field } from 'react-redux-form';

// ...
let { userForm } = this.props;

field(userForm.contacts[1].phone).valid ? 'Good job' : 'Invalid'
```

where the `field(fieldObject)` function grabs the magic `$field` property from it, so that you don't have to make the model stringly typed. The only difference between this and the existing approach is that it won't be a flat structure for the form shape; it'll be a structure that is congruent to the model shape.

**Comment by chrisblossom** [comment]
@davidkpiano Are you describing a helper method for the proposed changes? Maybe I am just misunderstanding what is going on with these arrays, but it looks to me with your example:

```js
field(userForm.contacts[1].phone).valid === userForm.contacts[1].phone.valid

field(userForm.contacts[1]).valid === userForm.contacts[1].$field.valid
```

**Comment by davidkpiano** [comment]
Yes @chrisblossom, with one fix:

```diff
- field(userForm.contacts[1].phone).valid === userForm.contacts[1].phone.valid
+ field(userForm.contacts[1].phone).valid === userForm.contacts[1].phone.$field.valid

field(userForm.contacts[1]).valid === userForm.contacts[1].$field.valid
```

Also, `field` would have the same behavior as `getField` in that it returns an initial field state if the field does not exist. _Maybe._

**Comment by chrisblossom** [comment]
Is this what the userForm object would look like?

```js
const userForm = {
  contacts: [
    { /* contacts[0] stuff */ },
    {
      phone: {
        $field: { valid: true, /* reset of field state */ },
        number: { /* number state */ },
        otherKey: { /* otherKey state */ },
      },
    },
  ],
};
```

**Comment by mdgbayly** [comment]
That matches my interpretation.
Just make sure we don't lose the ability to have field state on arrays.
```
field(userForm.contacts).valid === userForm.contacts.$field.valid
```

The ability to have field state on arrays was one of the reasons why I switched from redux-form.

**Comment by davidkpiano** [comment]
Right, with the way RRF works, field state can be on any part of the state.

**Comment by davidkpiano** [comment]
Closing this - I think it's best if we keep the current form shape for now.
