### ISSUE TITLE
actions.reset sets model value to undefined

### ISSUE THREAD

**Issue by jameshy** [davidkpiano/react-redux-form#561]
When I have a model like this:
```javascript
{
    user: {
        anArray: []
    }
}
```
Calling actions.reset('user') multiple times results in anArray to become undefined.

Here is a gist that shows the problem (1.3.2):
https://esnextb.in/?gist=774e09eda300aa56313d2718790e8334

The same gist without the problem (1.0.6)
https://esnextb.in/?gist=df83817a62cf98bb22dcc6bb7473a498

Clicking 'Reset Form' multiple times will cause the model array to become undefined.

**Comment by davidkpiano** [comment]
Does this also occur for you in 1.4.0 by any chance?

**Comment by lasergoat** [comment]
@davidkpiano this is 90% for sure the same issue I'm having.

**Comment by agustingp** [comment]
@davidkpiano I am using version 1.14.1 and I am having the same issue @lasergoat  had: I have store.sites[] and when `dispatch(actions.reset(sites[0]))` the key is updated in the model with undefined value.

**Comment by davidkpiano** [comment]
@agustingp That should be expected behavior - consider a non-empty array with more than one element. Choosing to reset a single value should result in, e.g., `[undefined, 1, 2, 3, 4]`.

**Comment by agustingp** [comment]
@davidkpiano thank you for answering! So, how can I do to reset (setting its initial value) the model of an object stored inside the array?

**Comment by davidkpiano** [comment]
If the array has dynamically loaded values, with `actions.load('model.array[0]', 'something')`, it should naturally reset to that `'something'` as the initial value. If it doesn't, please open a separate ticket and I'll look at it.
