### ISSUE TITLE
Typescript ControlProps UpdateOn/ValidateOn Fixes

### ISSUE THREAD

**Issue by sl33kr** [davidkpiano/react-redux-form#564]
Have just noticed that Typescript ControlProps doesn't allow an array to be passed to UpdateOn or ValidateOn.

I have just submitted pull request #563 with a potential fix for this.

Sorry if something is wrong or it isn't done correctly, first pull request.

**Comment by davidkpiano** [comment]
Awesome, thanks! Fixed by your PR, #563. Looks good to me 👍
