### ISSUE TITLE
Select dynamically renders child component

### ISSUE THREAD

**Issue by OrbX** [davidkpiano/react-redux-form#566]
Hello i'm learning react/redux and redux form.

I would like to create a container (selector) which dynamically renders diffenrents components (piece of form) dependent of the option selected.
But I don't know how to do this, with action/reducer or onChange ... 
Could you help me ?

**Comment by davidkpiano** [comment]
Sure, you can do it like this:

```jsx
const firstOptions = ['foo', 'bar', 'baz'];
const secondOptions = ['red', 'green', 'blue'];
const showColors = true;

// ...
const options = showColors ? secondOption : firstOption;

// then, in your render() method:
<Control.select model="user.something">
  {options.map(value =>
    <option value={value} key={value}>{value}</option>
  )}
</Control.select>
```

Just as you would dynamically render children in vanilla React.
