### ISSUE TITLE
How to reset validity after setting validity in async-action

### ISSUE THREAD

**Issue by toadle** [davidkpiano/react-redux-form#567]
Hey there, 

I got one little problem with using `setValidity`. I know that the documentation suggests to do validation asyncronously like any other validation. I tought I might even validate when the data gets send to the server and display those errors, when something problematic occurs: 

```
export function createNewUser(newUser) {
  return (dispatch) => {
    dispatch(actions.setPending("newUser", true));
    return jsonApi.create('user', newUser)
      .then((response) => {
               ...
      })
      .catch((err) => {
        dispatch(actions.setFieldsValidity('newUser', err));
        dispatch(actions.setPending("newUser", false));
               ...
      });
  };
}
```

Now my problem is: When I do this I can't resubmit the form unless I completely clear the field that was causing the error. 

e.g. if I reuse and email-address on a user and I get `{ email: {taken: false} }` in the `err`-response. 
I have to completely clear the email-field before RRF lets my resubmit the form. 

What am I doing wrong?

**Comment by davidkpiano** [comment]
You can programmatically dispatch `actions.resetValidity('newUser')` at the right time.

I'm working on an enhancement to distinguish between pre-submit and post-submit validity, which should resolve this issue.

**Comment by davidkpiano** [comment]
@toadle I fixed the issue - now the `<Form>` component will only check **sync** validity when determining whether it should submit or not. The existing spec is followed, so this is not a breaking change.

In retrospect, this makes sense; suppose you have a form that, when initially submitted, returns an error such as "You've submitted too fast. Please try again in 30 seconds." Ideally, you shouldn't need to change anything in the form to be able to submit it again. In other words, we shouldn't assume that an API endpoint for submitting a form is idempotent - we see often that this is _not_ the case.

-----

Now, in order for this to work with _your_ specific use case, please pass `{async: true}` as an option into `setFieldsValidity` - that's the only way RRF will know that the validity is from an async operation:

```js
      .catch((err) => {
        dispatch(actions.setFieldsValidity('newUser', err, {async: true}));
        dispatch(actions.setPending("newUser", false));
               ...
      });
```

This will automatically be done for you when using action thunk creators such as `actions.asyncSetValidity` or `actions.asyncSetErrors`.

**Comment by toadle** [comment]
Hey there! Thanks for tackling this. 
I wanted to try it, but couldn't find a way to install the latest version.

Tried `npm install davidkpiano/react-redux-form --save` but this would result in `node` complaining that it can not find the `react-redux-form` module. 

Installing with `npm install react-redux-form@latest --save` will not give me the latest code currently, right?

**Comment by toadle** [comment]
BTW: I tried your above suggestion by adding this: 
```
<Form className="l-fullwidth" model="newUser" onChange={this.resetValidity} onSubmit={this.props.createNewUserAction}>
```
where
```
  resetValidity() {
    console.log('resetValidity');
    actions.resetValidity('newUser');
  }
```

But it still wouldn't resubmit the form. 

Here is how Action flow looks like when first entering an already token user-email then changing it to one that should work. Then `setSubmitFailed` at the end looks strange to me. After that I will not submit anything - until you reload the page.

```
 action @ 10:57:14.472 rrf/setPending
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "rrf/setPending", model: "newUser", pending: true}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
:3000/api/v1/users:1 POST http://localhost:3000/api/v1/users 422 (Unprocessable Entity)
minilog.js:17 devour  Object {data: Object, status: 422, statusText: "Unprocessable Entity", headers: Object, config: Object…}
logger.write @ minilog.js:17
onItem @ transform.js:31
emit @ index.js:23
Filter.write @ filter.js:52
onItem @ transform.js:31
emit @ index.js:23
Transform.write @ transform.js:15
o.error @ minilog.js:12
(anonymous) @ index.js:328
tryCatch @ es6-promise.js:410
invokeCallback @ es6-promise.js:425
publish @ es6-promise.js:393
publishRejection @ es6-promise.js:335
flush @ es6-promise.js:121
core.js:99  action @ 10:57:14.506 rrf/setFieldsValidity
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "rrf/setFieldsValidity", model: "newUser", fieldsValidity: Object, options: Object}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:99  action @ 10:57:14.520 rrf/setPending
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "rrf/setPending", model: "newUser", pending: false}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:99  action @ 10:57:14.530 CREATE_NEW_USER_REJECTED
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "CREATE_NEW_USER_REJECTED", payload: Object}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:99  action @ 10:57:17.522 rrf/focus
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "rrf/focus", model: "newUser.email", value: undefined, silent: true}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:99  action @ 10:57:18.334 rrf/change
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "rrf/change", model: "newUser.email", value: "tim.adler@hansventures.com", silent: false, multi: false…}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:99  action @ 10:57:18.345 rrf/clearIntents
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "rrf/clearIntents", model: "newUser.email", intents: Object, options: Object}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:99  action @ 10:57:18.349 rrf/clearIntents
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "rrf/clearIntents", model: "newUser.email", intents: Object, options: Object}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
presenter.js:13 resetValidity
core.js:99  action @ 10:57:19.478 rrf/blur
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "rrf/blur", model: "newUser.email"}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:99  action @ 10:57:19.567 rrf/batch
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "rrf/batch", model: "newUser", actions: Array[2]}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:99  action @ 10:57:19.574 rrf/clearIntents
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "rrf/clearIntents", model: "newUser", intents: Object, options: Object}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:99  action @ 10:57:19.577 rrf/setSubmitFailed
core.js:111  prev state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
core.js:115  action Object {type: "rrf/setSubmitFailed", model: "newUser", submitFailed: true}
core.js:123  next state Object {routing: Object, activeMenuItem: "leads", patientList: Object, users: Object, newLead: Object…}
```

**Comment by davidkpiano** [comment]
@toadle It's not released yet 😅 will be today, though.

**Comment by peterox** [comment]
This is fantastic as this is exactly the problem I have just hit. I think this should be added to the documentation.

**Comment by davidkpiano** [comment]
Will do, @peterox !

**Comment by toadle** [comment]
Hey guys!

Sorry, I only came back to testing this just now. Seems to be broken at least for me. 
Here is what I'm working with: A simple login form that checks the current auth-token:

```
    dispatch(actions.setPending("authentication.token", true));
    return jsonApi.find('authentication', authentication.token, {include: 'user', 'authToken': authentication.token})
      .then((response) => {
        dispatch(loginSuccessful(response));
        dispatch(actions.setPending("authentication.token", false));
      })
      .catch((err) => {
        dispatch(actions.setValidity("authentication.token", { valid: false }));
        dispatch(loginFailed(err));
        dispatch(actions.setPending("authentication.token", false));
      });
```

Now without the `{async: true}` this works quite fine. Having the problem that after an initial "failure" the form will not resubmit. As described. 

Now changing this to `dispatch(actions.setValidity("authentication.token", { valid: false }, {async: true}));` causes mayhem:

**Before**
https://www.dropbox.com/s/xv4bty6ufy1408h/before-async.gif?dl=0

**After**
https://www.dropbox.com/s/u9qq74tya9ckkqa/after-async.gif?dl=0

RRF somehow ends in a very long loop of changing the validity. Somehow it is not endless. 


Here is the `<Form>` btw.

```
  <Form className="large-inputs" model="authentication" onSubmit={this.props.doLogin}>
    <TextField model="authentication.token" label="Token" required="required" messages={{valid: "Token ist ungültig"}}/>
    <Button color="info" size="lg">Dive In</Button>
  </Form>
```

Am I doing this wrong?

**Comment by davidkpiano** [comment]
@toadle Could you post a fully reproducible code example? There is a CodePen template in the README.

**Comment by toadle** [comment]
@davidkpiano Here you go:
http://codepen.io/toadle/pen/qrjVZq

**Comment by toadle** [comment]
@davidkpiano I checked a second example in my app, using `{async: true}`. In that case it is working. So I suppose I wired something incorrectly in my above example. Can't really tell what. Glad for any advice!

**Comment by davidkpiano** [comment]
@toadle So is it working for you now?

**Comment by toadle** [comment]
@davidkpiano Thanks for getting back! 
Mostly yes. Except for the above example, which still produces an endless barrage of `setValidity`-actions. I'd just like to know why. I'm still suspecting that I'm doing something wrong in the above example.

**Comment by davidkpiano** [comment]
Ah, that looks like a bug. Can you file a separate issue for that? @toadle

**Comment by toadle** [comment]
Done! https://github.com/davidkpiano/react-redux-form/issues/706
