### ISSUE TITLE
How to validate across model fields?

### ISSUE THREAD

**Issue by mgutz** [davidkpiano/react-redux-form#568]
I have a model like this

```
{ strategy: "dollars", amount: 1234 } // strategy can be  dollars or percentage
```

It seems like validation only returns the value for the single field. How do you access the entire model within the validation function? Need to know the value of strategy in amount validation function:

```
(val, form) => form.strategy === "percentage" ? (val > 0 && val <= 100) : (val > 0)
```

**Comment by mgutz** [comment]
Dupe of #545

**Comment by davidkpiano** [comment]
I also added a [Quick Reference](http://davidkpiano.github.io/react-redux-form/docs/guides/validation.html#quick-reference) to the validation docs to better find out how to do this. And it's in the FAQs 😉
