### ISSUE TITLE
error validators for validateErrors action passes undefined parameter

### ISSUE THREAD

**Issue by nickzarate** [davidkpiano/react-redux-form#57]
Having an issue with the new actions.validateErrors(). Any time errorValidators are used, the parameter is logged as undefined, when it should reflect the current value of the user model reducer. For instance:
```
// somewhere with dispatch()
dispatch(actions.validateErrors('user.email', (val) => {
  console.log(val) // undefined
}))
dispatch(actions.validateErrors('user.email', {
  required: (val) => { console.log(val) } // undefined
}))
```

**Comment by davidkpiano** [comment]
Can you post a full code example?

**Comment by nickzarate** [comment]
My code is separated into different files, I hope its readable. As of now, everything seems to be working as it is supposed to, even with validateErrors, except that the value passed in to the error validator is undefined.

```
// MyComponent.jsx

import React from 'react'
import { Form, createFieldClass, controls } from 'react-redux-form'
import { Input } from 'react-bootstrap'
import { handleSurveySubmit } from 'actions/survey'

const InputField = createFieldClass ({
  'Input': controls.text
})

export default class MyComponent extends React.Component {
  render() {
    <Form onSubmit={ () => this.props.actions.handleSurveySubmit() }>
      <InputField model="survey.isStudent">
          <label>{ 'Are you currently a student?' }</label>
          <Input type="radio" value="Yes" label="Yes" />
          <Input type="radio" value="No" label="No" />
        </InputField>
      <button type="submit">{ 'Continue' }</button>
    </Form>
  }
}

...

// actions/survey.js
import { actions } from 'react-redux-form'

export function handleSurveySubmit() {
  return (dispatch) => {
    const { forms: { surveyForm } } = getState()
    dispatch(actions.validateErrors('survey.isStudent', {
      required: (val) => { console.log(val) } // undefined
    }))

    if (surveyForm.valid) {
      // do something
    }
  }
}

...

// reducers/forms.js

import { modelReducer, formReducer } from 'react-redux-form'
import { combineReducers } from 'redux'

const initialSurveyState = {
  isStudent: ''
}

export default combineReducers({
  survey: modelReducer('survey', initialSurveyState),
  surveyForm: formReducer('survey')
})

...

// reducers/index.js

import combineReducers from 'redux'
import { forms } from 'reducers/forms'
...

export default combineReducers({
  forms,
  ...
})

```

**Comment by davidkpiano** [comment]
Might be a React-Bootstrap issue - have you tried `'Input': controls.radio` ?

**Comment by nickzarate** [comment]
Ya I have tried controls.radio. When I use controls.radio, everything works the same except that actual radio button that is chosen does not show up, and they are all unmarked (Although I think that's a separate issue). Are you sure it is a React-Bootstrap issue? Even when I take out the <InputField /> component and submit the form without any user interaction, the validateErrors should be accessing my survey model reducer independently of what is shown to the user right? In that case I am not using Bootstrap at all, but I should still be able to validate my survey model state, though there may not be a point to doing so. Thoughts?

**Comment by davidkpiano** [comment]
@nickzarate This definitely looks like a react-bootstrap issue. Check this example out - not even using Redux or React-Redux-Form, the console fails to log the "No" option: http://esnextb.in/?gist=fff6baa60ddd5e42e4ff

**Comment by davidkpiano** [comment]
Issue here: https://github.com/react-bootstrap/react-bootstrap/issues/1690

**Comment by nickzarate** [comment]
Using nearly the exact same code you used:
```
import React from 'react'
import { Input } from 'react-bootstrap'

export default class Foo extends React.Component {
  handle(e) {
    console.log(e.target.value);
  }
  render() {
    return (
      <form>
        <Input type="radio" name="asdf" value="Yes" label="Yes"
          onChange={e => this.handle(e)}/>
        <Input type="radio" name="asdf" value="No" label="No"
          onChange={e => this.handle(e)}/>
      </form>
    )
  }
}
```
I am not able to reproduce the issue, "Yes" and "No" are logged to the browser just fine. Not sure why that is. However, if I understood correctly, jquense answered that issue you submitted saying that that is the intended behavior right? (Implying it is not an issue to be 'fixed'). With that in mind, is there a possible workaround or is React-Bootstrap just going to be a problem? On that note, I am having issues with React-Bootstrap using a checkbox input and radio input, and I just saw issue #65, in your opinion, do you think it is worth it to use React-Bootstrap with RRF?

**Comment by davidkpiano** [comment]
Yes, if the above code works, then you should be able to do this:

```js
import React from 'react'
import { actions } from 'react-redux-form';
import { Input } from 'react-bootstrap'

const Foo = connect(s=>s)(class Foo extends React.Component {
  render() {
    let { dispatch } = this.props;
    return (
      <form>
        <Input type="radio" name="test" value="Yes" label="Yes"
          onChange={e => dispatch(actions.change('user.email', e))}/>
        <Input type="radio" name="test" value="No" label="No"
          onChange={e => dispatch(actions.change('user.email', e))}/>
      </form>
    )
  }
});
```

And for that issue, all custom components should have a `.displayName` property. I'll open a PR to add it to `react-bootstrap` if it's missing on some of their components.

**Comment by nickzarate** [comment]
Oh sorry I was actually referring to the original issue, which wasn't even with the Radio button actually, that is working for me fine (except for in production because of uglify, and also I use controls.text which works instead of controls.radio which does not work). The problem I am having is that when I submit the form, I cannot validate the errors of any specific field. So for the isStudent state inside my survey model reducer, I can see that "Yes" and "No" are actually being set as the states, but when I submit the form, my error validators get undefined as the value being pulled from those states. I was confused as to why it was a ReactBootstrap issue because I thought validateErrors was independent of the actually component itself, and only related to the state in the model reducer. Actually I just tried this, and when I use `input` instead of React Bootstraps `Input`, validateErrors is still returning undefined for me. This is the specific snippet of code where I am having trouble:
```
// actions/survey.js
import { actions } from 'react-redux-form'

export function handleSurveySubmit() {
  return (dispatch) => {
    const { forms: { surveyForm } } = getState()
    dispatch(actions.validateErrors('survey.isStudent', {
      required: (val) => { console.log(val) } // undefined
    }))

    if (surveyForm.valid) {
      // do something
    }
  }
}
```
I'm pretty new to all this stuff though (even React and Redux in general), so I'm sorry if I'm missing something here or not making any sense, I appreciate the help!

**Comment by davidkpiano** [comment]
@nickzarate Please see this gist (click **Execute**) and check the console upon clicking the text. I am successfully getting the value of `survey.isStudent` logged. http://esnextb.in/?gist=fdc389057dbb786e5925

Also, make sure to `return (dispatch, getState) => {` to provide `getState` inside your function body.

**Comment by nickzarate** [comment]
Ok, I figured out what the issue was. I actually suspected this from the beginning but for some reason forgot about it! So the issue I was having, and I think this extends to some other issues, was that I have been nesting my modelReducers, and formReducers. I `combinedReducers` of all of my model and form reducers under a `forms` reducer that I then use in my reducers/index.js, for some reason this extra layer lead to issues, maybe because of `combineReducers`? Here is the snippet of code (from above) that caused the issue:
```
// reducers/forms.js

import { modelReducer, formReducer } from 'react-redux-form'
import { combineReducers } from 'redux'

const initialSurveyState = {
  isStudent: ''
}

export default combineReducers({
  survey: modelReducer('survey', initialSurveyState),
  surveyForm: formReducer('survey')
})

...

// reducers/index.js

import combineReducers from 'redux'
import { forms } from 'reducers/forms'
...

export default combineReducers({
  forms,
  ...
})
```

**Comment by davidkpiano** [comment]
If you want to keep your original code, you can declare it as so: 

```js
export default combineReducers({
  survey: modelReducer('forms.survey', initialSurveyState),
  surveyForm: formReducer('forms.survey'),
  ... // other reducers
})
```

I will update the docs to clarify this. :smile:

**Comment by nickzarate** [comment]
Haha wow, such an easy fix. Thanks!
