### ISSUE TITLE
Form validation function

### ISSUE THREAD

**Issue by sl33kr** [davidkpiano/react-redux-form#572]
Hi @davidkpiano ,
I have done some work to get the form validation as a function somewhat working.

I was just wondering if you would like me to open a pull request for you to look at to see if it's something you are either currently working on or interested in.

The branch is here https://github.com/sl33kr/react-redux-form/tree/form_validation_function

It's rough at the moment but works for my case.

It isn't using invertValidators at the moment either.

Usage is
```
export function validateForm(model) {
    const cust = model && model.customers[0];

    if (cust && (required(cust.phoneNumber) || required(cust.email))) {
        return false;
    }

    return {
        'customers[0].phoneNumber': { 'hasPhoneOrEmail': true },
        'customers[0].email': { 'hasPhoneOrEmail': true }
    };
}

<Form model="appState.enquiry" validators={validateForm}>
	<div className="row">
		<div className="col-lg-6 with-icon">
			<Errors model=".customers[0].phoneNumber" 
					messages={{ hasPhoneOrEmail: 'Please enter either a phone number or email.' }} />
			<Control.text model=".customers[0].phoneNumber" id="new-customer-phone" />
			<label htmlFor="new-customer-phone">Phone number *</label>
		</div>
		<div className="col-lg-6 with-icon">
			<Errors model=".customers[0].email" 
					messages={{ typeMismatch: "Please enter a valid email.", hasPhoneOrEmail: 'Please enter either a phone number or email.' }} />
			<Control model=".customers[0].email" id="new-customer-email" />
			<label htmlFor="new-customer-email" className="">Email</label>
		</div>
	</div>
</Form>

**Comment by sl33kr** [comment]
Hi @davidkpiano 
Was just wondering if you have had a chance to consider this?

**Comment by davidkpiano** [comment]
Hey @sl33kr, taking a look at it now! Sorry for the delay.

**Comment by davidkpiano** [comment]
Would you mind merging in the latest from master and creating a pull request so I can further review? I definitely want to go forward with this.

**Comment by sl33kr** [comment]
Great! I'll tidy it up try to get this done over the next day or 2.
