### ISSUE TITLE
Form.forms.myform.value no longer there?

### ISSUE THREAD

**Issue by hermanfenderson** [davidkpiano/react-redux-form#573]
Just to double check my foundings....
If I have a form with a myform model... (e.g. with a field1 in it)
In version 1.3 I could gather the value of a field also at form.forms.myform.field1.value.
Updating to 1.4.2 values are no longer present there (I can find them at form.myform.field1.

Am I right? If so... is it intended or a bug? It broke a few things in my code...

**Comment by davidkpiano** [comment]
It's intended, but just curious, what was your use-case? If there's no better way to do it, I can add it back.

**Comment by davidkpiano** [comment]
Actually, I'm going to add it back in. I realize it is a breaking change, even if it's not documented. Sorry about that!

**Comment by hermanfenderson** [comment]
The use case was to pass a whole form to a function and use the values to calculate other values...it was useful as well to pass the model names (so if I had to refactor my code it didn't was too hard).

Are you putting it back in a few hours or it will take longer? In the latter case... I will manage to fix my code.

Thank you for your prompt reply!

**Comment by davidkpiano** [comment]
That's a good use case. Give me a few hours, I'll have the values back by this evening at the latest.

**Comment by hermanfenderson** [comment]
I appreciate that!!!!


Il giorno mar 13 dic 2016 alle 17:21 David Khourshid <
notifications@github.com> ha scritto:
