### ISSUE TITLE
Values set in redux aren't applied to target input box

### ISSUE THREAD

**Issue by CoinGame** [davidkpiano/react-redux-form#574]
Currently react-redux-form input boxes are not populating the redux store form data as the value of the input box when mounted. The parent Control component of the input box storing a name string recognizes the value from the redux store, but this value is not passed to the input box. I've simplified my code below as much as possible to try and troubleshoot the problem here without much luck. 

In my current code a user already has their name value set. When they login the name property is pulled from a request, and if they navigate to the route with the SimpleProfile component the name field should be populated.

```jsx
    SomePromise.ThatGetsProfileInfoAfterLogin()
    .success(success => {
      this.props.dispatch(dispatch => {
        //Setting form data with profile info
        dispatch(actions.load('profile', success.profile))
        //Setting general store for profile info
        dispatch(setProfile(success.profile))
      })
    })
```

This is the form component that is connected to the profile model.

```jsx
import React from 'react'
import { Control, Form, Field, actions, Errors } from 'react-redux-form';
import { connect } from 'react-redux'

@connect((store) => {
  return {
    ...store
  }
})
export default class SimpleProfile extends React.Component {

  render() {

    return (
      <Form model="profile">
            <Control.text model=".name"/>
      </Form>
    )
  }
}

```

RAW view for forms.profile.name redux store
```
{
  name: 'thismyname'
}
```

React debugging tools view of Control component values
![control](https://cloud.githubusercontent.com/assets/7383066/21152972/968f131e-c136-11e6-9e30-f4ef4f3bc040.png)

React debugging tools view of child input of Control component
![input](https://cloud.githubusercontent.com/assets/7383066/21152994/a6087722-c136-11e6-9e68-4d0ee5b6abd2.png)

Even after abstracting away all unnecessary code from this form component the value of the input box does not get set based on the existing data in the redux form store, even though parent components of the input are aware of the correct value. Any ideas on how to troubleshoot this further?

**Comment by davidkpiano** [comment]
What does your `store` look like?

**Comment by CoinGame** [comment]
`store`
```jsx
import { createStore, applyMiddleware, compose } from 'redux'
import normalizrMiddleware from 'redux-normalizr-middleware'
import logger from 'redux-logger'
import thunk from 'redux-thunk'
import combineReducers from './reducers/index.js'

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

export default createStore(
  combineReducers,
  composeEnhancers(
    applyMiddleware( thunk, normalizrMiddleware() ) 
  ))
```

reducer `index`
```jsx
import { combineReducers } from 'redux'
import { routerReducer } from 'react-router-redux'
import { combineForms } from 'react-redux-form'
import profile from './profileReducers'

const registrationFormState = {
  username: '',
  password: '',
  password2: '',
};

const loginFormState = {
  username: '',
  password: '',
};

const profileFormState = {
  name: '',
  type: 0
};

const forms = combineForms({
    register: registrationFormState,
    login: loginFormState,
    profile: profileFormState
  })

export default combineReducers({
  routing: routerReducer,
  forms: forms,
  profile,
})
```

**Comment by CoinGame** [comment]
Is there any examples of react-redux-form where inputs should be pre-populated? I couldn't find any in the documentation, but maybe I missed it. I can simplify further or reuse an existing example to see if it's something config related on my end.

**Comment by davidkpiano** [comment]
@CoinGame I believe the issue is here:

```js
const forms = combineForms({
    register: registrationFormState,
    login: loginFormState,
    profile: profileFormState
  })

export default combineReducers({
  routing: routerReducer,
  forms: forms,
  profile,
})
```

Since you're putting your forms in a nested part of your store, instead of at the root of your store (that is, it's at `store.getState().forms` instead of just `store.getState()`), you need to specify _where_ you are putting your forms in `combineForms`:

```diff
const forms = combineForms({
    register: registrationFormState,
    login: loginFormState,
    profile: profileFormState
- })
+ }, 'forms')
```

The above tells RRF "I'm going to be putting these forms under the `'forms'` key in my store."

Please add that and let me know if it fixes your issue.

**Comment by CoinGame** [comment]
Hi @davidkpiano, thanks for the quick reply. it looks like that actually breaks things further. As running the app immediately throws:

```javascript
Uncaught Error: Could not find form state for 'profile.name' model. Please make sure it exists in the store.
```

whereas before it seemed to be finding the forms in the store fine. RRF allows me to update, and submit data fine which it's drawing from the store. Notice in the screenshot above for the Control component that fieldValue.initialValue, and fieldValue.value are set correctly which it pulled from the store.

in the `CombineForms` [documentation](https://davidkpiano.github.io/react-redux-form/docs/api/combineForms.html) it stated that the default `key` for the form data would be `forms`, and that is how it's currently defined in my store. This gave me the impression that RRF would default to looking for a key called `forms` with the data rather than having all of the form data in the root.

![fuck](https://cloud.githubusercontent.com/assets/7383066/21189643/5aced8f2-c1ed-11e6-8d7e-87226f279b01.png)

This is how my store looks inside the browser.

**Comment by davidkpiano** [comment]
So because it's nested, you'd have to change the model here too:

```jsx
      <Form model="forms.profile">
            <Control.text model=".name"/>
      </Form>
```

Sorry, forgot to mention that.

Here's the general idea:

```js
const store = createStore(combineForms({
  foo: initialFoo,
  bar: initialBar,
}));
```

creates this store shape:

```
{
  foo: ...
  bar: ...
  forms: {
    foo: ...
    bar: ...
    $form: ...
  }
}
```

---
With nested form state:

```js
const store = createStore(combineReducers({
  something: somethingReducer,
  forms: combineForms({ foo: initialFoo })
});
```

You now get this shape:

```
{
  something: ...
  forms: {
    forms: { foo: ..., $form: ... }
  }
}
```

---

I recommend doing something like this: http://davidkpiano.github.io/react-redux-form/docs/api/createForms.html

```js
import { combineReducers } from 'redux';
import { createForms } from 'react-redux-form';

const initialUserState = {};
const initialGoatState = {};

const reducer = combineReducers({
  foo: fooReducer,
  bar: barReducer,
  ...createForms({
    user: initialUserState,
    goat: initialGoatState,
  }),
});

// reducer state shape will be:
// {
//   foo: fooReducer,
//   bar: barReducer,
//   user: modelReducer('user', initialUserState),
//   goat: modelReducer('goat', initialGoatState),
//   forms: formReducer(''),
// }
```

**Comment by CoinGame** [comment]
Boom. You're the dude. I just needed to add the `forms` key to my forms model attribute. My gut preference is the nested approach. Unless there's some serious drawbacks for the future i'm not aware of. Still kinda new to react/redux, and mixing in things like RRF has been a whirlwind. Appreciate your responsiveness and insights.

**Comment by davidkpiano** [comment]
No problem! Glad to help, and feel free to open another issue if you're still hung up on some aspects of RRF.
