### ISSUE TITLE
Control: onChange not working in deep composition Components

### ISSUE THREAD

**Issue by mikkelwf** [davidkpiano/react-redux-form#575]
I'm having some trouble with getting Control working.

I'm trying to build custom Input controls, that are composed from basic components:
```
* Input
* Checkbox
* Radio
```

I have the following setup of a composed component

Component 1:
```
Boolean
- Select
- - SelectList
- - - Radio (multiple)
```

Component 2:
```
Select
- SelectList
- - Radio (multiple)
```

The `Boolean` is just a wrapper around `Select` with some `props` applied/overridden.

Component 2 works as expected, but Component 1 does not. the `rrf/change` has no `value`

I'm using `<Control.select>` for both.

I've tried manually triggering the supplied `onChange` in the `Boolean` Component, ensuring that its sending the right value, but no value comes out in `rrf/change`

It's really weird, and i've been stuck solving the issue for a while, so if you guys have any input, please let me know.

**Update**
I think it could have something to do with which component the `<Control>` actually binds to.
I've console.logged the args and context of `handleChange` in `control-component.js`, and i both instances it looks like its bound to `Select`, and not `Boolean`.

**Update 2**
Found the culprit! I've been utilizing a `type` prop on my elements to choose which underlying component is should render i.e. `<Boolean type='radio'>` renders a  boolean in radio list form.

That conflicted with the controlProps, as radio and checkbox are read-only as per the `isReadOnlyValue` method in `control-component.js`. 

So nothing wrong with rff, thankfully, but damn, that was some hard debugging.. :)

**Comment by davidkpiano** [comment]
> That conflicted with the controlProps, as radio and checkbox are read-only as per the isReadOnlyValue method in control-component.js.

Yeah, I need to refactor that to not use "duck-typing" to figure out if a component is an actual input/radio button. Thanks for debugging, though!

**Comment by mikkelwf** [comment]
No problem.. :)

I've really enjoying this library, it makes form composition a breeze..

Keep up the good work..! 😃
