### ISSUE TITLE
LocalForm & Control errors

### ISSUE THREAD

**Issue by tberster** [davidkpiano/react-redux-form#576]
Trying to figure out how to dynamically set an error class to a Control based on the input. All of this in a LocalForm.

The item in question is found at `setErrorClass`. How can I access the controls internal state to dynamically set an error class on an input item.

As an example:
```jsx
<LocalForm
  validators={{
    password: { isRequired },
  }}
  onSubmit={(values) => {
    // do something
  }}
>
  <Control
    model='.password'
    type='password'
    className={cx('input', { 'input-error': setErrorClass(<????>) })} />
</LocalForm>
```

**Comment by davidkpiano** [comment]
See here, from the FAQs: http://davidkpiano.github.io/react-redux-form/docs/guides/faqs.html#how-do-you-add-conditional-class-names-based-on-field-state

In short, this would be something that you would use `mapProps` for:

```jsx
<Control
  model=".password"
  type="password"
  mapProps={{
    className: ({fieldValue}) => cx('input', {
      'input-error': !fieldValue.valid
    })
  }}
/>
```

**Comment by tberster** [comment]
Thanks for your prompt reply. I'm now running into the challenge that I would like to dynamically set the class. If you focus the field, and then immediately blur it, it should have the internal state of `pristine: true` and `touched: true`. But it doesn't change the classes on the field, because mapProps gets only called once the component gets mounted. Am I doing something wrong here?
