### ISSUE TITLE
Validation firing on load

### ISSUE THREAD

**Issue by sattaman** [davidkpiano/react-redux-form#58]
I am validating using 

` <Form model="mymodel" validators={validators} validateOn="change">`

1) I am finding the validation is firing before any change as soon as the page loads.

I've adapted this fiddle as an example https://jsfiddle.net/wbd86ewj/

2) Also to reset, I am finding I need to reset each field individually, so I am needing 

```
dispatch(actions.resetValidity("mymodel.field1"))
dispatch(actions.resetValidity("mymodel.field2"))
dispatch(actions.resetValidity("mymodel.field3"))
```

instead of 

`dispatch(actions.resetValidity("mymodel"))`

Which I saw mentioned

**Comment by davidkpiano** [comment]
The resetValidity issue is a bug, thanks for finding that.

As far as validation firing on load, this is standard behavior - the initial validity state of the form should be calculated, e.g. an empty sign up form that hasn't been touched yet is invalid.

What is your use case for not having validation on load?

**Comment by sattaman** [comment]
I don't want to display error messages until the person has either attempted to progress to the next section, or has blurred or changed the fields.

**Comment by davidkpiano** [comment]
Ah, that's why there's the `.touched` property on the field. ;-)

```js
// in render() 
let { userForm: { fields } } = this.props;

// displaying the error
{ fields.email.touched && !fields.email.valid &&
  <div>Please check your email address.</div>
}
```

Let me know if that makes sense. This is the same way that validation works in Angular. If RRF _didn't_ validate on load, the user would technically be able to submit an empty, untouched form because it's "valid", which is definitely not something we want.

**Comment by sattaman** [comment]
Ok , so if I want to display validation messages if someone attempts to go to the next section without touching what would you recommend?

**Comment by davidkpiano** [comment]
Good question. Would you expect the form to be `"touched"` if it were submitted (or at least attempted)? If so, I can add that functionality in.

**Comment by sattaman** [comment]
I don't actually use the submit functionality of the form at present. Would that touched be then passed down to all the fields? If updating the field.touched property is the way to go then any way of doing this from an action.

**Comment by davidkpiano** [comment]
Right now, no, `touched` is only passed to the model that is touched.

You can set any of these properties by dispatching actions: https://davidkpiano.gitbooks.io/react-redux-form/content/field_actions.html

**Comment by sattaman** [comment]
Would it make sense if setting touched on the model that this would propagate to the fields? 

`actions.setTouched(model)`

**Comment by davidkpiano** [comment]
Yes, it would. I'll add that in.

**Comment by chrisblossom** [comment]
So for validateOn="blur" I use:

``` javascript
// in render() 
let { userForm } = this.props;
```

``` javascript
// displaying the error
{ 
  !fields.email.valid && 
  (userForm.submitted || userForm.fields.email.touched) &&
  <div>Please check your email address.</div>
}
```

``` javascript
// validateOn="change" while-typing validation
{
  !fields.email.valid && 
  (
    userForm.submitted ||
    userForm.fields.email.touched ||
    (userForm.fields.email.dirty && userForm.fields.email.focus)
  ) &&
  <div>Please check your email address.</div>
}
```

**Comment by sattaman** [comment]
It would just be as david originally posted I think . .

```
let { userForm: { fields } } = this.props;

// displaying the error
{ fields.email.touched && !fields.email.valid &&
  <div>Please check your email address.</div>
}
```

**Comment by chrisblossom** [comment]
The form's submitted state should be true if the form has been submitted. Shouldn't have to add any additional code / actions for this to work properly.

You should check userForm.submitted as well as userForm.fields.email.touched

**Comment by davidkpiano** [comment]
@sattaman Version `0.8.4` includes two changes:
- Submitting a form now sets its `touched` state to true.
- Changing/dirtying a field now sets its `touched` state to true as well.

Validation on load is the expected behavior, as explained. I'm thinking of an alternate solution of resetting validity that doesn't force you to call multiple actions, stay tuned!

**Comment by sattaman** [comment]
Ok, so the plan is to know whether a field needs to display an error message you will need to check the form too? I currently have all my field validation handled by a wrapper around the bootstrap Input which I was just passing the field like so: 

 <ValidatedInput field={getField(myForm, "myField")}>

I guess I'll need to change to

 <ValidatedInput form={myForm} field="myField">

Just thought I'd double check..

**Comment by davidkpiano** [comment]
Right, because it's possible that a field could never be touched, but the form could be attempted to be submitted (which would cause it to be touched).

If you were just checking that the _field_ were touched, then you'd just need to pass the field.

**Comment by chrisblossom** [comment]
https://github.com/davidkpiano/react-redux-form/issues/56 would cut down on some code here

**Comment by zabojad** [comment]
> Submitting a form now sets its touched state to true.

In that case, submitting a form should set it's fields state to touched=true ?

When I do this:
```

**Comment by davidkpiano** [comment]
> I think submitting an untouched form should either:
> 
> - set the state of the fields to touched=true or
> - set the state of the field to submitted=true
> So that we can display an error message if the user clicks on submit before having tried to fill in the form

This works as expected in recent versions: https://github.com/davidkpiano/react-redux-form/blob/master/test/form-reducer-spec.js#L263-L285

That is, when the `formReducer` receives `actionTypes.SUBMIT_FAILED`, it will:
1. Set the `.submitFailed` and `.touched` properties to `true` on the form, and
2. Set the `.submitFailed` and `.touched` properties to `true` on _all of the form's fields_

Which version are you on? This was fixed in `0.12.7`

**Comment by zabojad** [comment]
I'm working on `"react-redux-form": "^0.12.6",` which was the latest available on npm yesterday...

**Comment by zabojad** [comment]
I just tried again and npm install keeps fetching 0.12.6, any idea why ?

**Comment by davidkpiano** [comment]
Should be `0.13.1`: https://www.npmjs.com/package/react-redux-form

Try `npm install react-redux-form@latest --save`

**Comment by zabojad** [comment]
Oh, it's OK now, I forgot the `--save` when `rm` and `install`... I have the `0.13.1` now.

**Comment by zabojad** [comment]
I also confirm the problem I've initially reported is fixed in latest version :)!
