### ISSUE TITLE
Dynamic Error Classes for Controls

### ISSUE THREAD

**Issue by avonian** [davidkpiano/react-redux-form#590]
Hi,

I didn't see this in any examples, but is there a simple way we can have custom error classes for controls, so we can manipulate their style when they have invalid data?

I assumed there wasn't, and went down the path of creating custom controls via component="{}"... tried a range of approaches in the manner that all seem to fail.

I got close in one way, which was to pass the actual validators into the custom component and have it revalidate internally, but this doesn't work quite right since the component has no way of knowing that form is pristine (props do appear in the child component but no .pristine there), and I would like the validation cycle to fire only after the form is submitted.

Any ideas would be appreciated.

**Comment by davidkpiano** [comment]
Yep, there is! Check out the FAQs: http://davidkpiano.github.io/react-redux-form/docs/guides/faqs.html

```jsx
<Control.text
  model="user.firstName"
  mapProps={{
    className: ({fieldValue}) => fieldValue.focus
      ? 'focused'
      : ''
  }}
/>
```

**Comment by avonian** [comment]
Thank you so much!
