### ISSUE TITLE
createModelReducer is not a function

### ISSUE THREAD

**Issue by l1br3** [davidkpiano/react-redux-form#591]
Just taking exemple from [wiki](https://github.com/davidkpiano/react-redux-form/wiki) and get the error.

This part does not work 

```javascript
import { createModelReducer } from 'react-redux-form';

import LoginForm from './forms/login-form';

const store = createStore(combineReducers({
  user: createModelReducer('user')
}));
```

**Comment by l1br3** [comment]
Exactly same issue with `createFormReducer ` from [other page of wiki](https://github.com/davidkpiano/react-redux-form/wiki/API:-Reducers)

**Comment by davidkpiano** [comment]
Sorry about that! Seems like you're reading outdated documentation from version 0.x. Please read the most up-to-date docs here: http://davidkpiano.github.io/react-redux-form/docs.html
