### ISSUE TITLE
Error should be shown at componentDidMount

### ISSUE THREAD

**Issue by l1br3** [davidkpiano/react-redux-form#594]
I don't know how to reproduce that but I basically have this code.

If I fill the email field with an already used email and then blur, the error message appears.
If I go to another page and then come back to my form, the error message is not here anymore, even if I focus/blur. 

I must `focus => change the value => blur ` to get the message back.

The console.log is triggered so this is just a problem from Error component I guess.

I just put a part of the form
```javascript
          <Errors
            className="errors"
            model=".email"
            messages = {{
              available  : val => `${val} is already used. Please choose another address`
            }}
          />
          <label>Email</label>
          <Control.text
            type="email"
            model=".email"
            validators={{
              required: (val) => val.length,
              isEmail
            }}
            asyncValidators={{
              available: (val, done) => {console.log('triggered');return actions.checkEmailAvailability2(val)
                                        .then(res => done(res))}
            }}
          />
```

**Comment by l1br3** [comment]
I've tried something like in #596 but it does not works for asyncValidation.
Maybe there is another workaround ?

**Comment by davidkpiano** [comment]
You should now (after the next release) be able to use the `persist` prop to accomplish this:

```jsx
<Control.text
  model="user.name"
  validators={{...}}
  persist
/>
```

This will prevent the validity from being reset when the component unmounts.
