### ISSUE TITLE
Bug when you import Fieldset from 'react-redux-form/immutable'

### ISSUE THREAD

**Issue by augustincouette** [davidkpiano/react-redux-form#595]
Hello, 
If you import `Fieldset` from `'react-redux-form/immutable'` you get an error at runtime :
Warning: React.createElement: type should not be null, undefined, boolean, or number.

With import from `'react-redux-form'` its works, but the doc is not clear on this point. 
Thanks for your (great) work.

**Comment by davidkpiano** [comment]
As a workaround, importing `Fieldset` from `react-redux-form` for use in your Immutable app should work fine.

**Comment by augustincouette** [comment]
Yes its work fine.
