### ISSUE TITLE
Radio buttons not checked with react-bootstrap + immutable

### ISSUE THREAD

**Issue by tmcdonnell87** [davidkpiano/react-redux-form#598]
Tried to reproduce with [ESNextbin](https://esnextb.in/?gist=b31277251f5c24df9b13b2cc95abc00c), but I get a ReactDOM error in the boilerplate sample. 

I have a simple form that uses react-bootstrap components. When the radio buttons are clicked, the state updates as expected, but the buttons do not appear clicked in the UI. Any suggestions would be appreciated. 

Happy to help try to reproduce in a working ESNextbin sandbox/provide additional information.

```jsx
import React from 'react';
import { Control, Form } from 'react-redux-form/immutable';
import { Radio } from 'react-bootstrap';

class MyForm extends React.PureComponent {

  handleSubmit(vals) {
    console.log(vals);
  }
  render() {
    return (
      <Form
        model="search"
        onSubmit={(vals) => this.handleSubmit(vals)}
      >
        <Control.radio model=".sex" value="male" component={Radio} inline>
          Male
        </Control.radio>
        <Control.radio model=".sex" value="female" component={Radio} inline>
          Female
        </Control.radio>
      </Form>
    );
  }
}

export default MyForm;
```

Thanks,
Terry

**Comment by davidkpiano** [comment]
Sure, can you make a reproducible example in www.esnextb.in ?

**Comment by tmcdonnell87** [comment]
Sorry, to clarify, I was not able to get ESNextbin working with readt-redux-form/immutable, even well enough to just render the form. 

You can check out the following: https://esnextb.in/?gist=97d0c044a2f119de9993d1a6274a3639 (https://gist.github.com/tmcdonnell87/97d0c044a2f119de9993d1a6274a3639)

Adding the line `import { Control, Form } from 'react-redux-form/immutable';` causes ESNextbin to throw the following error: 
```
import { createModeler } from './reducers/model-reducer';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by davidkpiano** [comment]
@tmcdonnell87 I was not able to reproduce this. The following fully reproducible code works as expected and the buttons successfully appear as clicked in the UI:

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { Control, Form, combineForms } from 'react-redux-form/immutable';
import Immutable from 'immutable';
import { Radio } from 'react-bootstrap';

import { createStore } from 'redux';
import { Provider } from 'react-redux';

const store = createStore(combineForms({
  search: Immutable.fromJS({ sex: 'male' }),
}));

class MyForm extends React.PureComponent {

  handleSubmit(vals) {
    console.log(vals);
  }
  render() {
    return (
      <Provider store={store}>
        <Form
          model="search"
          onSubmit={(vals) => this.handleSubmit(vals)}
        >
          <Control.radio model=".sex" value="male" component={Radio} inline>
            Male
          </Control.radio>
          <Control.radio model=".sex" value="female" component={Radio} inline>
            Female
          </Control.radio>
        </Form>
      </Provider>
    );
  }
}

ReactDOM.render(<MyForm />, document.querySelector('#app'))
```

Please review the above code and let me know if there are any large discrepancies between the above and your code.

**Comment by tmcdonnell87** [comment]
That works for you in ESNextbin? I copied and pasted that directly and it's still erroring

![image](https://cloud.githubusercontent.com/assets/4717014/21593938/b8ac527c-d0d1-11e6-8937-621fe35ebc13.png)

**Comment by davidkpiano** [comment]
I tried it directly on a local project. I'm not sure why it's going to `react-redux-form/src/immutable.js` - it should instead be hitting `react-redux-form/immutable.js` directly.

**Comment by weichenghsu** [comment]
any update? i had the same problem as you have

**Comment by tmcdonnell87** [comment]
@weichenghsu I ended up using a LocalForm for that particular use case so didn't spend more time on it. Were you able to reproduce in a sandbox?
