### ISSUE TITLE
Components indexing an array model lose sync

### ISSUE THREAD

**Issue by FelixHenninger** [davidkpiano/react-redux-form#599]
If the model state is an array, and a grid of `Control` components each index one cell, such as in the following example ...

```
<Control.text
  model={ `.grid[${ rowIndex }][${ colIndex }]` }
  className="form-control code"
/>
```

... the state is synced perfectly as long as there is no change in array dimensions. If the array is mutated (e.g. by adding an additional row), the mechanism breaks down.

A full minimal working example, as a project based on `create-react-app` is available at https://github.com/FelixHenninger/rrf-bug-demo/tree/grid-demo (please note the branch!)

It might very well be that I have introduced a mistake, so I'm hesitant to open an issue here. Nonetheless, I would very much appreciate any hints, and am glad to assist with debugging. Thank you very much!

**Comment by davidkpiano** [comment]
Have you tried using the `getDispatch` prop to get the internal dispatch for the `<LocalForm>`'s store, in order to dispatch an `actions.change` with the new data?

**Comment by FelixHenninger** [comment]
Thanks a lot for this suggestion! (and a very happy new year!) Indeed I hadn't tried that, but I've updated the [online example](https://github.com/FelixHenninger/rrf-bug-demo/tree/grid-demo) so that the internal dispatch can be tested easily and it still doesn't seem to work.

Poking around in the form internals a bit, I noticed that the connected Form component in React's component tree looks unexpected after updating througth the form dispatch method: The changed values are stored in an entry with an empty key. Might this be part of the solution?

**Comment by FelixHenninger** [comment]
Ah! I figured it out: By prepending 'local' to every model id, the changes get propagated correctly. So if I use the following action/dispatch combination

```
this.formDispatch(actions.change('local.title', 'I just changed via the form\'s dispatch method!')
```

Instead of just targeting `.title`, everything works perfectly. This is fantastic, thanks for pointing me in the correct direction! I'm unsure whether this is intended behavior, though?

**Comment by davidkpiano** [comment]
That is the intended behavior - I'll make the docs clearer on this!

**Comment by FelixHenninger** [comment]
Awesome, thank you again for your excellent work on the library! I'd offer to help with the docs, but I'm not sure I know the code well enough. Hope that day will come, though!

(closing the issue for now, please feel free to reopen if, for example, you'd like to track the doc changes)
