### ISSUE TITLE
[PROPOSAL] Form states

### ISSUE THREAD

**Issue by chrisblossom** [davidkpiano/react-redux-form#60]
There is a lot of confusion about form states.
I propose we remove extraneous fields and change behavior as expected by the questions below

#### .blur
Opposite of focus? **extraneous (also I don't think this works)
Remove.

### .dirty
Did the user change initial state?
**_initial:_** false
**_field:_** Change to true there has been any changes to the field.
**_form:_** Change to true if there has been any changes to any fields inside that form.

### .focus
Is the user currently highlighting the field/form?
**_initial:_** false
**_field:_** True when the user is currently interacting with the field, false otherwise.
**_form:_** True when the user is interacting with any part of the form, false otherwise.

### .pending
Did the user submit and is the onSubmit handler currently running?
**_initial:_** false
**_field:_** Equal to form's value when updated, not created. (Dynamic fields)
**_form:_** True only when the onSubmit handler has been called, false once it has been completed. Validity not taken into consideration.

### .pristine
opposite of dirty? **extraneous
Remove.

### .submitted
Did the user submit the form?
**_initial:_** false
**_field:_** Equal to form's value when updated, not created. (Dynamic fields)
**_form:_** True only when the onSubmit handler has been called. Field/form validity not taken into consideration.

### .touched
Did the user interact with the field/form?
**_initial:_** false
**_field:_** True once the user clicks the field.
**_form:_** True once the user clicks any field in the form.

### .untouched
Opposite of touched? **extraneous
Remove.

### .valid
Is the field/form valid?
**_initial:_** true (assuming no validation/everything passes)
**_field:_** false when fails valid/error checks, true when passes
**_form:_** false when any field fails valid/error checks, true when all fields pass

### .validating
Is the field/form being validated (includes checking for errors)?
**_initial:_** false
**_field:_** true when validation is occurring
**_form:_** true when any field is validating

### .viewValue
No idea? **extraneous?
Remove.

### .validity
Is the field/form valid?
**_initial:_** null
**_field:_** Field specific validation checks
**_form:_** Form as whole validation checks

I think this should be removed and merged with errors. And then you ask the question, is the field/form invalid? Simplifies and shrinks API.

### .errors
If any, what are the errors?
**_initial:_** null
**_field:_** Field specific error checks
**_form:_** Form as whole error checks

### .fields
What are the available fields?
**_initial:_** null (if no initial fields specified)
**_field:_** Sub-fields? No idea about this one.
**_form:_** Current fields.

See also https://github.com/davidkpiano/react-redux-form/issues/56.

### .validSubmit
Did the user submit the form and was it successful?
**_initial:_** false
**_field:_** Equal to form's value when updated, not created. (Dynamic fields)
**_form:_** True when the onSubmit handler has been and successfully passed checks.

**Comment by chrisblossom** [comment]
Given: updateOn="change" validateOn="blur"

```javascript
// After initial validation:
blur:true
dirty:false
focus:false
pending:false
pristine:true
submitted:false
touched:false
untouched:true
valid:false
validating:false
viewValue:null
validity:false
errors:"Required"
initialValue:""

// First focus
blur:false
dirty:false
focus:true
pending:false
pristine:true
submitted:false
touched:false
untouched:true
valid:false
validating:false
viewValue:null
validity:false
errors:"Required"
initialValue:""

// First change, non-blank
blur:false
dirty:true
focus:true
pending:false
pristine:false
submitted:false
touched:true
untouched:true
valid:false
validating:false
viewValue:null
validity:false
errors:"Required"
initialValue:""
```

Currently, touched does not get updated until a change happens to the field. This is making it difficult to reliably predict when errors should be shown. I am thinking touched should be false until first blur as shown https://scotch.io/tutorials/angularjs-form-validation

**Comment by davidkpiano** [comment]
So here's the plan so far:

- Have `touched` follow Angular's implementation (on `blur`) as you suggested
- Remove all "negative" redundant fields:
  - `blur`
  - `dirty`
  - `untouched`

**Comment by chrisblossom** [comment]
I believe the ```touched``` change to change on ```blur``` was done in commit https://github.com/davidkpiano/react-redux-form/commit/953af9a5963198dc3f8c37eff1af405826c4d4cc

**Comment by ataube** [comment]
I would like to contribute to this issue, if there is anything I can do, give me ping...

**Comment by davidkpiano** [comment]
Planning on getting these changes in within the next couple days, wondering if I should deprecate the redundant properties first though.

**Comment by ataube** [comment]
Nice - would love to have this changes soon...
I am wondering how to deprecate them? Printing a console.warn for every form reducer?

**Comment by davidkpiano** [comment]
Deprecation has started for these three fields in `0.9.6`:

- `dirty`
- `blur`
- `untouched`
