### ISSUE TITLE
Support testing react-redux-form/immutable without transpile with NODE_ENV=test

### ISSUE THREAD

**Issue by tmcdonnell87** [davidkpiano/react-redux-form#600]
Running a test suite using react-redux-form/immutable fails unless you explicitly transpile this module. This is because the import is referencing the raw source when NODE_ENV is `test`.

```
module.exports = process.env.NODE_ENV === 'test'
  ? require('./src/immutable')
  : require('./lib/immutable');
```
https://github.com/davidkpiano/react-redux-form/blob/master/immutable.js

This breaks numerous testing setups, such as the excellent https://github.com/mxstbr/react-boilerplate. 

Side note: updating this might also fix ESNextbin's import of `react-redux-form/immutable`, which is also crashing because it's looking at src/immutable.

**Comment by davidkpiano** [comment]
So you're saying it should just be:

```js
module.exports = require('./lib/immutable');
```

Is that correct?

**Comment by tmcdonnell87** [comment]
Seemed like a hack, but it worked. Can't say it's the _best_ approach. Also not clear if it would fix the ESNextbin issue.

**Comment by davidkpiano** [comment]
I wouldn't say it's a hack - it's exactly what's expected. I'll go ahead and push that as a patch and see if it fixes the ESNextBin issue.
