### ISSUE TITLE
Usage with custom text component

### ISSUE THREAD

**Issue by karolbarkowski** [davidkpiano/react-redux-form#601]
Hi,

I'm having quite hard time trying to connect my text component with RRF.
Let's say I have this extremely simple custom component:

```jsx
import React from 'react';

const MyInput = (props) => {
  return <input value={props.value} className={props.className} onChange={() => { console.log('MyInputOnChange'); }} />;
};

export default MyInput ;
```

So I'm only tryign to attach some custom event handler to onChange and do something inside of it.
Then, I'm importing it in other component as usually:

```jsx
import MyInput from './MyInput ';     //this is my custom component pasted above
```

and then trying to use it like that:

```jsx
<Control
        model=".myModel"
        component={MyInput }
        validators={props.validators}
        mapProps={{
          value: (props) => props.modelValue,
          onChange: (props) => props.onChange,
          className: 'myClassName'
        }}
        />
```

value is passed correctly, className as well, my custom handler of 'onChange' is also firing. But none of react-redux-form actions are triggered when value is changing so my control is not binded to model and model is not updating it's state.
What is the proper way to connect RRF <Control> component with my custom component so they are properly connected?

**Comment by davidkpiano** [comment]
RRF needs some way of knowing _when_ a value changed, and _what_ the value changed to, at the very minimum. With your current custom component, there is no way of doing that, because your custom input's `onChange` prop is locked to your own function, so it isn't open to receiving any props.

Changing it to allow for this is trivial:

```diff
const MyInput = (props) => {
  return <input
    value={props.value}
    className={props.className}
    onChange={(event) => {
      console.log('MyInputOnChange');
+     return props.onChange(event);
    }}
  />;
};
```

**Comment by karolbarkowski** [comment]
Aaah, the missing piece. Thank you for such quick answer. It's all working as expected now.
