### ISSUE TITLE
Is there a easier way to show all field validation within the form Errors tag

### ISSUE THREAD

**Issue by aaronmagi** [davidkpiano/react-redux-form#605]
I wanted to know if its possible to list field level errors within the form's Errors tag?

I am looking at displaying the errors at the top of the form and within the field.  The reason for this is that some fields are hidden in tabs within the form.  I have found that this can be done by creating <Errors> tags with the model set to the field but is there a way to set the model to the base object and reference a particular field within the message?

Example below the errors are being shown within the field to display that the field requires a value.

```
<Form model="user" />
         <FieldGroup
            model=".lastName"
            type="text"
            label="Last name"
            placeholder="Enter Last name"
            validators={{
              required: notEmpty
            }}
            errorMessages={{
              required: "Last name is required"
            }}
            validateOn="change"
          />

</Form>
```

Here is a working example on creating a Errors tag for "user.lastName" on the Form level.
```

<Form model="user" />

<Errors
          model="user.lastName"
          messages={{
            required: 'Last name',
          }}
        />

         <FieldGroup
            model=".lastName"
            type="text"
            label="Last name"
            placeholder="Enter Last name"
            validators={{
              required: notEmpty
            }}
            errorMessages={{
              required: "Last name is required"
            }}
            validateOn="change"
          />

</Form>
```

**Questions**
1) Is there a better way to display each field error without creating a Error tag for each as shown below.
```
<Form model="user" />
<Errors
          model="user"
          messages={{
            **** how do I specify the lastName field here for the validator "required": 'Last name',
          }}
        />
```
2) Is there a way to display all the field error messages within the Error tag?

Thank you

**Comment by davidkpiano** [comment]
> 1. Is there a better way to display each field error without creating a Error tag for each

Currently, no, and this is because `messages` has the strict shape of:

```
{ validatorKey: message }
```

> 2. Is there a way to display all the field error messages within the Error tag?

Not currently, as well, though it might be a good enhancement to have the `messages={(errors) => ...}` prop accept a function that takes in the `errors` and returns an array of messages. What do you think about that?

For the first one, I'd have to think of a good solution. Might have to be a separate component, like `<ErrorGroup>` or something like that (naming stuff is hard).

**Comment by aaronmagi** [comment]
Hi @davidkpiano 

The more I ended up using the multiple errors tags, one for each field they actually seemed to work ok I just thought it would be nice to be able to setup a grouping of field errors in a single tag.  

I think after working with the multiple error tags its not such a big deal.

Thanks or the quick reply

**Comment by davidkpiano** [comment]
Awesome! Glad they weren't too painful!
