### ISSUE TITLE
Accessing array model from reducer on array value change

### ISSUE THREAD

**Issue by brianleonard15** [davidkpiano/react-redux-form#607]
Hi,

I have a form that contains a dynamic number of sub-forms and when a value changes in one of the sub-forms, e.g. from `user.cars[1].type.blackBentley` to `user.items[1].type.greenBentley`, I would like to update `user.cars[1].color.black` to `user.cars[1].color.green`.  

I know this can be done through the changeAction prop on the Control component by dispatching action.change for that particular car in the array, but is this possible through the reducer? The value of `action.model` in the reducer is a string of `user.cars[1].type`, making it difficult to access `user.cars[1].color`.

Thank you

**Comment by davidkpiano** [comment]
> I know this can be done through the changeAction prop on the Control component by dispatching action.change for that particular car in the array, but is this possible through the reducer? 

Sure, anything is possible through a custom reducer. http://davidkpiano.github.io/react-redux-form/docs/guides/models.html#using-existing-reducers

In your use case, you would have to use `lodash.toPath` to separate out the parts of the path from `user.cars[1].type` to `['user', 'cars', '1', 'type']`, and then `path.slice(0, -1)` to get the path without the last subpath. Then, with `['user', 'cars', '1']`, you can use whatever method you're most comfortable with (a library like `icepick`, something similar to Immutable.js, or depth-first search) to update the car in your custom reducer.

Does that help? I'll try to think of other simpler solutions.

**Comment by brianleonard15** [comment]
Ah I see. I thought there might be some obvious way without using string slicing operations in the reducer, since I'm new to react-redux-form, but the reasoning for having the logic in the reducer vs. the changeAction prop on the Control component was to make the code a little more robust. However, I think using those string operations is even more fragile than just handling the logic with the changeAction prop. Thank you for your help and quick response, David!

**Comment by davidkpiano** [comment]
If you're using `redux-thunk` as middleware, you can do this:

```js
<Control.radio
  model="user.cars[1]"
  changeAction={actions.merge}
  value={{ type: 'greenBentley', color: 'green' }}
/>
```

Pretty cool, huh? Might be the simplest solution to your issue.

**Comment by brianleonard15** [comment]
Very cool! I'm trying to avoid installing redux-thunk for now so I'm sticking with just manually doing it in changeAction, but that's definitely a more concise way.

**Comment by brianleonard15** [comment]
Very cool! I'm trying to avoid installing redux-thunk for now so I'm sticking with just manually doing it in changeAction, but that's definitely a more concise way.

**Comment by baffleinc** [comment]
Don't resist the thunk brian. The thunk is inevitable. I was in the same position however it's not worth the effort trying to push the RRF square peg into the saga round hole - at least not on a deadline.

They live side by side just fine. As a side note - would be awesome if RRF had a saga version.
