### ISSUE TITLE
v0.14.6 and collections

### ISSUE THREAD

**Issue by marcpeterson** [davidkpiano/react-redux-form#608]
Do you still answer questions about v0.14.6?  We're stuck on it for a while due to some legacy code.

If so, I've set up my reducers like so:
```
const modelReducer = modeled(reducer, 'parent.child');
const formReducer = formReducer('parent.child');
```
Add added them to the main reducer so they appear in the state tree as parent.child and parent.childForm respectively.

I've been adding collection items to the model with something like
`actions.push('parent.child.collection', { first:'tim', last:'peters'});`

This correctly adds items to the model's state tree:
```
parent: {
  child: {
    collection: [
      0: {
        first: 'tim',
        last: 'peters'
      }
    ]
  }
}
```

But it doesn't make the correct entries in the form's state tree.  The new item is added as a value to the collection:
```
parent: {
  childForm: {
    fields: {
      collection: {
       ... field data (blur, dirty, focus, etc),
        value: [
          0: {
            first: 'tim',
            last: 'peters'
          }
       ]
    }
  }
}
```

However, using actions.change() to add each of those individually does work:
```
actions.push('parent.child.collection[0].first', 'tim);
actions.push('parent.child.collection[0].last', 'peters');

```
Results in the same model state tree entries, and the correct form state tree entries:
```
parent: {
  childForm: {
    fields: {
      collection.0.first:
        ...all field data,
        value: 'tim'
      collection.0.last: 'peters':
        ...all field data,
        value: 'peters'
    }
  }
}
```

Am I misunderstanding how to add a collection item to the model and have it automatically appear in the form's fields?  Or is this a bug in how the collection's items translate into field names?

**Comment by davidkpiano** [comment]
It might be a bug that has long been fixed in the latest version of React Redux Form.

Is there anything I can help answer in terms of upgrading? v0.x to v1.x is not a huge migration, and there would be relatively few things you'd need to change to get it working.

**Comment by brianleonard15** [comment]
Just FYI, actions.push() is not in the table of contents in the documentation for those that have trouble finding it.

**Comment by marcpeterson** [comment]
Our teams share a common input component library, and we built a special layer that helps those input components work with v0.x.  So it's a matter of getting our custom components to work with the new version, then changing how we reference the newer state tree, and our custom validation layer would change too...  It's a bit more than we can do at the moment.

But I'd like to share things I've had troubles with that were very difficult to understand in v0.x.  It might be useful for you to know some pain points in case they exist in v1.x (and maybe could use some extra documentation).  Please don't take it as criticism, I really like this library :)
- There is a tight relation between the model and form.  But it's not necessary for their initial state to match.  Adding things to the model via RRF's `actions` automatically adds things to the form's fields in the state tree.
- Use `modeled()` to add RRF functionality to an existing reducer.  It was right there in the docs but we somehow missed this for months...
- The naming of collection items in the model is different than in the form.  It's tricky understanding when to use which.  I believe x1.x has solved this.
- A <Field> can be added to your JSX without being defined in the model or form.  But it won't appear in the state tree until it's touched by the user.  _Unless_ you give it a defaultValue, then it appears in the state tree immediately.

**Comment by davidkpiano** [comment]
> The naming of collection items in the model is different than in the form. It's tricky understanding when to use which. I believe x1.x has solved this.

Yes, this has been solved.

>  can be added to your JSX without being defined in the model or form. But it won't appear in the state tree until it's touched by the user. _Unless_ you give it a defaultValue, then it appears in the state tree immediately.

Yep, this is what setting the `initialState` is beneficial for. In V1.0 it's even simpler:

```
const store = createStore(combineForms({
  foo: initialFoo, // not a reducer
  bar: initialBar, // not a reducer
});
```

**Comment by marcpeterson** [comment]
Thanks for the quick responses.  Hopefully we'll get to migrate to v1.x soon...
