### ISSUE TITLE
Creating a Form validator with x: (vals) => vals.field causes the page to hang

### ISSUE THREAD

**Issue by aaronmagi** [davidkpiano/react-redux-form#610]
Hi,

I have ran into this issue a few times while trying to build different validators at the form level and I am not sure why this causes the page to hang and I get a popup that the browser has run into an unresponsive script.  

This only happens when I set this type of validation on the form, when setting it on a field it works fine.

```jsx

<Form model="user"
        onSubmit={user => onSave(user)}
        onChange={onChange}
        validators={{
                  '': {
                    // Form-level validator
                    checkChangePassword: (vals) => (vals.passwordNew),
                  }
                }}
        >
```

But the following validator will work without hanging

```jsx
validators={{
                  '': {
                    // Form-level validator
                    checkChangePassword: (vals) => (!(vals.passwordNew)),
                  }
                }}
        >
```

I want to setup a validator to check to make sure that something is not null from the Form level?  Do I need to change when the validation is preformed?

Below is the actual validation happening to check for empty or not.  'notEmpty' causes the page to hang when used on the Form validation.

```
const notEmpty = (val) => val && val.length;

const isEmpty = (val) => !notEmpty(val);

```
Thank you

**Comment by davidkpiano** [comment]
What version of RRF are you using? This might be a previously solved issue - in short, the validator has to return a boolean value, but it _should_ still work if truthy/falsey values are returned.

**Comment by aaronmagi** [comment]
1.2.2.  I just reran the test on 1.5.2 and it works.  Thank you
