### ISSUE TITLE
Module parse fails on immutable

### ISSUE THREAD

**Issue by brianleonard15** [davidkpiano/react-redux-form#611]
Hi,

I get the following error when using webpack to bundle and importing react-redux-form/immutable.js

`ERROR in ./~/react-redux-form/src/immutable.js
Module parse failed: node_modules/react-redux-form/src/immutable.js Unexpected token (73:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (73:2)
 ...
 @ ./~/react-redux-form/immutable.js 2:4-30`

Any ideas on how to solve this?

**Comment by davidkpiano** [comment]
Are you using Babel?

**Comment by brianleonard15** [comment]
Yes, I've got "babel-preset-es2015": "^6.16.0", "babel-preset-react": "^6.16.0","babel-preset-stage-2": "^6.17.0", "babel-loader": "^6.2.5", and in webpack:
     ` loaders: [
        {
          test: /\.js$/,
          loaders: ['babel'],
          include: path.join(__dirname, 'src')
        },`

Any thoughts?

**Comment by brianleonard15** [comment]
Using `import ... from react-redux-form/lib/immutable` vs `import ... from react-redux-form/immutable` seemed to solve the problem.

**Comment by hoangtrucit** [comment]
@brianleonard15 i have same issue, how to do fix this problem ?

**Comment by brianleonard15** [comment]
@hoangtrucit See my previous post. I just changed the import from this:
```
import {} from react-redux-form/immutable
```
to this
```
import {} from react-redux-form/lib/immutable
```

**Comment by hoangtrucit** [comment]
thanks @brianleonard15 , i have installed lastest version and use 
`import {} from react-redux-form/lib/immutable` but i don't fix this issue. I'm using create-react-app

**Comment by brianleonard15** [comment]
Sorry either that solution never worked, or suddenly the error is back for me, too.

**Comment by brianleonard15** [comment]
Did you make sure you did that for every react-redux-form import in your app?

**Comment by hoangtrucit** [comment]
This is log error
`Error in ./~/react-redux-form/src/immutable.js
Module parse failed: /Users/tructran/react-project/react-nv-client/node_modules/react-redux-form/src/immutable.js Unexpected token (73:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (73:2)
 @ ./src/redux/reducers/index.js 15:18-59

`

**Comment by danilotorrisi** [comment]
I'm having the same issues here, using only `react-redux-form/lib/immutable` but I still get this:

```
ERROR in ./~/react-redux-form/src/immutable.js
Module parse failed: /Users/danilotorrisi/Desktop/Workspaces/Keix/people-frontend/node_modules/react-redux-form/src/immutable.js Unexpected token (73:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (73:2)

```

**Comment by davidkpiano** [comment]
@danilotorrisi @hoangtrucit Is it possible to link me to the repos where you are experiencing the issues?

**Comment by danilotorrisi** [comment]
Unfortunately the repo is private :\

Found the issue btw, the problem was the webpack configuration ( resolver.modulesDirectories ) that contained the 'src' folder.
