### ISSUE TITLE
Changing form fields value based on focus and other forms value

### ISSUE THREAD

**Issue by pjatacsukb** [davidkpiano/react-redux-form#612]
Hello!
This is a newbie question:
I want to change one Control's value based on another control's value.
For example in my case: login form.
If the username's field left empty and the password field got focus how I can change back username's field to the initialState (custom reducer? but I have to access the username's field value from the password's reducer?)
I am new on the react-redux field but I really would like to get along with your library.
Thank you for your answer,
Pjata

**Comment by davidkpiano** [comment]
I'm a little confused - a custom reducer would make sense, especially one that has both the username and password in its state, right?

**Comment by pjatacsukb** [comment]
Yep thats what I want to achive. I just kinda confused how I can create a reducer that has both of the username and password in its state. Im following the documentation, the pieces is not coming together for me how I can achive that.

**Comment by davidkpiano** [comment]
How about something like this?

```js
import { createStore } from 'redux';
import { combineForms } from 'react-redux-form';

const initialUser = { username: 'Bob', password: '' };

const userReducer = (state = initialUser, action) => {
  switch (action.type) {
    case actionTypes.FOCUS:
      if (action.model === 'user.password') {
        return { ...state, username: initialUser.username };
      }
      return state;
    default:
      return state;
  }
};

const store = createStore(combineForms({
  user: userReducer,
});
```

**Comment by pjatacsukb** [comment]
Thank you for making things clear with a good example!
