### ISSUE TITLE
How can I access the changed model after a control component is changed?

### ISSUE THREAD

**Issue by micahalcorn** [davidkpiano/react-redux-form#617]
I'm trying to find an appropriate way to POST _part_ of my model via ajax when some nested, dynamically-generated fields change. Here are my issues that I am running into:

**Using Control Component `changeAction`**
Since my payload needs to include more than the value of the changed field, it would seem anti-React if I replicate the state, modify my replica, and then send the new object when RRF & Redux are already handling this in my app state.

**Using Form Component `onChange`**
Here I can access the new state, but I can't distinguish which child model my changed field belonged to without doing my own diff. Knowing the changed value is critical to my case.

**Using Form Component `onUpdate`**
Here I can access all of the form states, but none of them seem to be returning `focus: true` to indicate where the change has happened. 

I would hate to replace any of the default actions since RRF is doing such a great job handling the form and model states out of the box. Thanks so much for your efforts @davidkpiano! 😄

```javascript
const ParentForm = ({ onClick, onSubmit, parent }) => {
  const children = parent.children.map((c, i) => {
    return <Child key={i} index={i} child={c} />;
  });

  function handleChange (modelValue) {
    // model is the changed parent, only want the changed child
  }

  function handleUpdate (formValue) {
    // can't find any nested $form objects that are "focus: true"
  }

  return (
    <Form model="rrf.parent"
      onSubmit={p => onSubmit(p)} onChange={handleChange} onUpdate={handleUpdate}>
      <SomeParentFields />
      <SomeOtherNestedFields />
      <div className="dynamic-nested-forms-container">
        <a className="new-child" onClick={onClick}>Add New Child To Dynamic Form</a>
        <div className="children">
          {children}
        </div>
      </div>
      <input type="submit" className="save-parent" />
    </Form>
  );
};

const Child = ({ dispatch, index, child, onClick }) => {
  function handleChange (model, value) {
    return (dispatch) => {
      dispatch(actions.change(model, value));
      
      // must access model (child) from state, then modify a replica with value
      // would prefer to access model (child) after its state change has already been handled by RRF
    };
  }

  return (
    <div>
      <Control.text model={`.children[${index}].foo`} changeAction={handleChange} placeholder="POST entire child if I change" />
      <Control.text model={`.children[${index}].bar`} changeAction={handleChange} placeholder="POST entire child if I change" />
      <Control.text model={`.children[${index}].baz`} changeAction={handleChange} placeholder="POST entire child if I change" />
      <Control.text model={`.children[${index}].a`} placeholder="Don't POST my changes" />
      <Control.text model={`.children[${index}].b`} placeholder="Don't POST my changes" />
      <Control.text model={`.children[${index}].c`} placeholder="Don't POST my changes" />
    </div>
  );
};

export default connect()(Child);

```

**Comment by davidkpiano** [comment]
What if you set up an extra custom reducer to listen for `actionTypes.CHANGE` actions and build the changed model from there?

There's a few reasons that RRF doesn't come with a built-in "submit-only-changed-fields" feature, and that's mainly because of ambiguity, complexity, and weight. See here for more context: https://github.com/davidkpiano/react-redux-form/issues/409

Also, you can do a breadth-first search for fields that are `.touched` when preparing the data for submitting. Let me know what you think - if your general question doesn't fall into the diffing category, I'll reopen this.
