### ISSUE TITLE
Actions.remove doesn't remove field values

### ISSUE THREAD

**Issue by brianleonard15** [davidkpiano/react-redux-form#619]
React Redux Form version: 1.5.3

## Steps to reproduce:

Create repeating form element with just one initialized to start. Programatically add a form element, then remove the last one using actions.remove().

## Expected Result:

The models and field values are removed as expected.

## Actual Result:

The models and field values are removed, but then resetValidity is dispatched for every key of the item that was just removed, bringing the field values for the removed item back into the state. This leaves the model and field values out of sync.

**Comment by brianleonard15** [comment]
Also, if you add three items to the array and remove the second item, the model pointed to by the field value of the now second item (used to be the third item) is not updated.

For example:
Start with item 0, item 1, item 2. 
Remove item 1.
Now you have item0, item 2, as expected.
Unexpected field value for item 2:
     model: "items.2"
Expected this field value's model to be "items.1", since that is its new position in the array.

**Comment by davidkpiano** [comment]
@brianleonard15 Can you create a simple reproducible example in www.esnextb.in ? Would be greatly appreciated.

**Comment by davidkpiano** [comment]
The first issue has most likely been fixed in a previous release and is not reproducible.
The second issue was just fixed 🎉
