### ISSUE TITLE
actions.reset sets the model to the initialState but the form to the previous loaded value

### ISSUE THREAD

**Issue by konzz** [davidkpiano/react-redux-form#622]
I have a store similar to this:
`
{
  user: modelReducer('user', {name: ''}),
  userForm: formReducer({'user': {name: ''})
}
`
I'f I load the form with some data like `actions.load('user', {name: 'Jon', surname: 'Doe'})`
and then call `actions.reset('user')` the state.user looks like `{name: 'Jon'}` but if I also call  `actions.setInitial('user')` the state.user looks like `{name: ''}`

**Comment by davidkpiano** [comment]
When `1.5.4` is published (tomorrow) can you please see if you can still recreate this?

**Comment by konzz** [comment]
Sure!

**Comment by davidkpiano** [comment]
This has been fixed in recent versions - please get the latest version and make sure that this is fixed for your use case.

**Comment by konzz** [comment]
Thanks! Yes it's working perfectly now
