### ISSUE TITLE
The behavior of LocalForm which is connected to the external redux store

### ISSUE THREAD

**Issue by kostik-noir** [davidkpiano/react-redux-form#623]
Let's suppose I want to have the reusable form component like this one:

```js

// my-form.js

import React from 'react';
import { LocalForm, Field } from 'react-redux-form';

export default function MyForm({ onUpdate }) {
  return (
    <LocalForm onUpdate={onUpdate}>
      <Field model=".username">
        <input type="text" />
      </Field>
    </LocalForm>
  );
}
```

which I want to use so:

```js
// my-form-container.js

import React from 'react';
import { connect } from 'react-redux';
import MyForm from './my-form';
import * as actions from './actions';

const mapStateToProps = () => ({});

const mapDispatchToProps = (dispatch) => ({
  onUpdate() {
    dispatch(actions.onMyFormUpdated());
  }
});

export default connect(mapStateToProps, mapDispatchToProps)(MyForm);
```
But this does not work. There is only one call of the function `onUpdate` which is called from [componentDidMount](https://github.com/davidkpiano/react-redux-form/blob/master/src/components/form-component.js#L78). Later there are no calls of this function when user interacts with the form.  
The same is true for `onChange`. `onSubmit` is not called too.

Also I tried to use this approach:

```js
import React from 'react';
import { createStore } from 'react-redux';
import { Form, Field, combineForms } from 'react-redux-form';

const formName = 'myForm';

export class MyForm extends Component {
  constructor(props) {
    super(props);

    this.store = createStore(combineForms({
      [formName]: {
        username: ''
      }
    }));
  }

  render() {
    const { onUpdate } = this.props;

    return (
      <Form store={this.store} model={formName} onUpdate={onUpdate}>
        <Field model=".username">
          <input type="text" />
        </Field>
      </Form>
    );
  }
}
```

but the result is the same.

What is wrong?

---
the used libraries:

+ react@15.4.2
+ react-redux@5.0.1
+ redux@3.6.0
+ react-redux-form@1.5.3

the examples (see the output in the console when you interact with the form):

+ without `connect(...)`: http://codepen.io/anon/pen/BpWzzY
+ with `connect(...)`: http://codepen.io/anon/pen/xgqOEw

**Comment by davidkpiano** [comment]
> - react-redux@5.0.1

This is currently an issue with the latest `react-redux` - more info in this ticket: https://github.com/davidkpiano/react-redux-form/issues/592

**Comment by kostik-noir** [comment]
@davidkpiano 
thanks for the answer

**Comment by davidkpiano** [comment]
Please try this again with the [latest React-Redux](https://github.com/reactjs/react-redux/releases/tag/v5.0.3) version.

**Comment by alvinthen** [comment]
The behaviour of LocalForm is now as expected, only with one small warning from React

```
Warning: Unknown prop `storeSubscription` on <form> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

**Comment by davidkpiano** [comment]
Awesome, good catch!
