### ISSUE TITLE
No example on how to actually submit/process vaules with the native form.

### ISSUE THREAD

**Issue by krsmedlund** [davidkpiano/react-redux-form#625]
The documentation for the web seems to just add a `<button>` and use it as a submit.

For the native examples the submission is omitted and a note in the documentation says it does not have an onSubmit mechanism in the native `<Form>` but does not give any help/hints on what to use instead.

**Comment by davidkpiano** [comment]
Good catch. The Redux way of doing this would be to just connect your parent component with the model, and then handle the `onPress` to submit the model's values:

```jsx
class MyForm extends Component {
  handleSubmit() {
    const { user } = this.props;

    // submit the user however you'd want,
    // or dispatch(actions.submit('user', somePromise))
  }
  render() {
    return (
      // ...
      <Button onPress={() => this.handleSubmit()} />
      // ...
    );
  }
}
```

const mapStateToProps = ({ user }) => ({ user });

export default connect(mapStateToProps)(MyForm);
```

**Comment by davidkpiano** [comment]
Docs updated here: http://davidkpiano.github.io/react-redux-form/docs/guides/react-native.html

----

To submit a React Native form programmatically:
1. Ensure that the `<Form model="foo">` component has an `onSubmit={(values) => ...}` callback.
2. Dispatch a submit action for the form's model (and no other arguments): `dispatch(actions.submit('foo'))`

```jsx
<Form model="user" onSubmit={(vals) => console.log(vals)}>
  <Control.TextInput model=".firstName" />
  <Control.TextInput model=".lastName" />

  <Button onPress={() => dispatch(actions.submit('user'))} />
</Form>
```
