### ISSUE TITLE
Optionally let default happen

### ISSUE THREAD

**Issue by BerkeleyTrue** [davidkpiano/react-redux-form#626]
This doesn't seem possible at the moment but a requirement I have for my forms

**Comment by davidkpiano** [comment]
Can you please expand on this? I'm not exactly sure what you mean.

**Comment by BerkeleyTrue** [comment]
Sure:

My use case: I have forms that has action/method but I want to use react-redux-form to manage validation and also maintain the form state in redux. But the code without react-redux-form will always `preventDefault`. 

https://github.com/davidkpiano/react-redux-form/blob/master/src/components/form-component.js#L64

It would be great to have the option to let the default happen.

This is something I do regularly with redux-form. Usually with things like paypal buttons and mailchimp forms.

**Comment by davidkpiano** [comment]
Gotcha. For most use cases, preventing the default action of an event is preferable, I would think - otherwise, most forms would navigate to a different state/route, which is undesirable.

With that said, what do you think about `<Form preventDefault={false} >` ?

**Comment by BerkeleyTrue** [comment]
> For most use cases, preventing the default action of an event is preferable, I would think - otherwise, most forms would navigate to a different state/route

If you add `target='_blank'` the action will take place in a new tab keeping the user session active while they do whatever it is needed. 

> <Form preventDefault={false} > ?

Might be a good patch but the I believe a better option is to always leave it up to the developer, since developers are used to adding `preventDefault` to their event handlers.

Maybe adding that option in this version and then in the next update remove the call to `preventDefault` and letting the developer handle it.

**Comment by davidkpiano** [comment]
> Might be a good patch but the I believe a better option is to always leave it up to the developer

That was my first thought as well. This would probably be a breaking change, however. I will definitely pass the event as-is in V2.
