### ISSUE TITLE
Best practices for updating <Control.select> options on field value change

### ISSUE THREAD

**Issue by thomasboyt** [davidkpiano/react-redux-form#628]
Had a quick question around a fairly simple use case. I've got a form with a "country" dropdown, and then a "state/province" dropdown. When I change the country from "US" to "Canada," I want the state/province dropdown to change from displaying a list of US states to a list of Canadian provinces.

My initial strategy for this was simply to supply the form reducer to the form component and change the options accordingly:

```js
function mapStateToProps(state) {
  return {
    address: state.forms.shippingAddressForm,
  };
}

export class ShippingAddressForm extends Component {
  render() {
    const currentCountry = this.props.address.country;
    const stateProvinceOptions = getStatesOrProvincesForCountry(currentCountry);

    // return form using {stateProvinceOptions}
  }
}

export default connect(mapStateToProps)(ShippingAddressForm);
```

This sort of works, in that it does update the options in the form. However, it has one major flaw: If the user selects a state, then changes their country, it doesn't unset the previously-selected state.

Unfortunately, I don't immediately see a good pattern for this. I'm sure there's a few ways to do this - one of which would be to use some sort of custom reducer, though I'm not sure what that'd look like, and it seems like a lot of boilerplate - but is there a "best practice" way to handle this use case?

**Comment by davidkpiano** [comment]
This looks like a very similar solution: https://github.com/davidkpiano/react-redux-form/issues/620#issuecomment-273768987

In short, you would solve this the same way you would solve it using just React + Redux. That is, have an `onChange` handler that ensures that the second value is related to the first value.

Alternatively, you can make this special "two-in-one" custom component and manage the logic of what is selected in component-specific state. Then, you can just do the custom component pattern of `<Control component={CountryStateSelector} />` or something like that.

**Comment by thomasboyt** [comment]
Oh, I didn't realize you could just pass `onChange` through to a `<Control.select />` (or, in my specific case, a `<Field />` that wraps a `<select />`). Is that explicitly documented somewhere I missed?

This handler seems to work :)

```js
    handleCountryChange(evt) {
        const newCountry = evt.target.value;
        const newStates = getStatesOrProvincesForCountry(newCountry);
        this.props.dispatch(actions.change('forms.shippingAddressForm.stateOrProvince', newStates[0].value));
    }
```

**Comment by davidkpiano** [comment]
> Is that explicitly documented somewhere I missed?

I should probably add that, but you can pass any props that you would normally pass to the component anyway, and they'll be passed to the component.
