### ISSUE TITLE
Form + Field validation errors

### ISSUE THREAD

**Issue by GarrisonD** [davidkpiano/react-redux-form#635]
Hello, guys!

I don't know for sure if it is bug or I am doing something wrong, but there is no form validation error, only field one. 

How can I get form validation error too?

http://codepen.io/garrisond/pen/OWOZpW

**Comment by GarrisonD** [comment]
And if you add `console.log` to form validators function, it will print nothing when you change input's value to valid one or submit the form. So it looks like this function isn't invoked at all.

**Comment by GarrisonD** [comment]
I would like to help you with solving this and other issues, but unfortunately I can't understand how to debug it 😢

**Comment by GarrisonD** [comment]
@davidkpiano Thank you for your fast fix.

But when I install `react-redux-from` package via `npm install <git-repository>`, then webpack tells me that there is no `react-redux-form` package.

And really there is no `lib` directory in `node_modules/react-redux-form`.

How can I fix this?

**Comment by davidkpiano** [comment]
Try `rm -rf ./node_modules` and `npm install` again, if you're having issues with `npm`. Also, try installing via `npm install react-redux-form --save`
