### ISSUE TITLE
Tracking: form submits unaltered initialiser object

### ISSUE THREAD

**Issue by richchurcher** [davidkpiano/react-redux-form#640]
Thanks for all the work on this excellent library!

I've been playing with tracking, as while the documentation is very good so far it doesn't have many examples of edit forms, or pre-populated forms. I'd be very happy to contribute one by the way, I just would like to understand the desired process better first.)

Take the following example, working with a Redux container (sorry no esnextbin, it throws all kinds of mixed content errors for me):

http://codepen.io/richchurcher/pen/xgjGrB?editors=0010#0

```js
const thing = {
  id: 0,
  name: ''
}
const reducers = combineReducers({
  things,
  forms: combineForms({ thing }, 'forms')
})
const store = createStore(reducers)

const editThingForm = React.createClass({
  handleSubmit (thing) {
    console.log(thing)
    this.props.save(thing)
  },

  render () {
    return (
      <Form model="forms.thing"
        onSubmit={thing => this.handleSubmit(thing)}>
        <label>Thing:</label>
        <Control.text model={track('things[].name', { id: this.props.id })} />
        <button type="submit">Save</button>
      </Form>
    )
  }    
})
const mapDispatchToProps = dispatch => ({
  save: thing => dispatch(saveThing(thing)),
})
const EditThingForm = connect(null, mapDispatchToProps)(editThingForm)
```
The overall component structure is something like:
```js
<Provider>
  <App>
    <ThingsContainer>
      <Things>
        <EditThingForm>
```
Although I can quite happily get the control to populate with the correct value, when the form is submitted the argument `handleSubmit` receives is still the unaltered initial model (`name` is blank, `id` is 0).

Is there a tracking syntax intended for use in the model prop of `Form`? I can't see it in the docs, so not quite sure if I've misunderstood or found a bug. An edit or pre-populated form example would be awesome, and I can turn it into a documentation PR for you :)

**Comment by davidkpiano** [comment]
Ah, so the issue here is that currently, your state looks like this:

```js
{
  thing: { id: 0, name: '' },
  things: [...], // < RRF only knows about *this*
}
```

RRF has no idea about what `thing` is because it wasn't part of `combineForms`. If you simplify this, you'll see that it just works:

```jsx
const reducers = combineForms({ things });

// ...

  render () {
    return (
      <Form model={track('things[]', { id: this.props.id })}
        onSubmit={thing => this.handleSubmit(thing)}>
        <label>Thing:</label>
        <Control.text model=".name" />
        <button type="submit">Save</button>
      </Form>
    )
  }   
```

Notice how I moved the `track(...)` to the `<Form model={...}>` instead of the control. Hope this makes sense!

**Comment by richchurcher** [comment]
Ah, I see. I'd been assuming that `combineForms` always expects the single object as a 'model'. I'll see if I can come up with a clarifying example for the docs. Thanks!
