### ISSUE TITLE
Using action think creators in localform

### ISSUE THREAD

**Issue by sniepoort** [davidkpiano/react-redux-form#643]
How would you go about using for example, actions.push, in a local form?
Using the localforms dispatch, set on intial load, gives an error. Actions.change works because it doesn't rely on thunk middeware.

Ideas?
Something ala this would be great:
this.messageFormDispatch(FormActions.push('message.images', result.filename))

Of course, I could just retrieve the array from my state and then dispatch a change with a new file manually pushed. But would like to do it the "right" way :)

**Comment by davidkpiano** [comment]
Remember that thunks have the signature `(dispatch, getState) => ...`. And because you have the form state in your component state already, you can "dispatch" the thunks like this:

```js
FormActions.push('message.images', result.filename)(this.messageFormDispatch, this.state.message);
```

Hope that helps!
