### ISSUE TITLE
Nested reducer, mapStateToProps, and ImmutableJS

### ISSUE THREAD

**Issue by aestock** [davidkpiano/react-redux-form#647]
Hey there. I'm using ImmutableJS (and therefore the `/lib/immutable` version of `combineForms`) and need some help sorting some things out.

Below is my nested reducer:

```js
const createEvent = fromJS({
  comment: '',
  link: '',
});

export default function createReducer() {
  return combineReducers({
    report: combineReducers({
      summary: summaryReducer,
      components: componentsReducer,
    }),
    deep: combineForms({createEvent}, 'deep'),
  });
}
```

This JS is producing a state object like below:

```js
{
  report: [Object]
  deep: {
    createEvent: [Map]
    forms: {
      $form: [Object]
      createEvent: {
        $form: [Object]
      }
    }
  }
}
```

This is mostly what I expect, but I'm not really sure if the `createEvent` **Map** is supposed to be there or what purpose it serves. I'd like to cut to the chase and just have the `forms` Object be a top-level item if possible but have not been successful in trying to do so.

Second, I am trying to selectively `mapStateToProps` in my Form component (so I'm only sending that part of the state to the component).

```
class CreateEvent extends Component {
   ...
}

function mapStateToProps(state) {
  return state.get('deep').toJS();
}

export default connect(mapStateToProps)(CreateEvent);
```

However, this is producing an error (no webpack errors, masked by a general error in the console). If I change `deep` to `report` instead, it works perfectly fine. I can't understand why I cannot retrieve this Object even though it appears in the state (as shown above).

Any assistance in getting everything to play nice would be hugely appreciated.

**Comment by davidkpiano** [comment]
> ...I'd like to cut to the chase and just have the forms Object be a top-level item if possible but have not been successful in trying to do so.

Try using [`createForms`](http://davidkpiano.github.io/react-redux-form/docs/api/createForms.html) instead of `combineForms`. Let's see if that solves the second problem as well.

**Comment by aestock** [comment]
Ah, nice. I think I tried that syntax, missed that it was `createForms` and not `combineForms`. That's producing the structure I was hoping for. Still an extra createEvent Object in the root, but I guess that's by design.

```
{
  createEvent: [Object]
  report: [Object]
  forms: {
    $form: [Object],
    createEvent: {
      $form: [Object],
      comment: [Object]
      link: [Object]
    }
  }
}
```

I solved my second problem by omitting the `.toJS()` transformation in the return statement. So, it seems `forms` is just a standard Object rather than an Immutable Map like it should be?

**Comment by davidkpiano** [comment]
Yes, `forms` will always be a standard Object. RRF was created to work with most standard use-cases of React and Redux, and making form state an Immutable.JS Map would increase complexity and code size, which is unfavorable. Personally, I don't advocate using Immutable.JS - it's additional complexity and abstraction for very little gain in most use cases.

**Comment by aestock** [comment]
Understandable. I misunderstood what to expect with Immutable.JS compatibility. Unfortunately I'm forced to use a project boilerplate that uses it. But this will still work without `.toJS` in `mapStateToProps` and perhaps this thread will help someone else who might be make incorrect assumptions like me. Thanks!
