### ISSUE TITLE
setup error for universal environment

### ISSUE THREAD

**Issue by beckmeindia** [davidkpiano/react-redux-form#648]
Hey,
I am using a standard universal environment and my createStore(createReducer(), initialState, compose(...enhancers)) takes 3 args
If i try to add combineForms as a param it fails and throws error for the same.

Please suggest!

Thanks

**Comment by davidkpiano** [comment]
Can you show me your current code? `combineForms()` is to be used in place of `combineReducers()`.

**Comment by beckmeindia** [comment]
hey @davidkpiano my present store looks like this. I did think of combineforms as combinereducers and placed the respective in my reducers.js but that failed too

> import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import axios from 'axios';
import chalk from 'chalk';
import { browserHistory } from 'react-router';
import { routerMiddleware } from 'react-router-redux';
import createReducer from './reducers';
export default (initialState) => {
  const middlewares = [
    thunk.withExtraArgument(axios),
    routerMiddleware(browserHistory),
  ];
  const enhancers = [
    applyMiddleware(...middlewares),
    __DEV__ && typeof window === 'object' && typeof window.devToolsExtension !== 'undefined' ?
      window.devToolsExtension() : f => f,
  ];
  const store = createStore(createReducer(), initialState, compose(...enhancers));
  store.asyncReducers = {}; // Async reducer registry
  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('./reducers', () => {
      try {
        // eslint-disable-next-line import/newline-after-import
        const reducers = require('./reducers').default;
        store.replaceReducer(reducers(store.asyncReducers));
      } catch (error) {
        console.error(chalk.red(`==> 😭  Reducer hot reloading error ${error}`));
      }
    });
  }
  return store;
};

Let me know what needs to be done or should I just use LocalForms due to my setup.
By the way I am using [this-starter](https://github.com/wellyshen/react-cool-starter) as the universal boilerplate

Thanks

**Comment by davidkpiano** [comment]
I don't see React-Redux-Form being used in the above code. Can you show me the relevant code that is failing?

**Comment by beckmeindia** [comment]
Hey David, so I have not been able to change my store.js file yet because I already have a createreducer() which needs to be passed. So all I have been doing is wondering how to put both the createreducer() as well as combineForms() together. As of now my store looks the same way. I although tried 

>  createStore(combineForms({ user: value }), createReducer(), initialState, compose(...enhancers))

But it has the same problem as I said above about passing only 3 params to createstore

Thanks

**Comment by davidkpiano** [comment]
What does `createReducer()` look like?

**Comment by beckmeindia** [comment]
createReucer is just a combinereducers() 
Also I was seeing that there are options of adding things to combineducers in this lib with modelReducer and etc.

**Comment by davidkpiano** [comment]
Yeah, as long as the first argument is a reducer, it should work. Instead of using `combineReducers()`, use `combineForms()`, which returns a reducer.
