### ISSUE TITLE
Best way to add validation error from server?

### ISSUE THREAD

**Issue by BrainB** [davidkpiano/react-redux-form#649]
When validating I am making async request to REST server and I do not know what type error I get in return. However I can get error string from response which I would like to add as validation error to Component.

What would be best way to achieve this ?

**Comment by davidkpiano** [comment]
You would just `dispatch(actions.setErrors('your.model', 'Your string error', { async: true }))`. Does that answer your question?

**Comment by davidkpiano** [comment]
Hopefully this answered your question! Feel free to follow up if you have further questions.
