### ISSUE TITLE
Problem with custom Field component in production build

### ISSUE THREAD

**Issue by i4got10** [davidkpiano/react-redux-form#65]
I made my own field-wrapper wrote for react-bootstrap following "Custom Component Recipe"

```jsx
import { createFieldClass, controls } from 'react-redux-form';

export const TextField = createFieldClass({
    'Input': props => ({
        onChange: (event, val) => props.onChange(event.target.value),
        value: props.modelValue
    })
});

export const CheckboxField = createFieldClass({
    'Input': props => ({
        onChange: (event, val) => props.onChange(event.target.value),
        checked: !!props.modelValue
    })
});
```

While development everything seems to be ok, but in production form doesnt work properly. Problem here is that in production UglifyJs change component name to shortcuts like "k" or "t"(if DisplayName not specefied)

One way to solve this is specify displayName, or make new prop that specify it.

I use that workaround right now

```js
import { Input } from 'react-bootstrap';

Input.displayName = 'Input';
```

**Comment by davidkpiano** [comment]
Interesting. I don't know the best way to solve this other than for developers to just use your solution (which seems simple enough to do). Honestly, a good React UI package _should_ provide `displayName` for their custom components anyway.

React-Redux-Form looks for the display name in order to map the props correctly.

**Comment by davidkpiano** [comment]
Docs updated here to highlight best practices for components without a `displayName`: https://davidkpiano.gitbooks.io/react-redux-form/content/react_native_&_custom_components.html#custom-components

**Comment by i4got10** [comment]
Thanks!

**Comment by prawana-perera** [comment]
Thanks, helped me with my issue using reac-bootstrap:
`
const FormField = createFieldClass({
    'FormControl': controls.text
}, {
    componentMap: {
        FormControl: FormControl // recognize component by constructor
    }
});
`
