### ISSUE TITLE
React Native Babel error - react-dom - shallow-compare - babel-preset

### ISSUE THREAD

**Issue by tdurand** [davidkpiano/react-redux-form#654]
Hi, 

First thanks for your work on that library, I'm currently trying to use it for my React Native project, and i'm running into a weird issue. I get that error when I follow the quick start with latest React native and react redux form version.

## How to reproduce:

- react-native : 0.41.2
- react-redux-form : 1.5.5

```
react-native init myApp
yarn add react-redux-form redux react-redux
yarn install
```
copy paste this index.ios.js code:

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import { Control } from 'react-redux-form/native';

import {
  createStore,
  applyMiddleware
} from 'redux';
import { combineForms } from 'react-redux-form';

const initialUserState = {
  firstName: '',
  lastName: ''
};

const store = createStore(combineForms({
  user: initialUserState,
}));

export default class myApp extends Component {
  render() {
    return (
       <Provider store={ store }>
        <View style={styles.container}>
          <Control.TextInput model="user.firstName" />
        </View>
      </Provider>
    );
  }
}

```

And finally:

**react-native run-ios**

## Description of the error:

![screen shot 2017-02-13 at 16 10 43](https://cloud.githubusercontent.com/assets/533590/22888812/4a4ce754-f207-11e6-9bc9-0944b0fddbe1.png)

Then I've added react-dom to the dependencies even if it normally isn't needed since you added that commit : https://github.com/davidkpiano/react-redux-form/commit/5be90a076209acdfbd79b77c62cbf1b2d0c182ed

But then I get another error:
![screen shot 2017-02-13 at 16 09 28](https://cloud.githubusercontent.com/assets/533590/22888904/9d6a43a0-f207-11e6-800f-fcb3b23123fc.png)

And if I try to add some babel preset I run into other errors ...

I'm trying to figure it out by myself, but if you have some idea, it's much welcome.

**Comment by tdurand** [comment]
I confirm it is babel related, I have manage to get react-redux-form worked in the react native app by adding the following devDependencies:

```
"babel-preset-es2015": "*",
"babel-preset-es2015-minimal": "^2.1.0",
"babel-preset-stage-0": "^6.22.0",
```

And that in the package.json:

```
"babel": {
    "presets": [
      "stage-0",
      "es2015",
      "es2015-minimal",
      "react-native"
    ]
  }
```

If I understood correctly it seems that react-native is compiling again react-redux-form, shouldn't it use the ES5 outputed version ? Also should we be able to use react-redux-form without react-dom in react native ?

Let me know if I can help, but hopefully this will help some other people stuck with React Native.

**Comment by davidkpiano** [comment]
You're right, it should ideally read from the ES5 version of the code. It worked at one point (since react-native does its own Babel transpilation) but I guess it doesn't work now. Will fix soon.

**Comment by aditya2592** [comment]
Hi @tdurand. Not able to run on react-native with these settings also. Is there any other change required?

**Comment by dfcarpenter** [comment]
This just happened for me with the latest version and the changes suggested by @tdurand aren't working. Any ideas?

**Comment by davidkpiano** [comment]
@dfcarpenter How are you importing `react-redux-form`?
