### ISSUE TITLE
How To Use “array of objects whith array” In “React-Redux-Form”

### ISSUE THREAD

**Issue by pquelmht** [davidkpiano/react-redux-form#655]
I want to have variable of model structured like this:

```
specialCondtions: [
   { terms: [ {obj1a},{obj2a},... ] }
   { terms: [ {obj1b},{obj2b},... ] }
   { terms: [ {obj1c},{obj2c},... ] }
   { terms: [ {obj1d},{obj2d},... ] }
]
```
So something like array of arrays. The problem is that at the begging I have only empty array in model

`specialCondtions: []`

Now first obj1a comes form user input. I can not use this:

```
let obj={terms:[]}
obj.terms.push(obj1a)
dispatch(actions.push("model.specialCondtions",obj))
```

because I get following error:

```
Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.
This is not async , so I am probably doing something wrong.
```

**Comment by davidkpiano** [comment]
You probably don't have `redux-thunk` set up in your middleware. That is required for doing anything besides a simple `actions.change`.

**Comment by pquelmht** [comment]
Hello,
Sorry I was probably following wrong guide:

[(http://davidkpiano.github.io/react-redux-form/docs/guides/quickstart.html)]((http://davidkpiano.github.io/react-redux-form/docs/guides/quickstart.html))

as it says that : "redux-thunk is no longer required for versions 1.3.0 and higher. If you are using a previous version, make sure to install it as well."

and now I found out here is also guide: 
[https://davidkpiano.gitbooks.io/react-redux-form/](https://davidkpiano.gitbooks.io/react-redux-form/)

Which one is actual or both?

**Comment by davidkpiano** [comment]
> Ah i see its required for anything besides actions.change

Yes, that's correct. And it is pretty clear in the most up-to-date docs here: http://davidkpiano.github.io/react-redux-form/docs/api/actions.html . However, I'll update the quickstart docs.
