### ISSUE TITLE
nested reducer + immutableJS + init value :question

### ISSUE THREAD

**Issue by abudel** [davidkpiano/react-redux-form#657]
Hi! 
i'm trying to use immutableJS with nested reducer. but what i got doesn't work.
my state should look like this:
```
...
user: Map
    profile: Map
        firstName: String
        lastName: String
...
```

i have a reducer, listening for the success fetch of the profile info from the server:
```
export const initState = Immutable.fromJS({firstName:'', lastName:''})
export const function reducer(state = initState, action) {
switch(action.type){
case 'FETCT_PROFILE_SUCCESS': return state.merge(action.payload)
}
```

and from the rootReducer i try with this

```
export default combineReducer({
user: combineReducers({
profile: modeled(profileReducer, 'user'),
forms: formReducer('user', initStateFromProfileReducer)
})
```

from my view ( i use react native ) this is my code
```
mapStateToProps = (state) =>({
profile: state.getIn(['user', 'profile']).toJS(),
form: state.getIn(['user','forms']).$form
})
<Form model="user.profile" >
<Control.TextInput model=".firstName" />
<Control.TextInput model=".lastName" />
<Button onPress={this.onSubmit.bind(this)}>SUBMIT</Button>
</Form>
```
i also use some validation, but it looks like the model it's not updated, and the validation fails.
And when the button is pressed the model this.props.user.profile still the same when was retrieved from the server.

I also tryed to use createForms, or combineForms, but i can not found a way to use my reducer.
Do you have any advise ?

thank you! 
Btw, awesome library!! :D

**Comment by davidkpiano** [comment]
Your code's a little bit confusing, but why not try this:

```js
export default combineForms({
  user: Immutable.fromJS({ profile: { firstName: '', lastName: '' } })
});
```

I'd start there and see if that works for your use case.

**Comment by abudel** [comment]
First of all thanks to get time to answer!
i tried also in that way, but by using combineForms and instead of passing a initalState, i'm going to pass a reducer.
So my rootReducer look like this:
`
....
user: combineForms({
        profile: profileReducer,
    }, 'user'),
....
`
But when i access to the state, "profile" is not a Immutable object is a plainObject. ( i'm using 'react-redux-form/immutable' )

state.get('user')
Object {profile: Map, forms: Object}

And if i'm using combineReducers, i will get a regular Immutable object.

Is it the correct behaviors ?

Thanks

**Comment by davidkpiano** [comment]
Right - `combineForms` will return a plain JS object. The model state _inside_ that object will be whatever you give it (in this case, an Immutable `Map`).

There's a good reason for this - the form state is always a plain JS object, and RRF needs a way to access that object without jumping back and forth between ImmutableJS and plain JS objects.

**Comment by abudel** [comment]
Thanks for the tips.

if someone is interests on it, I made it works by using the rootReducer like this:

```
user: combineReducers({
        ...createForms({
            profile: userReducer
        }, 'user')
        
    }),
```

and changed in my view

```
mapStateToProps = (state) =>({
        profile: state.getIn(['user', 'profile']),
        form: state.getIn(['user', 'forms']).$form
})
```

In this way it seams to works as aspected.
