### ISSUE TITLE
confused about custom controls

### ISSUE THREAD

**Issue by greaber** [davidkpiano/react-redux-form#66]
I'm confused about how to use custom controls in a really simple case.  My controls use the standard props `onChange` and `value`, so I don't think I should need to do any special mapping.  But I'm still not sure what I am supposed to do.

I looked a little at the source, but I am still confused.  One thing I wondered about is why the Control component specifies that `modelValue` should be a string in its propTypes -- couldn't it be anything?

Here is a simplified version of one of my controls (not tested).  The real control does some validation and normalization (some of which React Redux Form could help with, but I prefer to do it in my custom controls, let's say).

```javascript

class DayAndMonthInput extends Component {

    render() {

        const {onChange, value} = this.props

        return (
            <div>
                <input type="text"
                       onChange={e => onChange({day: e.target.value, month: value.month})}
                       value={value.day}
                />
                <input type="text"
                       onChange={e => onChange({day: value.day, month: e.target.value})}
                       value={value.month}
                />
            </div>
        )
    }
}

DayAndMonthInput.defaultProps = {
    value: {day: 'xxx', month: 'yyy'}
}
```

**Comment by davidkpiano** [comment]
You can always use RRF as simply a collection of actions and reducers to update the relevant state of each of your fields. In this case, you can use RRF with your component defined above like so:

Suppose your date lives in the `user.birthdate` model:

```js
// in render():
const { user } = this.props;

return (
<DayAndMonthInput
  onChange={val => dispatch(actions.change('user.birthdate', val))}
  value={ user.birthdate } />
);
```

This should work. Does this make sense?

**Comment by greaber** [comment]
Yes, this approach makes sense.  But I am confused about how I would use the Field component if, for whatever reason, I wanted to.  I may just be overlooking something very obvious.

**Comment by davidkpiano** [comment]
If you are doing it like I did it in the code sample above, you don't need `<Field>`. The `<Field>` component is just a helper that abstracts all that for convenience; it's definitely optional.

**Comment by greaber** [comment]
Whatever convenience bonus the Field component adds, shouldn't I be able to get it for my custom component?  Or if the added convenience is trivial, shouldn't it be trivial when using stock components too?  I'm not yet seeing why using the Field component makes sense in one case but not the other.

**Comment by davidkpiano** [comment]
Yes - and here's how you can do it:

```js
const CustomField = createFieldClass({
  DayAndMonthInput: (props) => ({
    onChange: props.onChange,
    value: props.modelValue
  });
});

// Then use it:
<CustomField model="user.birthdate">
  <DayAndMonthInput />
</CustomField>
```

Of course, it's best to give your `DayAndMonthInput` a `.displayName = "DayAndMonthInput"`.

**Comment by greaber** [comment]
OK, thanks.  This is what I tried initially (although I didn't think about the displayName issue -- I thought an advantage of JSX was never having to think about that).  It wasn't working, but it is possible that is due to some other issue in my code.  I will try to make it work (or just go with the non-Field-involving approach you first suggested).  I'll let you know how it goes.

**Comment by davidkpiano** [comment]
Okay, please do! `createFieldClass` just lets you avoid having to manually map everything every single time.

**Comment by greaber** [comment]
It looks like the Field-involving approach you suggest doesn't work because the mapping of `value` to `props.modelValue` gets overwritten by the value of `value` in  `props` itself.  I was able to make my component work by changing

```
const {onChange, value} = this.props
```
to
```
const {onChange} = this.props
const value = this.props.modelValue || this.props.value
```
although I get a warning that `modelValue` is failing its propTypes check since it has type object instead of type string.  (As I said in my original message, I am confused about why that propType check is being done.)

**Comment by davidkpiano** [comment]
Just pushed `react-redux-form@0.8.5` that fixes the propType issue!

Also, you can mitigate that issue with `<Field>` by just adding value to your custom control:

```js
<CustomField model="user.birthdate">
  <DayAndMonthInput value={ user.birthdate } />
</CustomField>
```

I'll look into why `defaultProps` might have the behavior of overwriting the value.

**Comment by greaber** [comment]
Thanks.

It looks like `defaultProps` in general take precedence over mappings specified using `createFieldClass`.  Probably that should be changed.  I looked through the code of React Redux Form, and it appears to me that the overwriting may be happening in the control component, here:

```
return cloneElement(
      control, {
        ...this.props,
        ...control.props,
      });
```

I also found a couple other places where there is props merging that may be questionable (but I'm not sure).

It looks like the controls you define in `controlPropsMap` are explicitly merging in the existing props last, which would override those mappings if I were using those, e.g.:

```
text: props => ({
  defaultValue: props.modelValue,
  name: props.model,
  ...props,
}),
```

In `createFieldControlComponent`, there is this code that seems to recursively accumulate props on nested components, which looks wrong to me, but I may be misunderstanding:

```
 if (!controlProps) {
   return React.cloneElement(
     control, {
       children: React.Children.map(
         control.props.children,
         child => createFieldControlComponent(
           child,
           { ...props, ...child.props },
           options
         )
       ),
     }
   );
 }
```

Also, in my own component, I wonder if it would be better form to set `defaultValue` using `defaultProps` and not `value`, and then I would not encounter any problem.  However, that is not really how `defaultValue` is used in the text component (see the mapping I quoted above).  That makes me wonder if I am confused about the semantics of `defaultValue` -- I would have guessed that the text control would map `value` to `props.modelValue`, not `defaultValue`.

More generally, it might be useful to have in the docs a recommendation about how to design the props on custom components if one has the luxury of doing so.  And the recommended ways should have preset mappings in `controls` under suitably named keys.

**Comment by davidkpiano** [comment]
> In createFieldControlComponent, there is this code that seems to recursively accumulate props on nested components, which looks wrong to me, but I may be misunderstanding:

Yeah, don't worry - props aren't accumulated recursively. Rather, the component tree is traversed to look for valid controls inside `<Field>` - if a component is not a control, it is ignored.

The `defaultValue` mapping is for when you have set an `initialState` in your `modelReducer` - it properly reflects the value in the `<input>`. 

> That makes me wonder if I am confused about the semantics of defaultValue -- I would have guessed that the text control would map value to props.modelValue, not defaultValue.

It's important that the components remain uncontrolled - since RRF allows you to update the model value at any time, e.g. on blur or debounced, etc. Which, of course, would be problematic if the components were controlled.

> More generally, it might be useful to have in the docs a recommendation about how to design the props on custom components if one has the luxury of doing so. And the recommended ways should have preset mappings in controls under suitably named keys.

Agreed. I'm thinking for certain components, it's better to manually map them yourself, which isn't difficult at all. The example (from the [previous comment](https://github.com/davidkpiano/react-redux-form/issues/66#issuecomment-195468949)) demonstrates this pretty well.
