### ISSUE TITLE
Form onSubmit, bypass validity check

### ISSUE THREAD

**Issue by sniepoort** [davidkpiano/react-redux-form#662]
I have (maybe) an edge case here, where I would like to display server side validation errrors/field validity, but don't really care about client side validation. So, after setting errors on a form due to server response, i currently can't submit the form again because it is invalid. 
I feel that Form should have a boolean prop where you can overide if it should submit even if it is invalid. 
Until that happens, any workaround solutions? Other than dispatching a submit onSubmitFailed?

**Comment by davidkpiano** [comment]
You can manually submit a form by dispatching `actions.submit(model, promise)` and then get the errors from there, does that help?

**Comment by sniepoort** [comment]
Yes, right not the workaround is just to manually dispatch my async action on a button click.
It would still be great to be able to override it in the Form component though :) 

However, after I have done this, I need to reset the forms validity after a succesful post.
resetValidity is not working. I'm getting a type error:
`Cannot read property 'valid' of null` 
I am correct in the understanding the resetValidity, when provided with a form model, will set validity back to true for all fields?

**Comment by davidkpiano** [comment]
Can I see your code?

**Comment by sniepoort** [comment]
`const saveTask = (task) => {
  return dispatch => {
    api.put('/task/${task.id}', task)
    .then(({ body }) => {

      dispatch(FormActions.merge('data.task.current', body))
      dispatch(notifySuccess('Task blev gemt'))
      dispatch(FormActions.resetValidity('data.task.current'))
    })
    .catch(error => {
      console.log(error)
      if (error instanceof ApiError) {
        dispatch(notifyDanger('Der skete en fejl'))
      }
      if (error.body.metadata) {
        dispatch(FormActions.setFieldsErrors('data.task.current', error.body.metadata))
      }
    })
  }
}
`

**Comment by sniepoort** [comment]
@davidkpiano any luck on this? i'm kind of stuck :)

**Comment by davidkpiano** [comment]
Over here, try this:

```diff
      if (error instanceof ApiError) {
        dispatch(notifyDanger('Der skete en fejl'))
      }
      if (error.body.metadata) {
-       dispatch(FormActions.setFieldsErrors('data.task.current', error.body.metadata))
+       dispatch(FormActions.setFieldsErrors('data.task.current', error.body.metadata, { async: true }))
      }
    })
```

By providing `{async: true}` as an option, it will tell RRF that server validation came from _outside_ normal validation (i.e., it came from async validation), which will let it be submitted again.

**Comment by sniepoort** [comment]
That is nifty :)
However, I'm still stuck on the resetValidity not working, which i still need to do when a succesful response comes from the server

**Comment by davidkpiano** [comment]
Can you verify that `body` is not `undefined` here:

```js
dispatch(FormActions.merge('data.task.current', body))
```

**Comment by sniepoort** [comment]
It is not undefined. 
However, this morning I stumbled upon the problem. Our knex + bookshelp was outputting interval types in the format { minute: '' , hours: ''}, and not in ISO 8601 as we were expecting. So, when merging the new task into redux forms, one of the fields suddenly had an object instead of a string as it was set up to be. So I guess resetValidity was trying to loop over this object that didn't have a corresponding form key, or something like that? 

Thanks for the help :)

**Comment by davidkpiano** [comment]
> So I guess resetValidity was trying to loop over this object that didn't have a corresponding form key, or something like that?

Sounds about right. Closing this as it seems you've found your solution (please let me know if I'm wrong!)

**Comment by sniepoort** [comment]
Hey again @davidkpiano 
I unfortunately got the same problem again, although this time it can't be attributed to to an unknown object being returned. 
It still seems like updateSubFields (from your utils lib) is trying to set validity on a field that doesn't exist? I've double checked that all fields i get returned from my server are included in my initial form reducer. 
I tried logging subField in updateSubFields, and got this:

``` javascript 
Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}
Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}errors: Objectfocus: falseinitialValue: 1intents: Array[1]model: "data.task.current.property_id"pending: falsepristine: falseretouched: falsesubmitFailed: falsesubmitted: falsetouched: falsevalid: truevalidated: falsevalidating: falsevalidity: Objectvalue: 4__proto__: Object
Object {focus: false, pending: false, pristine: false, submitted: false, submitFailed: false…}errors: Objectfocus: falseinitialValue: ""intents: Array[0]model: "data.task.current.priority"pending: falsepristine: falseretouched: falsesubmitFailed: falsesubmitted: falsetouched: falsevalid: truevalidated: falsevalidating: falsevalidity: Objectvalue: null__proto__: Object
Object {$form: Object, validated: false, retouched: false, intents: Array[1], pristine: false…}
 false
Array[1]0: Objecttype: "validate"__proto__: Objectlength: 1__proto__: Array[0]
false
null
TypeError: Cannot read property 'valid' of null
    at Object.assoc (http://localhost:5000/assets/app.bundle.js:14705:12)
    at http://localhost:5000/assets/app.bundle.js:14832:15
    at Array.reduce (native)
    at singleAssign (http://localhost:5000/assets/app.bundle.js:14831:29)
    at Array.reduce (native)
    at Object.assign (http://localhost:5000/assets/app.bundle.js:14825:33)
    at updateSubField (http://localhost:5000/assets/app.bundle.js:18758:29)
    at http://localhost:5000/assets/app.bundle.js:18745:26
    at Array.forEach (native)
    at http://localhost:5000/assets/app.bundle.js:18741:30
```

Not sure if you can see anything useful there, so let me know what else i could do to diagnose

**Comment by sniepoort** [comment]
I did some more digging, and I think it has to do with the way I have been mixing LocalForms into the equation. 
The problem arises in my initial form state. Here I have some normal fields that have a matching input/edit in my form. Normal stuff. However, I also have some fields that are designated as arrays. One example (which is the first one that fails in the about console log), is contact_persons. This is an array of objects, but the objects themselves do not have corresponding form fields in my initial form. To add a new contact person, a modal opens up with a LocalForm, where the fields are specified there. Upon "saving" the contact person, I push this object to the array of contact persons. And then on a save of the whole form, I throw the whole form to the server. 
The problem arises when there for example are no contact persons added yet, and the server returns a null value (these persons are just saved as a json string). I guess this null value gets merged into my state, and contact persons is no longer an array but just a null value. 
 
This seemed like a smart way to mix redux forms with these local forms, but it's possible that I misunderstood how you imagined local forms should be implemented.  
However, I think my specific problems comes from redux forms expecting array values, but getting null values returned.

**Comment by davidkpiano** [comment]
If you can give me a reproducible code example (you can fork this CodePen: http://codepen.io/davidkpiano/pen/2cbfd61bdcff474ca6e40e8ed2221ef9 ) I'd be better able to diagnose and hopefully fix the problem.
