### ISSUE TITLE
Jest tests fail because of babel transformations not applied

### ISSUE THREAD

**Issue by gvidon** [davidkpiano/react-redux-form#663]
This https://github.com/davidkpiano/react-redux-form/blob/master/immutable.js#L2 have broken jest tests in one of my apps.

![2017-02-14 23 09 36](https://cloud.githubusercontent.com/assets/58164/22947081/b945c578-f30a-11e6-809c-6084d7f4df0d.png)

Jest does not apply babel transformations to `node_modules/` by default https://facebook.github.io/jest/docs/configuration.html#transformignorepatterns-array-string

**Comment by davidkpiano** [comment]
Instead of importing directly from the folder, import from the `lib` directory:

```js
import { Control, Form, /* etc. */ } from 'react-redux-form/lib/immutable';
```

**Comment by gvidon** [comment]
@davidkpiano do you mean it is a proper way to import from `lib/immutable` instead of `/immutable` or is it just a temporary fix?

**Comment by davidkpiano** [comment]
I would point to it being the proper way and change the documentation to reflect that.

**Comment by gvidon** [comment]
@davidkpiano thanks!

**Comment by cal0610** [comment]
@gvidon @davidkpiano  this had me scratching my head for a while, yet another issue I had in my project which is not documented, thank you for pointing me to the right direction.
