### ISSUE TITLE
Form type='multipart' not working

### ISSUE THREAD

**Issue by stanleycyang** [davidkpiano/react-redux-form#664]
I'm uploading some images along with my form. However, when I specify `type='multipart/form-data` it's not working. 

What can do to enable image uploading for this form?

**Comment by davidkpiano** [comment]
Do you mean `enctype="multipart/form-data"`?

**Comment by stanleycyang** [comment]
Oops yes. I tried `encType` per the React specs however that doesn't work. Now I'm just passing it via `FormData` to the backend instead

**Comment by davidkpiano** [comment]
Can you show me a fully reproducible code example?

**Comment by davidkpiano** [comment]
Added to FAQs here: http://davidkpiano.github.io/react-redux-form/docs/guides/faqs.html
