### ISSUE TITLE
Remove and change collection items in bulk

### ISSUE THREAD

**Issue by marcpeterson** [davidkpiano/react-redux-form#669]
I have a scenario similar to #553 in which I have an array of form items.  There are situations in which I'd like to clear or modify some (or all) of the array items.  I know I can dispatch actions.remove('model', index) and actions.change('model', value) on each item in a loop.  Is that the best approach, or is there a way to do things in bulk?  I'm guessing actions.merge() might be able to handle bulk changes to array data...?  But I see nothing similar for removing multiple items.

**Comment by davidkpiano** [comment]
You can pass in a function to `actions.change`:

```js
const itemsToRemove = ['foo', 'bar', 'baz'];

dispatch(actions.change('something', (value) => {
  const newValue = {...value};
  itemsToRemove.forEach(item => delete newValue[item]);
  return newValue;
}));
```

This requires `redux-thunk`. You can also use `actions.batch` for multiple actions at once.

**Comment by marcpeterson** [comment]
Ok using #553 as an example, I was able to use something like `dispatch(actions.change('applicantsForm.applicants', []))` to clear all the items in that array of forms.

But I don't see any documentation on `actions.batch()` if I want to change multiple items.  Is that somewhere, or should I just dig into the source?

**Comment by davidkpiano** [comment]
> Is that somewhere, or should I just dig into the source?

Ah, it's really only internally used - not meant to be exposed externally, but it _can_ be used. I'd stick to your found solution, if it works for you.
