### ISSUE TITLE
Field's change visually when Chrome's autofill kicks in

### ISSUE THREAD

**Issue by mjohnsonengr** [davidkpiano/react-redux-form#67]
In the following image, you see the address field looks odd.  It originally looked like the others when the page loaded and then changed to this after a second -- it seemed to be related to LastPass adding it's little autofill icon there.  This is in the [Autofill Fields](http://davidkpiano.github.io/react-redux-form/#recipe/autofill-fields) recipe in the documentation.
![image](https://cloud.githubusercontent.com/assets/7274059/13712748/a7863df2-e782-11e5-9021-8f3af9c5c49c.png)

The input looks like this in Chrome dev tools

`<input type="text" name="order.billing.address" data-reactid=".0.1.0.0.0.1:1.$/=11" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHklEQVQ4EaVTO26DQBD1ohQWaS2lg9JybZ+AK7hNwx2oIoVf4UPQ0Lj1FdKktevIpel8AKNUkDcWMxpgSaIEaTVv3sx7uztiTdu2s/98DywOw3Dued4Who/M2aIx5lZV1aEsy0+qiwHELyi+Ytl0PQ69SxAxkWIA4RMRTdNsKE59juMcuZd6xIAFeZ6fGCdJ8kY4y7KAuTRNGd7jyEBXsdOPE3a0QGPsniOnnYMO67LgSQN9T41F2QGrQRRFCwyzoIF2qyBuKKbcOgPXdVeY9rMWgNsjf9ccYesJhk3f5dYT1HX9gR0LLQR30TnjkUEcx2uIuS4RnI+aj6sJR0AM8AaumPaM/rRehyWhXqbFAA9kh3/8/NvHxAYGAsZ/il8IalkCLBfNVAAAAABJRU5ErkJggg==&quot;);background-attachment: scroll;background-size: 16px 18px;background-position: 98% 50%;background-repeat: no-repeat;">`

Compared to the other input that looks fine:
`<input type="text" name="order.billing.city" data-reactid=".0.1.0.0.0.1:2.$/=11">`

The style attribute I believe is added by LastPass's autofill; removing it fixes the appearence which then causes the following style to apply to the input because of the "not([style])" selector

![image](https://cloud.githubusercontent.com/assets/7274059/13712907/607bb6f2-e783-11e5-81bc-163403c9a92b.png)

Seems like it's simply not a good idea to use CSS selectors that say "not([style])" for this reason; I'm not sure why that particular selector is included though, nor the effects of removing it.

**Comment by mjohnsonengr** [comment]
Wait, my bad, that's not Chrome's autofill, it's LastPass that's doing it.  Bug still stands.

**Comment by davidkpiano** [comment]
Ah, good catch. I'm currently reworking the documentation and will address this.
