### ISSUE TITLE
LocalForm not triggering validation

### ISSUE THREAD

**Issue by alvinthen** [davidkpiano/react-redux-form#671]
Hi, I'm trying to use LocalForm for login purpose, for the convenience of reseting the form when it's unmounted. But when using LocalForm it's not triggering any validation.

Please see this [codepen](https://codepen.io/anon/pen/qRGapp) forked from then synchronous validation.

What I have done is basically replace Form with LocalForm.

Is this intended? Could it be a new feature request?

I understand that I could dispatch a reset action at componentWillUnmount, but using LocalForm is much more convenient.

**Comment by davidkpiano** [comment]
Don't forget to add `initialState={initialUserState}` to `<LocalForm>`. Try that and let me know if it works.

**Comment by alvinthen** [comment]
Thanks for the reply, it works on codepen, but not on my app, see the updated codepen

https://codepen.io/anon/pen/qRGapp

Although the button doesn't become enabled when the form is valid

```es6
<Control.button
  className="Login-button"
  model="loginForm"
  type="submit"
  disabled={{ valid: false }}
>
  Log In
</Control.button>
```

I'm using the same UserForm component as below, however it doesn't work on my app, I wonder what went wrong. Running on rrf@1.5.5

```es6
export default function LoginForm(props: Props) {
  return (
    <LocalForm
      className="Login-container"
      model="loginForm"
      initialState={{ email: '', password: '' }}
    >
      <div className="Login-input-group">
        <Control
          required
          model=".email"
          type="email"
          placeholder="Email"
          validators={{ isEmail: val => !!val.length }}
        />
        <Errors
          className="popover-bottom"
          model=".email"
          show="touched"
          messages={{ isEmail: 'Invalid email address' }}
        />
      </div>
      <div className="Login-input-group Login-password-group">
        <Control
          required
          model=".password"
          type="password"
          placeholder="Password"
          validators={{ required: val => !!val.length }}
        />
        <Errors
          className="popover-bottom"
          model=".password"
          show="touched"
          messages={{ required: 'Password is required' }}
        />
      </div>
      <Control.button
        className="Login-button"
        model="loginForm"
        type="submit"
        disabled={{ valid: false }}
      >
        Log In
      </Control.button>
    </LocalForm>
  );
}
```

FWIW, from React Chrome tools, the modelValue and formValue remain unchanged despite typing on the text fields and blurring.

Btw, I'm not sure if this question suits here, I'll switch to stackoverflow if it does't.

**Comment by davidkpiano** [comment]
What version of react-redux do you have?

**Comment by alvinthen** [comment]
After trying to debug my code and exploring the issues here, it's totally related to #592 
Closing this. Thanks for the help

**Comment by davidkpiano** [comment]
Yeah, the fix is already in `react-redux` - a new version just hasn't been released yet. 😞

**Comment by alvinthen** [comment]
We just have to wait then. Thanks for the amazing library 😊

**Comment by davidkpiano** [comment]
Please try this again after upgrading to [React-Redux 5.0.3](https://github.com/reactjs/react-redux/releases/tag/v5.0.3).

**Comment by alvinthen** [comment]
It's working nicely now, thanks!
