### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by nanocreaator** [davidkpiano/react-redux-form#674]
### The Problem
TypeError

### Steps to Reproduce
I just followed and setup your tutorial here:
http://davidkpiano.github.io/react-redux-form/docs/guides/quickstart.html

### Expected Behavior
Execute the promises... and clear the form

### Actual Behavior
TypeError: dispatch is not a function. (In 'dispatch(_reactReduxForm.actions.submit('user', ThePromise))', 'dispatch' is undefined)

### Reproducible Code Example
same code as tutorial (...guides/quickstart.html) and uncomment the line 3:
1 // Do whatever you like in here.
2 // You can use actions such as:
3 // dispatch(actions.submit('user', ThePromise));
4 // etc.

Thank you

**Comment by davidkpiano** [comment]
If you want to use `dispatch`, you have to first `connect()` the form. Please see here: http://redux.js.org/docs/basics/UsageWithReact.html#implementing-container-components

I'll clarify the quick start guide for this.
