### ISSUE TITLE
How to change and validate?

### ISSUE THREAD

**Issue by tero** [davidkpiano/react-redux-form#677]
### The Problem

How I should validate value when changed?

### Steps to Reproduce
I have following code on my custom input component:
```
onChange(model, date) {
  dispatch(actions.change(model, formatDate(date)))
  dispatch(actions.validate(model), ownProps.validators)
}
```
### Expected Behavior

I would like to dispatch action where model is changed and validated with new value

### Actual Behavior

Validation is triggered before value is changed and therefore is "one step behind" meaning:

If I add invalid value, validator will first see valid result
When I change value to valid, validator validates previous invalid message
and so on...

**Comment by davidkpiano** [comment]
Right - you can't expect `dispatch(...)` to be synchronous. If you want to do validation manually, you should either wait for the model value to be updated in `componentDidUpdate`, or you can assume that the value passed in is the value that it will be changed to:

```js
onChange(model, date) {
  dispatch(actions.change(model, formatDate(date)))
  dispatch(actions.setValidity(model, ownProps.validators(formatDate(date))))
}
```

assuming that `ownProps.validators` is a function.
