### ISSUE TITLE
intents undefined in handleIntents function

### ISSUE THREAD

**Issue by daisy-cyt** [davidkpiano/react-redux-form#679]
Hi:
I came across a problem that when I run or focus on my custom input. the error "control-component.js:456 Uncaught TypeError: Cannot read property 'length' of undefined" will show. I used it in this way:
```
                  <Control
                    model="host.account"
                    component={TextInput} validators={{required}}
                   />
                   <Errors
                      className="errors"
                      model="host.account"
                      show="touched"
                      messages={{
                        required: 'Required'
                      }}
                    />
```

I debugged the program and found that "fieldValue.intents" undefined so call intents.length in line 456 in "node_modules\react-redux-form\lib\components\control-component.js" will result this error, but I don't know why. Please help me, thanks a lot

**Comment by davidkpiano** [comment]
Which version are you using?

**Comment by daisy-cyt** [comment]
latest version 
I used npm install react-redux-form@latest


陈宇婷

**Comment by davidkpiano** [comment]
Can you make a fully reproducible code example? Fork from this pen: http://codepen.io/davidkpiano/pen/2cbfd61bdcff474ca6e40e8ed2221ef9

**Comment by daisy-cyt** [comment]
I don't know why, but the error disappeared. So I closed the issue.
