### ISSUE TITLE
Fields do not update when underlying model updates

### ISSUE THREAD

**Issue by tomlagier** [davidkpiano/react-redux-form#68]
Hi! We're building a form-heavy Salesforce app and are running into a pretty major issue with react-redux-forms:

When you update an underlying form model, the field does not appear to be synced with the model. You can see this demonstrated in this fiddle:

https://jsfiddle.net/7t46vv0g/

Clicking the button does reset the underlying model, but does not reset the form field values.

Our expectation would be that clearing the model would also update the form fields, or failing that, that there be some other method of telling the form fields to sync with their models. It's hard to tell whether this is a bug or intended behavior.

Is there any way currently to do what we're looking for, without having to manually connect each input element to state?

**Comment by davidkpiano** [comment]
I'll add this to the docs, but thankfully this is not an issue - inputs with values that can be written **are not controlled components** by default.

That means, if you add `value={...}` below, you'll get your expected result! :smile: 

```diff
class Root extends React.Component {
  render() {
    return (
      <div>
        <Field model="test.field">
-          <input type="text" />
+          <input type="text" value={store.getState().test.field} />
        </Field>
        <button onClick={(e)=> store.dispatch(actions.reset('test'))}>Click me</button>
      </div>
    );
  }
}
```

Let me know if that makes sense!

**Comment by tomlagier** [comment]
Awesome, thanks for the quick response.

**Comment by tw0517tw** [comment]
after react 15.0, set `value={}` on `<input>` will cause warning.
> Warning: Input elements must be either controlled or uncontrolled

**Comment by karissame** [comment]
I am having a similar issue with the control.text model. With below fields when I call dispatch(actions.reset('prospectMeters')); the store gets cleared out but the visual fields on the page still show what was previously there. Can you help pretty please?

I also have a screenshot of the form model in reset state next to the form which still shows the submitted values from before the reset. ANY help much appreciated.

https://www.dropbox.com/s/l9x3iocqocxwfuy/Screenshot%202017-03-23%2011.10.17.png?dl=0


<Form model="prospectMeters" onSubmit={() => this.handleSubmit()}>
        <div className="field">
        <label>Meter Account Number</label>
        <Control.text model=".MeterAccountNumber" />
        </div>
        <div className="field">
        <label>Meter Address Line1</label>
        <Control.text model=".MeterAddressLine1" />
        </div>
