### ISSUE TITLE
controlProps overrides children prop in Control

### ISSUE THREAD

**Issue by nigredo-tori** [davidkpiano/react-redux-form#680]
### The Problem
Currently `controlProps` (if present) disables any additional props passed to `Control`, including `children`.

### Steps to Reproduce
```scala
<Control.button model="user" controlProps={{ style: {color: "red"} }}>
  Go
</Control.button>
```

### Expected Behavior
Button with red text "Go" is displayed

### Actual Behavior
Button is displayed without text

### Reproducible Code Example
I can't save the pen for some reason ("You're not allowed to fork a private Pen."), so here's the [gist](https://gist.github.com/nigredo-tori/603b1127dc63f9d875938684acbc5dca).

**Comment by davidkpiano** [comment]
Sorry about that, here's a forkable pen: http://codepen.io/davidkpiano/pen/yJwmEa

**Comment by nigredo-tori** [comment]
OK, here's the fork: http://codepen.io/nigredo/pen/ygmEGM .
