### ISSUE TITLE
set model validity after loading form data

### ISSUE THREAD

**Issue by texas697** [davidkpiano/react-redux-form#684]
### The Problem
I am using the same form for creating and editing a user profile. After I populate the form model for user edit. I set the validity of the form using

```js
componentDidUpdate(prevProps) {
    if (this.props.userForm != prevProps.userForm)
      this.props.dispatch(actions.setValidity('userForm', true))
  }
```

It shows the form validity set to true but the models set to false? Even so shouldn't the valid property be set to true?

Here is a screenshot of my redux-dev-panel showing one of the input models valid set to false
http://i68.tinypic.com/71ibrr.png

And here is a screenshot of my  redux-dev-panel showing the form model showing it validity set to true
http://i63.tinypic.com/2ltke8o.png

Sample of the code
```jsx
<Form model='userForm' onSubmit={v => this.props.handleSubmit(v)}>
<InputRedux
          required
          model='.first'
          label='First Name'
          messages={{ valueMissing: required('First Name') }} />
<InputRedux
          required
          model='.last'
          label='Last Name'
          messages={{ valueMissing: required('Last Name') }} />
</Form>
```

InputRedux Component
```jsx
const InputRedux = props => (
  <div className={`form-group col-md-${props.col || '6'} ${props.className}`}>
    <small>{props.label}</small>
    <div className='field'>
      <Control
        model={props.model}
        required={props.required}
        validators={props.validators}
        validateOn='blur'
        component={props.mask === 'phone' ? PhoneInput : TextInput}
      />
      <Errors
        className='errors'
        model={props.model}
        show='touched'
        messages={messageCheck(props.messages)}
      />
    </div>
  </div >
)
```

### Reproducible Code Example
(please fork from [this CodePen template](http://codepen.io/davidkpiano/pen/yJwmEa))

**Comment by mikkelwf** [comment]
I have the same issue..

**Comment by davidkpiano** [comment]
What about using `resetValidity` instead?

```js
this.props.dispatch(actions.resetValidity('userForm'));
```

This should work as expected.

**Comment by texas697** [comment]
it worked! thank you!

**Comment by davidkpiano** [comment]
Awesome! Also, just for reference, when you `setValidity()` to a form, the intention is that you're setting form-specific validation on it. For example:

```js
// Form is invalid even if models are valid
dispatch(actions.setValidity('user', { passwordsMatch: false }));

// Form-specific validity is valid, but overall validity
// depends on if models are valid or not
dispatch(actions.setValidity('user', { passwordsMatch: true }));
```
