### ISSUE TITLE
Share last fixes with everybody

### ISSUE THREAD

**Issue by GarrisonD** [davidkpiano/react-redux-form#687]
Hello, @davidkpiano 

Unfortunately I can't install `react-redux-form` module from master: webpack says that module can't be found.

Can you publish a new version to `npm` please?

**Comment by davidkpiano** [comment]
Which version are you trying to install?

**Comment by GarrisonD** [comment]
I used `yarn add react-redux-form` in order to install the latest version of `react-redux-form` module.

Version `1.7.0` was installed and there were not last fixes.

**Comment by davidkpiano** [comment]
Which last fixes are you referring to?

**Comment by GarrisonD** [comment]
Sorry, everything seems to be OK now. 👍
