### ISSUE TITLE
could the value in model is not mapped directly

### ISSUE THREAD

**Issue by daisy-cyt** [davidkpiano/react-redux-form#691]
### The Problem
I have a requirements like this.
```
const initialState = {
  host:{
    'type': 1
  }
}
const map = {1: 'apple', 2: 'orange'}
<Control.text
     model="host.type"
 />
```
then I want "apple" is shown in the input component not "1" is shown
Could it be? Tks

**Comment by davidkpiano** [comment]
Sure! You can use the [`parser`](http://davidkpiano.github.io/react-redux-form/docs/api/Control.html) prop:

```jsx
<Control.text
  model="host.type"
  parser={(val) => map[val]}
/>
```
