### ISSUE TITLE
AsyncValidator not setting Form to invalid

### ISSUE THREAD

**Issue by benmann497** [davidkpiano/react-redux-form#692]
Hello,

I am using asyncValidators against some Control components as well as some sync validation on the Form. The Form validation is working correctly and the async function is called and is registering against the control as valid = false, which is right. However, when submitting the form, it is always set as valid, so if the async function is invalid, the form is still submitted. Am i missing something? I expect the onSubmitFailed to be called, not onSubmit, if the sync or async validations fail?

I have made an example below:

http://codepen.io/anon/pen/KWdOmM?editors=0011

**Comment by davidkpiano** [comment]
Here's the problem:

```diff
function nameAvailable(value, done) {
    checkNameAsync(value)
        .then(response => {
-           done({ nameAvailable: response });
+           done(response);
        });
}
```

Before, it was setting `user.firstName.validity` to `{ nameAvailable: { nameAvailable: false } }` (accidentally nested objects), and an object is truthy. The specific validator's validity is what's expected to be returned from the promise: `done(response)` to give us `{ nameAvailable: false }`.

**Comment by benmann497** [comment]
Brilliant, thanks for your help.
