### ISSUE TITLE
console.error is unavoidable in actions.submit()

### ISSUE THREAD

**Issue by marceux** [davidkpiano/react-redux-form#696]
While creating/testing my own wrappers for `actions.submit()`, I noticed that I was printing out intentionally rejected Promise values to the console, when I hadn't explicitly stated any `console.log` or `console.error` statements.

Here is the line that was printing the values in the code:
https://github.com/davidkpiano/react-redux-form/blob/master/src/actions/field-actions.js#L217

While I understand that this behavior may be desired in non-native environments or for debugging, it's a little annoying while creating my own error handlers and procedures.

You can reproduce this issue by simply passing a rejected `Promise` to `actions.submit()`'s second argument.

Ideally, I wouldn't want to print out anything unless I had to on my end. Should I make a PR? Is this an artifact from a previous commit? What would you guys do?

**Comment by davidkpiano** [comment]
Sure, you can make a PR to refactor/remove this. I think it's safe to remove it, as the error (in most cases) would get shown in the console anyway.

**Comment by marceux** [comment]
Thanks, I'll submit one later. Love the library so far.

**Comment by davidkpiano** [comment]
Closed by #697
