### ISSUE TITLE
Typescript: combineForms and createForms missing third options parameter.

### ISSUE THREAD

**Issue by Aryk** [davidkpiano/react-redux-form#699]
On 1.8.0, in the type definitions, we are missing the third options parameter for combineForms and createForms:

```ts
export function combineForms(data: any, deep?: string): any;
export function createForms(data: any, deep?: string): any;
```

should be

```ts
 export function combineForms(data: any, deep?: string, options?: Object): any;
 export function createForms(data: any, deep?: string, options?: Object): any;
```

**Comment by Aryk** [comment]
@davidkpiano : should I reopen a new ticket for 

setFieldsErrors
setErrors
...anything else where you can set async: true?
The example you gave here will throw a TS error because of the third parameter: https://github.com/davidkpiano/react-redux-form/issues/649#issuecomment-278801937

**Comment by davidkpiano** [comment]
@Aryk Yes please! And a PR if you're feeling up to it ;-)

**Comment by Aryk** [comment]
Thanks for fixing this, sorry I didn't get around to the PR, I got side-tracked on some stuff.

**Comment by Aryk** [comment]
Oh noticed the extra options wasn't added, would you like me to PR it?

**Comment by davidkpiano** [comment]
Sure thing!
