### ISSUE TITLE
[Validation] Control with default value 

### ISSUE THREAD

**Issue by jpmelnik** [davidkpiano/react-redux-form#702]
I have a Form with one Control with default value.

`
<Control
                id="user-height"
                className="form-control"
                type="number"
                model="deep.imc.height"
                changeAction={this.onHeightChange}
                placeholder="Height"
                validators={{ isRequired }}
                validateOn="change"
                value="1.75"
              />
`

`const isRequired = (val) => val && val.length > 0;`

**On Load, isRequired Validation value always return undefined.**

Same with mapProps={{value: 1.75}}

Whats happend? and How can fix it?
Thanks.

**Resolved**:
`
asyncValidators={{
                  isAvailable: (value, done) => {
                    isRequired(value)
                      .then((result) => done(result));
                  }
                }}
`

**Comment by davidkpiano** [comment]
Can I see a full code example? Also try setting `defaultValue={1.75}` instead, and I'd like to see what's inside that `this.onHeightChange` function

**Comment by jpmelnik** [comment]
```
// Libs
import React, { Component, PropTypes } from 'react'
import classNames from 'classnames';
import {bindActionCreators} from 'redux';
import {connect} from 'react-redux';
import { Form, Control, Field, Errors } from 'react-redux-form';
import validator from 'validator';
// Actions
import { calculateIMC } from '../actions';
// Components
import Display from './display';

const isRequired = (val) => val && val.length > 0;

const lessThan10 = (val) => {
  const lessThan = 10;
  if (!(val < 10)) {
    return { lessThan };
  }
  return false;
};

class IMC extends Component {
  constructor( props ) {
    super( props );

    this.state = {
      weight: this.props.weight,
      height: this.props.height,
    };

    this.onSubmit       = this.onSubmit.bind(this);
    this.onWeightChange = this.onWeightChange.bind(this);
    this.onHeightChange = this.onHeightChange.bind(this);
  }
  onWeightChange( model, value ) {
    this.setState((prevState, props) => {
      return { weight: +value };
    });
  }
  onHeightChange( model, value ) {
    this.setState((prevState, props) => {
      return { height: +value };
    });
  }
  onSubmit() {
    this.props.calculateIMC( this.state.weight, this.state.height );
  }
  render () {
    let buttonClasses = classNames('btn', {
      status: this.props.button.status
    })
    return(
      <div className="panel panel-success">
        <div className="panel-heading">
          <h2>{this.props.title}</h2>
        </div>
        <div className="panel-body">
          <Form
            model={this.props.model}
            onSubmit={(imc) => this.onSubmit(imc)}
          >
            <Display {...this.props} />

            <div className="form-group">
              <label htmlFor="user-weight">Your Weight?</label>
              <Control
                id="user-weight"
                className="form-control"
                type="number"
                model=".weight"
                changeAction={this.onWeightChange}
                placeholder="Weight"

              />
            </div>

            <div className="form-group">
              <label htmlFor="user-height"> Your Height? </label>
              <Control
                id="user-height"
                className="form-control"
                type="number"
                model="deep.imc.height"
                changeAction={this.onHeightChange}
                placeholder="Height"
              />
            </div>

            <Control.button model={this.props.model} type={this.props.button.type} className={buttonClasses}>
              {this.props.button.name}
            </Control.button>
          </Form>
        </div>
      </div>
    );
  }
};

IMC.propTypes = {
  title: PropTypes.string,
  weight: PropTypes.number,
  height: PropTypes.number,
};

IMC.defaultProps = {
  model: 'deep.imc', // Review
  title: "Índice de Masa Corporal (IMC)",
  weight: undefined,
  height: undefined,
  button: {
    type: 'submit',
    status: 'btn-success',
    name: "Calcular!",
  }
};

const mapDispatchToProps = ( dispatch ) => {
  return bindActionCreators( { calculateIMC: calculateIMC }, dispatch );
};

export default connect( undefined, mapDispatchToProps )( IMC );

```

**Comment by davidkpiano** [comment]
Instead of: `changeAction={this.onHeightChange}`, you should be using `onChange={this.onHeightChange}`. Let me know if this fixes your problem, or if you have any questions as to why.

Short explanation:
- `changeAction` specifies which action is to be dispatched, so `setState` makes no sense here.
- `onChange` is called whenever the model changes, which is perfect for your use-case.

**Comment by guywald1** [comment]
@davidkpiano , is there a reason `defaultValue` is not in the docs? Or fine to use?
Thanks!

**Comment by davidkpiano** [comment]
It's not in the docs because it's not encouraged - `defaultValue` is for **uncontrolled** components, and technically, all RRF components are **controlled** components. In order to prevent conflicts/warnings and to preserve the intent of the developer, `defaultValue` in RRF is just a proxy for setting the initial value of the model.

**Comment by guywald1** [comment]
@davidkpiano 
Thanks for taking the time to reply! I currently have a project in which I receive default values as props to some component that renders a `Form` component.
I would export an "initialState" object for the reducer of that form in the module but I am not sure how to approach setting initial state inside my wrapper component.
What would be best practice in that scenario?

**Comment by davidkpiano** [comment]
@guywald1 Have you looked into using `<LocalForm>`? Might be useful for your use-case, and you can set `initialState={...}` right on the component.
