### ISSUE TITLE
Model not working in LocalForm

### ISSUE THREAD

**Issue by dragGH102** [davidkpiano/react-redux-form#704]
### The Problem

Updating the model, doesn't update the form

### Steps to Reproduce
User LocalForm and update initialValue / model (I tried with both, in this example I use the component's state).
The prop userData is properly passed into the component.

e.g.

```
  constructor() {
    super();

    this.state = {
      profile: {}
    };
  }

  componentWillReceiveProps(nextProps) {
    this.setState({
      profile: (nextProps.userData ? nextProps.userData.user: {})
    });
  }
```

**in LocalForm** (same component):
```

<LocalForm model="profile"
                 initialState={{}}
                 onSubmit={(values) => this.props.onFormSubmit(values)}
      >
          <label htmlFor="firstName">First Name</label>
          <Control.text name="firstName" model=".firstName"/>
```
### Expected Behavior
firstName should update updated

### Actual Behavior
firstName is not updated

### Reproducible Code Example
I'm still learning React. a bit tricky to reproduce

**Comment by davidkpiano** [comment]
Can I see the full code of `onFormSubmit`?

**Comment by dragGH102** [comment]
@davidkpiano sure.

e```
xport function mapDispatchToProps(dispatch) {
  return {
    onFormSubmit: (values) => {
      dispatch(storeProfile(values));
    },

  };
}

// connect reducers for model updating based on state
export default connect(mapStateToProps, mapDispatchToProps)(ProfileForm);

```

It works as intended. The issue is only with loading data *into* the model

**Comment by hellojere** [comment]
@lasergoat Thanks for this already! I would highly appreciate a walk through for changing values outside of the LocalForm. Basically what I'm trying to do is to get an image uploader working inside the LocalForm, so I need to update values inside a custom function. 

Also, is there a way to keep some values in the form and have them returned on submit without creating `<Control>` components for them?

**Comment by davidkpiano** [comment]
> Also, is there a way to keep some values in the form and have them returned on submit without creating <Control> components for them?

If I understand correctly, you can just keep them in `initialState`:

```jsx
<LocalForm initialState={{ keep: 'this', value: 'around' }} />
```

I'll update the documentation, but in `<LocalForm>` you have access to the internal dispatcher via `getDispatch`, so you can do this:

```jsx
<LocalForm model="local" getDispatch={dispatch => this.formDispatch = dispatch}>

// and then anywhere in the same component where LocalForm is rendered:
onButtonClick() {
  this.formDispatch(actions.change('local.whatever', 'any value'));
}
```

With the latest version of RRF (1.9.x), you can even use action thunk creators inside of `this.formDispatch`.

**Comment by davidkpiano** [comment]
See here for the latest documentation: http://davidkpiano.github.io/react-redux-form/docs/guides/local.html

Specifically the **Updating the model externally** section

**Comment by hellojere** [comment]
Thank you so much!
