### ISSUE TITLE
Dynamic models/change event turning state into read-only?

### ISSUE THREAD

**Issue by prime-ralph** [davidkpiano/react-redux-form#705]
I have this normalized state consisting of an array of objects, which all had reducers prior to rrf setup and I used `combineForms` on. 
This normalized state was functioning as defined until the form has been touched, at which point errors start to throw: `Cannot assign to read only property 'id' of object` for a parser that is run at `componentWillReceiveProps()` of a different component.
Looking at the Redux DevTools, I can see the state being updated accordingly, but for some reason, the `rrf/change` event turns my normalized state object into read-only.

The form looks something like this:
```
<Form model={`page.body`}>
   <Control type="text" ignore={['focus', 'blur']} model={`.sections.entities.children[${this.props.id}].attributes.dataset.displayName`}/>
</Form>
```

And the root reducer something like this: 
```
const rootReducer = combineForms({
...
   page: combineReducers({
   ...
   body: combineForms({
            intro: BrowserWindow.intro,
            scripts: BrowserWindow.scripts,
            sections: BrowserWindow.sections,
            dev_scripts: BrowserWindow.dev_scripts,
            dev_sections: BrowserWindow.dev_sections,
            empty_placeholder: (state) => {return state==undefined ? {} : state}
        }, 'page.body'),
   ...
   })
...
});
```

All other actions function normally until I try to edit the form, at which point the `page.body.sections.entities.children` items are turned into read-only objects.

**Comment by davidkpiano** [comment]
Is there a specific reason you would want the state to not be read-only? Generally, with Redux, you should avoid mutation.

**Comment by prime-ralph** [comment]
First up, thanks for the response! Really appreciate it.

I just happened to straight-up use the `page.body.sections.entities.children` collection inside a component using `mapStateToProps()`, and the same collection is being interpreted as read-only inside that component only after `rrf/change` triggers on said collection. The component runs the said collection to a parser before displaying it, I'm not mutating the state directly (right?).

Am I doing an anti-pattern of sorts? Am I supposed to not directly use the returned props from `mapStateToProps()`? I'm not that much of an expert but so far, all of the packages I used did not require me to spin off a new object from every props that I pulled out from the store.
If this is intentional behavior or I'm just doing things wrong I'll close this issue.

**Comment by davidkpiano** [comment]
Can you show me the code that is trying to set `.id` to the object?

**Comment by prime-ralph** [comment]
In the component that makes use of `page.body`:
```
componentWillReceiveProps = (nextProps) => {
  ...
  if (this.props.body.sections !== nextProps.body.sections) {
    const tree= parseTree(nextProps.body.sections);
  }
  ...
}
```

Inside `parseTree`:
```
const parseTree= (obj) => {
  let tree = [];
  ...
  //state holds the normalized array
  obj..entities.state[0].elements.forEach((i) => {
    let el = obj.entities.children[i];
    el.id = i;
  })  
  ...
  return tree;
}
```

Given all that, I can assume that a workaround might be to spin off new instances of the objects `rrf` touches, but I can't help but think that this couldn't be intended behavior. Thanks for sticking with this so far.

**Comment by davidkpiano** [comment]
Right, that's mutating props, which is something that should _ definitely_ be avoided.

Perhaps try looking into using something like [Normalizr](https://github.com/paularmstrong/normalizr) to do this in a non-mutative way.
