### ISSUE TITLE
Using { async: true } in setValidity or setFieldsValidity can cause an endless loop of setValidity-actions

### ISSUE THREAD

**Issue by toadle** [davidkpiano/react-redux-form#706]
### The Problem
Hey guys!

Here is what I'm working with: A simple login form that checks the current auth-token:

```js
    dispatch(actions.setPending("authentication.token", true));
    return jsonApi.find('authentication', authentication.token, {include: 'user', 'authToken': authentication.token})
      .then((response) => {
        dispatch(loginSuccessful(response));
        dispatch(actions.setPending("authentication.token", false));
      })
      .catch((err) => {
        dispatch(actions.setValidity("authentication.token", { valid: false }));
        dispatch(loginFailed(err));
        dispatch(actions.setPending("authentication.token", false));
      });
```

Now without the `{async: true}` this works quite fine. 
Now changing this to `dispatch(actions.setValidity("authentication.token", { valid: false }, {async: true}));` causes mayhem:

**Before**
https://www.dropbox.com/s/xv4bty6ufy1408h/before-async.gif?dl=0

**After**
https://www.dropbox.com/s/u9qq74tya9ckkqa/after-async.gif?dl=0

RRF somehow ends in a very long loop of changing the validity. There seems to be a loop running while a concurrent action might kill it of. I've noticed that this loop is NOT endless, but at some point ends and does the right thing. 

Here is the `<Form>` btw.

```
  <Form className="large-inputs" model="authentication" onSubmit={this.props.doLogin}>
    <TextField model="authentication.token" label="Token" required="required" messages={{valid: "Token ist ungültig"}}/>
    <Button color="info" size="lg">Dive In</Button>
  </Form>
```

After `{async: true}` it simply looks like this: 

```js
    dispatch(actions.setPending("authentication.token", true));
    return jsonApi.find('authentication', authentication.token, {include: 'user', 'authToken': authentication.token})
      .then((response) => {
        dispatch(loginSuccessful(response));
        dispatch(actions.setPending("authentication.token", false));
      })
      .catch((err) => {
        dispatch(actions.setValidity("authentication.token", { valid: false }, {async: true}));
        dispatch(loginFailed(err));
        dispatch(actions.setPending("authentication.token", false));
      });
```

### Steps to Reproduce
This Codepen shows the problem in more distilled from: http://codepen.io/toadle/pen/qrjVZq

### Expected Behavior
Well it should just not end up in the loop and submit the form.

### Actual Behavior
Ends up in a loop.

### Reproducible Code Example
http://codepen.io/toadle/pen/qrjVZq

**Comment by toadle** [comment]
BTW: If somebody wants to steer clear of this problem, while it is not fixed.

Just leave out the `{async: true}` and rather `resetValidity`in your `<Form>` manually or `<input>` like so: 

```
<Form model="<your model>" onSubmit={this.props.doLogin} onKeyUp={this.props.resetValidity} onFocus={this.props.resetValidity}>
```

```
import { actions } from 'react-redux-form';
...
export function mapDispatchToProps(dispatch) {
  return {
     resetValidity: () => dispatch(actions.resetValidity('<your model>')),
     ...
  }
}
```

**Comment by davidkpiano** [comment]
It actually has nothing to do with `{async: true}`. Unfortunately, I noticed that you're wrapping a `<Field>` inside of a `<Control component={...}>`, both with the same model. That kind of wrapping is definitely going to cause some issues - ideally, (and this is by design) the component you pass into `Control` should not even be aware of React-Redux-Form at all. 

Here's how you can refactor:

```diff
const TextFieldPresenter = (props) => {
  const { label, passedProps, required, messages, size, className, disabled, placeholder, unit } = props;
  const { model, fieldValue } = passedProps;
  const classes = classNames({
      className: true,
      'form-control': true,
  });
  const wrapperClasses = classNames({
    "has-danger" : (fieldValue.touched && !fieldValue.valid),
    "form-group" : true
  });

  return (
    <div className={wrapperClasses}>
      {label && <label>{label}</label>}
        {unit && <span className="input-unit">{unit}</span>}
-      <Field model={model}>
-        {unit && <span className="input-unit">{unit}</span>}
-        <input className={classes} required={required} disabled={disabled} placeholder={placeholder} />
-      </Field>
+       <input
+         {...passedProps}
+         className={classes}
+         required={required}
+         disabled={disabled}
+         placeholder={placeholder}
+       />

      <div class="form-control-feedback"><Errors model={model} messages={messages}/></div>
    </div>
  );
};
```

**Comment by toadle** [comment]
@davidkpiano Sadly this does not solve it. I still get the infinite loop. I also changed the upper codepen to demonstrate.
