### ISSUE TITLE
how to get the validation status of form

### ISSUE THREAD

**Issue by daisy-cyt** [davidkpiano/react-redux-form#709]
I have a requirement that if all fields are valid then the submit button is enabled otherwise disabled.
So I need the whole validation status of the form.  How to get it? thanks a lot

**Comment by davidkpiano** [comment]
So there's two ways:

**1. use `<Control.button>`
```jsx
<Control.button
  model="user"
  disabled={{ valid: false }}
>
  Submit user!
</Control>
```

If you put this inside a `<Form>`, it will _just work_ because a normal `<button>` will submit the form.

**2. use normal redux state**

Suppose you have a store that looks like:

```js
const store = createStore(combineForms({
  user: initialUserState
}));
```

Then you can just `connect()` to get the form state you need:

```jsx
class MyForm extends Component {
  render() {
    const { userForm } = this.props;

    // ...
    <button disabled={!userForm.$form.valid}>
      Submit!
    </button>
    // ...
  }
}

const mapStateToProps = (state) => ({
  userForm: state.forms.user
});

export default connect(mapStateToProps)(MyForm);
```
