### ISSUE TITLE
Form onSubmit always has undefined as argument

### ISSUE THREAD

**Issue by ffxsam** [davidkpiano/react-redux-form#71]
I'm not sure what I'm doing wrong, but I've got this:

```
      <Form
        style={styles.form}
        noValidate
        onSubmit={(adminOrg) => console.info(adminOrg)}
      >
```

And the console always dumps out `undefined` when I submit the form. How exactly does `Form`'s `onSubmit` work? Where does it get its expected value from?

**Comment by ffxsam** [comment]
Ahh. There's a mistake in the documentation:

https://davidkpiano.gitbooks.io/react-redux-form/content/step_by_step.html

`<Form>` requires a `model` prop passed to it.

**Comment by davidkpiano** [comment]
Thanks @ffxsam ! Fixed the documentation.
