### ISSUE TITLE
The initialFieldState is not restored

### ISSUE THREAD

**Issue by kenta88** [davidkpiano/react-redux-form#713]
### The Problem
**The initial initialFieldState is setted properly, but after using actions.reset(model) the default one is restored instead of the initialFieldState.**

```jsx
import type { Store } from 'redux';
import { modelReducer, formReducer } from 'react-redux-form';

const initialFieldState = {
    focus: false,
    pending: false,
    pristine: true,
    submitted: false,
    touched: false,
    valid: false,
    validating: false,
    viewValue: null,
    validity: {},
    errors: {},
};

const initialState = {
    currentPassword: '',
    newPassword: '',
    confirmNewPassword: '',
};

export const model = modelReducer('modules.settings.forms.userPassword');
export const form = formReducer('modules.settings.forms.userPassword', initialState, {
    initialFieldState
});
```

### Steps to Reproduce

- set a initialFieldState as the example

- call setInitial or reset action ( valid prop will be true instead of false as setted)

### Expected Behavior
calling setInitial and reset action the initialFieldState setted will be restored.

### Actual Behavior
calling setInitial and reset action the default initialFieldState will be restored.

**Comment by davidkpiano** [comment]
Try passing it into `modelReducer` as well:

```jsx
export const model = modelReducer('modules.settings.forms.userPassword', initialState);
```

The recommended way is to use `combineForms()` since it does that step for you:

```
const userPasswordReducer = combineForms({
  userPassword: initialState
});
```

**Comment by kenta88** [comment]
nope. This solutions is not working for my purpose.

**Comment by kenta88** [comment]
**here my solution**
`const customFormReducer = (state: Store, action: Action) => {
    switch (action.type) {
        case 'rrf/reset': {
            const updatedState = Object.assign({}, state);
            Object.keys(updatedState).forEach((key) => {
                updatedState[key] = {
                    ...updatedState[key],
                    ...initialFieldState,
                };
            });
            return updatedState;
        }
        default: {
            return state;
        }
    }
};

export const model = modelReducer('modules.settings.forms.userPassword', initialState);
export const form = formReducer('modules.settings.forms.userPassword', initialState, {
    initialFieldState,
    plugins: [customFormReducer]
});`
