### ISSUE TITLE
Control.radio default checked

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#716]
How do I check by default a `Control.radio` ?

This does not work:
```
<Control.radio model=".toto" checked="checked"  value="2" />
<Control.radio model=".toto" value="1" />
```

**Comment by davidkpiano** [comment]
Have you tried setting the initial state of `.toto` to `2`?

**Comment by zabojad** [comment]
Thank you @davidkpiano, it solved my issue !

**Comment by Juandresyn** [comment]
If anyone is still looking for an answer, Control.Checkbox has a `defaultValue` props, simply pass a boolean to it.

**Comment by Gricardov** [comment]
Is there any other way? I'm using Localform so I cannot set the initial state. defaultValue doesn't work either

**Comment by Juandresyn** [comment]
> Is there any other way? I'm using Localform so I cannot set the initial state. defaultValue doesn't work either

You can also use the `model` prop

<AgreementCheckbox
     model=".accepttoc"
     className="form__input checkbox w-8"
     id="acceptoc"
     defaultValue={this.state.acceptToc}
/>

**Comment by AnkitBagaria24** [comment]
I am using localform. I am unable to check a radio button by defualt. Below is my radio button code. Someone please help.

 <Control.radio model={".present" + e.employeeid} name={"present" + e.employeeid} value="present" onChange={handleInputChange}/>
<Control.radio model={".present" + e.employeeid} name={"present" + e.employeeid} value="absent" onChange={handleInputChange} />

I have the relevant keys in this.state and its is set to absent by default.
