### ISSUE TITLE
Add Control.email and Control.password

### ISSUE THREAD

**Issue by zabojad** [davidkpiano/react-redux-form#717]
Could we add to RRF the `Control.email` and `Control.password` components that should be relatively easy to implement ?

This way we would not have to do it in our application code...

**Comment by thomasboyt** [comment]
As of v1.10, `<Control.text>` now has some special properties around how `value` is handled (https://github.com/davidkpiano/react-redux-form/commit/85799170bf432a4fd84981784c6a0ebf1ffe775b) to prevent React warnings on undefined form values. It'd be great if there were `Control.email` and `Control.password` controls that used this same logic.

fwiw, my current workaround to use Control.text as `type="email"` or `type="password"` looks like:

```
const PasswordInput = (props) => <input {...props} type="password" />;

const PasswordField = (props) => (
  <Control.text
    component={PasswordField}
    {...props} />
);
```

**Comment by davidkpiano** [comment]
@thomasboyt @zabojad You can just do:

```jsx
<Control.text type="email" />

// or even
<Control type="email" />
```

Is that not working for you?

**Comment by zabojad** [comment]
@davidkpiano indeed it works. It could be useful to add to the doc though...

**Comment by davidkpiano** [comment]
It's in the [Control docs](http://davidkpiano.github.io/react-redux-form/docs/api/Control.html) but I'll add it to the FAQs:

> You can add your own types to the basic `<Control>` component as an attribute: `<Control type="password">`
