### ISSUE TITLE
How to prepopulate a form?

### ISSUE THREAD

**Issue by ffxsam** [davidkpiano/react-redux-form#72]
I'm probably missing something from the docs, but how do I prepopulate a form? Say I have a dialog that pops up with a form in it, and I have a few fields I'm passing as props to the form, and but I also want rrf in Redux to also be aware of the default values.

**Comment by davidkpiano** [comment]
In normal Redux, you would "prepopulate" a model with an `initialState` in your reducer. React Redux Form works the same way, by providing the `initialState` as the second argument to the reducer creator:

```js
import { modelReducer } from 'react-redux-form';

const initialUserState = {
  firstName: '',
  lastName: ''
};

const userReducer = modelReducer('user', initialUserState);

export default userReducer;
```

All the fields will be prepopulated, using `defaultValue` (if you're using `<Field>`). Hope that helps!

**Comment by ffxsam** [comment]
This happens way after the creation of the Redux store and any reducers, though. To give more context, imagine a list of items, each with an edit button. Clicking edit for any particular item pops up a Material UI `<Dialog>` which contains a form, and that form is pre-filled with the item's existing data. But those form fields have to be linked with rrf.

**Comment by ffxsam** [comment]
I feel like I'd need to have some sort of dispatch that updates several fields at once, something I can call in `componentDidMount`.

**Comment by davidkpiano** [comment]
Sure, you can do that with [`actions.merge(model, object)`](https://davidkpiano.gitbooks.io/react-redux-form/content/model_actions.html#actionsmergemodel-values).

**Comment by ffxsam** [comment]
Thanks!

**Comment by madeinspace** [comment]
Hi there, 

I have a similar issue although I'm trying to prepopulate a form with some data that are stored in LocalStorage after authentication. The probleme I have is that the reducer doesn't get the initial data from local storage in time before the form gets rendered. haven't found a way so far but a little help would be appreciated! thanks

**Comment by madeinspace** [comment]
Hope this can be helpfull but I fixed it by dispatching the action.merge actioncreator in the componentDidMount function like so:

` componentDidMount(){`
       ` let user = JSON.parse(localStorage.getItem('user'));`
        `const initialUserState = user ? { loggedIn: true, user } : {};`
       ` store.dispatch(actions.merge("userProfile", initialUserState));`
    }`
