### ISSUE TITLE
Anchors don't work in docs

### ISSUE THREAD

**Issue by guywald1** [davidkpiano/react-redux-form#721]
### The Problem
In the docs (i.e. [here](https://davidkpiano.github.io/react-redux-form/docs/api/actions.html)), when changing the URL - browser doesn't scroll to anchor.
UA:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/56.0.2924.87 Safari/537.36
```

### Steps to Reproduce
Navigate to `https://davidkpiano.github.io/react-redux-form/docs/api/actions.html`.
Click on one of the links (i.e. `actions.change()`).
URL changes to `https://davidkpiano.github.io/react-redux-form/docs/api/actions.html#actions-change`

### Expected Behavior
Should scroll to anchor.

### Actual Behavior
Nothing happens.

P.S. You're awesome and this library is, too.

**Comment by danedavid** [comment]
It's not working in the Markdown docs inside Github

**Comment by davidkpiano** [comment]
If you can do number 2 I will merge that PR in ASAP. Thank you!

**Comment by danedavid** [comment]
Ok I'm on it :+1:  Will open a PR in a couple of days. Let me check whether all docs must be changed, or just the API docs..
