### ISSUE TITLE
Material-ui Textfield as Custom Control

### ISSUE THREAD

**Issue by rorbla** [davidkpiano/react-redux-form#724]
### The Problem
Hi,
I'm starting with react-redux and i'm trying to make a form with material-ui components: 

When I submit the form I print the values (onSubmit={v => console.log(v)) and they are always null (No problem with basic Controls).  

<TextField
                    floatingLabelText={t('login')}
                    name={t('login')}
                    {...props}
                   />

...

<Form model={loginForm} onSubmit={v => console.log(v)}>
                <Control
                    type="text"
                    model={userName}
                    component={loginField}
                   
                }}/>

I've tried updating the value

function mapDispatchToProps(dispatch) {
    return {
          actions: bindActionCreators(actions, dispatch),
    };
}

handleUpdateForm(model, value) {
        actions.change(model, value);
   }

<TextField
                    floatingLabelText={t('login')}
                    name={t('login')}
                    {...props}
                    onChange=
                    { (e) => {onModelChange('loginForm.userName', e.target.value)}}/>
 

This too: 
<Control
                    type="text"
                    model={userName}
                    component={loginField}
                    mapProps={{
                    value: (props) => props.viewValue, (hintText: (props) => props.viewValue )
                    
                }}/>

### Steps to Reproduce

This is my Store configuration: 

let loginForm = combineForms({loginForm: loginModel});
let reducers = {
    loginForm: loginForm,
    routing: routerReducer,
    session: session,
    user: user,
};
const reducer = combineReducers(reducers);

### Expected Behavior
loginForm:
value= input 

### Actual Behavior
loginForm
value= null

Thanks!!!

**Comment by davidkpiano** [comment]
Can you please post a reproducible code example?

**Comment by VictorBaron** [comment]
I also had a lot of problems to make RRF work with MUI components. I could not pass any props to the component, so had to use the default one (not very useful).
The Field was also losing the focus after every input.

It seems related since if I used only the TextField (not as a component in a Control.text), the TextField worked but the Form, as expected, didn't.

I found a work around by using [Material Components](https://github.com/material-components/material-components-web) instead of Material-UI, but still.
Here is the code, where I tried to pass a props to TextField: 

` render() {
    const CustomInput = props => (
      <Control.text
        model={props.model}
        component={TextField}
        updateOn="change"
        ignore={['focus', 'blur']}
        controlProps={props.controlProps}
      />
    ); `

    return (
        <Form 
         model="form.project"
          onSubmit={project =>  this.handleSubmit(project);  }
          form="form"  >
          <fieldset className="field">
            <label>Title </label>
            <CustomInput
              model=".name"
              controlProps={{
                floatingLabelText="foo"
              }}
            />
      </fieldset>
   `</Form> 
   )  
}`

I feel like I'm missing something in there, but tried virtually every solution and none fully worked. If you have a solution, it'd be helpful !

Thanks !

**Comment by davidkpiano** [comment]
Here's a similar library that might help:

https://www.npmjs.com/package/react-redux-form-materialize

Also, mind throwing that up on CodePen? A template is available on the README or the issue template for you to use. I'd be better able to investigate what's going on.

**Comment by VictorBaron** [comment]
I feel really idiot : while working on reproducing it on CodePen, I figured out I had accidentally downloaded the alpha version 1.0.0 from MUI. The problem came from there, it works fine with the last stable version, 0.17.2.

Thanks for the help though !
