### ISSUE TITLE
[PROPROSAL] One documentation source

### ISSUE THREAD

**Issue by ffxsam** [davidkpiano/react-redux-form#73]
I'm confused as to why there are two sources of documentation mentioned in the README:

http://davidkpiano.github.io/react-redux-form/#/api/Home?_k=n9d8hp
https://davidkpiano.gitbooks.io/react-redux-form/content/

If the latter is the most up to date, why not just reference that and remove the former?

**Comment by davidkpiano** [comment]
It's because I'm in the process of rewriting (updating) the documentation for 1.0 _and_ still have a place for the recipes. I'm going to be moving the recipes to a separate location though (ideally a live playground where you can play around with the code).

**Comment by ffxsam** [comment]
Ahh ok.

BTW, great work on RRF! I've tried many a React/Redux form package, and IMO this is the best one.

**Comment by davidkpiano** [comment]
Much thanks, @ffxsam! Feel free to let me know your pain points with creating forms, essential features you'd like to see, etc. as we get this ready for 1.0. (I am already using RRF in production, though)

**Comment by ffxsam** [comment]
The only thing so far (very minor) is that I think it'd be good to rename `actions.xor` to `actions.pull`, just for consistency (push vs pull).

**Comment by davidkpiano** [comment]
Hm, the only problem with that is that `actions.xor` can add _or_ remove a value in an array.

`[1, 2, 3] xor 2 = [1, 3]`
`[1, 2, 3] xor 4 = [1, 2, 3, 4]`
