### ISSUE TITLE
Custom Reducer in CombineReducers doesn't link to form state

### ISSUE THREAD

**Issue by greghawk** [davidkpiano/react-redux-form#731]
### The Problem
I can't get combine reducers to play nice with setting the model for the form

### Steps to Reproduce
Add an existing reducer to the combineForms function.  There will be your item in state and it will show under forms but it never has the updated state in the item under "forms". It is stuck on initial state.

### Expected Behavior
Add existing reducer with 'deep' option or not and have the form tie into the state properly

### Actual Behavior
State updated on the actual reducers item is updated but forms copy is not

### Reproducible Code Example
```
import {combineReducers} from 'redux';
import {routerReducer} from 'react-router-redux';
import initialStateReducer  from './initialStateReducer';
import offersReducer from './offerPageReducer';
import formReducer from './formReducer';
import {combineForms} from 'react-redux-form';


const rootReducer = combineReducers({
  initialState: initialStateReducer,
  offerData: offersReducer,
  formModel: combineForms({test:formReducer}),
  routing: routerReducer
});
export default rootReducer;
```

```
export default function formReducer(state = [], action) {

  switch (action.type) {
    case types.FORM_LOAD:
      return objectAssign([],state,action.formModel); ....
```

**Comment by davidkpiano** [comment]
Try this:

```diff
- formModel: combineForms({test:formReducer})
+ formModel: combineForms({test:formReducer}, 'formModel')
```

You need to tell RRF _where_ the form slice of state lives.

**Comment by greghawk** [comment]
I had tried the 'deep' method but didn't seem to help.  Where does the name 'test' come in? My actual state is formModel as an array of steps. When I do classic redux connect with my state it is fine.  Just cannot get forms to see it. It does set the initialState which is [].  Do I need to set it to this?

`formModel: combineForms({formModel:formReducer}, 'formModel')`

**Comment by greghawk** [comment]
Keep in mind the formReducer in my code is my own custom reducer not the one in react-redux-form

**Comment by greghawk** [comment]
@davidkpiano So this seems to be a state issue thing.  I just changed your stress test example to remove the initialState (set to []) and when i look in redux state the state never updates for the added rows.  How do i get react-redux-form to listen to state changes from my reducer? I can't seem to find the right combination

**Comment by davidkpiano** [comment]
RRF doesn't know about other actions (of course) so I'm thinking of having it be a configurable option for `combineForms()`. Just need to figure out the API for it.

**Comment by greghawk** [comment]
@davidkpiano Ok i may have just been being a little dumb.  The state doesn't update to the bundled state until you type in the form....

**Comment by davidkpiano** [comment]
@greghawk Did you solve your issue?

**Comment by greghawk** [comment]
@davidkpiano I did! thanks! I wasn't realizing that with UpdateOn change that it wouldn't change the state until you typed somewhere.  I was expecting when the form loaded that it would be in state
