### ISSUE TITLE
Problem with Refs

### ISSUE THREAD

**Issue by joinjoohny** [davidkpiano/react-redux-form#732]
I have problem with `React.Children`
I am doing React.Children.map(children) for this elements
Why refs from Control.text is `null`? Thank you for any help!
```js
     // react-card-input-checkout.cardnumber : null
    <Control.text
      model="checkout.cardnumber"
      type="text"
      placeholder="Card number"
      name="checkout.cardnumber"
    />
    // react-card-input-CCexpiry : input
    <input placeholder="MM/YY" type="text" name="CCexpiry" />
     // react-card-input-CCcvc: input
    <input placeholder="CVC" type="text" name="CCcvc" />
```
Result
```json
refs:
Object
react-card-input-CCcvc: input
react-card-input-CCexpiry : input
react-card-input-checkout.cardnumber : null
```

**Comment by davidkpiano** [comment]
I don't see in the code you showed me where you are logging the refs. In any case, you will need to use the prop `getRef={(node) => ...}` on `<Control.text` in order to get the ref.

See here for why: https://github.com/reactjs/react-redux/pull/270#issuecomment-175217424

**Comment by davidkpiano** [comment]
Hopefully your question is answered! `getRef` is also documented here: http://davidkpiano.github.io/react-redux-form/docs/api/Control.html
