### ISSUE TITLE
react-dates keypresses are suppressed

### ISSUE THREAD

**Issue by bovan** [davidkpiano/react-redux-form#737]
### The Problem
When using airbnb/react-dates (SingleDatePicker) as custom component I lose the ability to manually type in date.

I'm not sure if it's a bug or just a feature from rrf that supresses form input to force this to be handled through redux.

See github test repos below for example code

react-dates original functionality can be tested here : http://airbnb.io/react-dates/?selectedKind=SingleDatePicker%20%28SDP%29&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel
(click in input field and start typing)

### Steps to Reproduce
Wrap react-dates component in a Control element

### Expected Behavior
Able to click on input field and start typing

### Actual Behavior
Keypresses are not sent/registered in react-dates component

### Reproducible Code Example
https://github.com/bovan/test-rrf-react-dates

**Comment by davidkpiano** [comment]
Here's how to get it working:

```jsx
<Control component={SingleDatePicker}
  model="user.date"
  mapProps={{
    date: (props) => props.modelValue,
    focused: ({ fieldValue }) => fieldValue.focus,
    onDateChange: (props) => props.onChange,
    onFocusChange: (props) => ({ focused }) => focused
      ? props.onFocus()
      : props.onBlur()
  }}
  controlProps={{
    numberOfMonths: 1
  }}
/>
```

You can pass any control-specific props inside `controlProps`.

For `onFocusChange`, since it returns `{ focused: true }` or `{ focused: false }`, you have to help RRF interpret what that means (since React-Dates has no notion of "blurring" I suppose). That's why there's this:

```js
onFocusChange: (props) => ({ focused }) => focused
      ? props.onFocus()
      : props.onBlur()
```

Hope that helps! I tested it in your repo and it works fine.

**Comment by bovan** [comment]
Thanks for help, I've tested a bit and manual input seems to work like in your example (where you put SingleDatePicker) as component.

unfortunately, to remove all react-errors I have to wrap the component like
```
const dateField = (props) => {
            const fieldProps = omit(props, ["model", "name", "onBlur", "onChange", "onFocus", "onKeyPress", "value"]);
            return <SingleDatePicker {...fieldProps}/>;
        };
```
and use that as component, and then it stops working again. even just using `const dateField = (props) => <SingleDatePicker {...props }/>;` seems to be enough to stop it from working

I'll continue to dig into this, any tips would be greatly appreciated, thanks again.

**Comment by davidkpiano** [comment]
Which react errors are you getting? Can you open a separate issue for that?

**Comment by bovan** [comment]
sorry, thought the description was enough (probably as I had just read through 5 similar issues) 

it's the unknown props warning `warning.js?3efc:36 Warning: Failed prop type: SingleDatePicker: unknown props found: name, onChange, onBlur, onFocus, onKeyPress, value`

This is when I use `<Control component={SingleDatePicker} />`

If this isn't supposed to happen I can open an issue
