### ISSUE TITLE
FieldComponent doesn`t override defaultProps

### ISSUE THREAD

**Issue by i4got10** [davidkpiano/react-redux-form#74]
Problem raise then a wrote a wrapper for [react-select](https://github.com/JedWatson/react-select).

```jsx
export const SelectField = createFieldClass({
    'Select': props => ({
        onChange: () => console.log('CHANGE')
        value: props.modelValue
    })
});

<SelectField model={`${field}.classes`}>
  <Select options={CLASSES}/>
</SelectField>
```

``onChange`` never get called, because react-select set ``onChange`` to ``undefined`` by default, and [it doesnt get overrided](https://github.com/davidkpiano/react-redux-form/blob/v0.8.7/src/components/control-component.js#L18). 

May be provided props must be more prioritized over component props?

```diff
  render() {
    const { control } = this.props;

    return cloneElement(
      control, {
-        ...this.props,
-        ...control.props,
+        ...control.props,
+        ...this.props,
      });
  }
```

**Comment by davidkpiano** [comment]
> ...because react-select set onChange to `undefined` by default

Well _that's_ silly.

Anyway, I'm not sure how to go about this, because I want to allow developers to override properties that `<Field>` attaches to controls, e.g.:

```js
<Field model="foo.bar">
  <input type="text" onChange={(e) => customChange(e)} />
</Field>
```

Do you think the above is a necessary use-case? Or can we get by with `<Field>` overriding the props?

**Comment by i4got10** [comment]
Is there any way to detect which props user declare in component yourself, and which come from defaultProps?

Looks like in your example onChange handler must override Field props. Not sure is it common scenario, never use it it in this way

**Comment by davidkpiano** [comment]
> Is there any way to detect which props user declare in component yourself, and which come from defaultProps?

I don't think so. I think that after the fact, it just becomes normal props.

**Comment by i4got10** [comment]
Solve it this way, may be someone else will stack with it

```jsx
import React, { PropTypes } from 'react';
import _ from 'lodash';
import { connect } from 'react-redux';
import { actions } from 'react-redux-form';

function selector(state, { model }) {
    return {
        model,
        modelValue: _.get(state, model)
    };
}

class SelectField extends React.Component {
    render() {
        const { children, model, modelValue, change } = this.props;

        return React.cloneElement(children, {
            onChange: val => change(model, val),
            value: modelValue
        });
    }
}

export default connect(selector, {
    change: actions.change
})(SelectField);

```

**Comment by davidkpiano** [comment]
I reprioritized the props as you suggested in `react-redux-form@0.8.10`, mind trying it out and seeing if it fixes your issue?

**Comment by davidkpiano** [comment]
#77 verified that the issue has been resolved with the change! :fireworks:
