### ISSUE TITLE
Pre-fill input fields

### ISSUE THREAD

**Issue by ajits731** [davidkpiano/react-redux-form#742]
What would be the course of action for pre-filling the input fields when I click on 'Edit' on one page which redirects to another page and takes the data from the React BootstrapTable of that specific row and fills the input fields on the 'Edit' page.

**Comment by davidkpiano** [comment]
Simply dispatch `actions.change` or `actions.merge` (which allows you to change multiple fields at once) at any time:

```js
dispatch(actions.merge('user', {
  firstName: 'Ada'
  lastName: 'Lovelace'
});
```

**Comment by bryan-foong** [comment]
Any alternative for this if we're not using redux-thunk?

**Comment by davidkpiano** [comment]
@bryan-foong You can iterate over each of the fields:

```js
const changedUser = { firstName: 'Ada', lastName: 'Lovelace' };

Object.keys(changedUser).forEach(key => {
  dispatch(actions.change(`user.${key}`, changedUser[key]);
});
```

**Comment by bryan-foong** [comment]
Ok thanks for the solution! But will it affect performance to dispatch multiple change actions if I have a large form?

**Comment by davidkpiano** [comment]
Maybe... it's why it's good to batch (which is what `actions.merge` does). That said, there's nothing stopping you from merging yourself...

```js
dispatch(actions.change('user', {...user, firstName: 'Ada', lastName: 'Lovelace'}));
```

**Comment by iBasit** [comment]
I been trying to do this, but does not work :(

**Comment by davidkpiano** [comment]
@iBasit please post a reproducible CodePen or CodeSandbox example, and open a new ticket if you're having trouble.
