### ISSUE TITLE
Forms stop functioning after upgrade to 1.10.x

### ISSUE THREAD

**Issue by gmeans** [davidkpiano/react-redux-form#743]
### The Problem

After upgrading to 1.10.x, our rrf forms stopped functioning. These forms are using [react-md](https://react-md.mlaursen.com/) and use the `Control` component as follows:

```
<Control
            model="forms.client.name"
            component={TextField}
            id="name"
            name="name"
            label="Client Name"
            className="md-cell md-cell--12"
            customSize="headline"
            required
          />
```

Everything works fine on 1.8.3, however if we upgrade we no longer see rrf actions when typing in the text field and see no updates to the redux store.

### Steps to Reproduce

- Make form as described using 1.8.3
- Upgrade 1.10.x
- Try to use the form

### Expected Behavior

- We expect to see the typical rrf actions within redux's dev tools window.

### Actual Behavior

- The actions aren't seen.

### Reproducible Code Example
I wasn't able to get react-md to function correctly in the codepen to reproduce this. I'm happy to screen share and demonstrate the problem if necessary.

**Comment by davidkpiano** [comment]
You are using a default `<Control>`, which, when used with a custom component, makes no assumptions about that component. Replace `<Control>` with `<Control.text>` and it should work.

I'll clarify the docs on this, but a plain `<Control>` was never intended to assume which props it can map to a custom component (it doesn't make sense to do so). This was a bug in earlier versions that has been fixed.

**Comment by thomasboyt** [comment]
fwiw, can +1 that this was a really big surprise. In fact, this seems to directly contradict the docs for the `component` prop (http://davidkpiano.github.io/react-redux-form/docs/api/Control.html#component) _and_ the custom controls doc (http://davidkpiano.github.io/react-redux-form/docs/guides/custom-controls.html), which both clearly state that you should be able to expect that event handlers are implicitly bound (which is no longer true).

**Comment by gmeans** [comment]
@davidkpiano thanks for the explainer, as @thomasboyt mentioned we were going off of the docs.

Regarding the predefined `<Control />`s  do they do anything beyond controlling how props are mapped to the the `component={}`? I'm just wondering if we should watch out for things like Autocompletes that might not map clearly to an HTML input.

Is this section in the docs valid for `<Control />`?

> To prevent naming collisions or for more predictable prop-passing behavior, you can also specify the props in the controlProps={...} prop.

Specifically if I specify the controlProps here will `<Control />` pass them?

Thanks!

**Comment by davidkpiano** [comment]
You're right, I'll revert that change.

**Comment by davidkpiano** [comment]
Reverted in [1.10.2](https://github.com/davidkpiano/react-redux-form/releases/tag/v1.10.2)
