### ISSUE TITLE
Cannot access fact that field is in Error from sibling components

### ISSUE THREAD

**Issue by greghawk** [davidkpiano/react-redux-form#744]
### The Problem
When using the Error component I have no reference to its output unless i pass further state to my wrapping components

### Steps to Reproduce
If you look where it tries to set a classname in this case to show error styling on the input in question I don't have a way to tie it together using model references.

```
<Field model={`formModel.${step.name}`} validators={getValidations(step.validation)}
                     validateOn="blur">
        <input type="text" className={"form-control " + **(Field.errors ? 'sdf' : 'has-error')}**
               placeholder={step.placeholder}/>
        <Errors
          className="help-block has-error"
          wrapper="div"
          show={{ touched: true, focus: false }}
          model={`formModel.${step.name}`}
          messages={getValidationMessages(step.validation)}
        />
      </Field>
```

### Expected Behavior
Have a model call like formModel.fieldName.valid or something like that

### Actual Behavior
disconnected without state being brought in on top

### Reproducible Code Example
(please fork from [this CodePen template](http://codepen.io/davidkpiano/pen/yJwmEa))

**Comment by davidkpiano** [comment]
Instead of using `<Field>`, use `<Control.text>`. Example from the [FAQs](https://davidkpiano.github.io/react-redux-form/docs/guides/faqs.html):

```jsx
<Control.text
  model="user.firstName"
  mapProps={{
    className: ({fieldValue}) => fieldValue.valid
      ? 'valid'
      : ''
  }}
/>
```
