### ISSUE TITLE
Formatters versus Parsers missing functionality

### ISSUE THREAD

**Issue by greghawk** [davidkpiano/react-redux-form#745]
### The Problem
I don't wish to save parsed values in state i.e. money like $1,000.  I need to store 1000. I don't see a way to add formatted data to the Control from state. Parser property is great for preventing/formatting in the control itself but this also goes back to state this way.

### Expected Behavior
A functionality not unlike parser but formatter on the Control component

### Actual Behavior
There is parser only unless I am missing something I can't find in docs or repo.

**Comment by davidkpiano** [comment]
The fragile part of this is this: let's say you entered in `$1000` and expected `$1,000` to be the view value in a standard `<input type="text">`.

- The parser needs to always convert `1000` to `$1,000`
- The parser needs to _also_ know that `$1,000` converts to `$1,000`
- The formatter needs to convert that `$1,000` back to `1000` and send it back to the store.

And let's say you press backspace - your parser needs to be smart enough to know that `$1,00` should parse to `$100` so that your formatter can pick it up again. I can go on but this gets into some tricky logic where, if it's not perfectly in sync, can end up in an infinite loop.

I highly recommend creating a simple custom component for this instead, something like this:

```js
function parseCurrency(value) { /* ... */ }

function formatCurrency(value) { /* ... */ }

const Currency = (props) => (
  <input
    type="text"
    value={formatCurrency(props.value)}
    onChange={e => props.onChange(parseCurrency(e.target.value))}
  />
);

// rendered anywhere:
<Control.text component={Currency} model="invoice.total" />
```

The great thing about the above example is that it's more explicit and clear than using `parse` and (a nonexistent) `format`. But I'm curious to see how a `format` prop would look like to you - if you can make a compelling case (with good examples), I'd be more than happy to add it in.

**Comment by greghawk** [comment]
I hear what you’re saying.  It does seem to be a common need in form development though.  Show one way store another.  I will try the custom component wrapper and see how it fares.  I’ll think on the format property and get back.

I was thinking the formatter was for controlling how the data looks like in the input and the parser is for storage in the store. It is a little different of a concept of what you are using a parser for.

Angular has a standard way of doing this on its ngModel. See the section for parsers/formatters on this link. https://docs.angularjs.org/api/ng/type/ngModel.NgModelController

**Comment by greghawk** [comment]
Here is a more clear article if you aren’t familiar with angular’s implementation. https://alexperry.io/angularjs/2014/12/10/parsers-and-formatters-angular.html

**Comment by greghawk** [comment]
@davidkpiano I am trying the custom component but it doesn't seem to do anything with the model now? I am not quite sure how to use the custom component if I lose all the validators, model-state synch etc with this custom control.  Is there a production type example following  this pattern?

**Comment by davidkpiano** [comment]
Can you share the code?

**Comment by greghawk** [comment]
@davidkpiano I don't have a small example.  Can you tell me how the custom control is meant to work? It seems like it loses all the functionality of the standard controls. I'm at a loss as to how to use one.

**Comment by davidkpiano** [comment]
I'm actually going to implement formatters soon. I realize it's a necessary feature.

**Comment by greghawk** [comment]
Awesome!!!

**Comment by greghawk** [comment]
@davidkpiano any movement on the formatters? I am running up against a wall soon.

**Comment by davidkpiano** [comment]
@greghawk You can use a custom component as a stop-gap. What exactly is blocking you?

**Comment by greghawk** [comment]
@davidkpiano You're right. Let me try your example of above and see if can get it going. Will that custom control play nice with validations?

**Comment by davidkpiano** [comment]
Of course! Just add the right hooks to your component to let RRF know when it updates, and keep the view value in your own component's state.

That is, RRF shouldn't care what the view value is. It only should care what the real value is. Even something like [react-maskedinput](https://github.com/insin/react-maskedinput) should work, same concept.

**Comment by greghawk** [comment]
@davidkpiano Cool.  I am trying but the validation piece is not happy.  I'll look at masked input as well to see what they are doing.
This is what I've tried so far but I think it is trying to validate the formatted value even though redux is storing proper value:

const Formatter = (props) => (
  <input
    type={props.type}
    autoComplete={props.autoComplete}
    autoFocus={props.autoFocus}
    className ={props.className}
    placeholder={props.placeholder}
    onBlur={props.onBlur}
    value={props.formatter(props.value)}
    onKeyPress={props.onKeyPress}
    onFocus={props.onFocus}
    onChange={e => props.onChange(() => {
      return (e.target.value).replace(/\D/g, '');
    })}
  />
);

const TextControl = ({steps, step, formatter, type}) => {

  return (
    <div>
      <Control model={`formData.${step.name}`}
               component={formatter ? Formatter : null}
               validators={getValidations(step.validation)}
               formatter = {formatter}
               asyncValidateOn="blur"
               updateOn="change"
               asyncValidators={getAsyncValidations(step.validation)}
               validateOn="change"
               placeholder={step.placeholder}
               type={(step.mask) ? "password" : type}
               autoComplete={(step.mask) ? "new-password" : ""}
               autoFocus={steps.length === 1 || (steps.length > 1 && steps[0].name === step.name)}
               mapProps={{
                 className: ({fieldValue}) => (fieldValue.valid || fieldValue.pristine || !fieldValue.touched)
                   ? 'form-control'
                   : 'form-control has-error'
               }}/>
      <Control.text model={`formData.${step.name}`}
                    component={(props) => <ValidationIndicator>{props}</ValidationIndicator>}
                    mapProps={{
                      fieldValue: (props) => props.fieldValue
                    }}
      />

**Comment by daxiang28** [comment]
I was able to hack this together and it seems to work in case it helps anybody prior to 'formatting' being officially released:

```
import numeral from 'numeral';
const numberMask = createNumberMask({
    prefix: '',
    suffix: ''
})
const MyTextInput = (props) => <MaskedInput mask={numberMask} {...props} />;

<Control.text
    autoFocus
    model=".people"
    className="form-control"
    updateOn="blur"
    placeholder="Some text"
    autoComplete="off"
    component={MyTextInput}
    validators={{
        isNumeric: validator.isNumeric,
        required: val => val && val.length,
        minLength: val => val && val.length > 3
    }}
    parser={(val) => { return (val) ? numeral(val).format('0') : val; }}
/>
```

I think the trick is the parser cleaning it back up for validation

**Comment by brycesenz** [comment]
@davidkpiano - any thoughts on the PR?  I'll have some time this weekend to work on any revisions you might see fit.

**Comment by davidkpiano** [comment]
@brycesenz I'll accept it - if developers aren't careful, it can be a footgun, but I'm willing to give the feature a try!
