### ISSUE TITLE
Validating email field in v1.9+ causes maximum call stack error

### ISSUE THREAD

**Issue by ryanheathers** [davidkpiano/react-redux-form#746]
### The Problem
I'm running into a maximum call stack error for an email field that has validation turned on. Any kind of input into the field immediately triggers the error.

**I've verified that this error only occurs with RRF v1.9 or greater. Downgrading to v1.8.3 immediately clears up the issue.**

This is probably being caused by something in how my custom code is set up, but I haven't been able to pinpoint anything yet.

The interesting parts:
- If I remove the `validators` on the form, the error goes away (makes sense)
- If I keep the `validators` object but turn the Control's type to `text` rather than `email`, the error goes away

That second behavior made me think this is related to HTML validation. And since this error only occurs with RRF 1.9+, I thought it might be getting triggered by a change in this commit: https://github.com/davidkpiano/react-redux-form/commit/01476ff5c9c1234ce625b5a2f6808e95762701cb. I tried turning on `noValidate` for my form to disable HTML validation, however that had no effect. :/

Thanks in advance for any thoughts on how to fix this!

### Steps to Reproduce
Here's my code with just the relevant bits included:

```
class Signup extends React.Component {
  renderForm() {
    const { formState } = this.state;

    return (
      <FormWrapper>
        <LocalForm
          model="signup"
          validators={
            email: {
              isEmail: (val) => isEmail(String(val))
            }
          }
        >

          <Field
            type="email"
            model="email"
            fieldState={formState.email}
            showValidationIcon
            required
          />
        </LocalForm>
      </FormWrapper>
    );
}
```

```
class Field extends React.Component {
  createControl = () => {
    const { fieldSize, model, optionValues, type } = this.props;

    let size = fieldSize ? { [fieldSize]: true } : null;

    switch (type) {
      case ('select'): {
        return (
          <Control.select
            component={Select}
            model={`.${model}`}
            id={model}
            {...size}
          >
            { optionValues }
          </Control.select>
        );
      }

      case ('textarea'): {
        return (
          <Control.textarea
            component={Textarea}
            model={`.${model}`}
            id={model}
            {...size}
          />
        );
      }

      default: {
        return (
          <Control
            type={type}
            component={Input}
            model={`.${model}`}
            id={model}
            {...size}
          />
        );
      }
    }
  }

  render() {
    const { fieldState, instructions, model, showValidationIcon } = this.props;

    const control = this.createControl();

    return (
      <Wrapper>
        <Label htmlFor={model}>
          { model && splitCamelCaseToProperCase(model) }
        </Label>
        { instructions &&
          <Instructions>{ instructions }</Instructions>
        }
        <ControlWrapper>
          { control }
          { showValidationIcon && this.renderIcon(fieldState) }
        </ControlWrapper>
      </Wrapper>
    );
  }
```

**Comment by davidkpiano** [comment]
Would you be able to put that code example in a Codepen (using this template)? http://codepen.io/davidkpiano/pen/yJwmEa Would be really helpful for debugging.

**Comment by ryanheathers** [comment]
Thanks, I tried repro'ing in your Codepen template but couldn't trigger the error. The Codepen environment has pretty different tooling than my setup so it makes it a bit challenging to get an apples-to-apples test. The error is still happening for my local build, so I'll keep playing around and see if I can narrow down a cause. For now I'll go ahead and close this ticket.
