### ISSUE TITLE
Can't access 'name' parameter.

### ISSUE THREAD

**Issue by ajits731** [davidkpiano/react-redux-form#747]
console.log('App state Roles:', state.roles.selected_role.name); 

When I'm trying to access the name parameter with above command the error which pops up is "Cannot read property 'name' of undefined". But on using **console.log('App state Roles:', state.roles.selected_role)** I can see the array from which I want to retrieve the name.

**Comment by davidkpiano** [comment]
Can you post a full code example? At first glance, this doesn't even seem to be related to RRF.

**Comment by ajits731** [comment]
Sure ! Here is the code : `  render() {
    const heads = [{
      name: "Item 1"
    },{
      name: "Item 2"
    },{
      name:"Item 3"
    }];
   
        var selectRowProp = {
        mode: "checkbox",
        clickToSelect: true,
        bgColor: "rgb(238, 193, 213)",
        // onSelect: this.onRowSelect.bind(this),
        // onSelectAll: this.onSelectAll.bind(this)
     };

    return (
            
            <div className="page-container page-navigation-toggled page-container-wide">
            <Sidebar />
              <div className="page-content">
                  <Header />
                  <SettingsHeader />
                   <ButtonGroup className="suserbtn">
                   <Link to="/addhead" className="btn btn-primary"><i className="fa fa-plus" aria-hidden="true"></i>Choose Header</Link>
                   <Link to="/header" className="btn btn btn-danger" onClick={this.onDeleteClick.bind(this)}>Delete</Link>
                   </ButtonGroup>
                   
    
                  <BootstrapTable  
                      data={ heads }
                        selectRow={selectRowProp}
                         pagination className="table-hover" search={true} 
                       >
                             <TableHeaderColumn  dataField='name' isKey>Name</TableHeaderColumn>
                            
                             </BootstrapTable>       
                </div>
           </div>
       
      );
  }
}

function mapStateToProps(state) {
     console.log("New State",state.userdata.profile);
  
  
 return ({ selectedHeads: state.userdata.profile });
}


function mapDispatchToProps(dispatch) {
  return  {
      settingActions: bindActionCreators(settingActions, dispatch),
      indexActions : bindActionCreators(indexActions,dispatch)
    };
  
}

export default connect(mapStateToProps,mapDispatchToProps)(Head);`

**Comment by davidkpiano** [comment]
I don't see in the code where React-Redux-Form is being used (if at all). Can you please update your example (if you are using it)? I will reopen this ticket then. Also, I do not see where `.selected_role.name` is even being called.
