### ISSUE TITLE
<Field /> does not recurse into nested components

### ISSUE THREAD

**Issue by thatneat** [davidkpiano/react-redux-form#748]
### The Problem
[Documentation ](http://davidkpiano.github.io/react-redux-form/docs/api/Field.html)says "The <Field> component recursively checks its children to see if they can be made into a `<Control>`. " This doesn't seem to work if the descendant that can be turned into a `Control` is within a sub-component.

### Steps to Reproduce

Something like this:

```jsx
const VanillaField = () => (
    <div>
        <input type="text" />
    </div>
);
const MyField = () => (
    <Field>
        <VanillaField />
    </Field>
)
```

### Expected Behavior

The nested field is detected and turned into a `Control`. This would be quite a powerful feature since it allows arbitrary form fields to be used with `react-redux-form`

### Actual Behavior

The nested `<input>` isn't turned into a `Control` so actions are not fired on field events.

### Reproducible Code Example

http://codepen.io/jasoncurtis/pen/vmYeLb

**Comment by davidkpiano** [comment]
So, it'll recursively check something like this:

```jsx
<Field>
  <div>
      <input type="text" />
  </div>
<Field>
```

which works because the children are "visible" to the outer `<Field>` component. RRF has no idea what a `<VanillaField>` is, so it stops there. I highly encourage you to use `<Control>` instead of `<Field>`, if you can.

**Comment by thatneat** [comment]
Makes sense; I just saw it described in the docs and got excited about retrofitting my existing field components with RRF without having to fork or edit them all (I have several reusable fields used in different forms and didn't want to involve RRF in all of them at once). But I guess it is not to be. Maybe you could update the docs to be clearer on what you mean by "recursively"?

**Comment by davidkpiano** [comment]
Sure, I can do that. For your example, try this:

```jsx
const VanillaText = (props) => (
    <div>
        <input type="text" {...props} />
    </div>
);

// rendered:
<Control.text component={VanillaText} />
```

**Comment by thatneat** [comment]
That workaround doesn't seem to be doing the trick. See the [updated CodePen](http://codepen.io/jasoncurtis/pen/vmYeLb).
Either way, it seems like I should give up on the concept of wrapping vanilla components to RRF-ify them. At some point there will probably be further abstraction within my vanilla components, which would probably break the `<Control component={} />` approach as well. Sounds like a maintenance headache in the making. Best practice is probably to keep the RRF magic on the same level as the actual `<input>` so that it can be documented and prevented from regressing. Does that sound right to you?

**Comment by davidkpiano** [comment]
It works perfectly fine, you just need to change one thing:

```diff
class VanillaLastNameInput extends Component {
  render() {
    return (<span>
      <label>Last name:</label>
-     <input type="text" />
+     <input type="text" {...this.props} />
        </span>
    )
  }
}
```

**Comment by thatneat** [comment]
Ah, I missed that, thanks!
Will passing down `{this.props}` work for an arbitrary depth? Are there specific props that I need to be passing down?

**Comment by davidkpiano** [comment]
> Will passing down {this.props} work for an arbitrary depth? 

It's nothing magical; just as if you were passing props to any other component. When using `<Control.text>`, the standard props for `<input type="text">` (`onChange, onBlur, onFocus`, etc) are passed down.

**Comment by thatneat** [comment]
Ok, related question (lmk if you think this should be a separate issue): How should that work for multiple-checkbox inputs? Does each checkbox need to be a separate Control with a different `model` value?

To be clear, the model I'm aiming for has multiple values for a named checkbox input, so state is something like: `{choices: ['a', 'c']}` when the checkboxes with `value="a"` and `value="c"` are checked. I've been using `model={something.choices[]}` for each checkbox input but I still end up with only a single value `{choices: 'a'}` in the resulting state.

**Comment by davidkpiano** [comment]
> How should that work for multiple-checkbox inputs?

```jsx
<Control.checkbox model="choices[]" value="a" />
<Control.checkbox model="choices[]" value="b" />
<Control.checkbox model="choices[]" value="c" />
```

**Comment by thatneat** [comment]
There are a couple options that could be good. With your example, say we click checkboxes A and C. In one version (the one I described), the state would end up as an array `{choices: ['a', 'c']}`. In the other you'd get an object `{choices: {a: true, c: true}}`. Either one would be fine; is there a way to achieve either of those using RRF?

**Comment by davidkpiano** [comment]
Yes, haha:

```jsx
<Control.checkbox model="choices.a" />
<Control.checkbox model="choices.b" />
<Control.checkbox model="choices.c" />
```

will give you `{choices: {a: true, c: true}}`

**Comment by thatneat** [comment]
Perfect. thanks.

**Comment by thatneat** [comment]
I now see that I probably could have figured that out for myself, but more complete docs would be much appreciated.
