### ISSUE TITLE
Access model string from a wrapper component between Form and Field

### ISSUE THREAD

**Issue by RafaPolit** [davidkpiano/react-redux-form#751]
### The Problem
We have created a custom-made wrapper (very much like fieldset) in between Form and Field (to create custom error handling).

### Expected Behavior
Access the model string from within this middle-man wrapper to prevent adding aggain the model prop to each wrapper.  This could be achieved by exposing the resolveModel utils component. 

### Reproducible Code Example

```
<Form model={'modelString'}>
  <FieldWrapper model={'modelString'} field={'fieldName'}>
    <Field model={'.fieldName'} />
  </FieldWrapper>
</Form>
```
Ideally we would like to avoid repeating the model - field scenario in the FieldWrapper.  Ideally just put the field in the wrapper like the Field component syntax and pass it on to the Field.

Thanks for any feedback!
Rafa.

**Comment by davidkpiano** [comment]
You can grab the `model` from the context:

```jsx
class FieldWrapper {
  render() {
    const model = this.context.model;

    // ...
  }
}

FieldWrapper.contextTypes = {
  model: PropTypes.any, // could be a string or tracking function, choose what works in your use case
};
```

Let me know if that helps!

**Comment by RafaPolit** [comment]
Yes, thank you.  Sorry not to have mentioned before, we were hopping to access this inside MapStateToProps, as we are trying to avoid using this type of logic inside the render function.

Does that make sense at all?  
Tahnks again.

**Comment by davidkpiano** [comment]
But what you're talking about is grabbing the model **contextually**, which means that you'd use `context`, no?

**Comment by wichert** [comment]
I have a very similar situation here, where I am trying to create a label which updates its class based on a containing checkbox. Usage currently looks like this:

```html
<Fieldset model="profile">
  <legend>Subscribe to our newsletter</legend>
  <CheckedLabel model="profile.newsletter" value="yes">
    <Control.radio model=".newsletter" value="yes">  Yes
  </CheckedLabel>
  <CheckedLabel model="profile.newsletter" value="no">
    <Control.radio model=".newsletter" value="no">  No
  </CheckedLabel>
</Fieldset>
```

The CheckedLabel code is pretty simple:

```javascript
const mapStateToProps = (state, ownProps: PropType) => ({
  checked: getModel(state, ownProps.model) === ownProps.value,
})

const Label = ({ className, checked, children }: PropType, context) => {
  const cls = `${className || ''} ${checked ? 'checked' : 'unchecked'}`
  return (
    <label className={cls}>
      {children}
    </label>
  )
}

const CheckedLabel = resolveModel(connect(mapStateToProps)(Label))

export default CheckedLabel
```

Since mapStateToProps can not access the context (as @RafaPolit mentioned) I need to provide the full path here, which is quite awkward and possibly fragile if I want to reuse this component. It looks like the resolveModel wrapper is intended to fix that, but that is currently not exposed by react-redux-form.

In my case an alternative option might be to use a custom control, where the component renders both the label and the checkbox and copies all the wiring-logic that redux-react-form normally does.

**Comment by davidkpiano** [comment]
> In my case an alternative option might be to use a custom control, where the component renders both the label and the checkbox and copies all the wiring-logic that redux-react-form normally does.

This would actually be the simplest (and most idiomatic/pragmatic) option. Using `resolveModel` is meant for internal use, and you get the fully resolved model anyway available to you in `mapProps`:

```jsx
<Control.text
  model=".firstName"
  mapProps={{ model: ({ model }) => model }}
/>
// model will be the fully resolved model,
// e.g., "user.firstName"
```

I'll add this to the FAQs. This way, we can keep the API surface area low.
