### ISSUE TITLE
How to deal with entities, reducers and the form model?

### ISSUE THREAD

**Issue by toadle** [davidkpiano/react-redux-form#752]
Hey guys, 

sorry for asking this here, but I don't know of any better place. I got difficulty to understand how rrf should work on a collection of entities. 

Lets say I have this as my store: 

```js
currentUser: "10",
entities: {
  patients: {
    4: {
      id: "4"
      firstName: "John",
      lastName: "Doe"
    },
    5: {
      id: "5"
      firstName: "Foo",
      lastName: "Bar"
    },
  },
  users: {
    10: {
      email: "some@mail.com",
      id: "10",
      name: "username"
    }
  }
}
```

Now I'm trying to set up forms and especially the reducers for editing a `patient`. 
I've read [here](https://davidkpiano.github.io/react-redux-form/docs/guides/tracking.html) that I could technically write:
`<Form model="entities.patients[4]">`

But if so, how would I setup up my reducers?

I was thinking to dedicate a `forms`-key in my store just for that: 

```
currentUser: "10",
entities: {
  ...
},
forms: {
  patient: formReducer('<<< but what goes here? >>>', {}),
}
```

The question remains what do I give as the `model` to that reducer? Can't be `"entities.patients[4]"` because it contains a specific `id`.

Also, if I wanted to create a completely new `patient`. How would I write that `model` in `<Form>`?
Something like `<Form model="entities.patients[]`> ?

Also `combineForms` seemed like a good idea. But since I'd have to put it somehow like this: 

```
entities: combineForms({
  patients: patientsReducer,
  users: usersReducer
});
```
But then there is the question `<Form model="<<< but what goes here for a specific patient? >>>">`.

Hope I could make my problem somewhat clear. 
Thanks for any advice!

**Comment by davidkpiano** [comment]
> But then there is the question `<Form model="<<< but what goes here for a specific patient? >>>">`.

I'd assume you'd have some wrapper component:

```jsx
const PatientForm = (props) => (
  <Form model={`entities.patients[${props.patientId]`}>
    ...
  </Form>
);
```

And as far as your store, for most use cases you can just use `combineForms`:

```jsx
const store = createStore(combineForms({
    clinic: { /* your initial clinic state, same as JSON above */ }
});
```

Does that help?

**Comment by toadle** [comment]
@davidkpiano Thanks for getting back. 

Your suggestion was my first idea. But I always assumed that `<Form model="what goes here" ... >` also have to match 

```
const store = createStore(combineForms({
    some name here: { some: "defaults" }
});
```

otherwise the form/model for a rrf-form will not be found. 

Having a `<Form model={`entities.patients[${props.patientId]`}>` and a store like this: 

```
const store = createStore(combineForms({
    entities: combineForms({
       patients: patientsReducer
    })
});
```

Should this work?

**Comment by davidkpiano** [comment]
In order to avoid creating multiple form reducers, that could be:

```js
const store = createStore(combineForms({
    entities: combineReducers({
       patients: patientsReducer
    })
});
```

**Comment by toadle** [comment]
OK, here is how it will work - which perhaps illustrates my question a bit more. 

```
export default combineReducers({
  entities: combineReducers({
    patients: patientsReducer
  }),
  forms: {
    patient: formReducer("entities.patients", {})
  }
});
```

Now you can have a Form like this: `<Form model={`entities.patients[${this.props.patient.id}]`} onSubmit={this.props.updatePatient} >` and RRF will work as expected. 

Now one question remains: What if I had to create a new patient therefore need an empty form which is not really linked to an entity yet?

`<Form model={`entities.patients[new]`} onSubmit={this.props.updatePatient} >`

did not work.

**Comment by davidkpiano** [comment]
Use `<LocalForm>` - perfect use-case for it: davidkpiano.github.io/react-redux-form/docs/guides/local.html

**Comment by toadle** [comment]
@davidkpiano Thanks I'll take a look at that.

BTW: I forgot something in my above example. The reducers will only work if wired this way: 

```
import { modeled } from 'react-redux-form';

export default combineReducers({
  entities: combineReducers({
    patients: modeled(patientsReducer, 'entities.patients')
  }),
  forms: {
    patient: formReducer("entities.patients", {})
  }
});
```

**Comment by toadle** [comment]
@davidkpiano OK, I created a separate key for creating new objects like `entities.new.patient`. Works flawless. 

Still my question remains: I'm often trying to edit an entity via `<Form model="entities.patients[2]`/> with works when I have a reducer like

```
 forms: {
    patients: formReducer("entities.patients", {})
  }
```

But I'm often running into some endless `setFieldsValidity` loops when trying to do stuff like `actions.setDirty("entities.patients[4]")` or similar. 

Is *rrf* supposed to work this way on collections?

**Comment by davidkpiano** [comment]
Do you have a reproducible example that I can test?

**Comment by toadle** [comment]
@davidkpiano I just found this one: https://github.com/davidkpiano/react-redux-form/issues/796

So might be that it actually does not have to do with the collection.
