### ISSUE TITLE
Read-only mode for reviewing forms?

### ISSUE THREAD

**Issue by bebbi** [davidkpiano/react-redux-form#753]
I've been looking around with no answer to this question: How to show the same form in read-only mode.

An example use-case: a simple shop checkout process: `enter address` - `check order` - `confirm order`.

`Check order` contains the same address form as `enter address`. It has the same layout but is using different elements - e.g. a span instead of an input.

Is there any suggested way how this can be done with `react-redux-form`?

**Comment by davidkpiano** [comment]
Have you tried `<Control readOnly>`?

**Comment by bebbi** [comment]
I see, so looks like that's passed to underlying elements like it does for custom components.
That plus some css helps, thanks for quick reply!
