### ISSUE TITLE
Type definition missing for <Control.custom />

### ISSUE THREAD

**Issue by bovan** [davidkpiano/react-redux-form#756]
### The Problem
Property 'custom' does not exist on type 'typeof Control'.

https://github.com/davidkpiano/react-redux-form/blob/master/react-redux-form.d.ts#L215

not sure if it should be `static custom: React.ComponentClass<ControlProps<HTMLElement>>;` or something else or I would send PR :)

**Comment by davidkpiano** [comment]
`<HTMLElement>` is probably fine for now. 😄
