### ISSUE TITLE
Dynamic forms

### ISSUE THREAD

**Issue by kristian-puccio** [davidkpiano/react-redux-form#76]
Hi,

I'm very interested in using this form library. Seems simpler and more flexible than redux-form.

One thing I need to be able to support is dynamically creating form, each with a shape only know at run-time.

Basically I'm creating a bunch of 'people' objects, each of them will get a generated ID. Depending on the options they select during the creating the form they will see will be different. Also multiple of these form can be being edited at the one time. I know a UX nightmare! but it's what the client wants.

Is it possible to do this using react-redux-form?

Thanks

**Comment by davidkpiano** [comment]
**Yes you can**, and it's actually pretty simple to do. Did you take a look at this recipe? http://davidkpiano.github.io/react-redux-form/#/recipe/dynamic-fields

**Comment by jmeas** [comment]
@davidkpiano , thanks for the link! It seems that the site no longer has the recipe hosted – is that recipe still available somewhere?

**Comment by davidkpiano** [comment]
Sure, here you go: http://davidkpiano.github.io/react-redux-form/docs/index.html#/recipe/dynamic-fields

**Comment by jmeas** [comment]
Thank you! :v:

**Comment by Jore** [comment]
Thank you for this.

**Comment by eminaz** [comment]
@davidkpiano I could not open that link now, has the url changed?

**Comment by davidkpiano** [comment]
@eminaz Yes it has, in preparation for V1. I'll see if I can find the original, but there's no magic to making dynamic forms. It just works:

```js
<Field model="dynamicField.model">
  <input type="text" />
</Field>

// will dynamically modify...

<Field model={dynamicField.model}>
  <input type="text" />
</Field>
```

Contrived example, but you get the idea 😄
