### ISSUE TITLE
Validation failure does not block store changes

### ISSUE THREAD

**Issue by wichert** [davidkpiano/react-redux-form#763]
### The Problem

I am building a form which auto-stores fields on a backend after a change. I was expecting a validation error to result in the store not being changed, but this appears to be a misunderstanding.

### Expected Behavior

I would expect the store to only save valid data.

### Actual Behavior

All changes are stored in the store, even if they are invalid.

### Reproducible Code Example
http://codepen.io/wichert/pen/xdRZqX

**Comment by davidkpiano** [comment]
Hmm... the issue with that is that if the model value doesn't change for invalid values, the field would never know why it's invalid. It would just show as invalid, with an empty (or previously valid) model value. How would you expect this to work, re. desired API, etc.?

**Comment by wichert** [comment]
It's certainly an interesting problem. Trying to analyse this a bit I think we can distinguish two values for a control:

1. the current stored value (what you would revert to if you reset the form)
2. the current input value, which can be invalid (partial or incorrect input)

I think there is value on always having a saved and validated value in your state, which means the current input value (#2 above) is private to the form instead of part of the global state. You can of course still store that as part of the current state; if I remember correctly redux-form encourages that approach by using a `form` entry in the state.

The question then becomes how you move a value from one to the other at various points in time:

* when you first render / mount the form (copy from stored value to input value seems logical)
* when you submit the form if the entire form validates
* when you submit the form, the field is valid but another field in the form is invalid
* when you submit the form and the field itself is invalid
* when you change a field, and the new value is invalid
* when you change a field, and the new value is valid but another field in the form is invalid
* when you change a field, and the new value is valid

Perhaps the simplest approach is to add a level which can handle the copy. Something like:

```html
<VolatileForm model="profile" storeOn="submit-validate">
   <Control ... />
   <Control ... />
</VolatileForm>
```

Where VolatileForm would copy `profile` to `form.profile` in the state, and the values are copied back if the form is submitted and everything validates. `storeOn` could them be one of `submit`, `submit-validate`, `change` or `change-validate`. Maybe storeOn should also be allowed on a control to fine-tune behaviour?

```html
<VolatileForm model="profile" storeOn="submit-validate">
  <!-- Always save the value of the next control on change -->
   <Control storeOn="change" />
   <Control ... />
</VolatileForm>
```

That would be useful for global settings, for example a language selector or a unit switch (say celsius vs fahrenheit) that should have an immediate effect.

**Comment by wichert** [comment]
#700 seems related to this.

**Comment by caesay** [comment]
Data persistence of a store is not a form concern. The form tells you what the values of the fields are, and if they are valid or not. If you wanted `updateOn = "change"` and `validateOn = "blur"` you couldn't even make your suggestion work.

If you want non-standard behavior like this you could write your own `<Control />` as we have done (for other reasons).

Alternatively, you could simply check the validity of the model before persisting. You could just check the top level `$form` and fail if anything in the form is invalid, or you could be more granular and recurse the `$form` and only persist fields that are valid.

**Comment by davidkpiano** [comment]
@caesay is correct. This is intended behavior.
