### ISSUE TITLE
How to add wrapped error class?

### ISSUE THREAD

**Issue by divined** [davidkpiano/react-redux-form#773]
How to add wrapped error class? Add class if error in validator.

```
<div className="form-item"> <- add error class here
  <label>Nom</label>
  <Control.text model=".model" validators={{ required: this.rv }} />
  <Errors model=".model" messages={{ required: this.rm }} show="touched" />
</div>
```

**Comment by kkashou** [comment]
Did you ever figure how to do this?

**Comment by davidkpiano** [comment]
Hey @kkashou, see this answer: [How do I add conditional class names based on field state?](https://davidkpiano.github.io/react-redux-form/docs/guides/faqs.html)

**Comment by kkashou** [comment]
Thank you :)
