### ISSUE TITLE
FormActionsReducer: Uncaught TypeError: Cannot read property 'intents' of undefined

### ISSUE THREAD

**Issue by lasergoat** [davidkpiano/react-redux-form#775]
### The Problem

```
form-actions-reducer.js:164 Uncaught TypeError: Cannot read property 'intents' of undefined
    at formActionsReducer (http://localhost:5432/main.js:159328:29)
    at http://localhost:5432/main.js:26641:12
    at http://localhost:5432/main.js:159837:14
    at Array.reduceRight (native)
    at http://localhost:5432/main.js:159836:21
    at http://localhost:5432/main.js:39343:12
    at http://localhost:5432/main.js:81795:23
    at combination (http://localhost:5432/main.js:166428:29)
    at Object.dispatch (http://localhost:5432/main.js:84678:22)
    at AutomatedReceipts.LocalForm._this.dispatch [as localDispatch] (http://localhost:5432/main.js:158942:26)
```

Error here:

```JS
function createFormActionsReducer(options) {
  var formOptions = options ? _extends({}, defaultOptions, options, {
    initialFieldState: _extends({}, defaultOptions.initialFieldState, options.initialFieldState)
  }) : defaultOptions;

  var customInitialFieldState = formOptions.initialFieldState;

  return function formActionsReducer(state, action, localPath) {
    var _getFieldAndForm = (0, _updateField.getFieldAndForm)(state, localPath),
        _getFieldAndForm2 = _slicedToArray(_getFieldAndForm, 1),
        field = _getFieldAndForm2[0];

    var fieldState = field && field.$form ? field.$form : field;

    // ERROR HERE ___________________
    // Uncaught TypeError: Cannot read property 'intents' of undefined
    var intents = fieldState.intents;
    // ------------------------------


    var fieldUpdates = {};
    var subFieldUpdates = {};
    var parentFormUpdates = void 0;

    switch (action.type) {
      case _actionTypes2.default.FOCUS:
        {
          fieldUpdates = {
            focus: true,
            intents: action.silent ? intents : addIntent(intents, action)
          };

          break;
        }
```

### Steps to Reproduce

1. [open my codepen](http://codepen.io/polyesterhat/pen/ZKXBqE?editors=0010)
2. click the "Add Recipient" button
3. in the row that appears click the "delete" button
4. see the error

### Expected Behavior

The `dispatch(actions.remove())` should work fine and no errors should be throw 

### Actual Behavior

The `dispatch(actions.remove())` does work, but there are errors thrown.

### Reproducible Code Example

[http://codepen.io/polyesterhat/pen/ZKXBqE?editors=0010](http://codepen.io/polyesterhat/pen/ZKXBqE?editors=0010)

**Comment by gkweb** [comment]
@lasergoat -- Correct me if I'm wrong but you have called actions.remove on the model and then tried to reset validity on the removed Model. This would then cause the intents to be undefined? 

```javascript

this.localDispatch(actions.remove('local.receipts_emails', i));
this.localDispatch(actions.resetValidity(`local.receipts_emails.${i}`)); //Model has already been removed with first line, therefore is undefined / has no intents. Remove this line to fix error

```

**Comment by lasergoat** [comment]
@gkweb wow, you are right. By switching the dispatches (_I know, bad solution and could cause a race condition_) it fixes it. however, the reason i had to reset the validity is because without that if you had a validation error at index 0 and remove it, then suddenly the valid email at index 1 moves to index 0, but the field at index 0 is still marked as invalid.

[Here's an example of that in action](http://codepen.io/polyesterhat/pen/zwEMvB?editors=0010)

Notice that I commented out the resetValidity.

Steps:

1. [open my codepen](http://codepen.io/polyesterhat/pen/zwEMvB?editors=0010)
2. click add recipient twice to add two new emails
3. in email number three type an invalid email like `asdfasdf`
4. in email 4 type a valid email like `bartle4@doo.com`
5. now, click the "Delete email 3" button
6. `bartle4@doo.com` which is now in the third spot is now invalid

**Comment by gkweb** [comment]
@lasergoat -- 

Maybe at render the redux store is not yet updated or synced with the component state. Another race condition maybe? Also not sure how local form ties in with calling render on a component when not connected to the store. Maybe someone else has insight..

To quickly fix this issue associate the validation back with the component state: 

From this: 

```javascript

<Control.input
                      model={`local.receipts_emails[${i}]`}
                      className="ui-input"
                      placeholder="email address"
                      validators={{ isValid }}
                      style={!get(form, `receipts_emails.${i}.valid`) ? errorStyle : {}}
                    />

```

To this:

```javascript

<Control.input
                      model={`local.receipts_emails[${i}]`}
                      className="ui-input"
                      placeholder="email address"
                      validators={{ isValid }}
                      style={!isValid(lineItem) ? errorStyle : {}}
                    />

```
