### ISSUE TITLE
Debounce not in state loop when using parser control prop

### ISSUE THREAD

**Issue by greghawk** [davidkpiano/react-redux-form#780]
### The Problem
When using a parser function the value in the control does not use the debounce wrapper

### Steps to Reproduce
Create a control with debounce={800} and a parser function that adds random text to the input.  

### Expected Behavior
You will see the change only after debounce set time

### Actual Behavior
You will see the change immediately rather than after debounce set time

**Comment by davidkpiano** [comment]
This is expected. `parser` is how the value ends up as a model value, not as a view value. That the control displays that value is a side-effect of this - it's just displaying the view value as it appears as a model value. This sounds like something you'd need to make a custom control for.

Here's a timeline explanation for a debounced control:

- (0ms) Type `foobar`
- (1ms) `foobar` is shown as the view value
- (100ms) `foobar` still
- (800ms) view value parsed and saved to store as model value of `foobar1234`
- (801ms) control detects that view value doesn't match model value, so it updates the control
- (801ms) `foobar1234` shown

**Comment by greghawk** [comment]
So there is no mechanism to denounce view value?

On May 14, 2017, at 5:47 PM, David Khourshid <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #780<https://github.com/davidkpiano/react-redux-form/issues/780>.

**Comment by davidkpiano** [comment]
It's not a use case that makes sense. Think about it - let's say you type the letters `abcde` in an input. If you debounced the view value, you'd see:

- `a`
- `a`
- `a`
- `a`
- `a`
- `abcde` after 300 or so milliseconds

**Comment by greghawk** [comment]
It does if you type 1000 and want after about 300 ms to evaluate and add $ in front and comma after 1. Or type 2 digits and then add a / and then add a / again after 2 more digits like a date. Masking and formatting are common and not custom form needs as far as I've seen.

On May 14, 2017, at 11:35 PM, David Khourshid <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not a use case that makes sense. Think about it - let's say you type the letters abcde in an input. If you debounced the view value, you'd see:

  *   a
  *   a
  *   a
  *   a
  *   a
  *   abcde after 300 or so milliseconds

**Comment by greghawk** [comment]
I'm actually seeing on the 801 ms mentioned below this doesn't happen. My model value is set on dispatch changeaction but view value does not reflect.

On May 14, 2017, at 5:47 PM, David Khourshid <notifications@github.com<mailto:notifications@github.com>> wrote:


This is expected. parser is how the value ends up as a model value, not as a view value. That the control displays that value is a side-effect of this - it's just displaying the view value as it appears as a model value. This sounds like something you'd need to make a custom control for.

Here's a timeline explanation for a debounced control:

  *   (0ms) Type foobar
  *   (1ms) foobar is shown as the view value
  *   (100ms) foobar still
  *   (800ms) view value parsed and saved to store as model value of foobar1234
  *   (801ms) control detects that view value doesn't match model value, so it updates the control
  *   (801ms) foobar1234 shown
