### ISSUE TITLE
`mapProps` not recomputed when state changes

### ISSUE THREAD

**Issue by jmeas** [davidkpiano/react-redux-form#781]
### The Problem

`mapProps` isn't computed on every render. I would expect it to be called. This may be due to some simple misunderstanding of how `mapProps` works, but I would expect the two code samples in the below example to be identical in behavior:

### Steps to Reproduce

Here are two simplified code samples that don't behave similarly, when I expect that they would.

This first code behaves as expected. Basically, as the user types into the `Dropdown` component, `onUserInput` is called. We take that value, put it into state, then send it back into the Dropdown. With this first code sample, as the user types, the Dropdown gets its `value` prop updated:

```js
render() {
  const { stateValue } = this.state;
  return (
    <Control.custom
        model="some.model"
        component={Dropdown}
        value={stateValue}
        mapProps={{
          onUserInput: () => stateValue => {
            this.setState({ stateValue });
          }
        }}/>
  );
}
```

In this second code sample (all we did was move `value` into `mapProps`), the `mapProps` value is not called as the user types. Note that the component _is_ rerendering. But the `mapProps` are using some previous renders' mapProps. I added console logs to explain this: as the user types, "Rendering" will be output to the console on every key press, but "Updating value" is not.

```js
render() {
  const { stateValue } = this.state;

  console.log('Rendering');
  return (
    <Control.custom
        model="some.model"
        component={Dropdown}
        mapProps={{
          onUserInput: () => stateValue => {
            this.setState({ stateValue });
          },
          value: (props) => {
            console.log('Updating value');
            return stateValue;
          }
        }}/>
  );
}
```

Actual devtools screenshot of the above logs:

![image](https://cloud.githubusercontent.com/assets/2322305/25919532/d9d81d48-3583-11e7-8f57-3dfd803c746a.png)

My expectation is that there would be an "Updating value" after every "Rendering".

### Expected Behavior

The two code samples above would have the same behavior.

### Actual Behavior

`mapProps` isn't called for every render, so the second code snippet does not work.

---

Again, this might just be some simple misunderstanding I have about this library. @davidkpiano , off the top of your head, do you know if that's the case? If not, no worries – I'm sure I'll figure it out.

More details that may be relevant:

- this is a connected component (via react-redux)
- if I update this component's _props_, then `mapProps` will be recalculated

**Comment by davidkpiano** [comment]
The way `mapProps` works is that it defines a mapping between "standard" change props (such as `onChange`, `onBlur`, etc.) and custom ones. For performance reasons, it's also "cached" so RRF assumes that the mappings (which are all functions) never change.

These look to be props outside of that use case, so I would recommend defining them directly on the control:

```jsx
    <Control.custom
        model="some.model"
        component={Dropdown}
        value={stateValue}
        onUserInput={stateValue => this.setState({ stateValue })}
    />
```

Let me know if this works for your use case.

**Comment by jmeas** [comment]
Thanks for the quick reply, @davidkpiano ! I see now that I'm going outside of how `mapProps` is intended to be used. I'm sure I'll be able to find a way to refactor to make the problem go away. 

Thanks again 👌

**Comment by jmeas** [comment]
Actually, I figured I'd add more info. The example I gave was a simplified version of what I'm actually trying to do. The intent here is that sometimes, the `value` that I pass down will come from `modelValue` (which comes from RRF), and then other times, from state. So something like this:

```jsx
<Control.custom
  model="some.model"
  component={Dropdown}
  mapProps={{
    value: (props) => {
      return someCondition() ? props.modelValue : stateValue;
    }
  }}/>
```

But this only works sometimes.
