### ISSUE TITLE
Calling `setInitial`, then modifying form, throws internal Error

### ISSUE THREAD

**Issue by jmeas** [davidkpiano/react-redux-form#782]
### The Problem

I have a form, `forms.someResource`. It is available in a modal. When the modal closes, I want to call `setInitial` on the form. When I do this, then re-open the modal and change an input, RRF throws this error:

![image](https://cloud.githubusercontent.com/assets/2322305/25973496/3529da3a-3659-11e7-8f80-39a7a370de10.png)

The relevant code from RRF is:

![image](https://cloud.githubusercontent.com/assets/2322305/25973511/46bc0f84-3659-11e7-96e9-9093048ad04e.png)

### Steps to Reproduce

This minimal test case may or may not reproduce the problem, but it seems to be the gist of what's going on.

1. Mount a form
2. Call `setInitial` on that form
3. Unmount the form
4. Remount the form
5. Change an attribute

### Expected Behavior

No error would be thrown; the form would just work like normal.

### Actual Behavior

An error is thrown.

---

I've used another method to do what I intended to do here, so I'm not blocked, or anything. But it seemed like a possible bug with the library, or maybe I'm doing something wrong?

My code looks like:

```js
// This is called anytime the modal is closed
onClose = () => {
    const { onClose, setInitial } = this.props;
    // We reset whether the form is dirty/pristine/touched/etc.
    setInitial();
    onClose();
  };
```

Note that `setInitial` here has its arguments partially applied in `mapDispatchToProps`:

```js
function mapDispatchToProps(dispatch) {
  return bindActionCreators({
    setInitial: () => actions.setInitial('forms.someResource')
  }, dispatch);
}
```

**Comment by davidkpiano** [comment]
Can I see how your store is defined?

**Comment by davidkpiano** [comment]
Also, can you try to reproduce it on Codepen? (link available in the readme)

**Comment by henry-young** [comment]
I'm also experiencing this error. I'll try and get a codepen example. 
In the meantime, I was able to get the form working calling `actions.reset('forms.someresource')` after calling setInitial.

**Comment by henry-young** [comment]
Here is a link to the codepen.
http://codepen.io/henryyoung/pen/Wjyqjo?editors=0010

**Comment by jmeas** [comment]
@henry-young , thanks for adding a test case for this. I appreciate that.

Also, thanks for the fix @davidkpiano !
