### ISSUE TITLE
Errors limit?

### ISSUE THREAD

**Issue by divined** [davidkpiano/react-redux-form#783]
How can i show first error in stack only?

2 validation rules
1. length
2. structure

need to show structure error if no length error.

Need something like:
`<Errors limit="1" ... />`

**Comment by divined** [comment]
using two Errors element not a variant because it is a dynamic component, and create props for each validation rule not good

<MyElement
  validation1_rule=...
  validation2_rule=...
  ...
  validation1_message=...
  validation2_message=...
  ...
>

looks ugly.

**Comment by davidkpiano** [comment]
Easiest way is to pass in a function to the `<Errors wrapper={...} />` prop and only render a single child:

```jsx
function ErrorsWrapper({ children }) {
  return <div>{children && children.length > 1
    ? children[0]
    : children
  }</div>;
}

// render
<Errors wrapper={ErrorsWrapper} ... />
```

Personally, I'd just use CSS on a special errors class, something like this:

```css
.errors > .error:not(:first-child) {
  display: none;
}
```

**Comment by divined** [comment]
ty )
