### ISSUE TITLE
rrf/resetValidity is dispatched every time i navigate away from my form

### ISSUE THREAD

**Issue by mitko993** [davidkpiano/react-redux-form#785]
### The Problem
I have an App with 3 react-redux-forms, each on a separate page.
In my Form3 every time i navigate to the page setErrors is dispatched and every time i navigate away from it resetValidity is dispatched.
This is not the case in my Form1 and Form2. I do not want resetValidity to be dispatched when i navigate away from the page. I have no clue where it is coming from.

### Example code
This code is wrapped in a `<Form model='myForms.model3'>` tag, but it is not displaying.

    <div className='table-responsive'>
        <table className='table'>

            {this.props.items.map((item, index) =>
                <TableItem key={index}
                    item={item}
                    index={index}
                    inputs={this.props.inputs}
                    isTuneEnabled={this.props.forms[index].$form.valid}
                    onClickExpand={(index) => handleOnClickExpand(index, this.props.items.length)}
                    onClickTune={(index) => this.handleOnClickTune(index)}
                    onClickReset={() => this.handleOnClickReset(index)} />
            )}
        </table>
    </div>

**Comment by davidkpiano** [comment]
If you want validity to persist between pages, set `persist={true}` to all `<Control>` props where you want validation to persist. Otherwise, `resetValidity` will be dispatched whenever a Control component unmounts.

Let me know if this fixes your issue.
