### ISSUE TITLE
Displaying 1 error message at a time with multiple validator object

### ISSUE THREAD

**Issue by bryan-foong** [davidkpiano/react-redux-form#786]
Is there an option to  display 1 error message at a time depending on order of the validator object, lets say I have "required" and "validEmail" validator, the "required" validator need to be passed before the "validEmail" error message shows.

**Comment by davidkpiano** [comment]
Sure! The `validators` prop on `<Control>` can be a function, so you can have something like this:

```jsx
function emailValidator(value) {
  if (value === undefined || !value.length) {
    // don't show validEmail as invalid if value missing
    return { required: false, validEmail: true };
  }

  return {
    required: true,
    validEmail: isValidEmail(value); // external function
  }
}

// render...
<Control.text
  type="email"
  model="user.email"
  validators={emailValidator}
/>
```
