### ISSUE TITLE
Accessing state, without form? mapStateToProps?

### ISSUE THREAD

**Issue by businessnumbertwo** [davidkpiano/react-redux-form#789]
Guys

Very sorry to raise this here - but its a question not a bug. I'm very new to react, react-redux and react-redux-forms...

I'm using RRF to create all my models and forms. How though do I access the state, outside a Form or Control component. Basically I want to pass a value to a function which is held in the state. I've tried using the react-redux approach of mapping piece of the state to a prop using connect(), but this ended in bunch of errors

I'm assuming importing store from Redux and calling getState is not best practice either?

Got the feeling I'm barking up the wrong tree!

Many thanks, Phil

**Comment by davidkpiano** [comment]
What does your `store` setup look like? Your entire form and model state is in your Redux store, so you can just use `connect()` to get the pieces of data that you want: http://redux.js.org/docs/basics/UsageWithReact.html

**Comment by businessnumbertwo** [comment]
David,

Thanks for getting back to me! Ah yes - this works.

It worked when I mapped a state element to a prop (say state.meta.version), but wasn’t working if I tried to map state.meta then I got I whole bunch of endless rrf/setPending, rrf/batch and rrf/change actions.

Any idea (I have attached the code).

BTW - I have to reflect what others have said…this framework is immense! Super work.

Phil


import React, {Component} from "react";
import {Button, FormGroup, ControlLabel, FormControl, Panel, PageHeader, HelpBlock} from "react-bootstrap";
import {Form, Control, Errors} from "react-redux-form";
import {connect} from 'react-redux'
import {actions} from 'react-redux-form'

import {getBusinessObjectPromise, persistBusinessObjectPromise} from "./../objectStore/businessObjectActions"
import {EDITMODE, CREATEMODE} from "../formModes"


const required = (val) => val && val.length;
const maxLength = (len) => (val) => val.length <= len;


class Photo extends Component
{
    constructor(props)
    {
        super(props)
        this.persist = this.persist.bind(this)
    }


    componentDidMount()
    {
        const {dispatch, formMode, match} = this.props

        if(formMode !== CREATEMODE)
        {
            dispatch(actions.submit("photo", getBusinessObjectPromise("photo", match.params.id)))
                .then(response => 
                {
                    dispatch(actions.change('photo', response.photo))
                    dispatch(actions.change('meta', response.meta))
                    this.setState({version: response.meta.version})
                })
        }
    }


    componentWillReceiveProps(nextProps)
    {
        const {dispatch, formMode, match} = nextProps
  
        if(formMode !== CREATEMODE)
        {
            dispatch(actions.submit("photo", getBusinessObjectPromise("photo", match.params.id)))
                .then(response => 
                {
                    dispatch(actions.change('photo', response.photo))
                    dispatch(actions.change('meta', response.meta))
                    this.setState({version: response.meta.version})
                })
        }
        else
        {
            dispatch(actions.reset("photo"))
            this.setState({version: 0})
        }
    }


    persist(photo)
    {

        console.log(this.props)
        
        this.props.dispatch(actions.submit("photo", persistBusinessObjectPromise(photo,"photo", this.props.version)))
            .then ( () =>
            {
                
            })


        console.log(this.props)

    }

    selectActionButton()
    {
        switch(this.props.formMode)
        {
            case EDITMODE:
                return (<Button type="submit" name="Update Photo" bsStyle="primary" bsSize="small" disabled={false} >Save Changes</Button>)
            case CREATEMODE:
                return (<Button type="submit" name="Add Photo" bsStyle="primary" bsSize="small" disabled={false} >Create</Button>)
            default:
                return(<div></div>)
        }
    }


    render() 
    {
        return (
            <Panel>
                <PageHeader>Photograph</PageHeader>
                <Form model="photo"
                    onSubmit={(photo) => this.persist(photo)}>

                        <FormGroup bsSize="small" controlId="id1">
                            <ControlLabel>Title</ControlLabel>
                            <Control.text
                                model=".title"
                                component={FormControl}
                                validators={{
                                    required,
                                    maxLength: maxLength(15)
                                }}
                            />
                            <Errors
                                className="errors"
                                model="photo.title"
                                show="touched"
                                component={HelpBlock}
                                messages={{
                                required: 'Required',
                                maxLength: 'Must be 15 characters or less',
                                }}
                            />
                        </FormGroup>

                        <FormGroup bsSize="small" controlId="id2">
                            <ControlLabel>Reference</ControlLabel>
                            <Control.text
                                component={FormControl}
                                model=".reference"
                                validators={{
                                required
                                }}
                            />
                            <Errors
                                className="errors"
                                model="photo.reference"
                                show="touched"
                                component={HelpBlock}
                                messages={{
                                required: 'Required',
                                validEmail: 'Invalid email address'
                                }}
                            />
                        </FormGroup>
                    
                            <FormGroup bsSize="small" controlId="id3">    
                                {this.selectActionButton()}
                                {' '}

                    <Control.reset model="photo" type="reset" component={Button} bsSize="small">
                        Reset
                    </Control.reset>

                    
                            </FormGroup> 

            

                </Form>
            </Panel>
        )
    }
}

const mapStateToProps = (state) => {
    return {
        userName: state.user.userName,
        version: state.meta
    }
}



export default connect(mapStateToProps)(Photo)

**Comment by davidkpiano** [comment]
If you could put that in a Codepen that would be great (template here: http://codepen.io/davidkpiano/pen/yJwmEa ) but I suspect the infinite loop has to do with `componentWillReceiveProps`, because you're dispatching actions that can change props.

**Comment by businessnumbertwo** [comment]
Ah yes! That makes perfect sense…by mapping some state to a prop, then updating the mapped state in componentWillReceiveProps, I get myself into an endless loop, as the connected prop gets updated! But mapping a specific field the props themselves are not updated! I would have never spotted that - I’m still very much the novice.

Basically the form can be in one of two modes, create / update. If say the user has a form on screen with data in it, then clicks “Create New” from a top level menu, the form is not remounted, so I have to ensure the form is cleared out (hence the code in componentWillReceiveProps  I have also allowed it to reload the form with a new record also - say I added a Next Record button on the screen.

I need to think about how to architect this…I will try and put up in code pen later.

THANK YOU SO MUCH!

Phil

**Comment by businessnumbertwo** [comment]
So, after a little thought I put a guard around the update I was performing…works a treat! Thank you again! Phil

    componentWillReceiveProps(nextProps)
    {
        const {dispatch, formMode, match} = nextProps
  
        if(formMode!==this.props.formMode ||  match.params.id !==this.props.match.params.id)
        {
            if(formMode !== CREATEMODE)
            {
                this.getBusinessObject()
            }
            else
            {
                dispatch(actions.reset("photo"))
                dispatch(actions.reset("meta"))
            }
        }
    }

**Comment by davidkpiano** [comment]
Glad to help!

**Comment by businessnumbertwo** [comment]
David,

Quick question - is Control.button recommended? I noticed that you used <button> in your examples. Was there a reason for this?

I wanted to wrap a react-bootstrap button - if I use the react-bootstrap button unwrapped its “click” visual state doesn’t reset after the click.

Kind regards, Phil

**Comment by davidkpiano** [comment]
Shouldn't matter, `<Control.button>` is only a thin wrapper around the native `<button>`.

**Comment by businessnumbertwo** [comment]
I get lots of errors in the console, when I simply change<button type="submit">Save</button> to <Control.button type="submit">Save</Control.button>

such as: Uncaught TypeError: Cannot read property '0' of undefined

Any ideas? Am on latest version.

Thanks David, as ever!

full code below:

import React, {Component} from "react";
import {Button, FormGroup, ControlLabel, FormControl, Panel, PageHeader, HelpBlock} from "react-bootstrap";
import {Form, Control, Errors} from "react-redux-form";
import {connect} from 'react-redux'
import {actions} from 'react-redux-form'
import axios from "axios"

import {EDITMODE, CREATEMODE} from "../formModes"
import Meta from "./meta" 


const required = (val) => val && val.length;
const maxLength = (len) => (val) => val.length <= len;


class Photo extends Component
{
    constructor(props)
    {
        super(props)
        this.getBusinessObject= this.getBusinessObject.bind(this)
        this.persist = this.persist.bind(this)
        this.handleSubmit = this.handleSubmit.bind(this)
    }


    componentDidMount()
    {
        if(this.props.formMode !== CREATEMODE)
        {
            this.getBusinessObject()
        }
    }
    

    componentWillReceiveProps(nextProps)
    {
        const {dispatch, formMode, match} = nextProps
  
        if(formMode!==this.props.formMode ||  match.params.id !==this.props.match.params.id)
        {
            if(formMode !== CREATEMODE)
            {
                this.getBusinessObject()
            }
            else
            {
                dispatch(actions.reset("photo"))
                dispatch(actions.reset("meta"))
            }
        }
    }


    getBusinessObject()
    {
        const {dispatch, match} = this.props
        const id = match.params.id
        const objectType = "photo"
        const url = '/rest/' + objectType + '/' + id

        axios.get(url)
            .then(response => 
            {
                dispatch(actions.change(objectType, response.data.photo))
                dispatch(actions.change('meta', response.data.meta))
            })
            .catch(error => 
            {
                console.log("BAD")
            })
    }


    persist(payload)
    {   
        return new Promise((resolve, reject) =>
        {
            const {dispatch, match} = this.props
            const id = match.params.id
            const objectType = "photo"

            payload = Object.assign({},payload, {version: this.props.meta.version})

            if(this.props.meta.version>0)
            {
                const url = '/rest/' + objectType + '/' + id
                axios.patch(url, payload)
                    .then(response => {dispatch(actions.change('meta', response.data)); resolve(true)})
                    .catch(error => {console.log("CREATE FAILED")})
            }
            else
            {
                const url = '/rest/' + objectType
                axios.post(url, payload)
                    .then(response => {dispatch(actions.change('meta', response.data))})
                    .catch(error => {console.log("UPDATE FAILED")})
            }
        })
    }

  handleSubmit(values) {
    this.props.dispatch(actions.submit('photo', this.persist(values)));
  }


    render() 
    {
        return (
            <div>
                <Panel>
                    <PageHeader>Photograph</PageHeader>
                    <Form model="photo" onSubmit={(photo) => this.handleSubmit(photo)}>

                            <FormGroup bsSize="small" controlId="id1">
                                <ControlLabel>Title</ControlLabel>
                                <Control.text
                                    model=".title"
                                    component={FormControl}
                                    validators={{
                                        required,
                                        maxLength: maxLength(15)
                                    }}
                                />
                                <Errors
                                    className="errors"
                                    model="photo.title"
                                    show="touched"
                                    component={HelpBlock}
                                    messages={{
                                    required: 'Required',
                                    maxLength: 'Must be 15 characters or less',
                                    }}
                                />
                            </FormGroup>

                            <FormGroup bsSize="small" controlId="id2">
                                <ControlLabel>Reference</ControlLabel>
                                <Control.text
                                    component={FormControl}
                                    model=".reference"
                                    validators={{
                                        required
                                    }}
                                />
                                <Errors
                                    className="errors"
                                    model="photo.reference"
                                    show="touched"
                                    component={HelpBlock}
                                    messages={{
                                        required: 'Required',
                                        validEmail: 'Invalid email address'
                                    }}
                                />
                            </FormGroup>
                        

                            <FormGroup bsSize="small" controlId="id3">    
                                
                                <Control.button type="submit">Save</Control.button>

                            </FormGroup>
            
                    </Form>
                </Panel>
                {this.props.formMode!==CREATEMODE ? <Meta meta={this.props.meta}/>:<div></div> }
            </div>
        )
    }
}

const mapStateToProps = (state) => {
    return {
        meta: state.meta
    }
}

export default connect(mapStateToProps)(Photo)

**Comment by davidkpiano** [comment]
Do you need to use `<Control.button>`? If not, avoid it, use a plain button.
