### ISSUE TITLE
Question: Is there a feature comparable to redux-form field normalizers?

### ISSUE THREAD

**Issue by mdgbayly** [davidkpiano/react-redux-form#79]
We have a field that represents a weight between 0 and 100%.

When the user types in the field we parse out the weight value as an integer and that's what goes into our model. If the user types a number greater than 100 e.g. they type 95 and then 1, we want the value in the model to be 95.

In redux-form, I used a field normalizer for this which was given the new and previous value of the model field so I could return the prev value if the value went over 100.

It's not clear how I can do this in react-redux-form.

The most obvious solution seems to be to use a field parser to strip out the percent sign and prevent the value going above 100.  However, I don't have access to the previous value. Clearly I could get it from the state, but this feature is in a presentational component which doesn't currently need the state as props.

Any thoughts or would I need to pass the current state in as a prop?

**Comment by davidkpiano** [comment]
If your component is a connected component, you already have access to the current state. From there, you can use the `parse` prop to parse the view value for the model. I'll add this to the documentation - I must have forgotten to put it there (the documentation is still being completed).

```js
function parseWeight(value, prev) {
  let result = parseInt(value);

  if (result > 100) return prev;

  return result;
}

// in connected component's render() method:
let { user } = this.props;

return (
  <Field model="user.weight"
    parse={(value) => parseValue(value, user.weight)}>
    <input type="number" />
  </Field>
);
```

**Comment by mdgbayly** [comment]
Ok thanks. In this case it is not a connected component but I can pass prev val as a prop from a parent connected component. Just thought if rrf has the prev val at the point of calling parse it could pass it too. I took a quick look at the code and it didn't seem like it does directly? So passing as prop is fine.

Thanks

**Comment by davidkpiano** [comment]
It definitely can, but it would be the exact same as just passing in the value itself. Do you think that would be a good enhancement? To have `parse` be a function take in two arguments: `value` and `previousValue` ?

**Comment by mdgbayly** [comment]
"It definitely can, but it would be the exact same as just passing in the value itself. "

Didn't totally follow what you meant by that? Do you mean same as passing in the value from the state?

Yes but in this case we're in an unconnected component that just takes in a model path string so no state unless we explicitly pass as props.

Maybe it is wrong that we are doing the parsing in an unconnected component. But yes, for this particular use case it would be useful to have rrf pass current model value  as second parameter or have some way to reject a change.

Maybe I'm making it too complicated...

**Comment by mdgbayly** [comment]
Sorry, re-opening this to get some more input.

Incidentally RRF rocks!

I had a feeling this feature was going to be problematic.
So I've implemented the solution discussed above using the parser and passing in the previous value as a prop.  But the issue is that when the user types:

11 => all is ok

now then type one more 1 which pushes the model value over 100 so our parser returns the previous value of 11

RRF sends a change action, which updates the state (possiblly - it hasn't really changed), but then the component doesn't re-render so the edit control is left with the extra 1 and it still displays 111.

I know this really makes sense.  Presumably this is just pure Redux/React behavior rather than anything specific to RRF?

Just wondering if you have any hints on how to work around such things? e.g. including some other 'key' type parameter in the state which I can change even when the actual model value doesn't change to force a rerender. Thinking maybe I'll have to reach for updateOn again to send that additional action?

**Comment by mdgbayly** [comment]
OK - maybe this is because RRF is being smart and not updating a model value in the state if it has not changed?  If I explicitly update the state in my own model enhanced reducer, the component does re-render presumably because I'm forcing the state object to change?

**Comment by davidkpiano** [comment]
Ah, no, it's much simpler than that. In order to allow model changes to occur at any time, inputs are _uncontrolled_ components by default. That means, if you want to prevent the input field from actually showing `111` instead of `11`, you can just make it controlled like so:

```diff
<Field ...>
-  <input type="text" />
+  <input type="text" value={ user.weight } />
</Field>
```

**Comment by mdgbayly** [comment]
Ok - thanks - I'll give that a try.  The inner control in this case from my app's perspective is a custom 3rd party component.  A masked input. I believe it maintains internal state even though you pass it a value prop, so maybe it's not really playing by the rules or maybe by design it is uncontrolled.

Anyway, thanks, I'll close this one off again - you've been very helpful!
