### ISSUE TITLE
Please fix submit action in Actions interface in react-redux-form.d.ts

### ISSUE THREAD

**Issue by supostat** [davidkpiano/react-redux-form#795]
### The Problem

`actions.submit(model)` didn't work in TypeScript without `Promise` argument

### Solution
In `react-redux-form.d.ts` in `interface Actions` you have:
```javascript
submit: (model: string, promise: Promise<any>) => ActionThunk;
```
Please fix it on:
```javascript
submit: (model: string, promise?: Promise<any> | undefined, options?: any) => ActionThunk;
```

**Comment by davidkpiano** [comment]
Looks like this was already done. 👍
