### ISSUE TITLE
'Maximum call stack size exceeded' when trying to change validators

### ISSUE THREAD

**Issue by toadle** [davidkpiano/react-redux-form#796]
### The Problem
I have a `<Form model="entities.new.criteria" validators={validators} >` where validators gets build like this: 

```
    let validators = {
      type: {
        notEmpty
      },
      question: {
        notEmpty
      }
    };

    if(isCreatingSomethingNew()) {
      validators['name'] = { notEmpty, keyUnique };
    } else {
      validators['name'] = { notEmpty };
    }
```

So in cases where this form creates a new object, there are two validators `notEmpty` and `keyUnique` on `name` otherwise just one (`notEmpty`). 

I'm doing it this way, because I would like to have the validation on the field and not form-wide.

When the validators on the `<Form>` change this actually causes an infinite loop of `setFieldsValidity`-events in RRF. I can't see why. 

Trying different kinds of validators didn't change anything so I suppose this has to do with how RRF manages those validators internally.

### Steps to Reproduce
Just see the Code-Pen.

### Expected Behavior
This should not cause and infinite loop.

### Actual Behavior
Causes infinite loop up until `Maximum call stack size exceeded`.

### Reproducible Code Example
http://codepen.io/anon/pen/bWzPWv

**Comment by davidkpiano** [comment]
Could not reproduce - with the latest version (`1.11.1`) no infinite loop occurs.

**Comment by toadle** [comment]
OK - cool. Thanks for checking. I'm still on `1.8.0` here. Trying again. 
Thanks for the great work and the fast support. RRF is still the best solution for redux-forms. Much better that `redux-form` :-D!

**Comment by davidkpiano** [comment]
Hmm no I didn't. There was an error:

```
pen.js:81 Uncaught ReferenceError: noOp is not defined
```

so I just replaced it with `() => {}`.

**Comment by toadle** [comment]
Indeed works, with latest version `1.11.1`. 
Thanks.
