### ISSUE TITLE
this.props.dispatch(actions.reset('model')) - nothing happens

### ISSUE THREAD

**Issue by divined** [davidkpiano/react-redux-form#798]
### The Problem
actions.reset not works

### Steps to Reproduce
```
export default combineReducers({
  combineForms({
    filters: {},
  }, 'myContractsForm'),
})
```
  ```
componentWillUnmount() {
    this.props.dispatch(actions.reset('myContractsForm.filters'));
  }
```
### Expected Behavior
  model reset to initial state

### Actual Behavior
http://i.imgur.com/HXbsaVh.jpg
http://i.imgur.com/Xg3INQ6.jpg

 model have values (has not been reseted)

### Reproducible Code Example
(please fork from [this CodePen template](http://codepen.io/davidkpiano/pen/yJwmEa))

**Comment by davidkpiano** [comment]
Is there a way for you to isolate this in a reproducible example? (You can use the CodePen template above)

**Comment by divined** [comment]
problem if initial state is:

```
filters: {
  some_value_1: '',
  some_value_2: ''
}
```

this.props.dispatch(actions.reset('myContractsForm.filters')); -> not works
this.props.dispatch(actions.reset('myContractsForm.filters.some_value_1')) -> works;

**Comment by divined** [comment]
will try to create a codeSample.

**Comment by davidkpiano** [comment]
Ping @divined, were you able to create a code sample?

**Comment by divined** [comment]
Sorry, i'm on vacation now (

**Comment by davidkpiano** [comment]
No worries, I fixed it! Details are in the release notes for `1.12.0`.

**Comment by umair-khanzada** [comment]
@davidkpiano in my case `model` is an empty object `{}` and when reset the model nothing happens
