### ISSUE TITLE
Error messages with HTML5 constraint validators

### ISSUE THREAD

**Issue by zach-waggoner** [davidkpiano/react-redux-form#805]
### Problem

According to https://github.com/davidkpiano/react-redux-form/blob/bb050aa1467bd0e28e3af2b79772b611ea6301bb/docs/guides/validation.md, I must specify a validation function for isEmail in order to specify a corresponding error message. However, I would like to also specify `type="email"` for the purpose of HTML semantics. This binds my field validation state to the HTML5 validation, but my custom validator may not be the same as that. If my custom validator is too naive, then some bad emails will cause the field to be in an invalid state, but not show an error message. Perhaps there should be a way to either opt out of HTML5 constraint validators, or to specify error messages for them.

**Comment by davidkpiano** [comment]
You can use [`formNoValidate`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-formnovalidate) to disable HTML5 constraint validation on an input.

```jsx
<Control.input
  type="email"
  model="user.foo"
  formNoValidate
/>
```
