### ISSUE TITLE
Bug in xor/change?

### ISSUE THREAD

**Issue by djkz** [davidkpiano/react-redux-form#81]
When created a reducer with that looks like model.model.array,
using action.xor('model.array') seems to not get the state from it, but sends change to the right model,
using action.xor('model.model.array') gets the right array for xoring, but then sends action to 'model.array' instead.

**Comment by davidkpiano** [comment]
What does your store setup look like?

**Comment by djkz** [comment]
Here is how it's setup on my end:

let defaultQuoteFields = { recipients:[], signatory_id:'' }

const quote_reducers = {
  quote: combineReducers({ 
    quote: modelReducer("quote", defaultQuoteFields),
    quoteForm: formReducer("quote", defaultQuoteFields)
  })
}

const app = combineReducers({
    quote: quote_reducers.quote
})

store = createStore(app,  applyMiddleware( thunk, raygun))

model is 'quote.quote.recipients'

**Comment by davidkpiano** [comment]
Ah, so the `model` argument of the `modelReducer` and `formReducer` are expected to be **the exact path** of your model. In this case, you should change it like so:

```js
const quote_reducers = {
  quote: combineReducers({ 
-    quote: modelReducer("quote", defaultQuoteFields),
-    quoteForm: formReducer("quote", defaultQuoteFields)
+    quote: modelReducer("quote.quote", defaultQuoteFields),
+    quoteForm: formReducer("quote.quote", defaultQuoteFields)
  })
}
```

**Comment by djkz** [comment]
Thanks
