### ISSUE TITLE
Validation "onblur" occurs when a "blur" does not happen

### ISSUE THREAD

**Issue by sonarforte** [davidkpiano/react-redux-form#810]
### The Problem

I'm trying to implement validation on a simple form and it's quite a struggle. If I'm doing this wrong please let me know; I'm trying to combine this form with visual elements from a third-party library (semantic-ui) and use the validation in those elements.

However, I will ignore the ui library for now and just discuss the problem with react-redux-form, which is the `valid` key gets set to invalid on a form element before anything has happened, even though the `validateOn` prop is set to `blur`.

### Steps to Reproduce
```
      <Form 
        model="forms.widgetCreate"
        onSubmit={(values) => this.handleSubmit(values)}
      >
        <Control.text
          model=".name"
          validators={{
            required: (val) => val && val.length,
          }}
          validateOn="blur"
        />
        <button type="submit">Submit</button>

      </Form>
```

### Expected Behavior
I would expect, that when the form is initialized, the `name` field is valid, since no blur event has occurred.  This would allow me to use that aspect of the state as a prop to control whether the ui displays the field in "error mode".

### Actual Behavior

Unfortunately, when I examine the action history, an `rrf/setErrors` action is emitted before anything else happens. 

This has the effect of setting `forms.forms.widgetCreate.name.valid` to `false`, even though it should be valid at this point in time.

Thus I cannot use `forms.forms.widgetCreate.name.valid` to determine the validity of the input, since doing so would cause it to register as invalid before it has been touched. 

### Reproducible Code Example
By using the logger in [this example code](https://codepen.io/anon/pen/ybmymw
), you can see how the state for the form element will go from valid to invalid over the course of the `rrf/setErrors` action. 

The logger prints out all the actions that occur (and the before and after state), but for some reason I could not expand the whole state object. Thus the `stateTransformer` function prints out the value of the `name` field's `valid` key before and after each action.

It's possible that I'm using this in the wrong way, and if so, please let me know. Thanks!

**Comment by davidkpiano** [comment]
This is expected behavior, and here's why.

In this scenario, the `.name` is required - you want to ensure the user has entered a name before submitting the form. In order to ensure that, validation _must_ run when the component mounts, even if validating on blur.

Why? If validation does not occur, that means that `.name` is valid, without it being touched. So when you try to submit the for, you will be able to submit an empty `.name`, even though that's supposed to be invalid.

Can you walk me through your use case?

**Comment by sonarforte** [comment]
Sure, so I'm using `semantic-ui` to do the visuals. 

 ```
import { Control, Form, } from 'react-redux-form'
import {
  Button as UIButton,
  Form as UIForm,
} from 'semantic-ui-react'

//...

     <UIForm
        as={Form}
        model="forms.widgetCreate"
        onSubmit={(values) => this.handleSubmit(values)}
      >
        <UIForm.Input label="Name" required error={/* SOMETHING HERE */}>
          <Control.text
            model=".name"
            validators={{
              required: (val) => val && val.length,
            }}
            validateOn="blur"
          />
          </UIForm.Input>
        <UIForm.Button 
          type="submit">
          Submit
        </UIForm.Button>
      </UIForm>
```

The way this works is that you can compose ui elements with normal elements using the `as` prop in the ui element. 

The `Form.Input` [takes an](https://react.semantic-ui.com/collections/form) `error` prop, which is a boolean. When it's `true`, the field shows up red.

I'm trying to use the validation of the rrf form element to set the `error` prop. My idea is to pass the `forms` in as a prop using `mapStateToProps`, and accessing the validity as `props.forms.forms.widgetCreate.name.valid`. 

Is this the right way to go about doing it?

**Comment by davidkpiano** [comment]
You can probably pass `UIForm.Input` as a [custom control](http://davidkpiano.github.io/react-redux-form/docs/guides/custom-controls.html). From there, you can map props to the custom control and have access to the field's `.touched` state, so you can show errors only when the field is `touched && !valid`.

**Comment by toadle** [comment]
@sonarforte We are doing something similar with Bootstrap 4 as UI Kit. In my experience the behaviour regarding validation that @davidkpiano described is indeed more consistent and therefore desired. 

We also attach the displaying of error-messages to the `touched`-property. Since this will also correctly work when the user tries to submit something that he has never touched!

Example for a TextField from our code:

`TextField.js` 
```

const TextField = (props) => {
  const { model } = props;

  return (
    <Control component={TextFieldPresenter}
             mapProps={{passedProps: (props) => props }}
             controlProps={props}
             model={model} />
  );
}

export default TextField;
```

`TextFieldPresenter`
```
const TextFieldPresenter = (props) => {
  const { label, passedProps, required, messages, size, className, disabled, placeholder, unit, locked } = props;
  const { model, fieldValue, modelValue } = passedProps;

  const classes = classNames(
    className,
    'form-control',
    (size ? `input-${size}` : false),
    (!fieldValue.pristine) ? "has-changes" : false,
  );

  const wrapperClasses = classNames(
    size ? `form-group-${size}` : false,
    (fieldValue.touched && !fieldValue.valid) ? "has-danger" : false,
    locked ? `locked` : false,
  );

  return (
    <FormGroup className={wrapperClasses}>
      {label && <Label>{label}</Label>}
      {unit && <span className="input-unit">{unit}</span>}
      {locked && <GoFlame className="input-icon" />}
      <input
        {...passedProps}
        value={modelValue || ""}
        className={classes}
        required={required}
        disabled={disabled}
        placeholder={placeholder}
      />
      {fieldValue.touched && <FormFeedback>
        <Errors model={model} messages={messages} />
      </FormFeedback>}
    </FormGroup>
  );
};

export default TextFieldPresenter;
```

**Comment by davidkpiano** [comment]
That seems like a good solution. Alternatively, you can use the **How do you add conditional class names?** strategy in the FAQs: http://davidkpiano.github.io/react-redux-form/docs/guides/faqs.html

**Comment by sonarforte** [comment]
@davidkpiano I tried what I believe to be your suggestion, but I don't have access to the `touched` and `valid` state. Here is my code:

```
        <Control.custom
          model=".foo"
          component={UIForm}
          validators={{
            required: (val) => val && val.length,
          }}
          validateOn="blur"
          mapProps={{
            error: (props) => {
              console.log(props)
              return props.touched && !props.valid
            }
          }}
        />
```

When I print out the props, I don't see the desired fields; here is the output:

> {"model":"forms.mealCreate.foo","validators":{},"validateOn":"blur","mapProps":{},"fieldValue":{"focus":false,"pending":false,"pristine":true,"submitted":false,"submitFailed":false,"retouched":false,"touched":false,"valid":false,"validating":false,"validated":true,"validity":{"required":false},"errors":{"required":true},"intents":[],"model":"forms.mealCreate.foo","value":null,"initialValue":null},"controlProps":{},"updateOn":"change","asyncValidateOn":"blur","ignore":[],"dynamic":false,"withField":true,"persist":false,"isToggle":false}

**Comment by sonarforte** [comment]
@davidkpiano I tried your suggestion and it's close to working, although the state doesn't seem to update correctly. 

```
<Control.custom
  model=".foo"
  component={UIForm.Input}
  validators={{
    required: (val) => val && val.length,
  }}
  validateOn="blur"
  mapProps={{
    error: (props) => {
      console.log("touched: " + props.fieldValue.touched)
      console.log("valid: " + props.fieldValue.valid)
      return props.fieldValue.touched && !props.fieldValue.valid
    }
  }}
/>
```
It turns out that at first, `touched` is `false` and `valid` is `true`, but then after the `rrf/setErrors` action, both fields remain `false` despite typing into the field, blurring it, etc.  

Any ideas why this could be occurring?

**Comment by davidkpiano** [comment]
Can you make a reproducible code example? Most likely, something isn't mapping to `onBlur` in your custom control. That's how RRF knows that a control has been touched.

**Comment by sonarforte** [comment]
[Here is](https://codepen.io/anon/pen/bRNaaV) the example. For some reason the log statements in the `mapProps` function only get called twice, even if I continue blurring/focusing, etc. 

However, in my code they keep getting called with unchanging values. Either way, I think this might be part of the problem.

**Comment by sonarforte** [comment]
So I got this working and I'm not sure what exactly did it, but here is a complete example for posterity:

```
import { Control, Form, } from 'react-redux-form'
import {
  Button as UIButton,
  Form as UIForm,
  Input as UIInput,
} from 'semantic-ui-react'

...

  render() {

    const required = (val) => val && val.length > 0
    const requiredError = (props) => {
      const { touched, valid } = props.fieldValue
      return touched && !valid
    }

    return (

      <Form
        model="forms.widgetCreate"
        onSubmit={(values) => this.handleSubmit(values)}
        component={UIForm}
        className=""
        validators={{
          name: { required },
          description: { required },
        }}
      >
        <UIForm.Group>
          <Control
            type="text"
            model=".name"
            component={UIForm.Input}
            mapProps={{
              label: "Name",
              required: true,
              error: requiredError,
            }}
          />

        <Control
          type="textarea"
          model=".description"
          component={UIForm.TextArea}
          mapProps={{
            label: "Description",
            required: true,
            error: requiredError,
          }}
        />
    </UIForm.Group>

        <Control.file
          model=".image"
          accept="image/*"
          component={UIForm.Input}
          mapProps={{
            label: "Upload a photo",
            required: true,
          }}
        />

        <Control.button
          model="."
          type="submit"
          component={UIForm.Button}
        >
          Submit
        </Control.button>
      </Form>
    )
  }

```

**Comment by davidkpiano** [comment]
Nope, looks good! By the way, you can use `<Control.text>` for `<input type="text">` and `<Control.textarea>` for `<textarea />`.

**Comment by sonarforte** [comment]
Thanks! I don't know if I edited after you responded, but do you have any input on `requiredError` returning true after a failed submit?

**Comment by davidkpiano** [comment]
> do you have any input on requiredError returning true after a failed submit?

Can you elaborate?

**Comment by sonarforte** [comment]
When I submit the form with a required field missing, e.g. the `name` field in the above example, `requiredError` returns true for all fields with that `error` prop in `mapProps`, whether or not they have any text in them.

So let's say I type something in `name` above, then submit. Then`fieldValue.valid` shows up as true for `name`, even though it is valid since there is text in the field.

**Comment by davidkpiano** [comment]
@sonarforte If that's a different example, can you make a reproducible example of that on Codepen too?

**Comment by sonarforte** [comment]
@davidkpiano Do you mean a different example than the one I included in the previous comment? 

That codepen example illustrates what I'm talking about.

**Comment by davidkpiano** [comment]
Solved the issue, see below. The input-specific props were not being passed in. Here's how you can refactor:

```diff
const UIInput = (props) => {
+  const { error, label, ...inputProps } = props;

  return (
    <div>
      <label>{error ? "Error" : label}</label>
+    <input type="text" {...inputProps}></input>
    </div>
  )
}
```

Hopefully that's clear! Custom components can be tricky.
