### ISSUE TITLE
Debounced and flushed change handler is called twice

### ISSUE THREAD

**Issue by FelixHenninger** [davidkpiano/react-redux-form#813]
Hi y'all, hi @davidkpiano,

I think I've spotted a (tiny) bug :-) .

#### The Problem
When a debounced control is unmounted, previously debounced change handlers are flushed. This uses the `debounce` method from `utils/debounce.js`. However, flushing the debounced handler does not cancel the previously set timeout. Therefore, the handler might be called twice, and this can lead to problems (in my case, the delayed function is deleted inbetween, which leads to an error).

#### Steps to Reproduce

(these assume that the [`debounce` utility function](https://github.com/davidkpiano/react-redux-form/blob/master/src/utils/debounce.js) is loaded or copy-pasted):

```
// Define an arbitrary function
const myFunc = () => console.log('bounce!')

// Debounce it
const myDebouncedFunc = debounce(myFunc, 1000)

// Run and immediately flush the debounced function
myDebouncedFunc()
myDebouncedFunc.flush()
// -> 'bounce!'
// [delay]
// -> 'bounce!'
```

All issues disappear if I replace [line 16 in `debounce.js`](https://github.com/davidkpiano/react-redux-form/blob/master/src/utils/debounce.js#L16) with `debouncedFunc.flush = () => laterFunc ? laterFunc() : null;`, but I'm not sure that this is the best solution &mdash; probably, `flush` should also run `clearTimeout(timeout)`. There might be implications of such a change that I'm missing, however.

#### Expected behavior

The dounced method is only called once when flushed.

#### Actual behavior

It's called twice after the specified delay :-)

#### Reproducible Code Example

See above for a minimal example -- I am super-sorry to not have a demo using an actual form. I've [updated my previous example](https://codepen.io/anon/pen/KqPpmJ), but I can't get it to flush the `onChange` handler at all (and I can't tell why -- all dependencies should be up-to-date). In my app on the other hand, the debouncing and flushing works perfectly, but unmounting the `LocalForm` component results in an `Uncaught TypeError: laterFunc is not a function`.

**Comment by FelixHenninger** [comment]
That was super-quick, thanks a lot!

**Comment by FelixHenninger** [comment]
Btw., if you have a moment, can you spot why the example in the CodePen isn't flushing? I've spent hours today trying to figure out why, but I can't spot what's going on -- possibly there's another bug lurking somewhere.

**Comment by davidkpiano** [comment]
It's probably because you're destroying the entire `LocalForm`, not just the control. I'll investigate further.

**Comment by FelixHenninger** [comment]
Thanks a lot, that would be great! I've tried to replicate the bug inside my app (where I destroy `LocalForm`s regularly), but things seem to work perfectly there (there is some weirdness going on with an action getting lost when I destroy a form with pending changes, but that might my mistake). I'll see if I can pin this down, but I probably don't know enough about RRF internals.

**Comment by FelixHenninger** [comment]
Just a brief update: This seems to persist with version `1.12.0`. Slightly extending the [basic pen](https://codepen.io/anon/pen/qjdazJ) linked above, it appears that the `onChange` handler (line 45, cf. also console output) is being called correctly when the `LocalForm` is torn down, so flushing actually works, but the value that is passed to the handler is not up-to-date.

Would you like me to create a new issue around this? I'm somewhat hesitant to do this, as I can't rule out that I'm making a stupid mistake somewhere, but I intuit that this might be worth investigating. Thanks again for your effort and support!

**Comment by davidkpiano** [comment]
> Would you like me to create a new issue around this? I'm somewhat hesitant to do this, as I can't rule out that I'm making a stupid mistake somewhere, but I intuit that this might be worth investigating. Thanks again for your effort and support!

Please do!

**Comment by FelixHenninger** [comment]
Ok, I've put all information in #830 . I'd love to figure this one out!
