### ISSUE TITLE
Error thrown when asyncValidators are set and asyncSetValidity is called in componentDidMount

### ISSUE THREAD

**Issue by zach-waggoner** [davidkpiano/react-redux-form#818]
### The Problem

If I have an async validator validating on "change," and I also want to validate when the component mounts (to validate the initial state) by calling `asyncSetValidity`, then the error `Uncaught TypeError: e.asyncKeys.indexOf is not a function` is thrown after I modify the input.

### Reproducible Code Example
https://codepen.io/anon/pen/KqKNqx

If you make 2 changes to the input, you will see the error logged in the console. If you comment out `dispatch(actions.asyncSetValidity('user.firstName', isAvailable));` in `componentDidMount`, you will not see the error.

**Comment by netbek** [comment]
I get the same error after submitting a form that has an async submit handler, more than once. I'm not using `actions.asyncSetValidity`. Below is a simplified version of my case. PR https://github.com/davidkpiano/react-redux-form/pull/837 fixes things sufficiently for my case, and appears (I did a quick test only) to handle the original issue. A more comprehensive fix might address the fact that `asyncKeys` can have an array or boolean value (https://github.com/davidkpiano/react-redux-form/blob/58fa7ccc2fafe4b4bfb49b4448207b782071bf41/src/reducers/form-actions-reducer.js#L209), which could lead to unexpected behaviour.

```
const formsReducer = combineForms({
  myForm: {
    myField: []
  }
}, 'forms');

const rootReducer = combineReducers({forms: formsReducer});

class MyFormComponent extends React.Component {
  handleSubmit(myForm) {
    const {dispatch} = this.props;
    const submitPromise = new Promise(function(resolve, reject){
      setTimeout(function(){ reject(false); }, 500);
    });
    dispatch(actions.submit('forms.myForm', submitPromise));
  }
  render() {
    return (
<Form model="forms.myForm" validators={{
    '': {
      myFieldIsRequired: ({myField}) => !!myField.length
    }
  }} onSubmit={(myForm) => this.handleSubmit(myForm)}
>
  <MyCheckbox model=".myField[]" value={1} />
  <MyCheckbox model=".myField[]" value={2} />
  <MyCheckbox model=".myField[]" value={3} />
</Form>
    );
  }
}
```

**Comment by davidkpiano** [comment]
Looks like this is no longer reproducible in the latest version! 🎉 Please reopen if you encounter this again.
