### ISSUE TITLE
Question: Recommended way to reset all field errors after submit

### ISSUE THREAD

**Issue by mdgbayly** [davidkpiano/react-redux-form#82]
We do validation server side in our API. User can submit form and they might get some validation errors back. User can interact with a field that is in error (which will clear the error status on the field) and then resubmit.  But the change in form state, might also clear other errors that the user didn't interact with.

So after a form submission we'd like to reset all field errors and then setup the error state of the form from scratch again using the error info returned by the API.

Just wondering if there is a handy way to do that.  I see mechanisms for form reset/setinitial (synonyms currently?) but they seem to operate on a single model path, and don't allow resetting field state across the whole form?

I guess we could just implement our own action creator that iterates all fields in the form state and dispatches reset actions for each field?

**Comment by davidkpiano** [comment]
Fixed in `react-redux-form@0.8.12`! Now if you dispatch `actions.resetValidity('user')` to an entire **form** (such as `user`), then all of the form's fields will also have their validities reset.

**Comment by mdgbayly** [comment]
Sweet! thanks just what I needed.
