### ISSUE TITLE
dynamic forms questions

### ISSUE THREAD

**Issue by samcolby** [davidkpiano/react-redux-form#822]
### The Problem

I'm not sure I understand how dynamic forms are supposed to work!  I've been banging my head against this for nearly 3 days now.  

I've been trying to use the following as a guide to no avail https://github.com/davidkpiano/react-redux-form/issues/525

So, I'm looking for some advice really.

### Steps to Reproduce

Probably easiest if I explain what I'm trying to achieve...

I have the following state
```js
{ 
  calculators: {},
  favourites: {}
}
```

state.calculators contains a number of forms that are available on load and I'm using the following code, which is working brilliantly for state.calculators. 
 
```js
const rootReducer = combineReducers({
  calculators: combineForms(formsState, "calculators"),
  favourites
});
```
formsState contains the initial values and layout for each of the forms etc.

The favourites reducer contains an ADD_TO_FAVOURITES action (amongst others). Which will copy one of the "calculators", with its values at that point in time, from state.calculators into state.favourites.  

What would be the best way to enable RRF for the forms in state.favourites in a similar way to how I have it setup for state.calculators, given that the forms in state.favourites are dynamic?

Thanks for any advice on this...

**Comment by davidkpiano** [comment]
You can use an existing reducer in `combineForms`. Check out the bottom of this page (under **Using Existing Reducers**) and see if that helps: http://davidkpiano.github.io/react-redux-form/docs/guides/models.html

**Comment by samcolby** [comment]
Hi, Thanks for the response.

I still don't see how I can setup both the dynamic forms and my reducer into the same place in the state tree.  I'm guessing that is what I would need to do (?) 

If I use the following
```js
const rootReducer = combineReducers({
  calculators: combineForms(formsState, "calculators"),
  favourites: combineForms({favourites}, "favourites"),
});
```

I end up with the following state, where my own reducer is one level too low

```js
{
  calculators:{...},
  favourites: {
    favourites: {},
    forms:{}  
  }
}
```

**Comment by davidkpiano** [comment]
I don't know exactly what each of the variables are, but try this:

```js
const rootReducer = combineForms({
  calculators: initialCalculatorsState, // or formsState if that's what that is
  favourites: favourites,
});
```

**Comment by samcolby** [comment]
Hi,

Thanks, that gives me.

```js
{
  calculators: {},  // this is empty
  favourites: {}, // empty
  forms: { $forms: {...}}  // etc.. 
}
```

That might work (I need to tweak my other code), but it doesn't really feel right to have both the top level calculators:{} and favourites:{} as being permanently empty.  I'll have a play around with it.

So, if I want to dynamically add a new form this way, will I need to manually manipulate the RRF state tree to add new ones in?  I saw this thread https://github.com/davidkpiano/react-redux-form/issues/525 but didn't understand how to set the initial values of the form there.

btw  formsState is just a collection of objects that contain the configuration for each form eg 
```js
{
  calculator1: {...},
  calculator2:{...},
  calculator3:{...}
}
```

I guess, conceptually, I was hoping to have the following state tree, with the RRF state kept where ever it works best.  I'm not tied to that, but it makes it most sense to me.

```js
{
  calculators: {
    calculator1:{...},
    calculator2:{...},
    calculator3:{...}
  },
  favourites:{
    favouritedCalc1:{...},
    favouritedCalc3:{...}
  }
}
```

**Comment by samcolby** [comment]
Hi, 

Right, after a bit more faffing about, I think I've got that to work using the above!  

Although, it breaks if I add some initialState to the createStore call, but setting that to undefined allows it to work fine.

```js
const store = createStore(
    rootReducer,
    undefined,
    compose(applyMiddleware(...middleware), autoRehydrate())
  );
```

Also, my 'non forms' reducer does get called on every form update now, but I can live that!

Really big thanks for your help with this, it's been driving me potty.

Sam

**Comment by davidkpiano** [comment]
Interesting, can you isolate the case where using `initialState` with `createStore` causes it to break, and file an issue? I'd greatly appreciate that!

**Comment by samcolby** [comment]
I've had another look and it does make some sense the way it is currently working.  It was just too confusing for me to get it right with no previous knowledge of the combineForms call etc.

The state in state.calculators from the reducer is being overwritten by the initialState added to createStore call, but does get added back in when the form is first used (if that makes sense).

See https://codepen.io/samcolby/pen/weBwEy if you're interested and let me know if you still want me to file as a bug.

**Comment by davidkpiano** [comment]
Sure, please file this as a separate bug.
