### ISSUE TITLE
initialState in createForms overwrites initalFormsState created using combineForms

### ISSUE THREAD

**Issue by samcolby** [davidkpiano/react-redux-form#826]
### The Problem

I'm not sure if this is an issue or not, but logging as requested in https://github.com/davidkpiano/react-redux-form/issues/822

See https://codepen.io/samcolby/pen/weBwEy for an example

The values in initialFormsState are overwritten by whatever is in initialStateShape

```js
const store = createStore(combineForms({
  topLevel1: initialFormsState
}), initialStateShape, applyMiddleware(thunk));
```

### Steps to Reproduce

See [CodePen](https://codepen.io/samcolby/pen/weBwEy)

### Expected Behavior

Whatever created by the reducer should not be overwritten and instead be merged into the initialState

### Actual Behavior

the initialFormsState is overwritten, but recreated the first time a form is actually used

### Reproducible Code Example

https://codepen.io/samcolby/pen/weBwEy

**Comment by davidkpiano** [comment]
> Whatever created by the reducer should not be overwritten and instead be merged into the initialState

I'm not sure that was ever intended behavior with React Redux. Regardless, the CodePen example seems to work fine with the latest version of RRF.
