### ISSUE TITLE
Question: testing the existence of form fields with unit tests

### ISSUE THREAD

**Issue by pbreah** [davidkpiano/react-redux-form#827]
First let me congratulate you for such an awesome React form. Nice work and thanks for donating your valuable time.

### The Problem

This is more a question, as I have been trying to replicate your tests to check the existence of a form in my unit tests, but has taken too much time with no results. Everything works outside of unit tests, it's testing the challenge.

I have a hierarchy of components: 
```jsx
<ContainerConnectedComponent>
    <ControllerChildComponent>
            <ComponentThatShowsForm>
                  <RRF />
            </ComponentThatShowsForm>
    </ControllerChildComponent>
</ContainerConnectedComponent>
```
On my test I'm clicking a link that triggers a setState that renders the `<ComponentThatShowsForm>` and the form is supposed to be rendered.

Instead I get: Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(Form)

if I manually wire the component to the store passing the `<RRF store={store} />` I get this error: Uncaught Invariant Violation: dangerouslyReplaceNodeWithMarkup(...): Cannot render markup in a worker thread. Make sure `window` and `document` are available globally before requiring React when unit testing or use ReactDOMServer.renderToString() for server rendering.

The thing is I already have the window and document set with jsdom, and it works on other unit tests.

On my test I'm wrapping a provider with a store like so:

```jsx
<Provider store={store} >
    <ContainerConnectedComponent>
          ...same hierarchy as above
    </ContainerConnectedComponent>
</Provider>
```
My unit tests are targeting the `<ContainerConnectedComponent>` as a whole (not shallow) and not specifically the `<RRF />` but want to ensure I can trigger the visibility of the form from `<ContainerConnectedComponent>`

My test are basically ensuring that the form renders and the fields are present - after clicking the link.
 
### Steps to Reproduce

Basically testing any connected container component to show a nested form inside a tree of other components.

### Expected Behavior

I want to be able to render the whole tree until `<RRF />` from the Connected Container Component.

### Actual Behavior

Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(Form)

if I manually wire the component to the store passing the `<RRF store={store} />` I get this error: Uncaught Invariant Violation: dangerouslyReplaceNodeWithMarkup(...): Cannot render markup in a worker thread. Make sure `window` and `document` are available globally before requiring React when unit testing or use ReactDOMServer.renderToString() for server rendering.

Do you have any suggestions on how to setup a test that would allow the `<RRF />` to render so I can check that form fields are present using Mocha, Enzyme, etc or even just using the react test utils?

**Comment by davidkpiano** [comment]
That's really weird. If you do this:

```jsx
<Provider store={store}>
  <RRF />
</Provider>
```

without the intermediate components, do you still get the error?

**Comment by pbreah** [comment]
Same problem. It still gets:

Uncaught Invariant Violation: dangerouslyReplaceNodeWithMarkup(...): Cannot render markup in a worker thread. Make sure window and document are available globally before requiring React when unit testing or use ReactDOMServer.renderToString() for server rendering.

I'm disassembling and testing the hierarchy with different configurations to see if I can trace exactly what is generating this problem. The strange part is that it works on the browser (no warnings or errors) until running unit tests.

If I find anything I'll post an update here.

**Comment by davidkpiano** [comment]
This sounds like a general testing issue, not specific to RRF. Please make sure that `jsdom` is set up correctly. You can take a look at the unit tests inside RRF to see how that's set up.

**Comment by pbreah** [comment]
I did. jsdom is setup correctly - I have tests that rely on it, and the only test that fails is the one using RRF.

I also looked at your unit tests for RRF before posting this question, as I have a similar setup, the only difference is that I'm not only testing the form alone. I just wondered if there was something else not documented that causes that problem when rendering RRF on a test env.

**Comment by davidkpiano** [comment]
There shouldn't be. If you can point me to your code base (or a reproducible example) I'd be able to help better.

**Comment by pbreah** [comment]
After an in-depth check of the code, the problem was another dependency that caused the test to crash react-redux-form. It is now fixed after removing it. Sorry for the noise, this is one of those errors that required to take everything apart until finding the combination of "ingredients" that triggered the error.
