### ISSUE TITLE
No clean way to submit on blur

### ISSUE THREAD

**Issue by andykent** [davidkpiano/react-redux-form#83]
I have a form that needs to be able to submit in the background whilst it is being edited (sometimes triggered by onChange but usually onBlur) I started off by trying to handle `onBlur` events on the `input` elements directly but it looks like these are ignored, I then tried handling them on the `Field` component but these too are ignored. My plan would have been to trigger my own action from one of these events.

Failing that my second approach was to try listening to the store for blur actions, this could sort of work but it's pretty ugly as the actions for all forms have the same name so it would need some pattern matching on the model/field path to make sure I had the correct field that was being blurred. 

Am I being dumb here? I couldn't find any examples in the docs/tests but maybe I am completely missing the point?

Personally I think there should be a way to bind to onBlur and onChange events at the `Field` level to trigger custom logic (beyond the current support for validations).

**Comment by davidkpiano** [comment]
Just added an enhancement for this: Now the `<Field>` component can specify a custom `changeAction` prop. The `changeAction` is an action creator (function) that takes in two arguments:

`changeAction={(model, value) => {...}}`
- `model` - the model that is being changed
- `value` - the value that the model is being changed to

So, to solve your problem, you can do something like this:

```js
import { actions } from 'react-redux-form';

const submitPromise = ... // a promise

function changeAndSubmit(model, value) {
  return (dispatch) => {
    dispatch(actions.change(model, value));
    dispatch(actions.submit('user', submitPromise));
  };
}

// Then, in your <Field> components...
<Field model="user.name"
  changeAction= { changeAndSubmit }
  updateOn="blur">
  <input type="email" />
</Field>
```

Remember: you can always make your custom fields to group together similar props:

```js
class AutoSubmitField extends React.Component {
  render() {
    let { model } = this.props;
    
    return (
      <Field model={ model }
        changeAction={ changeAndSubmit }
        updateOn="blur">
        { this.props.children }
      </Field>
    );
}


// Use anywhere!
<AutoSubmitField model="user.email">
  <input type="email" />
</AutoSubmitField>
```

**Comment by andykent** [comment]
Wow, fast work thanks! 

I'll have a play now.

**Comment by mdgbayly** [comment]
Wow, you read my mind - also seems like a great solution for resetting field validity on change if you are not using validators...

**Comment by enkay** [comment]
@davidkpiano How would you get the whole form input values to submit whenever a text field changes? I'm using the same handleSubmit function as the form onSubmit for the submitPromise but it needs the input.

**Comment by davidkpiano** [comment]
@enkay Can you outline an example use-case for this? That way I can wire up an example/unit test.

**Comment by enkay** [comment]
Let's say I have a list of books and I want to filter through them using a text input for searching book titles, and an array of checkboxes for selecting genres.

This is the `input` object I would like to pass through to the `getBooks` action which handles fetching the books from the server every time the for submits.

`
{
  search: 'book title string',
  genres: ['fiction', 'historical']
}
`

I would also like this form to submit, and therefor dispatch the `getBooks`  action with that input object every time the search input changes or a genre is checked of unchecked.

What is the best way to do that?

**Comment by davidkpiano** [comment]
Wouldn't this just be something like this?

```js
<Form model="bookSearch" onSubmit={...}>
  <Field model="bookSearch.query">
    <input type="search" />
  </Field>
  <Field model="bookSearch.genres[]">
    <input type="checkbox" value="fiction" />
    <input type="checkbox" value="historical" />
  </Field>
</Form>
```
```

**Comment by enkay** [comment]
Yes but how do you get it to submit the form whenever the value of the search field changes or a checkbox gets checked or unchecked?

**Comment by enkay** [comment]
In this example handleSubmit doesn't accept any arguments, how do you get the form input data into the handleSubmit function?

**Comment by davidkpiano** [comment]
```js
class App extends React.Component {
  attachNode(node) {
    this._form = findDOMNode(node);
  }
  handleBlur() {
    this._form.submit();
  }
  handleSubmit(values) {
    // you get all the values here
  }
  render() {
    return (
      <div>
        <Form
          model="..."
          onSubmit={this.handleSubmit.bind(this)}
          ref={this.attachNode.bind(this)}
        >
          <Field
            model="test.foo"
          >
            <input type="text" onBlur={() => this.handleBlur()} />
          </Field>
        </Form>
      </div>
    );
  }
}
```

**Comment by enkay** [comment]
Awesome that works, thanks!

I also got it to work for onChange, I'm not sure if the code is optimal but it's working.

```
handleChange(e) {
   		this.props.dispatch(actions.change(e))
		setTimeout(() => {this._form.submit()})
	}
```
