### ISSUE TITLE
The updateOn setting is ignored in development environments

### ISSUE THREAD

**Issue by johnhampton** [davidkpiano/react-redux-form#831]
### The Problem
This [commit](https://github.com/davidkpiano/react-redux-form/commit/bc4b9b98c50bac022652f8e7d2aaf2515097134c) behaves differently depending on whether it’s run in development or production.  In development a `change` action is always issued on `blur` and `focus`, regardless of the setting of `updateOn`. In production, the `updateOn` setting is respected and it works as before.

The change is breaking my masked component since it's grabbing the incorrect value from the component’s input element. I’ve worked around the problem by providing a custom `getValue` function to the control, but I think the behavior should be consistent between development and production builds. 

### Possible cause
It looks like the development version of `react-dom` passes a second argument to the handler, which the new code designates as the `forceUpdate` argument. This causes `forceUpdate` to  always evaluate to a truthy value. 

### Steps to Reproduce
This [codepen](https://codepen.io/anon/pen/owgaPX?editors=1111) which uses the non-minified `react` and `react-dom` packages reproduce the batch action containing both a blur and change action being invoked on blur. 

```json
{
  "type": "rrf/batch",
  "model": "user.firstName",
  "actions": [
    {
      "model": "user.firstName",
      "type": "rrf/blur"
    },
    {
      "currentValue": "John",
      "external": false,
      "model": "user.firstName",
      "multi": false,
      "silent": false,
      "type": "rrf/change",
      "value": "John"
    }
  ]
}
```

### Expected Behavior
This [codepen](https://codepen.io/anon/pen/QgwVKb?editors=1111) which uses production builds of `react` and `react-dom`  correctly produces only a blur action.

```json
{
  "type": "rrf/blur", 
  "model": "user.firstName"
}
```

**Comment by davidkpiano** [comment]
This will be fixed in the next version 🔜 🎉

**Comment by johnhampton** [comment]
Wow, that was fast! Thank you!
