### ISSUE TITLE
valueMissing error when the value is not missing using "required" validator

### ISSUE THREAD

**Issue by jdelafon** [davidkpiano/react-redux-form#836]
### The Problem

While it makes sense to not use the "required" prop when there is no possibility to void the input, it should not prevent form submission, or at least say why.

### Steps to Reproduce

When submitting a form containing this, nothing will happen (the callback will not be called, no warning, no error):

    <Control.select model={modelName}  required>
      <option value="1">1</option>
      <option value="2">2</option>
    </Control.select>

With this instead (or without "required"), it works as expected:

    <Control.select model={modelName}  required>
      <option value="">-</option>
      <option value="1">1</option>
      <option value="2">2</option>
    </Control.select>

**Comment by jdelafon** [comment]
I will reopen this as soon as I can replicate in a CodePen... The problem definitely exists, and even for text inputs, but I can't see what the conditions are.

**Comment by davidkpiano** [comment]
Were you not able to replicate it?

**Comment by jdelafon** [comment]
In CodePen it seems to work in the minimal case:
https://codepen.io/jdelafon/pen/EXPXNr?editors=0011

In my case I get "rrf/setErrors" on every field when it mounts, and on submission:

    action rrf/addIntent
    action rrf/setSubmitFailed

because fields are marked as "valid: false" even when no value is empty and this is the only validator. This should just not be possible at all. 
Setting the initial value in the Redux store to something else than "" is enough to make it fail (even if there is a "" <option>). Any idea for me to test? I don't really know what to try anymore to reproduce that in CodePen.

**Comment by jdelafon** [comment]
I guess I don't have a choice. This is worrying, though:

![submitfailed](https://user-images.githubusercontent.com/12040845/26979043-c8e93faa-4d2d-11e7-8b08-8d82c4203f56.png)

A field that has `validated: false`, `valid: false`, `initialValue: ""`, `value: ""` and prevents submission. The only prop I passed to it is "required".

**Comment by davidkpiano** [comment]
@jdelafon With the below code, I was _not_ able to reproduce your issue:

```jsx
<Form model="user" onSubmit={val => console.log(val)}>
  <Control.text model="user.name" required />
  <button>Submit!</button>
</Form>
```

This will successfully show an error when the value is missing, and successfully submit the form when the value is not missing. Are you doing anything different? (assuming an initial state of `user: { name: '' }`

**Comment by jdelafon** [comment]
I give up sorry, I have no idea where it comes from. I will try with custom validators. Just in case it helps one day, a bit of code that I have:

My inputs:

    <Form model={formModelName} onSubmit={this.handleSubmit}>
        // Many of these, generated by a function, put in a HTML table, but I simplify:
        <Control.select  required model={modelName} updateOn="change" ignore={['focus','blur']} >
            {makeOptions()}
        </Control.select>
    <button type="submit">Submit</button>

My reducer:

    let userDataFormsReducers = combineForms(
        {
            libraries: {
                project: {...: "", ...: ""},
                requests: [
                    {...: "", ...: ""},
                ],
            },

            samples: {
                ...
            }
        },

        'userDataForms'
    );

store.js:

    let reducer = combineReducers({
        userData: userDataReducers, ...
    })

**Comment by davidkpiano** [comment]
What is an example of what is generated by `makeOptions`? I'll try to reproduce it with `<Control.select>`

**Comment by jdelafon** [comment]
/**
     * Build a list of <option>s based on an array representing the different options for a select input.
     * @param options: array [[id, label], ...] to become <option value={id}>{label}</option>.
     * @returns {Array}
     */
    function makeOptions(options) {
        let opts = options ? options.map((v,i) => <option value={v[0]} key={i}>{v[1]}</option>) : [];
        opts.unshift(<option value="" key="-">-</option>);
        return opts;
    }

**Comment by jdelafon** [comment]
I made a more resembling one but still cannot reproduce. Anyway here it is:
https://codepen.io/jdelafon/pen/EXPXNr?editors=0011

**Comment by davidkpiano** [comment]
Latest version is 1.12.1, please try with that 😄

**Comment by davidkpiano** [comment]
@jdelafon Were you able to reproduce this with the latest version? Please let me know and I will reopen the ticket.

**Comment by jdelafon** [comment]
Yes. What happens is this: 
- The form loads with the default store state (from the reducer), which is often `""` (invalid if required).
- The "rrf/setErrors" events fire and set the validity to "false".
- The Ajax call I do to get the data that fills the form gets back and triggers a `merge` action to fill the form.
- After the merge, all values are set and should be valid, but the validation status is not updated, thus all fields are marked `valid: false`.

So validation is not recalculated on `merge` (which is counter-intuitive imho) and needs to be triggered manually.  That is tedious because the `validate` action takes a `validators` argument that I have to read again from the model, but it should work.

Should validation not be re-calculated on `merge` ? 
I am struggling to update the CopePen to even dispatch a change action:
https://codepen.io/anon/pen/zzPZxb?editors=0011

**Comment by marcosschroh** [comment]
The same happens to me. Any updates?

**Comment by davidkpiano** [comment]
> The same happens to me. Any updates?

I'm currently looking into this.
