### ISSUE TITLE
Separating Concerns (Keeping Behavior/handler logic in Containers, not Views with react-redux-form)

### ISSUE THREAD

**Issue by dschinkel** [davidkpiano/react-redux-form#840]
All your examples show behavior in your Views.  I don't like behaviorin my views, I manage all my handler logic, calls to actions, etc. from my React Connected Container and pass handlers down as props to my dumb components.

Where are those kind of examples?  Can you do that with react-redux-form?  Are there any limitations preventing that?  If I have to add react-redux-form to my dumb component, what does that mean as far as being able to separate concerns!!?  seems like that would lock you into making your views become aware of behavior that should be abstracted into containers or elsewhere IMO.

**Comment by davidkpiano** [comment]
Behavior like what? Validation? Model changes?

Take a look at the very first section of [custom controls](http://davidkpiano.github.io/react-redux-form/docs/guides/custom-controls.html). There, you see one of the main benefits of React-Redux-Form: **you can handle absolutely everything in your own way.**

How? Nothing about RRF requires you to use `<Control>` or `<Form>`, etc. Those are just conveniences. Instead, you can `dispatch(actions.change('user.name', 'whatever'))` whenever you want, as well as handle practically any other form aspect from actions that **you can dispatch yourself**, whether it's `actions.setErrors('user.name', 'invalid')`, `actions.reset('user')`, etc.

RRF is a library, not a form framework. You can use as much or as little of it as you want.
