### ISSUE TITLE
Add 

### ISSUE THREAD

**Issue by klis87** [davidkpiano/react-redux-form#842]
### The Problem
It would be great to add new prop to ```Control``` component to allow automatic setting of dynamic css classes, in the same way like ```disabled``` prop is working currently:
```
<Control.button
  model="user"
  disabled={{ valid: false }}
>
  Submit!
</Control.button>
```

Thanks to this, it would be easier to integrate this library with external ones, like React Bootstrap. For example, below you can see a basic React Bootstrap way to create form text input:
 ```
<FormGroup validationState="error">
  <ControlLabel>Input with error</ControlLabel>
  <FormControl type="text" />
  <HelpBlock>Some error message</HelpBlock>
 </FormGroup>
```
Notice ```validationState="error"```, which would set correct error styles for this input. I propose something like this:
```
const MyReactComponent = ({ cssClasses, ...rest }) => (
  <FormGroup validationState={cssClasses}>
    <ControlLabel>Some label which should be passed as controlProps.</ControlLabel>
    <FormControl {...rest} />
    <Errors
      model={rest.name}
      messages={{
        someErrorKey: 'Some error message, this object could be passed as controlProps.',
      }}
      component={errorProps => <HelpBlock>{errorProps.children}</HelpBlock>}
      show="touched"
    />
  </FormGroup>
);

<Control.text
  model=".name"
  component={MyReactComponent}
  cssClasses={{ error: fieldValue => !fieldValue.valid }}
/>
```
I think it would be very nice additional to already excelent form library. For now it seems that this is the last part missing, at least for me. I know we could get valid state from redux store for example, but this would get repetitive and it wouldnt work for ```LocalForm``` (we could use ```onUpdate```, but still, it would get very repetitive).

**Comment by davidkpiano** [comment]
Thanks for the kind words, @klis87! Have you seen the section titled "How do I add conditional class names based on field state?" [in the FAQs?](http://davidkpiano.github.io/react-redux-form/docs/guides/faqs.html) 

```jsx
<Control.text
  model="user.firstName"
  mapProps={{
    className: ({fieldValue}) => fieldValue.focus
      ? 'focused'
      : ''
  }}
/>
```

I once considered a prop like you suggested (see #441 #509), and decided against it for a couple of reasons:
- would add much more code to the codebase (V2 is focused on dramatically reducing the amount of code)
- would be too magical/inflexible
- `mapProps` is perfect for this use-case

The third point is especially important - what if you want to have a dynamic class name only applied to an inner child component in a custom control? E.g., 

```jsx
<div className="special-wrapper-do-not-touch-me">
  <input className={className} {...inputProps} />
</div>
```

Hopefully the solution above works for your use-case!

**Comment by klis87** [comment]
@davidkpiano I missed that one, but it is even better than what I suggested! And exactly what I need :) Regarding removing some codebase, I guess you could remove ```disabled``` prop then, as you could achieve conditional disable based on field state by using ```mapProps``` as well.

Also, did you consider removing ```errors``` prop from ```Control``` component? In my opinion it duplicates  ```validators```, and the main use case for it is abusing it by doing something like ```!valid && 'this field is invalid'```, to show error messages. But as you said in docs, it should be discouraged and messages should be put in ```Errors``` component, as this is view part and should be separated.

**Comment by davidkpiano** [comment]
> Also, did you consider removing errors prop from Control component?

Yes, I did. I think the duplication is unnecessary as well. I think it will be removed in V2.
