### ISSUE TITLE
Incompatible with ReactNative >=0.43.4

### ISSUE THREAD

**Issue by andrewhl** [davidkpiano/react-redux-form#843]
### The Problem
react-redux-form (^1.12.1) is incompatible with the latest version of ReactNative (0.43.4), which has a dependency on React 16.0.0-alpha.6. react-redux-form's dependencies are "react@^0.14.0 || ^15.0.0".

Please update react-redux-form to be compatible with ReactNative >=0.43.4.

**Comment by davidkpiano** [comment]
Want to make a PR? I'll merge it in ASAP.

**Comment by andrewhl** [comment]
I gave it a go. Looks like it's not currently possible given the state of some of your third party dependencies.

I updated react and react-dom to v16.0.0-alpha.13, and these dependencies complain:
```
warning "shallow-compare@1.2.1" has incorrect peer dependency "react@15.x".
warning "react-addons-test-utils@15.6.0-rc.0" has incorrect peer dependency "react-dom@^15.4.2".
```
Those are the latest versions of each library. I suppose I'll have to forgo using react-redux-form in this project until everything catches up to React 16.

**Comment by andrewhl** [comment]
I may be having an unrelated issue with my local environment. I switched to yarn and the application is building despite the unmet dependencies. So the library appears to be usable with RN 0.43.4. Apologies. It would still be good to get the versions up, but that doesn't seem possible (or necessary) at this time. Closing this.

**Comment by rahulbasu710** [comment]
I guess the problem still persists especially because now React 16 is out! It's a warning but I assume it won't be a deal-breaker in any way

**Comment by davidkpiano** [comment]
@rahulbasu710 @andrewhl If it's a simple fix, mind making a quick PR? I'll merge it in ASAP.
