### ISSUE TITLE
Can the quick start guide clearly explain how to move combineForms into combineReducers?

### ISSUE THREAD

**Issue by asafigan** [davidkpiano/react-redux-form#845]
### The Problem
I struggled to figure out how to add combineForms to my reducers. My problem was that the quick start guide wasn't helpful to me. When I added combineForms to combineReducers and added the model string Form threw an error. I had no Idea why. It took me two hours to realize that I had to add the model string to the beginning of all my model string for Form and Control. I think it would be nice to have some clear documentation on this detail.

### Steps to Reproduce
Follow the quick start guide. 
Change
```
const store = createStore(combineForms({
  user: initialUserState,
}));
```
 into 
```
const store = createStore(
  combineReducers({
    forms: combineForms({
      user: initialUserState,
    }, 'forms')
  })
);
```

### Expected Behavior
Change will case no problem.

### Actual Behavior
Form throws an error.

**Comment by januszdotnl** [comment]
This actually helped me allot @asafigan ! Much appreciated.
