### ISSUE TITLE
Question: Controlled vs Uncontrolled inputs and implications for deleting model entries

### ISSUE THREAD

**Issue by mdgbayly** [davidkpiano/react-redux-form#85]
I've read the [react page](https://facebook.github.io/react/docs/forms.html) a few times and I think i'm beginning to get the difference between controlled vs uncontrolled components, but what I don't understand is why you would use uncontrolled components by default for react-redux-form. (So most likely I still don't really get them...). Is it a performance thing?

I think in another question of mine you made a comment:

>  In order to allow model changes to occur at any time, inputs are uncontrolled components by default.

I hit an issue with our form when deleting a row from a 'list' of text inputs, where each input represents an entry in a model array.

The input values were not updating correctly.  So if I had

```
|Option 1| x
|Option 2| x
```

and I delete Option 2, the page renders as:

```
|Option 1| x
```

Through debugging down to React (sort of...) I realized it's because the inputs are uncontrolled so they are not updating even though the state has changed.

I fixed by mapping modelValue to value in the createFieldClass call and now it's behaving as I would expect.

Thanks for your insights.

**Comment by davidkpiano** [comment]
Can you show me the exact code so I could further diagnose the problem?

Anyway, when a component is controlled, it means it represents the model value all the time. This is problematic if you want to change on blur, for example - on blur, what you type in an input won't always be the same as what your model value is.

**Comment by mdgbayly** [comment]
It's kind of hard to show our exact code as the Field components are spread across other components.  Is the code for your recipe examples available somewhere - maybe I could take your Deep Fields example and try and replicate there?

**Comment by davidkpiano** [comment]
The example you showed me: 

```
|Option 1| x
|Option 2| x
and I delete Option 2, the page renders as:

|Option 1| x
```

seems like the expected result, at least to me. What should the expected result be? Any chance you can provide a screenshot/gif of the page?

**Comment by mdgbayly** [comment]
Ah, sorry, yesterday was a long day...

I meant delete Option 1!

**Comment by mdgbayly** [comment]
I'll try and create a simple react-redux-form starter app tonight to demonstrate the issue I was hitting and to make sure it wasn't just some subtlety of the way we are using it.

**Comment by mdgbayly** [comment]
Created an example app here to demo the issue we are seeing:
https://github.com/mdgbayly/react-redux-form-starter

Contains two lists of things: phones and colors.
Create a couple of phone entries and a couple of color entries.
Then delete the first entry in the list in each section.
Phones list does NOT shift the second item up.
Colors list  does shift the second item up

**Comment by davidkpiano** [comment]
Have you tried adding `value` to the phones field?

```js
<Field model={`info.phones[${i}]`} key={i}>
  <input type="text" value={info.phones[i]} />
</Field>
```

**Comment by mdgbayly** [comment]
I'm sure that would work as then we're making it a controlled component? 

But with the way we are using these components the actual input tends to be a few layers deep. More like the CustomInput component I used for colors.  They are usually unconnected presentational components that don't have access to the form state.  Of course we could always set a value prop when we use those components.

```
<CustomField model={`info.colors[${i}]`} key={i}>
    <CustomInput type="text" value={info.colors[i]} />
</CustomField>
```

I guess it was just confusing to me that it doesn't just work out of the box.  On the other hand if you give the phones an initial value, then that value is rendered even without setting a value prop (presumably via defaultValue).  Whereas after that they don't take external state updates?

I was assuming the magic of react-redux-form was handling all the value syncing for me, so was surprised when it broke with remove.

I think I'm probably still just being a bit dense about the whole controlled/uncontrolled/value/defaultValue thing.

**Comment by davidkpiano** [comment]
Hmm... I'm _pretty sure_ we can make it a controlled component when `updateOn="change"` (which it is, by default). The problem is if you want `updateOn` to be anything else besides change, like `"blur"`.

Fact of the matter is, you can't have change on `"blur"` with a controlled component, because the view value is different than the model value.

I'll explore some solution for this, because in essence, you might be right - it _should_ be able to accurately show the value all the time.

**Comment by davidkpiano** [comment]
For now, I've added this to [the FAQs in the docs](https://davidkpiano.gitbooks.io/react-redux-form/content/faqs.html). There's nothing stopping you from creating a custom `<Field>` that _does_ control the value, though. I'd imagine something like this would work:

```js
const ControlledField = createFieldClass({
  text: (props) => ({
    ...controls.text,
    value: props.modelValue
  })
});
```

I might revisit this in the future, or for V1 - there's quite a few reasons where having a controlled input would _not_ be optimal and would case more headaches than not.
