### ISSUE TITLE
Disable submit when validation doesn't pass?

### ISSUE THREAD

**Issue by jcheroske** [davidkpiano/react-redux-form#851]
Right now, I'm trying to get the submit button to disable when validation hasn't passed. I have no idea how to accomplish such a simple task. I'm currently trying to use `Control.button`, but that control is strange and seems to want to associate the button with a field. I need the form-level validation status to determine the state of the button. How do I get that? Is there an HOC or something that I can wrap my button with?

**Comment by jcheroske** [comment]
Is `fieldValue.valid` the magic nugget?

**Comment by jcheroske** [comment]
And what should the `model` prop on `Control.button` be set to when the button really doesn't associate with a form field? I set it to `.`, but that seems like a hack.

**Comment by davidkpiano** [comment]
How is your store set up? If you just set up a simple `createStore(combineForms(...))`, then your form state will be under the `forms` key. So you can grab your form validity state under:

```js
const mapStateToProps = (state) => ({
  userFormValid: state.forms.user.$form.valid
});

connect(mapStateToProps)(MyForm);
```

And then use that:

```jsx
// in render()
<button disabled={!userFormValid}>
  Submit!
</button>
```

The easiest way to do it would be to use `<Control.button>`:

```jsx
<Control.button model="user" disabled={{ valid: false }}>
  Finish registration!
</Control.button>
```
