### ISSUE TITLE
control component props subtlety

### ISSUE THREAD

**Issue by greaber** [davidkpiano/react-redux-form#86]
In 0.8.10, you reverse the order of `this.props` and `control.props` in the Control component.  This broke my app because I guess because I have been mapping `modelValue` to `value`, and `value` is explicitly defined as undefined in `this.props`.  I'm not saying that the change was wrong, but I am a bit foggy on why it was done and what it means for users.

**Comment by greaber** [comment]
Sorry, I see this has been discussed under #74 and #77.  I will look at it more to see if I can understand the issue better.  But leaving this open for now.

**Comment by davidkpiano** [comment]
Can you show me your code so I can see where it is breaking for you?

**Comment by greaber** [comment]
I am using a Field component props mapping like so:

```
const standardControl = props => ({
    onChange: props.onChange
    , value: props.modelValue
})
```

I also assign a default value to the `value` props like so:

```
PublicationDateInput.defaultProps = {
    value: {
        year   : null
        , month: 0
        , day  : null
    }
}
```

But now that the control component merges `this.props` after `control.props`, my `value` prop starts out undefined instead of what I tried to set it to as a default.

A simple workaround would be to use some other prop instead of `value`, but it can be surprising for users if they can't name their props what they want.

**Comment by davidkpiano** [comment]
Why not do a simple check for undefined?

```js
const standardControl = props => ({
    onChange: props.onChange
    , value: typeof props.modelValue === 'undefined' ? props.value : props.modelValue
})
```

**Comment by greaber** [comment]
This works, thanks.  I can't decide if it is the Right Way to do it -- maybe I should be setting defaults in my model instead of with `defaultValue`, or maybe React Redux Form should be merging props differently -- but it does the job in a really simple way :-)

**Comment by davidkpiano** [comment]
_Ideally_, the "right way" to do it would be to _not_ map `value` in your prop mappings, and instead do it in your view (if you want the component to be controlled):

```js
<CustomField model="publication.date">
  <PublicationDateInput value={ publication.date } />
</CustomField>
```

This will allow you to use default props for your value still.
