### ISSUE TITLE
Errors in a custom control

### ISSUE THREAD

**Issue by januszdotnl** [davidkpiano/react-redux-form#866]
Hi David, all,

So far I'm enjoying react-redux-form more than redux-form. However, I'm stuck on something for a couple of days, looked everywhere but I'm still relatively inexperienced I guess.

I'm using a custom UI (Grommet) which I like and I just want to change (or enable) an attribute depending on whether there is a validation error or not:

The control:
```jsx
<Control
  model='.email'
  label='Email'
  errors={{
    required: val => !val.length,
  }}
  validateOn='change'
  component={renderInput}
>
  <Errors
    model='.email'
    show='touched'
    messages={{
      required: 'This field is required.',
    }}
  />
</Control>
```
The custom render:
```jsx
const renderInput = ({ label, children, ...otherProps }) => {
  return (
    <FormField
      className='authForm'
      // error={hasError && touched ? error : ''} <--------
      label={label}
      {...otherProps}
    >
      <TextInput {...otherProps} />
    </FormField>
  );
};
```
Now, I'm not really sure how I can use the children object to use with the error attribute. Redux-form just passes an error string which I used for a custom 'hasError' function to check whether there is an error and display the error or not but I can't seem to figure out how to do something similar. Am I overlooking something? Any help would be greatly appreciated.

**Comment by davidkpiano** [comment]
> Am I overlooking something?

Probably. 😄 

You'll want to utilize the `mapProps` prop, which allows you to map field-specific props (that come from RRF) to props on your own custom control. Here's a simple example:

```jsx
<Control
  model='.email'
  label='Email'
  errors={{
    required: val => !val.length,
  }}
  validateOn='change'
  component={renderInput}
  mapProps={{
    error: ({ fieldValue }) => fieldValue.touched && !fieldValue.valid
  }}
/>
```

Then you can use it directly:

```jsx
const renderInput = ({ label, children, error, ...otherProps }) => {
  return (
    <FormField
      className='authForm'
      error={error}
      label={label}
      {...otherProps}
    >
      <TextInput {...otherProps} />
    </FormField>
  );
};
```

Hope that helps! Feel free to reopen if this doesn't work for your specific use-case.

**Comment by januszdotnl** [comment]
Hi David,

Exactly what I needed to solve this issue! Thank you so much! For future reference and others here is my solution:

The control:
```
<Control
  model='.email'
  label='Email'
  errors={{
    required: val => !val.length,
    validEmail: val => !isEmail(val), // NOTE: isEmail is the validator package as mentioned in the docs.
  }}
  validateOn='change'
  mapProps={{
    required: ({ fieldValue }) =>
    fieldValue.errors.required && fieldValue.touched && !fieldValue.valid,
    validEmail: ({ fieldValue }) =>
    fieldValue.errors.validEmail && fieldValue.touched && !fieldValue.valid,
  }}
  component={renderInput}
/>
```
The custom render:
```
const renderInput = ({ label, required, validEmail, ...otherProps }) => {
  return (
    <FormField
      className='authForm'
      error={required ? 'This field is required.' : null ||
              validEmail ? 'Please enter a valid email.' : null} // NOTE: Might make a function function for this but I think this is still readable.
      label={label}
      {...otherProps}
    >
      <TextInput {...otherProps} />
    </FormField>
  );
};
```
