### ISSUE TITLE
Field Arrays? 

### ISSUE THREAD

**Issue by pbreah** [davidkpiano/react-redux-form#867]
### The Problem

After looking around: docs and other issues, didn't quite find an example or answered issue relating to Field Arrays and how to implement them on RRF.

### Steps to Reproduce

When I say "Field Arrays" I mean this: http://redux-form.com/6.0.0-rc.1/examples/fieldArrays/

### Expected Behavior

Would be great to see an example using Field Arrays on the docs: https://davidkpiano.github.io/react-redux-form/docs/recipes/redux-form.html

### Actual Behavior

There are no examples using field arrays.

**Comment by davidkpiano** [comment]
See the field arrays (and more) examples here: http://davidkpiano.github.io/react-redux-form/docs/guides/compare-redux-form.html#field-arrays

And here's an updated version:

```jsx
import { Control } from 'react-redux-form';

const initialMember = { firstName: '', lastName: '' };
const initialHobby = '';

const ClubForm = ({ club, dispatch }) => (
  <Form model="club">
    <div>
      <label>Club Name</label>
      <Control.text model=".name" required />
    </div>

    <button
      type="button"
      onClick={() => dispatch(actions.push('club.members', initialMember))}
    />
      Add Member
    </button>

    {club.members.map((member, i) =>
      <div key={i}>
        <div>Member #{i+1}</div>
        <div>
          <label>First Name</label>
          <Control.text model={`.members[${i}].firstName`} required />
        </div>

        <div>
          <label>Last Name</label>
          <Control.text model={`.members[${i}].lastName`} required />
        </div>

        <button
          type="button"
          onClick={() => dispatch(actions.push(`club.members[${i}].hobbies`, initialHobby))}
        />
          Add Hobby
        </button>

        {member.hobbies.map((hobby, j) =>
          <div key={j}>
            <label>Hobby #{j+1}</label>
            <Control.text model={`club.members[${i}].hobbies[${j}]`} required />
          </div>
        )}
      </div>
    )}
  </Form>
);

export default connect(({club}) => ({club}))(ClubForm);
```

See how much shorter the code is? 😉

**Comment by pbreah** [comment]
@davidkpiano thanks for the quick response! 👍

**Comment by husainshabbir** [comment]
Redux Form has a way of adding a new item in the middle of an array using `fields.insert(position, newObject)`. I was hoping to find something similar in the action creators, such as `actions.insert('myModel', position, newObject)`, but couldn't find anything. What is the recommended way of adding a new item in the middle of an array?

**Comment by davidkpiano** [comment]
@husainshabbir Two ways:

1. Think how you would do it normally in Redux, and do it like that 😉 no need for a magical method.
2. You can use `actions.change` as an action _thunk_ creator (make sure you have `redux-thunk` installed) and pass it an updater function:

```js
dispatch(actions.change('user.friends', (friends) =>
  [...friends].splice(index, 0, newFriend)));
```

Where `index` is the index you want to insert the new item.

**Comment by husainshabbir** [comment]
Of course! Sometimes the most obvious things are often overlooked. Thanks a lot for your help. I appreciate the speedy response.

**Comment by Escapado** [comment]
I am piggy bagging this in hope it will be seen. There are a few minor syntactic errors in the example above (as well as the docs) with closing tags at the buttons and import (of connect and React). However even when fixing this I am still having trouble to get this to work.

If I insert the corrected example into a new file and import that component then it initially renders properly and after clicking Add Member I even see that in my reducer the members field gets added with one entry. However it's not an array but an object. And if I console.log `club` then it's undefined. Does anyone know what my problem might be?
