### ISSUE TITLE
Action Creator triggers error: "Actions must be plain objects..."

### ISSUE THREAD

**Issue by pbreah** [davidkpiano/react-redux-form#869]
### The Problem

Action Creator triggers error: "Actions must be plain objects...". On my code it does exactly the same as the CodePen below.

### Steps to Reproduce

On the CodePen below click the "Add" button with the console open. The fields array works, but also shows this error on the console.

### Expected Behavior

The thunk middleware is there, so this error should not show.

### Actual Behavior

Action Creator triggers error: "Actions must be plain objects..."

### Reproducible Code Example

https://codepen.io/anon/pen/GEQvPN?editors=0011

**Comment by davidkpiano** [comment]
You're using `bindActionCreators()` wrong:

```js
const mapDispatchToProps = (dispatch) => bindActionCreators({
    dispatch, // <-- this doesn't go here
}, dispatch);
```

`bindActionCreators(actionCreators, dispatch)` takes an object of _action creators_ (not dispatch) as its first argument (see [the Redux docs](http://redux.js.org/docs/api/bindActionCreators.html)), so theoretically you can do:

```js
import { actions } from 'react-redux-form';

bindActionCreators(actions, dispatch);
```

Or you can piecemeal it (which is preferred):

```js
import { actions } from 'react-redux-form';

bindActionCreators({
  push: actions.push,
  remove: actions.remove
}, dispatch);
```

Or you can do what I do in all my examples (for simplicity) and omit `mapDispatchToProps` altogether. Up to you.

**Comment by pbreah** [comment]
@davidkpiano, thanks for your quick response.

Still, I made the change on the CodePen. It doesn't fix the problem with

```Javascript
const mapDispatchToProps = (dispatch) => bindActionCreators({
  push: actions.push,
  remove: actions.remove,
  dispatch
}, dispatch);
```
On the latest version of redux, if I don't pass "dispatch" explicitly on "mapDispatchToProps" I don't get access to it on the component. I don't see the point of wrong as dispatch is doing its work well on the example. Try removing "dispatch" from "mapDispatchToProps" (from the CodePen) and you'll see what I mean.

Again here is the new updated CodePen mapping the action creators - per your suggestion (with the same error): 
https://codepen.io/anon/pen/KqQydK?editors=0011

It would be helpful if you could fork the same CodePen with the fix that doesn't trigger the error.

**Comment by davidkpiano** [comment]
This works fine:

```js
const mapDispatchToProps = (dispatch) => bindActionCreators({
  push: actions.push,
  remove: actions.remove,
  // dispatch // <-- remove this
}, dispatch);
```

const UserFormConn = connect(mapStateToProps, mapDispatchToProps)(UserForm);

**Comment by pbreah** [comment]
@davidkpiano thanks again.

I see where the confusion came from... on the sample code on #867 you had: 

```Javascript
<button
    type="button"
    onClick={() => dispatch(actions.push(`club.members[${i}].hobbies`, initialHobby))}
/>
```
So using "dispatch" on the event handler call caused the problem. Removing "dispatch" from the button event handler solved it. 👍
