### ISSUE TITLE
Rest model initialization

### ISSUE THREAD

**Issue by divined** [davidkpiano/react-redux-form#873]
### The Question
How to initialize form data from REST API?

1. Reducer
```
export const myContractsForms = combineForms({
  proxy: {}
}, 'myContractsForms');
```

2. Add values from component props, came from rest api
// It is wrong variant (values in form redux updates from two directions - 1) form input, 2) props update)
// It cause a lag
// What a proper way for model initialize ? 

```
  componentDidUpdate() {
    let proxy = {};

    this.props.rows.map((row) => {
      if (row.data) {
        proxy[row.id] = {
          delegate: 1,
          data: row.data
        }
      }
    });

    this.props.dispatch(actions.change('myContractsForms.proxy', proxy));
  }
```

**Comment by davidkpiano** [comment]
That looks correct. You can also use `actions.load(model, value)` to set it as the initial value.
