### ISSUE TITLE
Is it possible to dispatch actions with some delay (debounce, setTimeout, defer, etc.)?

### ISSUE THREAD

**Issue by atatakobry** [davidkpiano/react-redux-form#875]

**Comment by davidkpiano** [comment]
You mean besides `change`?

**Comment by atatakobry** [comment]
i mean something like this:
`
...
const debouncedOnDispatchSubmit = debounce(() => {
  dispatch(actions.submit(formModel));
}, 1000);
...
changeAction={(model, value) => {
  dispatch(actions.change(model, value));
  debouncedOnDispatchSubmit();
}
...
`
In this implementation it works, but, unfortunately, `onSubmit` method in `Form` runs twice

**Comment by davidkpiano** [comment]
Where is `debounce` coming from?

**Comment by atatakobry** [comment]
`debounce` was taken from `lodash`.
but it's no matter, 'cause the bug with "calls twice" appears even in:
```
...
  setTimeout(() => {
    dispatch(actions.submit(formModel));
  }, 1000);
```

**Comment by davidkpiano** [comment]
Can you please make a reproducible code example if this is a RRF bug?

**Comment by atatakobry** [comment]
i dunno if it's really bug of RRF, but im gonna try to make some code example tomorrow. thank you!

**Comment by atatakobry** [comment]
https://codepen.io/anon/pen/OgBPxE?editors=0010

it's weird, but i can't reproduce bus in sandbox :( 
and `console.log('onSubmit');` runs only one time, not twice
gonna try to debug my app
