### ISSUE TITLE
Error message for rejected submit

### ISSUE THREAD

**Issue by cyberwombat** [davidkpiano/react-redux-form#876]
I am wanting to create an error message for my form when it fails server validation (promise rejected).

My current error section:

````
 { !valid && submitFailed ? <Alert>
          <Errors
            model='.email'
            messages={{ isEmail: 'Please provide a valid email.' }}
          />
          <Errors
            model='subscribe'
            messages={{  }} // <--- what goes here?
          />

        </Alert> : submitted ? <Alert type='success'>Good job!</Alert> : null }
````
This works great for field validation but I noticed that the ` !valid && submitFailed` field is called when the promise rejects however the first `<Errors/>` field is not called. So I assume I would make a form wide `<Errors/>` field but I am not clear what to put for messages. Inspecting my Redux flow I don't see much to go on:
````
type(pin): "rrf/batch"
model(pin): "subscribe"
▶actions(pin)
▶0(pin)
type(pin): "rrf/setSubmitFailed"
model(pin): "subscribe"
submitFailed(pin): true
▶1(pin)
type(pin): "rrf/setErrors"
model(pin): "subscribe"
async(pin): true
errors(pin): {}
````
What do you suggest?

**Comment by davidkpiano** [comment]
Are you setting a form-wide error when submit is rejected? If so, you can use that error key as the message key, and then have your own custom message as the value.

**Comment by cyberwombat** [comment]
I'm not clear on how to do so. Do you mean something like ` dispatch(actions.setErrors('subscribe', { 'foo': 'bar'}))`? I played around with that without success.

**Comment by cyberwombat** [comment]
OK I got it. Posting here for others.

My onSubmit should reject a promise:
````
export const subscribeUser = (data) => {
  return new Promise((resolve, reject) => {
    reject({
      foo: 'Wrong password'
    })
  }) 
}
````
Then in my form (given a form named 'subscribe'):
````
 <Errors model='subscribe' />
````
This will print: 
````
<div><span>Wrong password</span></div>
````

I can override the errors as in:
````
 <Errors model='subscribe' messages={{foo: 'Whatevs'}} />
````
Which gives:
````
<div><span>Whatevs</span></div>
````

**Comment by cyberwombat** [comment]
I've noticed that I must return a promise. Somehow it doesn't get any error message if an error is thrown.  See https://stackoverflow.com/questions/44989109/rejecting-react-redux-form-with-async-throw-instead-of-promise/44989164#44989164
