### ISSUE TITLE
Form isn't submitting with numbers with decimals

### ISSUE THREAD

**Issue by atatakobry** [davidkpiano/react-redux-form#878]
### The Problem
Can't submit form when `<input type="number" />` is exist and number with decimal is stored in its model.

### Steps to Reproduce
1. Go to some RRF with `<input type="number" />`. For example, [https://davidkpiano.github.io/react-redux-form/docs/recipes/sync-validation.html](https://davidkpiano.github.io/react-redux-form/docs/recipes/sync-validation.html). 
2. Open console. 
3. Type correct username, email and age `18.5`.
4. Push the submit button. 

### Expected Behavior
1. Form is valid.
2. Form is submitted.
3. `Object {username: "Username", email: "Email@dot.com", age: "18.5"}` is displayed in console.

### Actual Behavior
1. Form isn't valid and isn't invalid.
2. `onSubmit` and `onSubmitFailed` are not executed.
3. Console is empty.

P. S. Sometimes i can't reproduce this bug. For example, when you input `12`, then add `.5` and with arrows make it `18.5`.

**Comment by davidkpiano** [comment]
Is this replicable in other browsers? I recall this being a Chrome-specific bug.

**Comment by atatakobry** [comment]
OS X
Opera 46.0.2597.39  - same as Chrome
Safari 10.1.1 - show tooltip "Enter a valid value"
Firefox ESR 52.2.1 - don't recognize `18.5` as valid number; browser offers to input the nearest valid values: `18.5`(lol)  or `19.5`.

**Comment by davidkpiano** [comment]
Not a RRF issue. You need to add a `step={0.1}` attribute to allow steps.

See here for more info: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Allowing_decimal_values

**Comment by atatakobry** [comment]
https://stackoverflow.com/a/14371142

**Comment by atatakobry** [comment]
at least some solution: [https://stackoverflow.com/a/14371142](https://stackoverflow.com/a/14371142)
