### ISSUE TITLE
Parser doesn't seem to contain previous value

### ISSUE THREAD

**Issue by ip70** [davidkpiano/react-redux-form#880]
### The Problem

According to the [documentation](https://davidkpiano.github.io/react-redux-form/docs/api/Control.html#prop-parser), the parser function seems to take two argument - `value` and `previous`, which claims to be the model value of the field before it changed. However, this `previous` argument always seems to be undefined.

### Steps to Reproduce

Create a form and add a text field with a parser function. Log the `value` and `previous` arguments to the console.

Type characters into the field

### Expected Behavior

The console should print a `previous` value containing the field value just before the current keystroke.

### Actual Behavior

The `previous` value is always printed as undefined.

### Reproducible Code Example
https://codepen.io/ip70/pen/KqJwgy

**Comment by davidkpiano** [comment]
Sorry about that! That was a mistake in the documentation and never was meant to be a feature.
