### ISSUE TITLE
Asyc form validators on submit?

### ISSUE THREAD

**Issue by divined** [davidkpiano/react-redux-form#881]
### The Problem
How to validate big form with a lot of data on submit.
Form it is a list of users. Need to validate at backend 20+ users.

For now Form element hasn't asyncValidators props ((
And Field|Control elements are hasn't asyncValidatorsOn="submit".

**Comment by davidkpiano** [comment]
Please see the [docs on validation](http://davidkpiano.github.io/react-redux-form/docs/guides/validation.html). Specifically, look at `actions.submit(model, promise)`, where **rejecting** the promise will set the errors on the form, if the users are invalid.

Otherwise, please submit fully reproducible code examples explaining your problem. Thanks!

**Comment by divined** [comment]
Uncaught TypeError: promise.then is not a function
field-actions.js?c5db:292

**Comment by divined** [comment]
handleSubmit = (contracts) => {
    this.props.dispatch(actions.submit('myContractsForms.proxy', this.validateCourtiers));

   // dispatch submit action here
}

 validateCourtiers = (contracts) => {
    return (dispatch) => {
      dispatch(actions.setPending('myContractsForms.proxy', true));

      dispatch(api.contracts.validateProxy({data: {validate: contracts}, token: this.props.user.csrfToken}))
         .then(data => {
            //setValidityHere
            dispatch(actions.setPending('myContractsForms.proxy', false));
         });
   }
}

**Comment by davidkpiano** [comment]
`validateCourtiers` returns a function, not a promise. If you're going to do it that way, you don't need to use `actions.submit`, just call` validateCourtiers` directly.

**Comment by divined** [comment]
dispatch it is promise function!

i can use this.validateCourtiers (contracts).then()

**Comment by divined** [comment]
i can't call validateCourtiers directly.

form submited anyway, if i call it directly and not wait an answer (

**Comment by divined** [comment]
http://i.imgur.com/DA4Awbk.jpg

```
validateForm = (contracts) => {
    return new Promise((resolve, reject) => {
      this.props.dispatch(api.contracts.validateProxy({data: {validate: contracts}, token: this.props.user.csrfToken}))
        .then(errors => {
          if (_.size(errors) > 0)  {
            console.log('Reject');
            console.log(errors);
            reject(errors);
          } else {
            console.log('Resolve');
            resolve(true);
          }
        });
    });
  };
```

```
handleSubmit = (contracts) => {
    this.props.dispatch(actions.submit('myContractsForms.proxy', this.validateForm(contracts)));
 };
```

**Comment by davidkpiano** [comment]
Any errors in submitting for `'myContractsForms.proxy'` will set the errors on that model. Please provide a working, running code example in www.codesandbox.io or www.codepen.io .

**Comment by divined** [comment]
What i need to reject in Promise?

```
<Form model="myContractsForms.proxy" ..>

<Errors model=".$id.numeroTiersCourtier">
<Errors model=".$id.numeroTiersCourtierRassises">
<Errors model=".$id.numeroTiersCourtierNouvelles">
```

reject(
 {
  $id1: {
     numeroTiersCourtier: 'Error label',
     numeroTiersCourtierRassises: 'Error label 2',
  },
  $id2: {
     numeroTiersCourtier: 'Error label'
  },
  }
);  
// not work

reject(
 {`$id1.numeroTiersCourtier`: 'Error label'}
 {`$id1.numeroTiersCourtierRassises`: 'Error label 2'}
 {`$id2.numeroTiersCourtier`: 'Error label'}
 ...
)
// not work

**Comment by davidkpiano** [comment]
To have error messages for specific fields, use `actions.submitFields(...)`.

**Comment by divined** [comment]
It works =) Thx.

Another question: how to reset field state in this case?

first: 
```
reject(
  '$id1.numeroTiersCourtier': 'Error',
  '$id2.numeroTiersCourtier': 'Error',
)
```
second

```
reject(
  '$id1.numeroTiersCourtier': 'Error'
)
```

but $id2 field still has error ((

**Comment by divined** [comment]
this.props.dispatch(actions.resetErrors('myContractsForms.proxy'));

**Comment by divined** [comment]
Ty )
