### ISSUE TITLE
Webpack throws warning when react-native isn't installed.

### ISSUE THREAD

**Issue by KrisCoulson** [davidkpiano/react-redux-form#888]
### The Problem
Most recent [update](https://github.com/davidkpiano/react-redux-form/commit/5aa2a5d9890422b7e179be456989ecd843fb4fe1#diff-7c26edbf700ff7b1e588f557ee9a42da) causes webpack to throw a warning when react native does not exist. I am not quite sure if this is something with my webpack config or the try/catch if/else statement in the control file. But I assume it shouldn't even run that line of code if it is not native.

![image](https://user-images.githubusercontent.com/6943688/28537265-1663ed4e-705f-11e7-8805-c9f3f28cfa55.png)

**Comment by davidkpiano** [comment]
Sorry about that! `npm install react-redux-form@latest` (1.13.2) reverts that commit.
