### ISSUE TITLE
Suggestion for changing semantics in form reducer

### ISSUE THREAD

**Issue by ffxsam** [davidkpiano/react-redux-form#89]
There's kind of a semantics/logic disconnect, IMO, with form field validation.

Let's say I want to check to see if fields are filled:

```
    this.validators = {
      email: {
        filled(value) {
          return value && value.length > 0;
        },
        isValidEmail: validator.isEmail,
      },
    };
```

If the user supplies an invalid email address, `isValidEmail()` would return `false`, though in Redux, `fields.email.errors.isValidEmail` is `true`. I get that `true` means there's an error raised. But it seems kind of backwards to return false from the `isValidEmail()` function, which gets flipped into a `true` value. And in code, it might look confusing to other people working on the project:

```
if (fields.email.errors.isValidEmail) {
  // Email is actually invalid
}
```

Thoughts? Or am I doing something totally wrong?

**Comment by davidkpiano** [comment]
The values are only flipped for `.errors` - if you check `.validity`, they match whatever is returned from each of the validators.

A validator validates; i.e. it asks the question, **is this value valid?** Each value gets "flipped" for `.errors` to allow the capability for there to be error messages, even though I strongly do not recommend hardcoding error messages in error validators.

**Comment by ffxsam** [comment]
Hmm. If `.errors` and `.validity` are just opposites of each other, why have both instead of just one?

**Comment by davidkpiano** [comment]
To allow for error messages. For `.validity`, a truthy value means "valid", and a falsey value means "invalid". Makes sense, right? However, for `.errors`, a truthy value means "is an error" and a falsey value means "is not an error", and since strings are truthy, they can represent something that is an error with an error message.

**Comment by davidkpiano** [comment]
Does this make sense? Or should I keep this ticket open? @ffxsam

**Comment by ffxsam** [comment]
Let me check all this out today - I had a super busy weekend. Diving into the new changes now with a very barebones project and see if I can get it all working smoothly.

**Comment by ffxsam** [comment]
Ok, so this is just a first pass. Pasting here instead of a gist, because I don't want to have to keep the snippet around forever.

```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Form, Field, actions } from 'react-redux-form';
import autoBind from 'react-autobind';

class Home extends Component {
  constructor(props) {
    super(props);
    autoBind(this);
  }

  handleSubmit(user) {
    console.log(user);
  }

  getError(fieldName) {
    const field = this.props[fieldName];
    const errors = field.errors;

    if (!field.touched) return '';
    if (errors.required) return 'Field required.';
    if (errors.isNumber) return 'Need a number.';

    return '';
  }

  render() {
    const validators = {
      firstName: {
        required: value => !!(value && value.length),
      },
      lastName: {
        required: value => !!(value && value.length),
      },
      zip: {
        required: value => !!(value && value.length),
        isNumber: value => /^\d+$/.test(value),
      },
    };

    return <div>
      <h1>Home.</h1>

      <div>
        <Form
          model="user"
          validators={validators}
          validateOn="change"
          onSubmit={user => this.handleSubmit(user)}
        >
          <div>
            <Field model="user.firstName">
              <input placeholder="First name" />

              <div>
                {this.getError('firstName')}
              </div>
            </Field>
          </div>

          <div>
            <Field model="user.lastName">
              <input placeholder="Last name" />

              <div>
                {this.getError('lastName')}
              </div>
            </Field>
          </div>

          <div>
            <Field model="user.zip">
              <input placeholder="ZIP code" />

              <div>
                {this.getError('zip')}
              </div>
            </Field>
          </div>

          <input type="submit" />
        </Form>
      </div>
    </div>
  }
}

export default connect(({ user, userForm }) => ({
  user,
  ...userForm.fields,
}))(Home)
```

This works pretty great! A couple issues:

* I get a bunch of deprecation warnings every time I type, even though I'm not using any of the deprecated props.
* Hitting submit without touching any fields still does nothing. The `submitFailed` property remains `false` in the form property list.

**Comment by davidkpiano** [comment]
> I get a bunch of deprecation warnings every time I type, even though I'm not using any of the deprecated props.

Sorry about that! Update to `0.9.8` and you won't see the deprecation warnings anymore.

> Hitting submit without touching any fields still does nothing. The submitFailed property remains false in the form property list.

Looking into that now...

**Comment by ffxsam** [comment]
Thanks! I appreciate your taking the time on this. Once things calm down here, I'd like to learn the codebase and contribute with PRs.

**Comment by davidkpiano** [comment]
Last part fixed just now in `0.9.9`! It was just an oversight. I definitely welcome any PRs and contributions! The codebase is very modular/function-based, so hopefully it's easy enough to grok.

**Comment by ffxsam** [comment]
Works great! I modified my `getError` method accordingly:

```
  getError(fieldName) {
    const field = this.props[fieldName];
    const errors = field.errors;

    if (!field.touched && !this.props.submitFailed) return '';
    if (errors.required) return 'Field required.';
    if (errors.isNumber) return 'Need a number.';

    return '';
  }
```

And once the user corrects a field, the error goes away. :+1: :+1: I noticed the `retouched` prop didn't change at all, but it turns out I didn't need it. (I expected it to turn to `true` once I focused on a field after the submit failed)

**Comment by davidkpiano** [comment]
Glad it works! The behavior of `(re)touched` is to trigger `touched` if a field is changed/blurred, not focused, but if that ends up being a bug we can open another ticket for it.
