### ISSUE TITLE
Do LocalForms make use of the same middleware as the rest of app

### ISSUE THREAD

**Issue by cyberwombat** [davidkpiano/react-redux-form#893]
### The Problem

I am trying to convert a working Form to a LocalForm and cannot get it to dispatch my submit action. This action is handled by [redux-axios-middleware](https://github.com/svrcekmichal/redux-axios-middleware) but when I run the same code in LocalForm it just doesnt get a promise back.

### Steps to Reproduce

My onSubmit in both forms is
````
 handleSubmit (values) {
    
    this.formDispatch(actions.submit('subscribe', this.formDispatch(subscribeUser(values))))
    this.formDispatch(actions.reset('subscribe'))
  }
````
Note that the above works perfect with standard Form (using dispatch from props)

I load dispatch as in docs:

      getDispatch={(dispatch) => this.formDispatch = dispatch} 

My subscriberUser is as follows:
````

eexport function subscribeUser (data) {
  return {
    type: 'SUBSCRIBE_FORM',
    payload: {
      options: {
     /   onSuccess: () => true
     / },
      request: {
        url: '/newsletter/subscribe',
        method: 'post',
        data: data
      }
    }
  }
}
````
### Expected Behavior

I would expect `dispatch(subscribeUser(values))` to return a promise which is what happens in `<Form/>` but in `<LocalForm/>` I just get the exact same object back untransformed as in:
````
console.log( this.formDispatch(subscribeUser(values)))
console.log( subscribeUser(values))
```
Both return the same action object.
````
I know that axios middleware watches actions and handles them to return a promise. I suspect that my LocalForm dispatch is not aware of this. Is this your assumption as well and can it be remedied?

**Comment by davidkpiano** [comment]
They do not make use of the same middleware, as they use a separate internal Redux store instance (by design). In fact, in future versions (v2+) it's best to not even assume that `<LocalForm>` will use Redux at all.

**Comment by cyberwombat** [comment]
Thanks David that helps. Perhaps a mention in the docs (if not already there - I may have missed it) would be useful.  It seems logical now that I think about it but I didn't think of it when I initially attempted my conversion.
