### ISSUE TITLE
How to use existing reducer state as a model

### ISSUE THREAD

**Issue by optimistiks** [davidkpiano/react-redux-form#896]
Hi everyone, I read the docs but I can't find an answer.

Imagine I have the following root reducer (which I pass to createStore later):

```
import myReducer from './myReducer'

const rootReducer = combineReducers({
    myReducerState: myReducer
})
```

In myReducer, I have the following initial state: 

```
const initialState = {
  exampleProp1: null,
  exampleProp2: null,
  formData: { userName: '', password: '' }
}

... then I handle some actions ...

... then I export reducer ...
```

Next I want to do something like:
```
<Form model='myReducerState.formData' ...
   ... some inputs ...
```

I want to be able to access `state.myReducerState.formData` anytime I want it, but I also want that formData to be updated by react-redux-form when I type inside the form (so I don't need to handle input changes and all that).

Is it possible? Thanks in advance.

**Comment by davidkpiano** [comment]
Sure it is! Just replace `combineReducers` with `combineForms`. Works almost exactly the same way, but now your reducers will be made "visible" to React-Redux-Form and a form state slice will be set up for your reducers.

```jsx
import myReducer from './myReducer';
import { combineForms } from 'react-redux-form';

const rootReducer = combineForms({
    myReducerState: myReducer
})
```

**Comment by MatejMazur** [comment]
But that means that you have created whole form state for `exampleProp1` and `exampleProp2` which are not forms data or haven't you?

I need something similar but I don't want to create form state for props which are not forms values but I need in my form reducer the access to the state which is not part of the form. How can I do that?

Here is my attempt:
```js
const store = combineReducers({
  subApp: myReducer
  ...
})

const initialState = {
  schema: {...},
  uiSchema: {...},
  data: {...} // form values
}

function myReducer(state = initialState, action) {
  // there are some conditions between schema, uiSchema and data
  const modified = pipe(fn1, fn2, ...)(state) 

  return {
    schema: modified.schema,
    uiSchema: modified.uiSchema,
    data: modified.data
  }
}
```

How can I achieve that with react-redux-form?

I've tried `createForms()` but that created form state even for `schema` and `uiSchema` which is undesirable.
```js
const store = combineReducers({
  ...createForms({ subApp: myReducer }),
  ... 
})
```
