### ISSUE TITLE
Probably a super simple fix for checkbox initialization

### ISSUE THREAD

**Issue by maludwig** [davidkpiano/react-redux-form#905]
### The Problem
<Control.checkbox defaultChecked={false} /> does not make a checkbox that is false by default.

### Steps to Reproduce
Make a <Control.checkbox defaultChecked={false} /> and look at it with your eyes.

### Expected Behavior
<Control.checkbox defaultChecked={false} /> should initialize a checkbox that is not checked.

### Actual Behavior
<Control.checkbox defaultChecked={false} /> initializes a checked checkbox.

### Reproducible Code Example
https://codepen.io/maludwig/pen/KvyWxz

**Comment by maludwig** [comment]
So, I think the fix is in "checkWithValue" in model-actions.js, the last line should change from:

```
return change(model, !currentValue);
```

to:

```
if (typeof currentValue !== "undefined") {
  return change(model, !currentValue);
} else {
  return change(model, value);
}
```

but, it seems like this works too:

```
return change(model, value);
```

I'm not sure if this is where you want to fix it, but it does the trick.

**Comment by davidkpiano** [comment]
Wanna file a PR? 😄

**Comment by maludwig** [comment]
Oh gosh, it's been like 8 years since I've tried that. Let's do this! LEEERROOYYYYY, JENKIINNNSS.

**Comment by davidkpiano** [comment]
Let me know if you need help. Just make the changes and run:

- `npm test`
- `npm run lint:fix` (assuming tests pass)

If all is green, I'll 🚢

**Comment by maludwig** [comment]
Well, I think I fixed it, but, by build is failing, but I think it can't be with my code. It looks like it's with npm, or...something...I have no clue why it's not happy. I'm officially calling for help. It all works nice and happy on my local. #908

**Comment by akkie** [comment]
@davidkpiano This can be closed because https://github.com/davidkpiano/react-redux-form/pull/908 was merged!

**Comment by davidkpiano** [comment]
@akkie will do!
