### ISSUE TITLE
Form onChange called on mount

### ISSUE THREAD

**Issue by sakarit** [davidkpiano/react-redux-form#907]
https://github.com/davidkpiano/react-redux-form/blob/05bef7076aa151b854d2086e7c40933b41b4673f/src/components/form-component.js#L95

@davidkpiano Why is this change event fired when the component is mounted? I have a listener on the onChange prop in it gets called on mount even though nothing is changed.

How to avoid it?

**Comment by sakarit** [comment]
Nice! Thank you. :) When will you make a release?

**Comment by davidkpiano** [comment]
Probably later today!
