### ISSUE TITLE
InitialDate not used for validation on nested fields

### ISSUE THREAD

**Issue by Gidgidonihah** [davidkpiano/react-redux-form#910]
### The Problem
When looping on nested data with initial data set, validation does not appear to take initial data into account. Only nested fields are affected. Root level data works as expected.

### Steps to Reproduce
Create a store with initial state of nested data.
Create a form using that data with validation.
Add a `required` validation rule  (`validators={{ required: (value) => (value && value.length) }}`) on each field

### Expected Behavior
All field should be valid.

### Actual Behavior
All field are invalid.
Additionally, focus doesn't change validity. Field will remain invalid until the value is changed.

### Reproducible Code Example
Form: https://codepen.io/Gidgidonihah/pen/qXpQdw?editors=0110
LocalForm: https://codepen.io/Gidgidonihah/pen/VzrMRY?editors=0111

**Comment by davidkpiano** [comment]
Simple solution: your validator doesn't work for numbers:

```js
// numbers don't have a `.length` prop, and `0` is falsey
const required = val => val && val.length
```

Try this instead:
```js
const required = val => val !== undefined
```

**Comment by Gidgidonihah** [comment]
Wow. I feel real stupid right now. Well, thanks for at least pointing out my issue.
