### ISSUE TITLE
LocalForm: how to set Custom Control prop based on model validity?

### ISSUE THREAD

**Issue by ClementParis016** [davidkpiano/react-redux-form#912]
Let's say I have a LocalForm with a Custom Control, looking something like this:
```jsx
<LocalForm initialState={{ businessName: '' }}>
  <Control model=".businessName" component={BusinessNameInput} />
</LocalForm>
```
With the Custom Control BusinnessNameInput delegating to an Input component:
```jsx
const BusinessNameInput = props =>
  <Input type="text" label="Business name" {...props} />;
```

Now, how would I set an `invalid` prop on the Input component, based on the LocalForm's model validity?

I searched through the docs, but I don't understand how to pull some state (like validity in this case) from the LocalForm to achieve this. Or maybe I'm using it the wrong way?

**Comment by davidkpiano** [comment]
You would use `mapProps` to do this:

```jsx
<Control
  model=".businessName"
  component={BusinessNameInput}
  mapProps={{
    invalid: field => !field.valid
  }}
/>
```
