### ISSUE TITLE
Problem with react native

### ISSUE THREAD

**Issue by sejsworld** [davidkpiano/react-redux-form#920]
### The Problem
I get the following error when installing rrf
npm install react-redux-form@latest --save

_npm WARN react-redux-form@1.14.1 requires a peer of react@^15.3.0 || ^16.0.0 but none was installed.
npm WARN react-redux-form@1.14.1 requires a peer of react-dom@^0.14.7 || ^15.0.0 || ^16.0.0 but none was installed._

and when running the app:

_Unable to resolve module `react-dom` from `App/node_modules/react-redux-form/lib/components/control-component.js`: Module does not exist in the module map_

Should rrf be working with react native 0.47 ? Kind regards Steffen

dependencies:

 "dependencies": {
    "axios": "^0.16.2",
    "haversine-distance": "^1.1.3",
    "immutable": "^3.8.1",
    "minutes-seconds-milliseconds": "^1.0.3",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.2",
    "react-native-clean-form": "^0.4.2",
    "react-native-fbsdk": "^0.6.0",
    "react-native-keyboard-spacer": "^0.3.1",
    "react-native-maps": "^0.15.3",
    "react-native-orientation": "^2.0.0",
    "react-native-slider-button": "^0.1.1",
    "react-native-svg": "^5.3.0",
    "react-native-vector-icons": "^4.2.0",
    "react-navigation": "^1.0.0-beta.12",
    "react-redux": "^5.0.5",
    "react-redux-form": "^1.14.1",
    "redux": "^3.7.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  }

**Comment by andrewhl** [comment]
How are you importing Control? Should be: `import { Control } from 'react-redux-form/native';`

**Comment by davidkpiano** [comment]
What version React do you have?

**Comment by andrewhl** [comment]
@davidkpiano He's using 16.0.0-alpha.12. I'm using the same version. No issues here. It's very likely his import.

**Comment by sejsworld** [comment]
Sorry for the long delay, Due to my issues I switched to redux-form but it was probably a import or reducer configuration error. Thanks
