### ISSUE TITLE
Validation issues on checkboxes and select 

### ISSUE THREAD

**Issue by kkashou** [davidkpiano/react-redux-form#923]
Is there a documentation that specify how validation should be done for a list of checkboxes and select options?

I am having trouble triggering classnames base on if the checkboxes has no selection and also the select options has one value selected. It seems to be that the change event is not triggering when I do those two following. Mind you it works perfectly fine when I click the submit button it notes that it hasn't passed validation. It is only when I interact with it, it doesn't update.

Thanks

**Comment by kkashou** [comment]
After further investigation, I noticed for checkboxes since I have the model value like ```'user.checkbox[]'``` it doesn't update form state valid. Is there something that I need to do upon user selecting one or more checkboxes?

For select, it doesn't update the state valid when the user selects the first option which has ```value=''```. I am checking on validation ```(val) => val !== undefined || val === '';```

**Comment by kkashou** [comment]
Solved the select validation by changing the logic of that and then everything worked. ```(val) => val !== '' && val !== undefined```

As for checkbox still trying to figure out how validate as a whole group ... any tips would be helpful?

Thanks

**Comment by davidkpiano** [comment]
@kkashou Put is as a form validator:

```jsx
<Form model="user"
  validators={{
    'checkbox[]': val => val // must all be checked
  }}
>
  // ...
</Form>
```

You can have a validator that checks individual fields, e.g., `'users[].name': isRequired(name)` to check each name of each `user` in `users[]`. Or you can just do it manually: `checkbox: (vals) => vals.every(val => val)`

**Comment by davidkpiano** [comment]
Also can you put the original issue in a codepen? There might be an easier way to solve this.

**Comment by kkashou** [comment]
Hmmm that didn't seem to work ... here is codesandbox https://codesandbox.io/s/8z49z2wopj

So it validates when you click submit, but when you check a checkbox then unselect it the validation doesn't happen and does not put a wrapping classname change. Just got to be able to select at least one checkbox per group.

Hopefully this helps.

**Comment by kkashou** [comment]
Any possible solution for this?

**Comment by davidkpiano** [comment]
Log the validation:

```js
const validators = {
  required: () => {
    const fn = val => {
      console.log(val);
      return val !== "" && val !== undefined
    };
    fn.message = "Value is required.";
    return fn;
  }
};
```

You'll see that `val` is an array, could be empty (`[]`), could be full of values. So it'll never be "invalid". Since you are validating that model (which represents the array), you have to be more specific with your validation, e.g., check that `val.length > 0` or something like that.

Let me know if that helps!

**Comment by kkashou** [comment]
That's the thing I did try doing the ```val.length > 0``` I was getting TypeError: Cannot read property 'length' of undefined. :/

**Comment by davidkpiano** [comment]
Make sure it exists first. `(val && val.length > 0)`

**Comment by kkashou** [comment]
Okay that validation seems to work but the parent class names doesn't get updated depending on scenario for example:

When you start clicking the checkboxes and unchecking it only the error messages shows up and the classname of the parent element doesn't switch. Right now I currently am checking ```valid and touch``` has been updated. Is there something else I need to look for with checkboxes?

Here is the link to see demo ... https://codesandbox.io/s/8z49z2wopj

Thanks,

Kevin

**Comment by kkashou** [comment]
@davidkpiano - I know you closed this ticket but still not working how it should be. Any help would be appreciated.

**Comment by kkashou** [comment]
Any ideas why ?

**Comment by kkashou** [comment]
So I have converted this field to a control component and got the mapProps working. But is there a way to actually get that map to the parent content and update the class? 

Here is the update example ... https://codesandbox.io/s/kxz6831wjr (inside the checkbox.js file)
