### ISSUE TITLE
A way to style invalid inputs differently

### ISSUE THREAD

**Issue by sakarit** [davidkpiano/react-redux-form#925]
@davidkpiano Is there a way to use different css style for inputs that are not valid?

**Comment by spartDev** [comment]
Hi @sakarit 
You can check if the field is valid or not and had a custom className on the input
`({ fieldValue }) => !fieldValue.valid && fieldValue.validated`

**Comment by sakarit** [comment]
Yes but this is really inconvenient because I must do it manually for every input.

**Comment by spartDev** [comment]
You can create a custom component for you input

**Comment by davidkpiano** [comment]
Yep, @spartDev is right - this is exactly what higher-order components are for. Make a custom component 👍

**Comment by sakarit** [comment]
Okay I guess I could do it with the `resolve-model` and `get-field-from-state` utils...

However `resolve-model` is not exported from the index.js, so I have to import it with an another line of code. Also I'm using TypeScript so I would have to write a declaration file for it. Or use the full model name in every input which sucks.

**Comment by davidkpiano** [comment]
It will, but I think you're overthinking it. Check this out:

```jsx
const MyControl = ({ errorClassName, ...otherProps }) => (
  <Control.text
    {...otherProps}
    mapProps={{ className: ({ valid }) => valid ? errorClassName : '' }}
  />
);

// usage
<MyControl required model="foo.bar" errorClassName="has-error" />
```

**Comment by sakarit** [comment]
Ok, cool! Thanks mate!
