### ISSUE TITLE
Model validation incorrect when using custom action to hydrate custom form reducer

### ISSUE THREAD

**Issue by andrewhl** [davidkpiano/react-redux-form#926]
### The Problem
We use a custom `LOAD` action to hydrate our custom form reducer (which is is connected via `combineForms`). However, when we fire this action, the model validation is set to false even though `LOAD` provides values to the reducer. The validation rules are simple: `isRequired` and has length > 0. 

No `rrf/CHANGE` action happens on `LOAD`. We have found that when we fire `dispatch(actions.load('deep.editRecord', record))`, the form is hydrated appropriately, and the `rrf/CHANGE` action is fired, updating the model validation correctly. 

We would expect that, by virtue of the fact that `combineForms` wraps our reducer in `modeled`, that all actions passed to the reducer will trigger the model validation and `rrf/CHANGE`. Is this not correct?

Here is our code. We have our reducer connected to redux as follows:

**Root reducer**
```javascript
    deep: combineForms(
        {
            editRecord: recordFormReducer 
        },
        'deep',
    ),
```

**recordFormReducer.js**
```javascript
export const initialState = {
    name: '',
    description: '',
    first_name: '',
    last_name: '',
};

export default function reducer(state = initialState, action) {
    switch (action.type) {
    case LOAD: {
        const data = action.payload.record;
        const record = {
            name: data.relationship,
            description: data.gender,
            first_name: data.first_name,
            last_name: data.last_name,
        };

        return {
            ...state,
            ...record,
        };
    }
    default:
        return state;
}
```

**Comment by davidkpiano** [comment]
Can you put this in a CodePen? That way, if I suggest a fix, we can immediately verify that it works.

**Comment by davidkpiano** [comment]
Closing until this can be reproduced in a CodePen or CodeSandbox. 

For reference, validation is triggered on the component itself. It is not triggered automatically from external changes (such as `actions.change` or `actions.load`) unless that dispatched action itself triggers a change in the component. That will change in V2 (by the end of the year).

**Comment by stueynet** [comment]
@davidkpiano that explains a lot. So it is not enough to rely on your own redux actions acting upon form reducers, to run the validation process. So it would make sense to either run `actions.change` as part of a saga or other middleware. The key thing here is trying to hydrate the form data when you are editing an already existing resource.

In `componentDidMount` we would call `formReducer.LOAD` which would take the resource that is being edited as the payload. This would successfully hydrate the form but would not of course, properly process validation. So instead we can add a `watchFormLoad()` saga which will load the data to the correct redux form and then run `actions.load`.

We were trying to find clear documentation on best practices for loading an existing model into a form but it was not 100% clear how to do that.

Also thanks for the amazing project!

**Comment by andrewhl** [comment]
@davidkpiano Thanks for the response. Sorry, I didn't have time to post a codepen, but I think you answered our question.

**Comment by davidkpiano** [comment]
> We were trying to find clear documentation on best practices for loading an existing model into a form but it was not 100% clear how to do that.

You'd just dispatch `actions.load` which _will_ trigger validation if there's validators on the controls and the controls are present. Does that not work for your use case?

**Comment by stueynet** [comment]
Nope that works perfectly. I'm not sure why we were even confused.

**Comment by stueynet** [comment]
I guess the one issue we had was our local item was not the exact same shape as what ends up in the form. We we were using the reducer to transform it. So we would still need to have the two actions. One to load the model and transform it and the second for actions.load with the transformed model.
