### ISSUE TITLE
Travis CI takes a long time to run tests

### ISSUE THREAD

**Issue by maludwig** [davidkpiano/react-redux-form#927]
Travis CI takes a long time to run unit tests, specifically, due to two things. First, it runs the prepublish script in package.json, because the people who made npm hated human life:

https://docs.npmjs.com/misc/scripts

They won't hate it forever though, it's being phased out. But right now, when you run "npm install" with no arguments (like Travis does) it runs "prepublish", which currently runs the unit tests, the lint, the build, and copies the tsdef thing. THEN it runs all the unit tests again. Problematically, node is dropping that in the future of npm, so it won't run prepublish (they expect in a year). So, if you want those things to be run, they aren't futureproof, and if you don't want them to run, they are cluttering up the place.

The second slower-downer is the "npm install" itself, which grabs all the packages from npm's registry, which takes literally forever (288s).

Travis, however, has some fancy tricks up its sleeve. Like yarn support. Yarn is basically better npm. Notable benefits include caching of dependencies, and a yarn.lock file with hashes of dependencies, so if someone sneaks in a minor version update, and you've committed your yarn.lock file, you will get the exact same result as anyone else, which is super handy. Caching speeds stuff up a lot!

https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Travis-CI-supports-yarn

So I toyed with this a bit, but not enough to confidently make a pull request:

https://travis-ci.org/maludwig/react-redux-form/builds

When I started, the Node v4 package took 5m49s to run:

https://travis-ci.org/maludwig/react-redux-form/builds/269340240

When I turned on yarn, ignored the prepublish script, and cached the yarn deps, it took only 2m16s, which is like 3x faster!

https://travis-ci.org/maludwig/react-redux-form/builds/269747321

I attempted their npm cache (not yarn), but it apparently is shit because nothing worked for npm 5.3.0:

https://travis-ci.org/maludwig/react-redux-form/builds/269772450

SO. Options. It's up to you. 
- You can deal with having slow build times. 
- You can check out yarn (only the publisher actually needs it, but it is awesome), and ignore the prepublish script. 
- You should, either way, make the "prepublish" script into "prepublishOnly" (likely) or "prepare" (not likely) script, if that was the desired functionality. Yarn has all the same commands as npm, and you can use npm alongside it, so that your devs don't need yarn.

I can Pull Request whatever one is your preference. Sorry for the wall of text.

**Comment by davidkpiano** [comment]
Good analysis. Let's do this:

- Switch to `prepublishOnly`
- Add Yarn support

**Comment by maludwig** [comment]
Done! Caching should kick in with the next deploy!

**Comment by davidkpiano** [comment]
Fixed by #928
