### ISSUE TITLE
Local form - form wide errors

### ISSUE THREAD

**Issue by TAQ2** [davidkpiano/react-redux-form#936]
Hello,

### The Problem
I cannot seem to show form wide error messages

### Steps to Reproduce
https://codepen.io/anon/pen/eEwbxj?editors=0011

### Expected Behavior
if i do not type in 'bob' into the first field i should see an error message

### Actual Behavior
no error message is shown

Thanks for the help! :)

**Comment by dnlsandiego** [comment]
I'm experiencing the same issue too. Does form level validators don't work with `LocalForm`?

**Comment by davidkpiano** [comment]
> Does form level validators don't work with LocalForm?

They do.

With the validators you have set up, you aren't making a form-level validator, you're making a field-level validator:

```jsx
      <LocalForm
        model='local'
        validators={{
          model1: { checkBob: value => value === 'bob' }
        }}
        onSubmit={console.log}
      >
```

Try this:
```jsx
      <LocalForm
        model='local'
        validators={{
          // empty string is form-level validator
          '': {
            checkBob: value => value.model1 === 'bob'
          }
        }}
        onSubmit={console.log}
      >
```

And then you will see it will work 😄
