### ISSUE TITLE
Working with react-select

### ISSUE THREAD

**Issue by MikolajC** [davidkpiano/react-redux-form#939]
### The Problem
Can't make the react-redux form work with react-select

### Expected Behavior
I would like the form to send value from react-select.

### Actual Behavior
The props are passed down to my react-select component, but the values in form aren't updating.

### Reproducible Code Example
`
class SearchDropDown extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      value: this.props.options[0],
      searchable: this.props.search,
      multiSelect: this.props.multi
    }
  }
  updateState(element) {
    this.setState({
      value: element
    })
  }

  render() {
    const {model, dispatch} = this.props;
    let options = [];

    for (let i = 0; i < this.props.options.length; i++) {
      let option = {
        value: this.props.options[i],
        label: this.props.options[i]
      }
      console.log(option);
      options.push(option);
    }
    return (
      <Select
        multi={this.state.multiSelect}
        name="form-field-name"
        model=".example"
        value={this.state.value}
        options={options}
        searchable={this.state.searchable}
        onChange={this.updateState.bind(this)}
        onCustomChange={e => dispatch(actions.change(model, e))}
      />
    );
  }
}
`

And component, where I use it : 
`<FormGroup>
               <Control component={SearchDropDown} model=".example" controlProps={{
          search: false,
          multi: false,
          options: sex.selectOptions
        }}
        />
      </FormGroup>`

I think I wrapped it correctly, becouse the props are passed down to react-select component, but onSubmit(values), doesnt seem to include my model.

**Comment by davidkpiano** [comment]
Can you please put this into a fully functioning CodePen? I'll reopen once that happens. (Sorry, just trying to keep the valid issues clean!)

**Comment by brycesenz** [comment]
Hello @MikolajC ,

I was able to get `react-select` to work with this project using the Custom input type.  I'm not sure that this is the most optimal way, but please have a look at my code below:

```javascript
class DummyForm extends React.Component {
  updateMySelect(e) {
    const rawValues = _.map(e, (valObj) => valObj.value );
    this.formDispatch(actions.change('myForm.mySelect', rawValues))
  }

  handleSubmit(formValues) {
    this.props.onSubmit(formValues);
  }

  render() {
    const myReactSelect = (props) => {
      const options = [
        { label: 'Option 1', value: 'option1' },
        { label: 'Option 2', value: 'option2' },
        { label: 'Option 3', value: 'option3' },
      ];

      const valueMap = _.map(props.value, (value) => { return { value: value, label: value }; });

      return(
        <Select
          multi={true}
          name="form-field-name"
          value={valueMap}
          options={options}
          onChange={this.updateInformationCategory.bind(this)}
        />
      );
    };

    return (
      <div id="my-form">
          <LocalForm
            model="myForm"
            onSubmit={(values) => {
              return this.handleSubmit(values);
            }}
            initialState={{
              mySelect: this.props.mySelectValues,
            }}
          >
            <div className="input-field">
              <Control
                model="myForm.mySelect"
                component={myReactSelect}
              />
              <label for="myForm.mySelect">Select Values</label>
            </div>
            <button>Submit!</button>
          </LocalForm>
      </div>
    );
  }
}

```
