### ISSUE TITLE
Fields initial values

### ISSUE THREAD

**Issue by jekamoroz** [davidkpiano/react-redux-form#94]
Thanks for library, really good approach of handling form data
Just one question.

In my project I'm using normalizr library, so I have my own structure of data in store.
If want to update certain entity using react-redux-form, how is that possible to define so to say "initial values" for defined form. The only way I see, is to pass the "initialState" in model reducer, but this step seems to be on store creation. Right now, it is possible for example to dispatch action "merge", which gonna change the values, but then models get's dirty, isn't it?

So, would be nice to have/know how I can handle the "edit record forms" not only "create record forms"

**Comment by jekamoroz** [comment]
```
  componentWillMount() {
    this.props.dispatch(actions.merge('user', this.props.user));
  }

  componentWillUnmount() {
    this.props.dispatch(actions.reset('user'))
  }
```

for sure, that's a dirty solution

**Comment by jekamoroz** [comment]
hmm, figured out by having "modeled" reducer

```
function initialValues(state = initialState, action) {
  switch (action.type) {
    case 'SET_INITIAL_VALUES':
      return {
        ...state,
        ...action.values
      };
    default:
      return state;
  }
}
///////////
const rootReducer = combineReducers({
  entities,
  user: modeled(initialValues, 'user'),
  userForm: formReducer('user')
})
```
and just dispatch action
```
componentWillMount() {
  const {dispatch, user} = this.props;
  dispatch({
    type: 'SET_INITIAL_VALUES',
    values: user
  })
}
```

**Comment by davidkpiano** [comment]
Thanks! And yep, you can do it that way. Are you saying that you want to dynamically initialize values, after the store has been created/initialized already?

**Comment by jekamoroz** [comment]
exactly.
right now I'm about to give you PR, I think it would be "nice to have" this action globally ;)

**Comment by davidkpiano** [comment]
Sounds great! You're right, would be a good enhancement.
