### ISSUE TITLE
Questions about Control className & Form dirty state

### ISSUE THREAD

**Issue by netbull** [davidkpiano/react-redux-form#942]
So far everything works great, but i'm trying to figure out:

- how to set a className based on Control validation state /if the field is invalid to add xxxx className to the input/

- how to determinate the dirty state of the form to enable/disable the submit button. Currently the disable function works with **valid**, but it will be good to have the option for isDirty as well..

**Comment by davidkpiano** [comment]
There's some useful info in the [FAQs](http://davidkpiano.github.io/react-redux-form/docs/guides/faqs.html) that could help you.

> how to set a className based on Control validation state /if the field is invalid to add xxxx className to the input/

See "How do I add conditional class names based on field state?" in the FAQs (linked above)

> how to determinate the dirty state of the form to enable/disable the submit button. Currently the disable function works with valid, but it will be good to have the option for isDirty as well..

See these docs for the `disabled` prop: http://davidkpiano.github.io/react-redux-form/docs/api/Control.html

```jsx
// Disable the submit button when the form is invalid
<Control.button
  model="user"
  disabled={{ valid: false, pristine: false }}
>
  Submit!
</Control.button>
```

**Comment by netbull** [comment]
@davidkpiano thanks a lot! 🍺 

the first case works well, but the pristine it's not really like **isDirty** because if you make a change to an input the **pristine** becomes **true** and if you undo the change in the input value the pristine doesn't changes back to **false** which I think should be the behaviour of the dirty state, but I can live with that for now.
