### ISSUE TITLE
Control Input Date default value error

### ISSUE THREAD

**Issue by Escapado** [davidkpiano/react-redux-form#946]
Hey everyone, I make use of a control input in one of my forms like so

`<Control.input type="date" model="calendarForm.start" defaultValue={selectedDate}>`

where `selectedDate` is a string like `'2017-11-10'`.This results in a warning:

> Warning: Control is changing an uncontrolled input of type date to be controlled. Input elements 
should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

Once I remove the defaultValue prop I don't get the warning but I'd like to keep the prop. Is there anyway to circumvent this problem in a simple manner?

**Comment by davidkpiano** [comment]
This happens because `selectedDate` is most likely undefined. Can you put your code into a CodePen so I can show you an appropriate solution?

**Comment by Escapado** [comment]
I wasn't able to reproduce the warning I had in a codepen. I found the reason nonetheless:
`selectedDate `was properly defined but the model should have been `"calendarForm.entry.start" `since I defined a nested object as initial state and screwed up the refactor to adjust for that. Thanks for the quick response anyway and thanks for this great project. Saves me a lot of time and effort!
