### ISSUE TITLE
Errors component with track() and async validation

### ISSUE THREAD

**Issue by lilles88** [davidkpiano/react-redux-form#948]
I'd like to know if there is a way to show validation error messages received from server, as result of `action.submitFields()`, in an `<Errors>` component with a model provided by a `track()` function? I agree this is maybe an edge case, and I can't make it out right. I am able to track model value correctly, the problem is: 
how should I transform the errors received from server to make the `<Errors>` component display them? I tried every combination, but errors just don't show up. I assume the `<Errors>` component isn't smart enough to get validation error messages from the `Promise.reject(data)`, as the `track()` function is not, and can not be used there. Is this correct?

Sample code

```
<Number 
    min={1}
    max={999}
    model={track('deep.order.confirm.line_items_attributes[].product_qty', {id: this.props.item.id})}/>

<Errors
    show={{touched: true, focus: false}}
    className="errors"
    model={track('.line_items_attributes[].product_qty', {id: this.props.item.id})}/>
```

**Comment by davidkpiano** [comment]
Since RRF safely assumes that the server isn't going to return errors directly related to the specific fields, all async errors are considered errors on the form itself, so you'd have to parse them as e.g., `forms.deep.$form.errors` and then assign them directly to the model.

If you can get a CodePen showing the limitation and what you want to happen, I can reopen this and make it an enhancement.

**Comment by lilles88** [comment]
I'm using actions.submitFields(), as per the documentation:

> actions.submitFields(model, promise)
>
>  [...]
>
> If the promise fails, the action will:
> 
> 
> - set .submitFailed property of form for model to true
> - Each key in the response, which represents a sub-model (e.g., "name" for users.name) will have its .errors set to its value. (See example)

So when server-side validation error occurs, the Promise will fail, and the returned messages will be shown for the appropriate `<Errors>` with the given submodel. This worked great so far, but now my model is a track() expression. So I'd love to see an exampe or some hints how `<Errors>` works with `track()` model and `action.submitFields()`

**Comment by davidkpiano** [comment]
It should work like normal with `track()`, just as any other `<Control>`. If it doesn't, please submit a CodePen or CodeSandbox example demonstrating the issue.
