### ISSUE TITLE
Setting `value` property to anything jams changes to Form fields

### ISSUE THREAD

**Issue by nhooey** [davidkpiano/react-redux-form#955]
### The Problem

When I set the `value` property of a `Form` `Control.text` field in a React `Component` to anything, any attempt to change the value of that field by typing in it prevents the text from being modified. Removing the `value` property from the JSX fixes the problem.

### Steps to Reproduce

1. Make a `Control.text` entity and set its value to a Redux store value:
```javascript
import React from 'react';
import { Component } from 'react';

class MyForm extends Component {
render() {
  console.log('Rendering...');
  return (
    <Form model="search">
      <Control.text model="search.query" id="search.query"
                    value="whatever" />
    </Form>
  );
}
```
2. Click on the field in the browser and type some text.
3. Notice how the text won't change from the set value at all.

### Expected Behavior

The text should change when typing any characters.

### Actual Behavior

The text remains what the value was set to.

The `console.log()` statement doesn't get executed on every keystroke, so the problem is not that `render()` is getting called and resetting the value.

When using Redux's `applyMiddlware` to apply a `createLogger()` instance from `redux-logger`, you can see that the actual form state will change from whatever the value is, to whatever letter you just typed, but that change won't be reflected in the actual form field. So the state is being managed properly for only one letter that you type.

### Reproducible Code Example
Set this property on [this CodePen template](http://codepen.io/davidkpiano/pen/yJwmEa)'s first `Control.text` field:
```javascript
value="Setting value jams changes"
```
And then try to change the text with the keyboard after focusing on that text field.

**Comment by davidkpiano** [comment]
Trying to see the use-case here. By setting `value="whatever"`, you're making it controlled and telling React that on every render cycle, you want the value prop to be `"whatever"` no matter what, so of course it won't work.

Can you explain your use-case further?

**Comment by nhooey** [comment]
I just want to set the initial value when the page loads, because I'm specifically using `redux-query-sync` to keep the URL params in sync with some form fields, and it doesn't automatically set the text in the form fields.

**Comment by davidkpiano** [comment]
Try `defaultValue` or dispatch an `actions.load(model, value)` action.

**Comment by nhooey** [comment]
Setting the `defaultValue` property on a `Control.text` item does nothing.

And dispatching `actions.load(model, value)`, the values in the correct part of the model actually change, but the form fields don't display that text inside them.

To confirm that the correct part of the model is being changed, I type some text into the form fields, and it changes the model state to that text, replacing the text that was set by the dispatched action.

**Comment by nhooey** [comment]
The `defaultValue` of a regular form in HTML doesn't even set the text of an `<input>` tag anyway, so it can't be used for this purpose.

**Comment by nhooey** [comment]
To summarize, the resolution for this issue is to use `defaultValue` instead of `value`, because `value` will permanently set the value of the field, not allowing changes.
