### ISSUE TITLE
Control.checkbox default value is not applied

### ISSUE THREAD

**Issue by theodesp** [davidkpiano/react-redux-form#957]
### The Problem
I have a Control.checkbox component with an initial value set to true thus means checked. However when I load the form the initial value is always false. When I check the store the form model is not even initialized. When I check on the checkbox then  it initializes and updates the store with the field

### Steps to Reproduce
1. Create an initial model state with a boolean value set to `true`
2. Create Control.checkbox component with the associated model field.
3. Load the page. You will see that the checkbox is unchecked.  The form model field is not initialized.

### Expected Behavior
Checkbox should be checked and the form model field in the store initialized.

### Actual Behavior
Checkbox is no checked and the form model field in the store is not initialized.

### Reproducible Code Example
[this CodePen template](https://codepen.io/thdespou/pen/vemPqX))

**Comment by davidkpiano** [comment]
You misspelled `"employed"`:

```diff
const initialUserState = {
  firstName: '',
  lastName: '',
- empoyed: true
+ employed: true
};
```

I corrected the spelling and saw that everything worked as expected.
