### ISSUE TITLE
Question about loading data and tracking collections with an existing store.

### ISSUE THREAD

**Issue by mitchelldemler** [davidkpiano/react-redux-form#959]
Apologies if this is the wrong place for a usage question, I've been pulling my hair out for a week over this one. I'm looking for an example of collections (and nested collections). I've poured over the docs, and I'm a little confused about when to use `modelReducer()`, `formReducer()`, `combineForms()`, `createForms()`, and `track()`.

I'm working in a private repo with an existing form solution (migrating to react-redux-form), so I'll do my best to explain the current setup.

In my page's `componentDidMount()`, I am fetching data from an API. My existing reducer handles the fetching/success/error actions and stores the data in redux:
```
// My combine reducers:
const appReducer = combineReducers<IApplicationState>({
    feeTemplateState: feeTemplateReducer,
});

// Example of state after fetching of data:
feeTemplateState: {
    feeTemplateGroups: [{        
        id: 0,
        reportingRegion: 1,
        feeType: 0,
        items: [{
            amount: 1000,
            description: 'Example Description',
            name: 'Example Fee 1',
            id: 2
        }, {
            amount: 500,
            description: 'Example Description',
            name: 'Example Fee 2',
            id: 1
        }],
    }],
    isFetching: false,
    isPosting: false,
    fetched: true,
    error: null
}

// Pseudo example of my Form implementation:
<Form
    model="feeTemplates"
    onSubmit={this.handleSubmit}
>
    // Fee templates are from mapStateToProps
    {this.props.feeTemplates.map((template, index) => (
        <Control.text
            model={`.[${index}].name`}
            controlProps={{
                placeholder: 'Name',
            }}
        />
        <Control.text
            model={`.[${index}].description`}
            controlProps={{
                placeholder: 'Description',
            }}
        />
        <Control.text
            model={`.[${index}].amount`}
            controlProps={{
                placeholder: 'Amount',
            }}
        />
    ))}
</Form>
```

What is the best approach for:
- Loading existing data into the form?
- Tracking the ID's with track() so that I can add/delete rows.
- When/where/how do I use modelReducer/formReducer/combineForms etc?
Preferably looking for a repo with some examples.

Note: I'm using Typescript and also looking for some info on testing collections with Jest/Enzyme.

**Comment by davidkpiano** [comment]
> Loading existing data into the form?

Dispatching an `actions.load` action once you receive your data:

```js
dispatch(actions.load('user', userData));
```

> Tracking the ID's with track() so that I can add/delete rows.

The documentation is pretty thorough about this: http://davidkpiano.github.io/react-redux-form/docs/guides/tracking.html

> When/where/how do I use modelReducer/formReducer/combineForms etc?
Preferably looking for a repo with some examples.

Use `combineForms` - `modelReducer` and `formReducer` are lower-level and better left abstracted. There's a bunch of guides and examples in the documentation.

Hope that helps!

**Comment by mitchelldemler** [comment]
Thanks for the response! I think I was just missing the `actions.load` in my setup, I will try that out.
