### ISSUE TITLE
Can't figure out how to set checked on a list of radio buttons

### ISSUE THREAD

**Issue by greghawk** [davidkpiano/react-redux-form#960]
issue says it all

**Comment by davidkpiano** [comment]
You want them all checked? I don't understand the full issue.

**Comment by greghawk** [comment]
Just one checked. I tried defaultChecked and checked and I got errors.

**Comment by greghawk** [comment]
@davidkpiano  I worked it out with some tricks

**Comment by davidkpiano** [comment]
Awesome, want to share what those "tricks" were, in case there's a better way?

**Comment by greghawk** [comment]
Will do. Owe you a few snippets

On Oct 3, 2017, at 8:57 AM, David Khourshid <notifications@github.com<mailto:notifications@github.com>> wrote:


Awesome, want to share what those "tricks" were, in case there's a better way?

**Comment by greghawk** [comment]
@davidkpiano  here ya go. I am submitting onchange normally.  What i did was check if there was an event or not when onchange fires.  this prevents the background fire of onchange from advancing my form

`              <Control.radio
                name={choice.value} id={choice.value}
                model={`formData.${step.attributeid}`}
                className={`ltFormRadioButton${choice.value} ${step.attributeid}`}
                value={choice.value}
                defaultValue={(index === 1 ? choice.value : undefined)}
                changeAction={(model, value, event) => (dispatch, getState) => {
                  if (getState().forms.formData[step.attributeid]!==undefined && getState().forms.formData[step.attributeid].pristine === false && event===undefined) {
                    return;
                  }
                  let enums = getState().formDefinition.steps.find(step => step.attributeid === model.split('.')[1]).enumeration;
                  let modify = enums.find(item =>
                    item.value == value && item.actionAttribute !== undefined
                  );
                  if (modify !== undefined) {
                    let currVal = getState().formData[modify.actionAttribute];
                    model = `formData.${modify.actionAttribute}`;
                    value = (modify.action != undefined) ? transform(modify.action, getState().formData[modify.actionAttribute], modify.actionValue).toString() : currVal || value;
                  }
                  dispatch(actions.change(model, value));
                  if (event) {
                    handleNext();
                  }
                }}`
