### ISSUE TITLE
Access fieldValue state outside of <Control>

### ISSUE THREAD

**Issue by greghawk** [davidkpiano/react-redux-form#962]
I tried wrapping a control with a `<Field>` and did this below which runs the code in the mapProps but does not apply the className to the Field div.

<Field model={`formData.${step.attributeid}`
        mapProps={{
        className: ({fieldValue}) => (fieldValue.valid || fieldValue.pristine || !fieldValue.touched)
          ? `ltFormControl`
          : `ltFormControl ltHasError`
      }}>
        <Control  model={`formData.${step.attributeid}`}/>
</Field>

**Comment by davidkpiano** [comment]
You don't have to wrap `<Control>` with `<Field>` (and you shouldn't) - try transferring `Field` props over to `Control`, and it should work.

**Comment by greghawk** [comment]
@davidkpiano I may not have been clear or I am not understanding your meaning. Let me explain what i am trying to do:

create a div that wraps a Control but is aware of fieldValue. i.e valid, pending etc.  and use that meaning to add a class to the wrapper div when invalid for instance.  without passing props way down though my components which most are stateless i can't seem to access this.  I need this wrapper for attachment of pseudo classes.

**Comment by greghawk** [comment]
re

**Comment by greghawk** [comment]
@davidkpiano  fixed this via comments on https://github.com/davidkpiano/react-redux-form/issues/771
