### ISSUE TITLE
Form model

### ISSUE THREAD

**Issue by kkashou** [davidkpiano/react-redux-form#963]
When giving a model to a form element, I noticed there are some example has two of the following:

```Javascript

model='user.name'

or

model='.name'

```

Why Is that? 

Thanks

**Comment by davidkpiano** [comment]
See here: http://davidkpiano.github.io/react-redux-form/docs/guides/partial-models.html

**Comment by kkashou** [comment]
@davidkpiano  - I see that, now would validation still work the same way ? Because I am running into a case that validation doesn't output the same results.

**Comment by davidkpiano** [comment]
Can you post a CodePen example of that?

**Comment by kkashou** [comment]
@davidkpiano perfect example here https://codesandbox.io/s/8z49z2wopj the first one will have the user. and the second one will have . ... you will see the first work works right highlights everything in red where as the second one nothing gets highlighted.

Does that helps? 

Thanks

**Comment by davidkpiano** [comment]
@kkashou Can you open that in a new issue?

**Comment by kkashou** [comment]
@davidkpiano sure ... created the issue here https://github.com/davidkpiano/react-redux-form/issues/965
