### ISSUE TITLE
Pulling react-redux-forms from npm doesn't have 1.14.2 built code

### ISSUE THREAD

**Issue by stevenmason** [davidkpiano/react-redux-form#964]
After updating to `1.14.2` and using `isValid` an undefined error is thrown. It appears the changes are in the `/src` folder but not in `/lib`. I built it manually and it works fine.

**Comment by stevenmason** [comment]
@davidkpiano would you be able to push the changes to npm please?

**Comment by mewben** [comment]
Same here... exported `isValid` is found in the `/src` but not in the `/lib`

**Comment by davidkpiano** [comment]
1.14.4 was just published!

**Comment by stevenmason** [comment]
Thanks @davidkpiano !
