### ISSUE TITLE
Bug in validation with partial models

### ISSUE THREAD

**Issue by kkashou** [davidkpiano/react-redux-form#965]
https://codesandbox.io/s/8z49z2wopj - Here is the code base where I am having the issue.

The first checkbox will have the ```user.``` and the second one will have ```.``` ... you will see the first work works right highlights everything in red where as the second one nothing gets highlighted.

Any reason why that is ?

**Comment by kkashou** [comment]
@davidkpiano - Any help?

**Comment by davidkpiano** [comment]
Have you tried using `<Control>` instead of `<Field>`? Try that first. `<Field>` will be deprecated in v2.0.

**Comment by kkashou** [comment]
@davidkpiano - I converted it to ```<Control``` now it doesn't work at all.

When does v2.0 come out?

**Comment by davidkpiano** [comment]
End of the year. Please show me the code with `<Control>`

**Comment by kkashou** [comment]
@davidkpiano - It is in the checkbox.js file on the files side panel.
