### ISSUE TITLE
Enter Key does not fire form submit on form with only radio button controls

### ISSUE THREAD

**Issue by greghawk** [davidkpiano/react-redux-form#966]
### Expected Behavior
Form submit event should be fired

### Actual Behavior
nothing unless you first click on a radio button (even if already set from state) then it works

### Reproducible Code Example
https://codepen.io/ghawk/pen/oGqrGx

**Comment by davidkpiano** [comment]
The behavior is correct - an HTML5 form won't submit on <kbd>Enter</kbd> unless part of that form is focused, which you have to do by focusing (clicking, tabbing, etc.) on something.

**Comment by greghawk** [comment]
@davidkpiano so how do I focus on the desired option since defaultchecked and whatnot doesn’t work right and is discouraged?

**Comment by davidkpiano** [comment]
Add the `autoFocus` prop.

**Comment by greghawk** [comment]
@davidkpiano Thanks! Totally forgot about that option.
