### ISSUE TITLE
Make fieldValue part of the standardPropsMap

### ISSUE THREAD

**Issue by keattang** [davidkpiano/react-redux-form#967]
Hi, 

First off, thanks for writing this library, it has solve a fair few problems for me.

Is it possible to make `fieldValue` part of the `standardPropsMap`? The reason that I would like to do this is that I would like to pass in a component to a `Control` that can change dynamically based on the the touched/valid/submitting/etc states. 

I realise that this can be done with a custom `Control` but that would also require me to also map all of the standard props and the more specific props for other `Control` types. I'd like to still be able to use `Control.text` for example and also have the `fieldValue` prop available.

At the moment I am working around this by saving the form to the parent component's state with the `onUpdate` handler and then passing the form to the `Control`. This seems like it could result in a lot of unnecessary updates to the state. 

I'm happy to make a pull request however, looking at the code, it seems that the change is fairly trivial and so may be better off done directly. Let me know how you'd like to proceed.

Cheers!

**Comment by davidkpiano** [comment]
Feel free to make a pull request! As long as it doesn't affect performance, this could be a good feature.

**Comment by daronjay** [comment]
+1 on this, I want to be able to access the field value and all the meta info inside my controlled component in order to do various validation related highlighting on items that don't directly consume the model. like wrappers etc. Is there any way it could pass a field prop to the controlled component?

**Comment by keattang** [comment]
So I had a stab at this and the main issue that I ran into was that this would be a semi breaking change as the default behaviour is to pass all the props directly to the child. So if the child is an `<input />` component we get a react warning saying that `fieldValue` is not a recognised prop for `<input />`.

This is fairly fixable when the `component` prop of `Control` is a string e.g. `component="input"` as we can just check if its a string and then exclude `fieldValue` from the props passed through. 

For anyone using a component that looks something like this though, they will get the warning:
```
const CustomInput = (props) => (
    <div><input {...props} /></div>
);
```

Any thoughts @davidkpiano on how we may avoid causing everyone getting this warning and having to change their code to exclude `fieldValue`?

We could potentially have a flag on control like `passFieldValue` that controls whether it gets passed through or not but it would be nice to not have to.

**Comment by davidkpiano** [comment]
Simplest way to implement this would be to add a prop:

```jsx
<Control.custom
  model="foo.bar"
  component={CustomComponent}
  withFieldValue            // this would add fieldValue to the props map
/>
```

What do you think?

**Comment by keattang** [comment]
It would be nice not have to have the prop but if there's no better way i'm happy to implement it like that

**Comment by davidkpiano** [comment]
The problem is that it either has to be opt-in or opt-out.

- Opt-out (always add the prop) makes too many assumptions, and developers will get lots of "unrecognized prop" warnings.
- Opt-in (using `withFieldValue` prop) is only a little more typing, easily abstracted, and explicit.

**Comment by keattang** [comment]
Cool. I've just linked the PR. Let me know what you think.
