### ISSUE TITLE
Q: external field validity check

### ISSUE THREAD

**Issue by KubaChoice** [davidkpiano/react-redux-form#972]
Hi,
Is there any possibility to check if field (model .xyz) is valid or not from parent "container"? 
e.g Bootstrap FormGroup needs proper validationState ...

```
<Form>
  <FormGroup validationState={isXYZvalidOrNot}>
    <Control.text model=".xyz" />
    <Errors show="touched" model=".xyz" ... />
  </FormGroup>
</Form>`
```

Thanks for any advice

**Comment by davidkpiano** [comment]
Make a custom component that contains `<FormGroup>`. More info here: http://davidkpiano.github.io/react-redux-form/docs/guides/custom-controls.html

**Comment by KubaChoice** [comment]
Thank You for your answer, 
I did, and with mapToProps and other features it will successful, but it looked like a horrible way for checkboxes and radio buttons groups ...

But, still thanks
