### ISSUE TITLE
changeAction not fired with custom component.

### ISSUE THREAD

**Issue by divined** [davidkpiano/react-redux-form#978]
### The Problem
```
<Control.text
  changeAction={this.changeAndSubmit}
  model=".original.chargeRelation"
  component={customText}
  updateOn="change"
/>
```

**Comment by davidkpiano** [comment]
Please create a reproducible CodePen or CodeSandbox example and I'll reopen this. Thanks!

**Comment by cal0610** [comment]
@davidkpiano 

Hi David

I've encountered the same issue here.

**If you use control like this:**

<Control component={CustomComponent} changeAction={this.handleChange}/>

Then this.handleChange is called but the onChange for CustomComponent is not.

From the documentation it does not specify that the changeAction overwrites the onChange on the custom component.

**Why this matters?**
I want to update field B based on the value on field A.

**Comment by cal0610** [comment]
Any chance we can get this looked at ?

**Comment by davidkpiano** [comment]
If you have an idea of how you'd like to implement it, please prepare a PR.

**Comment by cal0610** [comment]
Thanks David!

Just wanted to confirm that this is expected  and changeAction is supposed to override CustomComponents onchange?

**Comment by davidkpiano** [comment]
It's not exactly supposed to override it; it's supposed to be used as a "hook" to perform an action when the `onChange` event occurs.
