### ISSUE TITLE
focus field not set on firefox

### ISSUE THREAD

**Issue by Sonith** [davidkpiano/react-redux-form#981]
### The Problem
Great job on the framework.
I think this is an issue. If I am doing something wrong, please let me know.

checkbox focus field not set on firefox when it's clicked on. Works on chrome. 
Is there a workaround?

### Steps to Reproduce
click the checkbox, check the console.

### Expected Behavior
employed:true

### Actual Behavior
employed:false

### Reproducible Code Example
https://codepen.io/anon/pen/ZXVORp?editors=0111

**Comment by davidkpiano** [comment]
This might be a React issue, not a RRF issue, since I tested it with a plain:

```jsx
<label>
  <input type="checkbox" />
  testing
</label>
```

and it didn't focus the checkbox for that either. Try posting an issue here: https://github.com/facebook/react/issues

**Comment by Sonith** [comment]
I see. Thank you for your quick response. I'll post an issue on the react page.
