### ISSUE TITLE
Reset intent on Control is not cleared when `updateOn="blur"`

### ISSUE THREAD

**Issue by kabbi** [davidkpiano/react-redux-form#982]
### The Problem
Control component does not clear `reset` intent, when `updateOn` (or `validateOn`) is set to `blur`. This forces the input to always show the initial value, and it becomes unchangeable.

Seems to be due to [these lines of code](https://github.com/davidkpiano/react-redux-form/blob/master/src/components/control-component.js#L413-L415).

### Steps to Reproduce
1. Issue reset event on control's model
2. Render `Control.text` with `updateOn="blur"`

### Expected Behavior
Input text can be changed

### Actual Behavior
Input text cannot be changed

### Reproducible Code Example
https://codesandbox.io/s/1okpx1z4z7

**Comment by aminul-technext** [comment]
+1
Even the form gets `reset` the fields needs to be `focused` twice.
On 1st cycle nothing can be written in the field, on 2nd cycle it works.

Validation works on as usual, even on the 1st cycle.

**Comment by davidkpiano** [comment]
Can you try removing the conditional @kabbi and see if that fixes the issue?

**Comment by kabbi** [comment]
I'll try to make a PR a bit later. I'm not entirely sure right now though why this check was there in the first place.

**Comment by davidkpiano** [comment]
Copying pasting here for clarity:

```jsx
          case 'validate':
          case 'reset':
            if (intent.type === 'reset') {
              this.setViewValue(modelValue);
              if (this.handleUpdate.cancel) {
                this.handleUpdate.cancel();
              }
            }
            if (containsEvent(validateOn, 'change')) {
              this.validate({ clearIntents: intent });
            }
            return;
```

So the logic is:
- If resetting, make sure to update the view value so that the control visually shows the correct value.
- If there is change validation on the control, resetting "changes" the value, so validate it.

I believe the fix here is to add an `else` clause (if it's a reset) to clear the intent.

**Comment by kabbi** [comment]
Oh, I didn't notice the `case: 'validate':` line. That's trivial then. Should I add a testcase to ensure that each intent type is cleared correctly?

**Comment by davidkpiano** [comment]
Yes please!

**Comment by yourfavorite** [comment]
Hi, I'm running into this bug currently using v1.16.8. My fields are set to update on blur and after calling reset on the model for the form, I have to click into a field to focus it, then blur it and then focus again before I can type anything. Was this bug fixed or do I need to do a modification locally?

**Comment by davidkpiano** [comment]
@yourfavorite Please create a new ticket with a reproduction.

**Comment by yourfavorite** [comment]
Actually, I deleted my node_modules folder forced an npm cache clean and then reinstalled. Looks like I had something cached that was causing the issue. All good now. Thanks!
