### ISSUE TITLE
Support for properties containing dots

### ISSUE THREAD

**Issue by akkie** [davidkpiano/react-redux-form#986]
I think this is a more general issue and I do not know if it's easy to fix because rrf uses the dot notation all over the API to access it's data.

In JS it's possible to create properties that contains dots.
```js
{
  "address.city": "Berlin"
}
```

And it's possible to access them with:
```js
obj['address.city']
```

There are also currently parts in rrf where it's possible to use the syntax with the square braces to access such properties.

Works
```js
actions.change('user[address.city]', 'Paris')
```

Don't work:
```js
actions.change('user', { 'address.city': 'Paris' })
```

One issue is also to initialize such a form with an initial state. Please also look at the result of the submit if you have filled the form.
https://codepen.io/anon/pen/PJLbwq?editors=1111

As you can see, the behavior is very inconsistent in rrf. Sometimes it works and sometimes it doesn't work. It this isn't fixable, it would be nice to add some notes to the documentation.

**Comment by davidkpiano** [comment]
Internally, RRF (and lodash) convert these string paths:

```
"foo.bar.baz"
```

into array paths:

```
['foo', 'bar', 'baz']
```

Unless, of course, it's already an array path. What this means is you can do this:

```jsx
        <div className="field">
          <label>First name:</label>
          <Control.text model={['user', 'firstName.test']} />
        </div>

        <div className="field">
          <label>Last name:</label>
          <Control.text model={['user', 'lastName.test']} />
        </div>
```

And it will work as expected. If this is a viable solution, I'll add it to the docs (or you can - Hacktoberfest is going on!)

**Comment by SuperOleg39** [comment]
@davidkpiano Hello! Control propTypes allow function or string:

`
model: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.string,
  ]).isRequired
`

And when i pass array of strings to Control component, catch error - "Failed prop type: Invalid prop `model` supplied to `Control`."

**Comment by SuperOleg39** [comment]
And example code `actions.change('user[firstName.test]', 'value')` - works strange:

if prev state is `user: { 'firstName.test': '' }`, next state will be  `user: { firstName: { test: 'value' }, 'firstName.test': '' }`,

**Comment by davidkpiano** [comment]
@SuperOleg39 Try `actions.change('user', (user) => { ... })` and updating the user through a function to mitigate this problem.

**Comment by sidharthdigiworks** [comment]
is there any way to use . in names without using array ?

I'm using dynamic fields and values with initialValues from state and using names like "User.Name" and the forms are not working as intended.

the form value is saved as follows and isn't being picked up from initialValues
```
{
  "User": {
     "Name": "Test"
  }
}
```
