### ISSUE TITLE
Upgrade shallow-compare to 1.2.2 for React 16 compatibility

### ISSUE THREAD

**Issue by bugzpodder** [davidkpiano/react-redux-form#987]
### The Problem
shallow-compare 1.2.1 has a peer dependency on React 15.  It is recently updated in 1.2.2 https://www.npmjs.com/package/shallow-compare which removes this dependency.

Currently RRF has an exact dependency on shallow-compare 1.2.1

### Steps to Reproduce
npm install gives a warning:  peer invalid: react@15.x, required by shallow-compare@1.2.1

**Comment by bugzpodder** [comment]
@davidkpiano would love a new release with this change.  npm shrinkwrap breaks with any peerDependency warnings.  Thanks!

**Comment by davidkpiano** [comment]
Will do first thing tomorrow.
