### ISSUE TITLE
debounce prevents select controls from changing

### ISSUE THREAD

**Issue by vectorjohn** [davidkpiano/react-redux-form#994]
### The Problem
If you use a select control with a debounce time, you will not be able to change the value of the select (or you will be able to change it once if the initial value is not one of the options).

I know debounce on a select is probably a weird use case. But it should work (IMO).

### Steps to Reproduce
View the code pen.

```
<Control.select debounce={10}>
    <option value="1">1</option>
    <option value="2">2</option>
</Control.select>
```

### Expected Behavior
It should work like any other input with debounce. The input should visibly change immediately, but dispatch changes after the debounce time.

### Actual Behavior
The above control won't be able to change more than once. If the initial form state has one of the values initially selected, you can't even change it once.

### Reproducible Code Example
https://codepen.io/anon/pen/aLeqEJ?editors=0010#0

### Hints or whatever
I tried to fix it myself, and got as far as confirming the source of the problem, but don't know the best way to fix it.

This seems to be related to how react updates the <option> elements when a select changes to set the selected attribute. Then at a later time, the debounced handleChange function gets called and is getting a wrong value.. or something.

**Comment by vectorjohn** [comment]
I added another case in the pen, the second one with debounce but where the form's initial state does not match one of the available options in the select. It shows how it's somehow related to what React is doing, when it tries to update the <option>s to set the selected attribute based on the select's props, the first time you change the <select>, nothing matches so React doesn't do anything. But after that, it is somehow resetting the control's selected option before the debounced function goes off.

**Comment by lstuartfry** [comment]
Also having this issue, mainly after 'resetting' a field that has a value in the form's initial state (and that value's format doesn't match the format of the Select's options)
