### ISSUE TITLE
parser for Fields

### ISSUE THREAD

**Issue by Sonith** [davidkpiano/react-redux-form#996]
### The Problem
The previous argument from parser property on Field is always undefined.
I am not sure if I am using this the right way. 
Please let me know if I have a bug in my code.
Thank you.

### Steps to Reproduce
start typing in the text box

### Expected Behavior
the previous value with hold the previous value

### Actual Behavior
its undefined

### Reproducible Code Example
https://codepen.io/anon/pen/VrLVPb?editors=1111

**Comment by davidkpiano** [comment]
Sorry about that, the documentation was wrong. There is no `previous` property.

**Comment by Sonith** [comment]
I figured that was the case, but got confused when I saw 
parser?: (value: any, previous?: any) => any;
in react-redux-form.d.ts
Thank you for your quick response.
