### ISSUE TITLE
Why must we use react-redux 4.x.x with LocalForm?

### ISSUE THREAD

**Issue by joshacheson** [davidkpiano/react-redux-form#997]
### The Problem

The README recommends that consumers use react-redux v4.x.x when using `<LocalForm />`

### The Question

I'm curious why this is the case? Is it possible that you would accept a PR to make `<LocalForm />` work with `react-redux` v5.x.x, assuming that's a scarcely reasonable thing to do.

**Comment by davidkpiano** [comment]
> Is it possible that you would accept a PR to make <LocalForm /> work with react-redux v5.x.x, assuming that's a scarcely reasonable thing to do.

Yes, go for it! I'll merge it in 🔜

**Comment by joshacheson** [comment]
Do you have any initial pointers as to why v4.x.x is recommended? AFAICT 5 introduced no breaking API changes. I only ask so that I can hone in on the issue quicker :) Will definitely be taking care of the PR here!

**Comment by davidkpiano** [comment]
I think early versions of 5 did have breaking issues that were since fixed. As long as the tests pass with the latest, should be good to go.

**Comment by joshacheson** [comment]
I ran the tests against `react-redux` v5.0.6 (most recent). They passed. I'd put together some doc changes, but there's already a PR: #1000.

Closing this since it just makes sense to merge #1000.
