### ISSUE TITLE
Text control won't update first time after remount in updateOn="blur" case

### ISSUE THREAD

**Issue by NewOldMax** [davidkpiano/react-redux-form#999]
### The Problem
When my form is unmounts and mounts again, text inputs with updateOn="blur" property won't show any entered values until I focus them, blur, and focus again. When I add `onChange` prop to check what happens, I see my entered values in `onChange`, but they don't appears in input. When I debug sources I saw that `render` triggers twice, first time with correct value, second one - with empty.

### Steps to Reproduce
- mount form with text input and updateOn="blur" prop
- focus text input
- type "1"
- remount form with initial state
- focus text input
- try to type "1"

### Expected Behavior
After remounting text input should show typed value

### Actual Behavior
After remounting text input doesn't show any type values, you need to blur it and focus again, then you can type

### Reproducible Code Example
https://codepen.io/anon/pen/oojKVM?editors=1111
![asd44](https://user-images.githubusercontent.com/1328473/32325116-ac0e7944-bfde-11e7-88d2-15641fa39deb.gif)

**Comment by davidkpiano** [comment]
I can't reproduce the initial issue. When you unmount the form, you have this logic:

```js
componentWillUnmount() {
    this.props.dispatch(actions.reset('user'));
  }
```

that will remove the current value.

**Comment by NewOldMax** [comment]
Yes, it will remove value and it's ok, but you can't enter new value after mounting component again
